### ISSUE TITLE
honor HOMEBREW_PREFIX environment variable to override the one in https://raw.githubusercontent.com/Linuxbrew/install/master/install

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/brew#102]
HOMEBREW_PREFIX=/tmp/foo ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
should install in HOMEBREW_PREFIX
right now it overrides HOMEBREW_PREFIX always

**Comment by sjackman** [comment]
`HOMEBREW_PREFIX` is meant to be an internal variable of the `install` script that cannot be overridden by the user. It's reasonable to want to specify the install location, but that's not currently possible with the `install` script. You can however do this:

``` sh
git clone https://github.com/Linuxbrew/brew /tmp/foo
```
