### ISSUE TITLE
hdf4 - error.h conflict with glibc

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/brew#104]
```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/hdf4/4.2.
==> make install
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink include/error.h
Target /home/linuxbrew/.linuxbrew/include/error.h
is a symlink belonging to glibc. You can unlink it:
  brew unlink glibc

To force the link and overwrite all conflicting files:
  brew link --overwrite hdf4

To list all files that would be deleted:
  brew link --overwrite --dry-run hdf4

Possible conflicting files are:
```

**Comment by sjackman** [comment]
Hi, Torsten. `hdf4` is in the tap Homebrew/versions, and the Homebrew/versions tap is not currently supported by Linuxbrew. Someone would need to volunteer to maintain this tap if Linuxbrew were to support it.

**Comment by sjackman** [comment]
I'm surprised that `hdf4` conflicts with `glibc`. Two possible workarounds are to leave `hdf4` unlinked, or to remove the file `include/error.h` from the `hdf4` keg and then link it. That may of course break `hdf4` if that file is necessary to it.

**Comment by tseemann** [comment]
I didn't need hd4 explicity, but something else depended on it. But I can't remember what now.

**Comment by sjackman** [comment]
`homebrew/science/nexusformat` depends on `homebrew/versions/hdf4`
No bioinformatics formula in homebrew/science seem to depend on it.
