### ISSUE TITLE
Imagemagick formulae needs to be updated

### ISSUE THREAD

**Issue by michaeljohnsargent** [Linuxbrew/brew#106]
I'm having an issue with the current link to imagemagick - "404 Not Found"

 `brew install imagemagick --with-jasper                                              08-30-16 10:34:49
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick-6.9.5-7.tar.xz`

`curl: (28) Connection timed out after 5338 milliseconds
Trying a mirror...
==> Downloading https://www.imagemagick.org/download/ImageMagick-6.9.5-7.tar.xz`

`curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "imagemagick"
Download failed: https://www.imagemagick.org/download/ImageMagick-6.9.5-7.tar.xz`

Can someone assist?

**Comment by bw-yuhogg** [comment]
Can you retry the installation please? The Homebrew download URL works fine for me (using `wget`).

If the download is only failing inside brew, you could try manually downloading  with `wget` or something similar, copying the file into your Homebrew cache, and then retrying the installation, but I suspect this is just a temporary fluke.

As for the ImageMagick URL returning a 404, that's sadly unsurprising. The formula actually says this about the primary download URL:

``` ruby
  # Please always keep the Homebrew mirror as the primary URL as the
  # ImageMagick site removes tarballs regularly which means we get issues
  # unnecessarily and older versions of the formula are broken
```

**Comment by michaeljohnsargent** [comment]
I ran cd $(brew --repo) && git fetch && git reset --hard origin/master &&
brew update
and then tried brew install imagemagick --with-jasper again. All is well
thanks for being so responsive!

**Comment by bw-yuhogg** [comment]
np, happy to help :smile_cat: 

Referencing https://github.com/Homebrew/homebrew-core/issues/4354 for completeness' sake and closing.
