### ISSUE TITLE
Bottles for ARM

### ISSUE THREAD

**Issue by staticfloat** [Linuxbrew/brew#107]
Are there any plans to try bottling things for ARM?  I've started using Linuxbrew to manage my software deployments to some Raspberry Pi 3's, and although things are working great (except for annoying old GCC bugs) compile times are excruciating.  Bottles would be a most welcome addition, although I realize that ARM devices are still a little "exotic" at the moment, not to mention there is a wide range of architectures to compile for.

**Comment by sjackman** [comment]
I had thought of it, but no plans. Infrastructure is needed to compile the bottles, like for example Jenkins running on a Raspberry Pi, and someone to volunteer to head up the effort.

**Comment by staticfloat** [comment]
Unfortunately, I don't think I'm your guy.  I can barely keep up with the stuff I'm working on already.  :)  I will, however, be happy to donate to any kind of hardware drive if you eventually start one for ARM hardware.

**Comment by sjackman** [comment]
Cool. I'll keep in mind that you're an ally if someone else raises the topic.

**Comment by DoomHammer** [comment]
Or building bottles in an ARM container running qemu?

**Comment by sjackman** [comment]
Yeah, that's doable. It may even be possible to build the bottles using our existing CircleCI infrastructure running qemu on Circle.

**Comment by DoomHammer** [comment]
Shall we try reusing our current configuration for this?

**Comment by sjackman** [comment]
Existing Circle CI configuration? I'm not really sure. The host CI would only need run an ARM VM, so its requirements are pretty slim.

**Comment by DoomHammer** [comment]
My idea was to use the existing configuration as far as possible (scripts for certain, maybe even infrastructure) and as a first step only change environment from x86_64 to ARM using an ARM container with `qemu-static`. Hence `qemu` would be used performance would certainly decrease but at least we will not have to bother with cross-compilation (as well as running tests). This way we could at least generate the "basic" bottles.

**Comment by sjackman** [comment]
I'm not sure how much demand there is for ARM bottles, and I'm guessing it would add a fair bit of maintenance burden. I'd be fine with it if it were implemented as a third CI system whose failure would be ignored by GitHub.

**Comment by DoomHammer** [comment]
Agree, but is it possible to use a second CircleCI for example? Or should it be some other provider?

**Comment by sjackman** [comment]
As far as I know it's only possible to run one Circle configuration for a given repo, but I could easily be wrong. I'd suggest setting up Jenkins as the third build bot. If that goes well, we could potentially build both `x86_64_linux` and `arm_linux` on Jenkins.

Here's two related ARM on Travis conversations:
- https://github.com/travis-ci/travis-ci/issues/3376
- https://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html

**Comment by DoomHammer** [comment]
And where to put this Jenkins? Do we have some AWS instances for that?

**Comment by sjackman** [comment]
We don't have any such machine yet. If you get it up and running on your local box, and we decide it's a good way to go forward with bottling for Linuxbrew, then I can fire up an AWS instance to host it, at least for one year. After that we'll have to apply for [AWS Cloud Credits for Research](https://aws.amazon.com/research-credits/) or a similar program to keep Jenkins running.

**Comment by DoomHammer** [comment]
Sounds reasonable. So, where can I get the CircleCI config (minus secrets)?

**Comment by sjackman** [comment]
@DoomHammer Responded on Slack.
