### ISSUE TITLE
Can't link with -lX11

### ISSUE THREAD

**Issue by vladfi1** [Linuxbrew/brew#11]
I've used linuxbrew to install gcc 5.3 on a machine on which I don't have sudo access. I now want to link with X11:

```
> gcc test.c -lX11
ld: cannot find -lX11
```

I've checked that libX11.so exists in /usr/lib64/ which is on the compiler's LIBRARY_PATH. If I use the system's gcc it works fine, but I need a newer version to compile my actual program.

**Comment by vladfi1** [comment]
Some more information:

```
bash-4.2$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Linuxbrew/linuxbrew.git
HEAD: dc1c2b57d5b9253f19d667976d098ecb1a4566d8
Last commit: 2 weeks ago
HOMEBREW_PREFIX: /om/user/vladfi1/linuxbrew
HOMEBREW_REPOSITORY: /om/user/vladfi1/linuxbrew
HOMEBREW_CELLAR: /om/user/vladfi1/linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 40-core 64-bit ivybridge
Kernel: Linux 3.10.0-229.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.2.1511 (Core) 
OS glibc: 2.17
OS gcc: 4.8.5
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 2.0.0-p598 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby
Java: openjdk version "1.8.0_71"
bash-4.2$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /om/user/vladfi1/linuxbrew/sbin.
Consider setting the PATH for example like so
    echo 'export PATH="/om/user/vladfi1/linuxbrew/sbin:$PATH"' >> ~/.bash_profile

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.
```

**Comment by bw-yuhogg** [comment]
Maybe try adding `-Wl,-rpath,/usr/lib64`?

If that fails, there's some other advice at https://stackoverflow.com/questions/8835108/how-to-specify-non-default-shared-library-path-in-gcc-linux-getting-error-whil

**Comment by vladfi1** [comment]
Adding `-Wl,-rpath,/usr/lib64` didn't seem to change anything. The stackoverflow thread talks about a runtime error, not a linktime error, so I'm not sure if it is applicable.

**Comment by bw-yuhogg** [comment]
Can you show the LIBRARY_PATH variables for both compilers (system and Linuxbrew)? Maybe that will provide some more insight.

**Comment by vladfi1** [comment]
brew gcc:

```
LIBRARY_PATH=/om/user/vladfi1/linuxbrew/Cellar/gcc/5.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/:/om/user/vladfi1/linuxbrew/Cellar/gcc/5.3.0/bin/../lib/gcc/:/om/user/vladfi1/linuxbrew/Cellar/gcc/5.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/om/user/vladfi1/linuxbrew/Cellar/gcc/5.3.0/bin/../lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../:/lib/:/usr/lib/
```

system gcc:

```
LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
```

Note that both contain `/usr/lib/../lib64/`.

**Comment by bw-yuhogg** [comment]
I apologize, but I'm not sure.

As a workaround, if you'd like you can build Linuxbrew's X11 and try using that:

``` bash
$ brew tap linuxbrew/xorg
$ brew install xorg
```

**Comment by vladfi1** [comment]
My solution was to replace a bunch of instances of `-lFoo` with `/usr/lib64/libFoo.so`, which allowed the link step to succeed. The binary then crashed at runtime with missing libs, but that was fixed by exporting `LD_LIBRARY_PATH=/usr/lib64`.

Obviously I would like a better solution, as this requires editing autogenerated Makefiles.

**Comment by vladfi1** [comment]
I've also tried adding in `-L/usr/lib64`. If I'm using C++, I get an error.

```
$ g++ test.cpp -L/usr/lib64 -lX11
/om/user/vladfi1/linuxbrew/lib/libstdc++.so: undefined reference to `__cxa_thread_atexit_impl@GLIBC_2.18'
```

But it works if I use plain `gcc`.

**Comment by sjackman** [comment]
The simplest solution is `brew install linuxbrew/xorg/xorg`
The linuxbrewed gcc removes `/usr/lib64` from the default library path because mixing system libraries with brewed libraries creates havoc.

**Comment by vladfi1** [comment]
That worked! Thanks @sjackman for clearing this up.
