### ISSUE TITLE
docbook2x fails on perl dependency

### ISSUE THREAD

**Issue by adam-stokes** [Linuxbrew/brew#113]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

So I was just trying out this package manager and wanted to install something small to see how things went. I'm trying to install `pastebinit` and getting the following errors:

```
[adam:~] 130 $ brew doctor
Your system is ready to brew.
[adam:~] $ brew install pastebinit
==> Installing dependencies for pastebinit: docbook2x
==> Installing pastebinit dependency: docbook2x
==> Downloading https://downloads.sourceforge.net/docbook2x/docbook2X-0.8.8.tar.gz
Already downloaded: /home/adam/.cache/Homebrew/docbook2x-0.8.8.tar.gz
==> ./configure --prefix=/home/adam/.linuxbrew/Cellar/docbook2x/0.8.8
==> make install
Last 15 lines from /home/adam/.cache/Homebrew/Logs/docbook2x/02.make:
docbook2man syntax OK
docbook2texi syntax OK
db2x_xsltproc syntax OK
Can't locate XML/SAX/ParserFactory.pm in @INC (you may need to install the XML::SAX::ParserFactory module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at db2x_manxml line 2413.
BEGIN failed--compilation aborted at db2x_manxml line 2413.
Makefile:383: recipe for target 'db2x_manxml' failed
make[1]: *** [db2x_manxml] Error 2
make[1]: *** Waiting for unfinished jobs....
Can't locate XML/SAX/ParserFactory.pm in @INC (you may need to install the XML::SAX::ParserFactory module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at db2x_texixml line 2147.
BEGIN failed--compilation aborted at db2x_texixml line 2147.
Makefile:389: recipe for target 'db2x_texixml' failed
make[1]: *** [db2x_texixml] Error 2
make[1]: Leaving directory '/tmp/docbook2x-20160921-12013-avdjyh/docbook2X-0.8.8/perl'
Makefile:255: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Linuxbrew/homebrew-core/issues
```

I did go through the troubleshooting steps along with making sure to install `brew install gcc`. My environments variables are:

```
export PATH="/home/adam/.linuxbrew/bin:$PATH"
export MANPATH="/home/adam/.linuxbrew/share/man:$MANPATH"
export INFOPATH="/home/adam/.linuxbrew/share/info:$INFOPATH"
export XDG_DATA_DIRS="/home/adam/.linuxbrew/share:$XDG_DATA_DIRS"
```

I see the formulae where it shows a `depends_on "XML::Parser" => :perl` but I'm not sure how that dependency is supposed to get installed or where it pulls from (didnt see it in `brew search`)

Thanks for any advice

**Comment by bw-yuhogg** [comment]
> I see the formulae where it shows a depends_on "XML::Parser" => :perl but I'm not sure how that dependency is supposed to get installed

You have to install it manually for the moment, unfortunately. `cpan XML::SAX::ParserFactory` should do the trick. Then you can retry the installation. If that doesn't work, you might also have to do `cpan XML::Parser`.

We've been struggling with this for months, unfortunately. The issue is with `docbook2x`, not `pastebinit` itself. https://github.com/Linuxbrew/homebrew-core/pull/326

**Comment by adam-stokes** [comment]
Is this just the matter of writing formulae for those perl dependencies?

**Comment by bw-yuhogg** [comment]
We want to have a way to easily install all of the Perl modules that macOS is known to ship without having to tell people all the time "oh, just do `cpan $some_perl_module` and then retry". That's complicated by the fact that there's lots of different ways the Perl requirement can be satisfied - by a system Perl, by brewed Perl, by a Perl installed through `perl-build` or similar, etc.

@DoomHammer has been working on this issue; anything you'd like to add?

**Comment by adam-stokes** [comment]
Gotcha. Personally, I would treat brew as the authoritative source and have `brew` install `cpanminus` and have the `depends_on` trigger that `cpanm` install for it's dependencies. I wouldn't worry about checking in system locations for those modules.
