### ISSUE TITLE
Linuxbrew not working on Windows10 Linux Subsystem

### ISSUE THREAD

**Issue by erwstout** [Linuxbrew/brew#117]
Hello!

So I know this might be a little out of scope here, but I am trying to install Linuxbrew on the Ubuntu subsystem in Windows 10. 

When I run

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
PATH="$HOME/.linuxbrew/bin:$PATH"
```

Everything appears fine but one warning line:

```
Warning: /home/ericstout/.linuxbrew/bin is not in your PATH.
```

However, when I edit my bash profile by using `nano ~/.bash_profile` I have the paths setup:

```
#LinuxBrew
echo 'export PATH="/home/ericstout/.linuxbrew/bin:$PATH"' >>~/.bash_profile
echo 'export MANPATH="/home/ericstout/.linuxbrew/share/man:$MANPATH"' >>~/.bash_profile
echo 'export INFOPATH="/home/ericstout/.linuxbrew/share/info:$INFOPATH"' >>~/.bash_profile
```

When I try to run any `brew` commands I get an error of `command not found`

Any thoughts as to why this may be happening? I appreciate the support and the awesome work (I use Linuxbrew on other machines as well and I love it.)

Thanks!

**Comment by sjackman** [comment]
Try running at the command line:

``` sh
echo 'export PATH="/home/ericstout/.linuxbrew/bin:$PATH"' >>~/.bash_profile
echo 'export MANPATH="/home/ericstout/.linuxbrew/share/man:$MANPATH"' >>~/.bash_profile
echo 'export INFOPATH="/home/ericstout/.linuxbrew/share/info:$INFOPATH"' >>~/.bash_profile
```

or alternatively to your `~/.bash_profile`

``` sh
PATH="/home/ericstout/.linuxbrew/bin:$PATH"
MANPATH="/home/ericstout/.linuxbrew/share/man:$MANPATH"
INFOPATH="/home/ericstout/.linuxbrew/share/info:$INFOPATH"
```

Then start a new shell and report the output of

``` sh
echo $PATH
which brew
```

**Comment by erwstout** [comment]
I followed the `echo` approach and then verified it was written to `~/.bash_profile` and it was. When I run `echo $PATH` it returns:

``` sh
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

Which doesn't appear to be correct, although this part is a little over my head so I'm not exactly sure how to remedy it.

Running `which brew` returns nothing at all. Just a blank command prompt.

Any other suggestions? Thanks for your help!

EDIT: I wonder if that `$PATH` has anything to do with the application SteamMover which allows you to move Steam games to different locations while still being installed... Seems like that would be possible but wouldn't that not affect the Linux subsystem?

**Comment by sjackman** [comment]
> Then start a new shell and report the output of

After modifying `~/.bash_profile` you have to open a new shell to make the change take effect. Alternatively enter at the command line

``` sh
PATH="/home/ericstout/.linuxbrew/bin:$PATH
echo $PATH
which brew
```

**Comment by erwstout** [comment]
Yeah, I did open a new shell and thats what I got. When I get home I'll test again. Thanks!

**Comment by sjackman** [comment]
Hmm. I'm not sure how the Windows 10 shell is configured. Try modifying `~/.bashrc` instead of `~/.bash_profile`

**Comment by retokromer** [comment]
Or put `source ~/.bashrc` into `~/.bash_profile`.

**Comment by BrianHawley** [comment]
The Windows bash session is not a login shell, unless you provide a `--login` command line parameter to bash.exe, usually in the properties of its shortcut. I had to do something similar to get rvm running in WSL.

**Comment by erwstout** [comment]
Just to update, I've been incredibly busy and have not been able to come back to this and probably will not be able to in the foreseeable future, as I've had to go back to my normal dev environment for now.

**Comment by sjackman** [comment]
I'm going to close this issue in the mean time. Feel free to come back to it, and we'll reopen the issue.

**Comment by spences10** [comment]
@sjackman apologies for digging this up but I was thinking about using Linuxbrew ans was wondering if this is still an issue?

Thanks

**Comment by sjackman** [comment]
From the reports that I've read, Linuxbrew is working on Windows Subsystem for Linux. Feel free to open a new issue if you encounter any trouble.
