### ISSUE TITLE
List of installed binaries

### ISSUE THREAD

**Issue by jinmel** [Linuxbrew/brew#123]
Just like the requirements.txt in python or package.json in node is there a file that keeps track of installed binaries? `brew install` to install all binaries listed in a specific file would be convenient.

**Comment by bw-yuhogg** [comment]
You may wish to try https://github.com/homebrew/homebrew-bundle:

``` bash
% brew tap Homebrew/bundle;
```

**Comment by sjackman** [comment]
`brew bundle` is a useful tool. Here's a low-tech solution:

``` sh
brew list >my-installed-packages
brew install `<my-installed-packages`
```

**Comment by jinmel** [comment]
Thanks for letting me know this :smile:
