### ISSUE TITLE
hello failed to build on Raspbian 8 (jessie) - *** Error in `/usr/bin/gcc-4.9': double free or corruption (top): 0x00330718 ***

### ISSUE THREAD

**Issue by jorgelopezs** [Linuxbrew/brew#137]
I ran `brew install hello`. I got the error below.
https://gist.github.com/jorgelopezs/0e8ea41c1ca2d6f9f7461942e52ec958

This is hello's my [config.log](https://gist.github.com/jorgelopezs/a1024c382833c21cad7b9e7fa4c38757).

This is the [01.configure](https://gist.github.com/jorgelopezs/8c77c840390ef74e21bcae7c7796082e)

Here's my Raspbian version. https://gist.github.com/jorgelopezs/f53fd5985cfa3c3007270c781154c9e1

I updated my GCC and G++ version to the latest 6.2. The default that comes with Raspbian 8 is gcc 4.9. Below is my ouput of `gcc -v`.
https://gist.github.com/jorgelopezs/83fc1e981178a3d77c528567dcaf286b

I researched and found that the error `double free or corruption (top): 0x00330718` is a known bug in gcc 4.9. It has been fixed in gcc 6.2. [Source Here.](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139091).

The error is caused while ./configure is testing for the compiler. The flag that's causing it is `-march=native`. A user in the forum topic posts a solution to the error. The solution consists of adding `-mcpu=cortex-a53 -mfpu=neon-vfpv4` to the formula. I ran `brew edit hello` and added the fix as  https://gist.github.com/jorgelopezs/b58a33da62e630fc7688093c688be9c8

Success. `hello` installs successfully. Now the issue comes with installing other formulas. I add the same flags and it doesn't work. 
### Gcc 6.2 has fixed the bug. I have it installed as the default gcc. Why is `brew` ignoring the updated version of gcc-6 and still compiling with gcc 4.9? Is there any way of forcing `brew` to use gcc 6.2?

For example I tried to install `node` formula. The `/.configure` goes ok, but if fails on `make`. Make still tries to compile with gcc 4.9 and fails every time. Why doesn't it use my default gcc 6.2?

I tried setting `CC=/usr/local/gcc-6.2/gcc-6 CXX=/usr/local/gcc-6.2/g++-6` before invoking `brew install node` and are ignored.
### I found a temporary Fix
1. `brew install -vd formula` 
2. Wait for it to fail on the error and select `shell` option.
3. On the shell CC is the old /usr/bin/gcc-4.9 and CXX=/usr/bin/g++-4.9. Execute `export CC=gcc` and `export CXX=g++`.
4. Run `./configure` again. This time `configure` picks up the updated gcc-6 and g++-6.
5. Execute `make install`. It compiles with no error since it uses gcc-6 and g++-6. Thank you.

**Comment by bw-yuhogg** [comment]
> I just need a way to force Linuxbrew to use gcc-6 and g++-6.

You should be able to accomplish this with the following:
1. Make symlinks named `gcc-6` and `g++-6` in your HOMEBREW_PREFIX/bin to the actual executables in /usr/local/bin.
2. Export the environment variable `HOMEBREW_CC=gcc-6` before compiling anything. This will force Linuxbrew to use GCC 6 (including `g++`).
3. You might also additionally have to run `brew tap homebrew/versions` if it refuses to let you use GCC 6. That's a bug in my opinion, since we don't require you to install alternate GCC's from the Homebrew versions tap and they're not guaranteed to work.

**Comment by sjackman** [comment]
Once you've created the symlinks, Linuxbrew should find them automatically (untested), in which case step 2 should be unnecessary.

**Comment by jorgelopezs** [comment]
@rwhogg It worked. Linuxbrew is recognizing `gcc-6`. No more error.

@sjackman You're absolutely right, only the 1st step is necessary. I added symlinks `gcc-6 and g++-6` to `HOMEBREW_PREFIX/bin` (in my case `/home/pi/.linuxbrew/bin/`.  

Thank you.

**Comment by bw-yuhogg** [comment]
Happy to help!
