### ISSUE TITLE
Any plans to support homebrew-php?

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/brew#139]
There is a homebrew-php repo that Linuxbrew does not have a fork of. I am currently installing the homebrew version after tapping it, but I had to make a modification to build on Linux. I would like to contribute it to the Linuxbrew group.

**Comment by bw-yuhogg** [comment]
First of all, thanks for offering to contribute your fix to Linuxbrew :smile_cat: 

homebrew-php is not currently supported. I've used a few of the formulae, like `composer`, with a system PHP before without major issues, but it's not supported either.

I would be _very_ happy to see it supported though. Easier availability of modern PHP versions (rather than outdated 5.3's and 5.4's) is nothing but a good thing.

My concern is that we currently lack the time necessary to properly support it, so I'm not ready to fork homebrew-php just yet.

I don't expect upstream will accept the modification, so my recommendation for now is to keep a fork of homebrew-php, but @sjackman might have a better suggestion.

**Comment by sjackman** [comment]
@ablyler @javian Would you accept patches to Homebrew/php that allow the formulas to build on Linuxbrew?

**Comment by javian** [comment]
@sjackman I'm for it and the only concern that I might have is the recent changes we made to require the httpd package to build on macOS Sierra but feel free to put in a proposal and we can have a look at it.

**Comment by sjackman** [comment]
That's excellent news, Javian. I don't use PHP myself, so I won't be the point person on this project, but I'm happy to answer questions and give opinions on any Linuxbrew questions about the PHP packages. Just tag in the question.

@carlorosati Would you like to submit a PR with your modifications to homebrew/php?

**Comment by carlorosati** [comment]
Sure. how would I make my changes? What if the settings for Linux and Mac are different? Do I need to wrap my changes in an if statement that tests for Linux? What's the standard procedure for this?

**Comment by sjackman** [comment]
Make the code portable so that it works on both Mac and Linux if possible. Use `if OS.mac?` and `if OS.linux?` as necessary but preferably sparingly.

**Comment by carlorosati** [comment]
--enable-dtrace is enabled by defualt.  This causes the build to fail on Linux if dtrace is not installed.
Would you rather 
1. check if dtrace is installed,
2. add dtrace as a formula dependency
3. wrap --enable-dtrace in OS.mac?

**Comment by sjackman** [comment]
`dtrace` does not currently have a formula for Linux. Would you be interested in creating a formula for https://github.com/dtrace4linux/linux?

Either `add dtrace as a formula dependency` or `wrap --enable-dtrace unless OS.linux?` are reasonable solutions.

**Comment by carlorosati** [comment]
Sure, I'm game.

EDIT:
Nevermind. You need sudo to install dtrace.

**Comment by sjackman** [comment]
I expect that you need `sudo` to load the `dtrace` kernel module. Is it possible to build and install the `dtrace` client libraries without `sudo`? Note that I'm not terribly familiar with `dtrace`.

**Comment by javian** [comment]
I would vote for wrapping dtrace in OS.mac? for now

**Comment by sjackman** [comment]
Works for me.

**Comment by black-snow** [comment]
@sjackman @carlorosati has this ever been resolved? Trying to `brew install php72` but it fails:

```
configure: error: Cannot find sys/sdt.h which is required for DTrace support
```

**Comment by sjackman** [comment]
@black-snow Hi, Roland. Homebrew/php is not a supported tap of Linuxbrew. You may, if you like, submit a PR to https://github.com/Homebrew/homebrew-php to add support for Linux to `php72`.

**Comment by iMichka** [comment]
Also, I think that most of the content of the pho tap is being migrated to homebrew core. But I do not known how far they went.

**Comment by javian** [comment]
We've not merged the first formula yet but its in the works. The aim is to retire the php tap before the summer and merge what's necessary in to core see https://github.com/Homebrew/homebrew-core/pull/16067 .

**Comment by black-snow** [comment]
In fact I'd like to help. Not sure how to start, though @sjackman

**Comment by sjackman** [comment]
@javian Is the person to ask about PHP.

**Comment by iMichka** [comment]
I think it will be easier when some php formulae have been migrated to core.

**Comment by unixfox** [comment]
I got a successful build of php on Linuxbrew by using `--with-phpdbg` because it disable dtrace on `./configure`: https://github.com/Homebrew/homebrew-php/blob/master/Abstract/abstract-php.rb#L379
```
brew install --with-phpdbg --without-ldap php72
```

**Comment by sjackman** [comment]
Thanks for the workaround, Emilien.
