### ISSUE TITLE
How to link with -lGL

### ISSUE THREAD

**Issue by vladfi1** [Linuxbrew/brew#14]
I'm compiling an application with `-lGL`, and this predictably fails because brew's ld doesn't use `/usr/lib64`. However, I can't figure out how to get a brew-compatible `libGL.so`. I tried `brew install`ing a some packages such as `homebrew/x11/freeglut` and `glew`, to no avail. I even tried installing `homebrew/x11/mesalib-glw` but it failed with missing `-lGL` -  I would have expected this package to at least bring in the right dependencies that provide `libGL.so`. This makes me suspect that there is no way to link with `-lGL` outside of manually changing each `-lGL` to `/usr/lib64/libGL.so`, which I hear may cause problems.

**Comment by sjackman** [comment]
This issue should probably be moved to https://github.com/Linuxbrew/homebrew-xorg
@rwhogg If you agree please move it.

**Comment by bw-yuhogg** [comment]
This issue was moved to Linuxbrew/homebrew-xorg#22
