### ISSUE TITLE
brew tap homebrew/science

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/brew#140]
```
==> Tapping homebrew/science
Cloning into '/home/timothee/temp/stage/brew/Library/Taps/homebrew/homebrew-science'...
remote: Counting objects: 647, done.
remote: Compressing objects: 100% (643/643), done.
remote: Total 647 (delta 0), reused 67 (delta 0), pack-reused 0
Receiving objects: 100% (647/647), 574.15 KiB | 0 bytes/s, done.
Error: Invalid formula: /home/timothee/temp/stage/brew/Library/Taps/homebrew/homebrew-science/opencv.rb
undefined method `>=' for nil:NilClass
Error: Cannot tap homebrew/science: invalid syntax in tap!
```

**Comment by bw-yuhogg** [comment]
@timotheecour: thanks for reporting!

We had a problem like that with `qscintilla2` just recently. Guess there's a formula in homebrew-science with the same problem.

Upstream is working on a general fix for this problem (which is that certain methods return `nil`, which can't be compared against), but until that fix lands we'll just have to fix individual formulae.

**Comment by bw-yuhogg** [comment]
@timotheecour can you try tapping again? I believe I've fixed `opencv`.

**Comment by sjackman** [comment]
I believe this bug is fixed.

**Comment by timotheecour** [comment]
yes thanks
