### ISSUE TITLE
Filename too long for Bash on Windows

### ISSUE THREAD

**Issue by siennathesane** [Linuxbrew/brew#141]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

https://github.com/Microsoft/BashOnWindows/issues/1226
### Problem

It looks like the error is related to the filename being too long. While this is really an issue with Homebrew in general, and I don't necessarily expect a fix from this team, I wanted to bring attention to it, as more users may use this as Bash on Windows becomes more popular. Granted, it's in Beta right now, but they are quickly hashing out most problems.

**Comment by sjackman** [comment]
Thanks for the heads up, Mike. You could try creating the `specs` file manually.

**Comment by siennathesane** [comment]
I know almost nothing about the homebrew internals. Any docs/web pages you can point me to?

**Comment by sjackman** [comment]
The `specs` file is GCC configuration file. Use `gcc -dumpspecs` to get the default `specs` file, then see the `gcc.rb` formula code for the lines that Linuxbrew adds to it. https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/gcc.rb#L266-L274
