### ISSUE TITLE
ChromeOS discussion

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#142]
@aghasemi wrote…

> Is there any active development on the ChromeOS version?

**Comment by sjackman** [comment]
Here's the Chromebook installation instructions:
https://github.com/Linuxbrew/brew/wiki/Chromebook-Install-Instructions

@DoomHammer What's the status of Linuxbrew on ChromeOS?

**Comment by DoomHammer** [comment]
Hi, I lack a ChromeOS machine myself, but tried installing Linuxbrew on a VM running ChromiumOS. If I recall correctly it mostly worked when bootstrapped using [Brewstrap](https://github.com/doomhammer/brewstrap). I would like to integrate it with upstream Linuxbrew/installer at some point, though I haven't touched it for a while.

**Comment by aghasemi** [comment]
Thank you. I'm pretty sure it will dramatically increase the market share of linuxbrew.

**Comment by DoomHammer** [comment]
@aghasemi If you could try Brewstrap and tell whether it works for you I would be obliged :)

**Comment by aghasemi** [comment]
I don't have Chromebook myself :D 
I will try it on CloudReady.

**Comment by DoomHammer** [comment]
That's what I use as well :)

**Comment by aghasemi** [comment]
Maybe we can ask reddit users for testing?
https://www.reddit.com/r/chromeos/
https://www.reddit.com/r/Crouton/

**Comment by sjackman** [comment]
Let's confirm that it works without any significant gotchas before we release it upon the reddit hoards.

**Comment by aghasemi** [comment]
Hi,
I tried to do the step by step guide mentioned here:
https://github.com/Linuxbrew/brew/wiki/Chromebook-Install-Instructions. 

At this step: 

> Let's see if everything is working. For now to make gcc work right we need to temporarily set LD_LIBRARY_PATH.
> 
> ``````
> export LD_LIBRARY_PATH=/usr/local/lib
> brew install hello && brew test hello && brew remove hello
> unset LD_LIBRARY_PATH. ```
> ``````

I got this error:

`/bin/bash: symbol lookup error: /bin/bash: undefined symbol: rl_signal_event_hook`

Any idea?

I'm on the un-official VirtualBox image of the CloudReady team, version 48: https://neverware.zendesk.com/hc/en-us/articles/214564457--UPDATED-Un-Official-CloudReady-Virtual-Machine-Images-

**Comment by sjackman** [comment]
~~That symbol `rl_signal_event_hook` may be defined in `librt.so`. I haven't confirmed.~~
This symbol is defined by `readline`.

**Comment by aghasemi** [comment]
Which means??

I tried copying librt.so.1 and librt-2.19.so from /lib to /usr/local/lib or lib64. No success. If you unset LD_LIBRARY_PATH, this error is not thrown, but another set of errors are given, which I think is expected.

**Comment by aghasemi** [comment]
Thank you. I'm pretty sure it will dramatically increase the market share
of linuxbrew.


On Mon, Oct 24, 2016 at 11:52 AM, Piotr Gaczkowski <notifications@github.com

**Comment by sjackman** [comment]
Setting `LD_LIBRARY_PATH` can create all sorts of havoc that are difficult to debug. Perhaps @DoomHammer has a suggestion to avoid setting `LD_LIBRARY_PATH`.

**Comment by DoomHammer** [comment]
Didn't have time recently to get back to it, but I will try to get up to date (both myself and the code). I remember I had some issues regarding `glibc` installation via `brewstrap` but don't quite remember whether they were seen on ChromeOS or other systems.

**Comment by sjackman** [comment]
I just had an idea for a workaround for installation prefix. Try

``` sh
mkdir /home/linuxbrew
ln -s /usr/local/.linuxbrew /home/linuxbrew/.linuxbrew
```

And then try installing a bottle using `--force-bottle`, for example

``` sh
brew install --force-bottle openssl
```

Untested, but it might work!

**Comment by aghasemi** [comment]
May I ask ignorantly what is a bottle and why should we force it? :)

**Comment by sjackman** [comment]
Not at all. A bottle is a precompiled binary package. Using bottles means you don't have to compile packages from source.

**Comment by axk4545** [comment]
@sjackman is this resolved and do the instructions for ChromeOS on the wiki work?

**Comment by sjackman** [comment]
I don't have access to a ChromeOS device, so I don't know the answer myself. The wiki is publicly editable for anyone who would like to update it.
