### ISSUE TITLE
Install receipt generation breaks over NFS and nothing can be installed

### ISSUE THREAD

**Issue by 00dani** [Linuxbrew/brew#146]
I've installed Linuxbrew following the prescribed steps, on a RHEL system where I have no root access. Installation ran without a hitch - however, attempting to install any package fails miserably:

``` shellsession
$ brew install hello
==> Installing dependencies for hello: patchelf, zlib, binutils, linux-headers, glibc, xz, gmp, mpfr, libmpc, isl, gcc
==> Installing hello dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/c3120668/.cache/Homebrew/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
Error: Device or resource busy - (/home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1/INSTALL_RECEIPT.json20161025-23513-1b3nqxm, /home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1/INSTALL_RECEIPT.json)
Warning: Bottle installation failed: building from source.
==> Downloading http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz
Already downloaded: /home/c3120668/.cache/Homebrew/patchelf-0.9.tar.gz
==> ./configure --prefix=/home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1 CXXFLAGS=-static-libgcc -static-libstdc++ --disable-silent-rules
==> make install
Error: Device or resource busy - (/home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1/INSTALL_RECEIPT.json20161025-24031-exh1it, /home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1/INSTALL_RECEIPT.json)
```

It appears that everything depends on the presence of `patchelf` and fails in exactly the same way. I tried compiling my own copy of `patchelf`, which worked, but Homebrew still attempts to install its version and fails. Additionally, `brew cleanup` fails:

``` shellsession
$ brew cleanup
Error: Bad file descriptor - /home/c3120668/.linuxbrew/var/homebrew/locks/update
```

My assumption is that all these filesystem errors are caused by the fact that my `$HOME` is an NFS mount. Indeed, I tried changing the location of `HOMEBREW_TEMP` to the local filesystem and `brew cleanup` was fixed, but installations still failed with no change.

``` shellsession
$ mount | grep $LOGNAME
zfssa0:/export/uncle/home/student/c3120668 on /home/c3120668 type nfs (rw,nosuid,vers=4,hard,intr,sloppy,addr=134.148.4.212,clientaddr=134.148.4.104)
$ export XDG_RUNTIME_DIR=/tmp/xdg-$UID; export HOMEBREW_TEMP=$XDG_RUNTIME_DIR/brew
$ mkdir -p $HOMEBREW_TEMP
$ brew cleanup
$ # silently succeeded
```

Google indicates that Linuxbrew _does_ work over NFS, so this is all very unexpected.
- [x] Ran `brew update` and retried your prior step?
  
  Yes, I've run `brew update` twice and also tried removing `~/.linuxbrew` and reinstalling from scratch. No change.
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
  
  The only issue `brew doctor` shows is that my Git version is 1.7.1, and it recommends 1.7.10 or newer. I can't easily fix this since `brew install git` attempts to install `patchelf` and fails; since checking out the actual Homebrew repos worked fine, I don't think this is the cause.
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
  
  I can't `sudo` but I'm not seeing permission errors anyway.

**Comment by sjackman** [comment]
Hi, Danielle. I primarily use Linuxbrew on NFS, so I can confirm that it definitely can work on NFS. I'm afraid that I don't have a solution for you. 😕 Sorry. Perhaps your systems/IT group could help you troubleshoot the NFS error, and perhaps your NFS could be reconfigured to work. I'm not sure.

**Comment by 00dani** [comment]
Ah, curses. Hmm, perhaps the mount options are different?

```
type nfs (rw,nosuid,vers=4,hard,intr,sloppy,addr=134.148.4.212,clientaddr=134.148.4.104)
```

I looked these up, however, and none of them seem like they'd cause a problem here. :confused:

**Comment by sjackman** [comment]
If it's helpful to you…

```
isilon:/ifs/home/sjackman on /home/sjackman type nfs (rw,tcp,nfsvers=3,rsize=32768,wsize=32768,sloppy,addr=10.1.2.3)
```

**Comment by sjackman** [comment]
This page suggests switch from `nfsvers=4` to `nfsvers=3` (I'm not sure why):
https://www.veeam.com/kb1741

**Comment by 00dani** [comment]
Hmm, that'd be worth a try, but it looks like I don't actually have the ability to adjust the mount options, given that I'm not root and FUSE isn't installed. :expressionless: Are there environment variables I can change to move the install receipts elsewhere, or something like that? It seems from the output that installing `patchelf` actually works but just fails to rename the receipt when it's done.

Of course it's possible a more complex package than `patchelf` will require more from the filesystem and therefore also not work over NFS. :sleepy:

**Comment by sjackman** [comment]
It's a long shot, but you could try a more recent version of Ruby. Which version of Ruby are you using? Check out http://phusion.github.io/traveling-ruby/

**Comment by sjackman** [comment]
Also try:

```
brew install -dv patchelf
brew gist-logs patchelf
```

**Comment by 00dani** [comment]
The system Ruby is 1.8.7 and there's no `gem` or `irb` command available, so it's entirely possible installing a Better Ruby will help. I'll give that a go. :cat2:

**Comment by 00dani** [comment]
``` shellsession
$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```

Under this version I get a slightly more descriptive error message, but still not a success:

```
Error: Device or resource busy @ sys_fail2 - (/home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1/INSTALL_RECEIPT.json20161025-32923-31w6yu, /home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1/INSTALL_RECEIPT.json)
```

Here're the [gist-logs](https://gist.github.com/anonymous/ae70e6af197dea7574767af97a09e12e) - it looks like the build went totally fine, and the "device or resource busy" error doesn't even appear in that gist.

**Comment by sjackman** [comment]
Does `brew install -dv patchelf` report a Ruby stack traceback?

**Comment by 00dani** [comment]
Yes, here's the [full output](https://gist.github.com/00dani/aad8d56578033e9bbd70bda4fed2f870). The NFS mount doesn't like something to do with renaming, it seems?

**Comment by sjackman** [comment]
```
make[2]: Leaving directory `/tmp/patchelf-20161026-57796-a0dxpy/patchelf-0.9'
make[1]: Leaving directory `/tmp/patchelf-20161026-57796-a0dxpy/patchelf-0.9'
==> Kept temporary files
Temporary files retained at /tmp/patchelf-20161026-57796-a0dxpy
Error: Device or resource busy @ sys_fail2 - (/home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1/INSTALL_RECEIPT.json20161026-57796-lyp92r, /home/c3120668/.linuxbrew/Cellar/patchelf/0.9_1/INSTALL_RECEIPT.json)
/home/c3120668/.linuxbrew/Library/Homebrew/extend/pathname.rb:182:in `rename'
/home/c3120668/.linuxbrew/Library/Homebrew/extend/pathname.rb:182:in `atomic_write'
/home/c3120668/.linuxbrew/Library/Homebrew/tab.rb:329:in `write'
/home/c3120668/.linuxbrew/Library/Homebrew/build.rb:139:in `block in install'
/home/c3120668/.linuxbrew/Library/Homebrew/formula.rb:1080:in `block in brew'
/home/c3120668/.linuxbrew/Library/Homebrew/formula.rb:1814:in `block in stage'
/home/c3120668/.linuxbrew/Library/Homebrew/resource.rb:98:in `block in unpack'
/home/c3120668/.linuxbrew/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/home/c3120668/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `block in run'
/home/c3120668/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `chdir'
/home/c3120668/.linuxbrew/Library/Homebrew/extend/fileutils.rb:74:in `run'
/home/c3120668/.linuxbrew/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/home/c3120668/.linuxbrew/Library/Homebrew/resource.rb:94:in `unpack'
/home/c3120668/.linuxbrew/Library/Homebrew/resource.rb:86:in `stage'
/home/c3120668/.linuxbrew/Library/Homebrew/formula.rb:1801:in `stage'
/home/c3120668/.linuxbrew/Library/Homebrew/formula.rb:1075:in `brew'
/home/c3120668/.linuxbrew/Library/Homebrew/build.rb:112:in `install'
/home/c3120668/.linuxbrew/Library/Homebrew/build.rb:187:in `<main>'
```

https://gist.github.com/00dani/aad8d56578033e9bbd70bda4fed2f870#file-brew-install-dv-patchelf-L168

**Comment by sjackman** [comment]
Yeah, here's the line of code that's failing:
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/pathname.rb#L182

I'm afraid that I don't have the time to dig into this myself. =/

**Comment by 00dani** [comment]
Ah, no problem. I'll try poking at it myself now I know how to get a stack trace. 😄

**Comment by 00dani** [comment]
It looks like the problem is that that method, `atomic_write`, tries to rename the temp file without closing the file handle first. Presumably this works on a Normal filesystem because POSIX is cool that way, but it confuses my NFS setup. Making this change, as far as I can tell, fixes installation entirely:

``` diff
diff --git a/Library/Homebrew/extend/pathname.rb b/Library/Homebrew/extend/pathname.rb
index 04ba77f..76e1717 100644
--- a/Library/Homebrew/extend/pathname.rb
+++ b/Library/Homebrew/extend/pathname.rb
@@ -179,6 +179,7 @@ class Pathname
       rescue Errno::EPERM
       end

+      tf.close
       File.rename(tf.path, self)
     ensure
       tf.close!
```

I'm still building `glibc` so it remains to be seen whether _everything_ now works, but it's looking promising. 😉

**Comment by sjackman** [comment]
Nice work, Danielle! Please submit a PR, and I'll merge tout de suite once it passes CI.
I'm somewhat surprised that you're the first person to run into this issue. I wonder what's unique about your particular NFS configuration.

**Comment by sjackman** [comment]
Merged. Thanks for the fix, Danielle!
