### ISSUE TITLE
Cannot update Linuxbrew

### ISSUE THREAD

**Issue by siennathesane** [Linuxbrew/brew#149]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

I cannot properly update linuxbrew due to unstaged changes. Stashing changes fails to resolve the issue.

``` bash
$ cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
remote: Counting objects: 231, done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 231 (delta 119), reused 231 (delta 119), pack-reused 0
Receiving objects: 100% (231/231), 133.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (119/119), completed with 5 local objects.
From https://github.com/Linuxbrew/brew
 * [new branch]      gh-pages   -> origin/gh-pages
   186ff68..7e9cdc7  master     -> origin/master
HEAD is now at 7e9cdc7 atomic_write: Close before rename for Linuxbrew
Cannot rebase: You have unstaged changes.
Please commit or stash them.
To restore the stashed changes to /mnt/archives/mike/.linuxbrew/Library/Taps/homebrew/homebrew-core run:
  'cd /mnt/archives/mike/.linuxbrew/Library/Taps/homebrew/homebrew-core && git stash pop'
Already up-to-date.
```

**Comment by sjackman** [comment]
> Cannot rebase: You have unstaged changes.
> Please commit or stash them.

You have modified files in Linuxbrew. Undo those modifications, or if you prefer, reinstall Linuxbrew.
