### ISSUE TITLE
git: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#15]
`git` includes 114 hard links to the same `git` executable. Running `patchelf` on the same executable 64 times breaks it and gives the above error message. We can work around this issue by checking whether the executable has already been patched and skip it if so.

I've opened an upstream `patchelf` issue: https://github.com/NixOS/patchelf/issues/96

**Comment by DoomHammer** [comment]
Workaround implemented in #20

**Comment by sjackman** [comment]
Thanks, Piotr!
