### ISSUE TITLE
Permission problem in ChromiumOS

### ISSUE THREAD

**Issue by aghasemi** [Linuxbrew/brew#150]
Hi,

I tried the easy way for ChromiumOS. First I installed Chromebrew, and then tried to install linuxbrew using the ordinary ruby line in linuxbrew.sh.

Both installations went ok until the end, but when trying `brew install hello` I got a permission error. If I do `sudo brew install hello` it complaints of not finding brew.

Any idea?

**Comment by aghasemi** [comment]
Update: I moved `.linuxbrew` to `/usr/local/`. Now I get the good old `bash: symbol lookup error: bash: undefined symbol: rl_signal_event_hook`.

**Comment by sjackman** [comment]
> Update: I moved .linuxbrew to /usr/local/

That's probably not a good plan. The best installation location for Linuxbrew is `/home/linuxbrew/.linuxbrew`

**Comment by aghasemi** [comment]
ChromeOS doesn't allow running scripts in home. No?

**Comment by sjackman** [comment]
I know pretty much nothing about ChromeOS.
@DoomHammer Where do you recommend installing Linuxbrew on ChromeOS?

**Comment by DoomHammer** [comment]
`/usr/local/.linuxbrew` unfortunately.

**Comment by aghasemi** [comment]
May I ask why you don't allow running brew in root/su mode? That seems to be the only way in ChromeOS.

**Comment by sjackman** [comment]
Can you change the owner of `/usr/local/.linuxbrew` to your user? That's recommended over using `sudo`.

**Comment by aghasemi** [comment]
Done. No permission error any more, but the bloody `rl_signal_event_hook`. what does that even mean?

**Comment by sjackman** [comment]
Please open a new issue and report the exact command and error message related to `rl_signal_event_hook`.

**Comment by aghasemi** [comment]
I solved it with `brew remove readline`, as was mentioned in another issue.

**Comment by sjackman** [comment]
Thanks for the feedback.
