### ISSUE TITLE
node: /usr/bin/g++-5: Command not found

### ISSUE THREAD

**Issue by aghasemi** [Linuxbrew/brew#153]
Here's the result of `brew gist-logs npm`: (Great idea, btw)

https://gist.github.com/88ad4b9652214d6e4b90e1c2c9ea1cec

**Comment by sjackman** [comment]
```
make[1]: /usr/bin/g++-5: Command not found
```

Try

``` sh
sudo apt-get install build-essential
```

See http://linuxbrew.sh/#dependencies
