### ISSUE TITLE
Issue Downloading Binaries from linuxbrew.bintray.com

### ISSUE THREAD

**Issue by davidryderuk** [Linuxbrew/brew#155]
Hi,

I am running Ubuntu 14.04 (+ Bio Linux 8 packages) behind an internet proxy. When installing binutils, the installer fails to download the precompiled binaries, due to an issue with SSL certificates, and starts compiling packages from source. Investigating the issue, I found that Linuxbrew was using the system version of curl, with the following options:

`/usr/bin/curl --fail --remote-time --location --user-agent "Linuxbrew/1.0.7 (Linux; x86_64 Ubuntu 14.04.5 LTS) curl/7.35.0" https://linuxbrew.bintray.com/bottles/binutils-2.27.x86_64_linux.bottle.tar.gz -C 0 -o /home/david/.cache/Homebrew/binutils-2.27.x86_64_linux.bottle.tar.gz.incomplete`

I tried upgrading curl, from version 7.35.0 to 7.50.3, and found the issue solved, on the command line:

`curl --fail --remote-time --location --user-agent "Linuxbrew/1.0.7 (Linux; x86_64 Ubuntu 14.04.5 LTS) curl/7.35.0" https://linuxbrew.bintray.com/bottles/binutils-2.27.x86_64_linux.bottle.tar.gz -C 0 -o /home/david/.cache/Homebrew/binutils-2.27.x86_64_linux.bottle.tar.gz.incomplete`

However, since Linuxbrew specifically calls the system version of curl, I am still unable to download binaries using the 'brew install' command. Logs are attached.

[brew.txt](https://github.com/Linuxbrew/brew/files/558119/brew.txt)
[upgraded_curl.txt](https://github.com/Linuxbrew/brew/files/558118/upgraded_curl.txt)
[system_curl.txt](https://github.com/Linuxbrew/brew/files/558120/system_curl.txt)

Thanks,
David

**Comment by sjackman** [comment]
This bug should be fixed by #143. You won't see this fix until we release 1.0.8. If you're comfortable with `git`, you can fast-forward to the `master` branch.

**Comment by davidryderuk** [comment]
Thanks. That seems to work. I'll try and remember to check the master branch next time.
