### ISSUE TITLE
Brew is hard to run in a system with glibc 2.12

### ISSUE THREAD

**Issue by hzhangxyz** [Linuxbrew/brew#156]
When I install some package, it says glibc 2.14 required,
When I use LD_\* to use library provided by brew.
Then I run brew, brew itself encounter segment fault
What should I do?
Can I install all the library required within one time and don't check requirement?

**Comment by sjackman** [comment]
Don't use `LD_LIBRARY_PATH` with Linuxbrew. It will break things. Which package are you trying to install that requires `glibc` 2.14, and is the package in Linuxbrew?

**Comment by hzhangxyz** [comment]
Well, since the `/etc/resolv.conf` is emtpy, I must copy the origin `libc.so.6` and change `/etc/resolv.conf` to a file I can write, then use `$LD_PRELOAD` to use this libc first.

Then I git clone brew and add it to `$PATH` and `export LD_LIBRARY_PATH=$HOME/.linuxbrew/lib`

After that, I `brew install coreutils`, it reports `GLIBC_2.14 not found`,
and I try to install something like vim,
it also reports something like `GLIBC_2.15 not found (required by **~/.linuxbrew/lib/libxxx)`**

if I delete `$LD_PRELOAD`, then all the things go `segmentation fault (core dumped)`
but gcc in brew work well, but brew itself won't work any more.

**Comment by sjackman** [comment]
What is your end goal? What software are you trying to install?

> Well, since the /etc/resolv.conf is emtpy

You can `brew install glibc` and edit `$(brew --prefix)/etc/resolv.conf`
