### ISSUE TITLE
Can't install x264 with or without --force-bottle 

### ISSUE THREAD

**Issue by aghasemi** [Linuxbrew/brew#157]
no force bottle: https://gist.github.com/b35dfcc83fcecb036cee4522d96bda52

force bottle: https://gist.github.com/2876921688951f8845fddbaa8269d042

**Comment by sjackman** [comment]
`x264` isn't bottle. I've opened a PR to bottle it. https://github.com/Linuxbrew/homebrew-core/pull/1159
