### ISSUE TITLE
gflags requires Homebrew gcc?

### ISSUE THREAD

**Issue by dpo** [Linuxbrew/brew#162]
```
$ cat /proc/version 
Linux version 3.10.0-229.14.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Tue Sep 15 15:05:51 UTC 2015
$ uname -a
Linux amdahl 3.10.0-229.14.1.el7.x86_64 #1 SMP Tue Sep 15 15:05:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Without Homebrew gcc installed, `brew install -v gflags` yields

```
cmake: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Attempting to set `LD_LIBRARY_PATH` to point to a location where a native `libstdc++.so.6` is located (such as `/usr/lib64`) results in

```
cmake: relocation error: /usr/lib64/libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

The solution is

```
unset LD_LIBRARY_PATH
brew install gcc
brew install gflags
```

Is there a way to require Homebrew gcc in `gflags.rb`? There's `depends_on "gcc"` but that's not very elegant.

**Comment by sjackman** [comment]
Installing any bottle will pull in both `glibc` and `gcc` on a system that provides `glibc` < 2.19. Installing `glibc` on a system with `glibc` ≥ 2.19 isn't well tested or recommended, but is possible, at least in principle. This situation needs better testing, or perhaps implement a warning/error to recommend against it.
