### ISSUE TITLE
rake: Failed to execute /usr/bin/rake

### ISSUE THREAD

**Issue by dpo** [Linuxbrew/brew#165]
I guess my Linux system doesn't come with much:
```
$ brew install -v gist
==> Downloading https://github.com/defunkt/gist/archive/v4.5.0.tar.gz
Already downloaded: /home/mgi.polymtl.ca/doorba/.cache/Homebrew/gist-4.5.0.tar.gz
==> Verifying gist-4.5.0.tar.gz checksum
tar xzf /home/mgi.polymtl.ca/doorba/.cache/Homebrew/gist-4.5.0.tar.gz
==> /usr/bin/rake install prefix=/home/mgi.polymtl.ca/doorba/.linuxbrew/Cellar/gist/4.5.0
Failed to execute: /usr/bin/rake
```
Linux is quite unreliable when it comes to what you can assume is installed on the system, unfortunately. `brew install ruby` did the job. Perhaps `gem install gist` would also have done it?!

**Comment by sjackman** [comment]
Currently Homebrew assumes that `rake` is installed in the same directory as `ruby`.
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/fileutils.rb#L105
That requirement could be relaxed for Linuxbrew to check first in `RUBY_BIN` and if it's not found there to fall back to `PATH`. A PR would be welcome. Even better if it's merged upstream to `Homebrew/brew`.

**Comment by sjackman** [comment]
Thanks for the bug reports, Dominique.

**Comment by dpo** [comment]
No problem, sorry for the deluge of small issues.

**Comment by sjackman** [comment]
Not at all. It's helpful to document these installation issues.
