### ISSUE TITLE
XDG_DATA_DIRS

### ISSUE THREAD

**Issue by alexstaj** [Linuxbrew/brew#167]
Hi

Fresh install of desktop ubuntu 16.04.  I installed linuxbrew according to SOP.  Then it wants me to export $XDG_DATA_DIRS to my .profile.  So when I do this I can no longer login to the GUI of Ubuntu.

Apparently the GUI tries to load my .profile first which defines my $XDG_DATA_DIRS and then it can't find the appropriate files to continue the login and I get booted back to login screen.

If I don't set my $XDG_DATA_DIRS to $HOME/.linuxbrew/share then logging into the ubuntu GUI adds all these directories to $XDG_DATA_DIRS variable and login can proceed through the GUI.

So how can I have $HOME/.linuxbrew/share append to $XDG_DATA_DIRS after successful login to the GUI?

**Comment by sjackman** [comment]
@alexstaj Please report the output of `echo $XDG_DATA_DIRS` without modifying `~/.profile`
@DoomHammer  Any suggestions?

**Comment by alexstaj** [comment]
so without modifying ~/.profile if I login via commandline only echo $XDG_DATA_DIRS returns nothing.  If however I login via the GUI it returns:

```
/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
```

I have settled into this modification of my ~/.profile until a better solution can be found:

``` sh
export XDG_DATA_DIRS="/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop:$HOME/.linuxbrew/share:$XDG_DATA_DIRS"
```

**Comment by DoomHammer** [comment]
That would be my suggestion, yes :)

Another approach: `export XDG_DATA_DIRS=$XDG_DATA_DIRS:$HOME/.linuxbrew/share`

**Comment by alexstaj** [comment]
yes thanks DoomHammer your suggestion worked!
