### ISSUE TITLE
Bug: Setting RPATH when running CMake breaks builds

### ISSUE THREAD

**Issue by rleigh-codelibre** [Linuxbrew/brew#171]
Linuxbrew is forcibly setting the `CMAKE_BUILD_WITH_INSTALL_RPATH` and `CMAKE_INSTALL_RPATH_USE_LINK_PATH` variables when building with CMake.  This breaks builds by forcing the rpaths to be invalid during the build, breaking all unit tests (or any running of code in the build tree).  This is basically any CMake build involving a shared library.  Here's an example:

- https://github.com/Homebrew/homebrew-science/pull/4569
- https://s3.amazonaws.com/archive.travis-ci.org/jobs/173396623/log.txt

Why it it setting the *BUILD* rpath rather than just the *INSTALL* rpath?  That is to say, setting `CMAKE_BUILD_WITH_INSTALL_RPATH` when `CMAKE_INSTALL_RPATH` is the correct one to use?  So long as `LD_LIBRARY_PATH` contains the linuxbrew root during the build, so it can find the dependency libs when running unit tests, it should be able to then run the unit tests properly.

While what you are doing is probably OK in setting a usable runtime environment after installation (modulo all the caveats of using rpath in the first place), but it's not OK in creating a usable runtime environment for package building.

Regards,
Roger

**Comment by sjackman** [comment]
- 2015-05-06 https://github.com/Linuxbrew/brew/commit/9875b9154e792e622f5ac8fcbeb17709c3c84d13 adds `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=1`
- 2015-06-26 https://github.com/Linuxbrew/brew/commit/07c7f4407afa278e9e017aeb030a0f663899d17f adds `-DCMAKE_BUILD_WITH_INSTALL_RPATH=1`

Both of these commits addressed a particular build error, but I sadly did not record which issue they addressed. I know that this particular issue has been reported before (probably back in legacy-linuxbrew somewhere, or possibly in Homebrew-science). Although I'm not yet sure what the proper solution is, I'm going to revert these two commits. I'm fairly sure that this change will cause new build failures in other formula. We can address those failure when they happen and figure out what the correct solution is.

I've opened PR https://github.com/Linuxbrew/brew/pull/172 to revert these two commits.
@Linuxbrew/core Heads up.

**Comment by sjackman** [comment]
Merged #172. Let's hope it doesn't break too too much.
