### ISSUE TITLE
Error: Invalid formula: internetarchive.rb: cannot load such file -- utils/json

### ISSUE THREAD

**Issue by dongz9** [Linuxbrew/brew#194]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I installed linuxbrew today and met the following error:

```
==> Tapping homebrew/core
Cloning into '/home/dongz/.linuxbrew/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3775, done.
remote: Compressing objects: 100% (3665/3665), done.
remote: Total 3775 (delta 12), reused 340 (delta 1), pack-reused 0
Receiving objects: 100% (3775/3775), 3.05 MiB | 0 bytes/s, done.
Resolving deltas: 100% (12/12), done.
Error: Invalid formula: /home/dongz/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/internetarchive.rb
cannot load such file -- utils/json
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing: /home/dongz/.linuxbrew/bin/brew tap homebrew/core
```

### Propose a feature:

Instead of creating an issue here, please create a pull request with your change proposal in the [Homebrew Evolution](https://github.com/Homebrew/brew-evolution) repository using the [proposal template](https://github.com/Homebrew/brew-evolution/blob/master/proposal_template.md).

**Comment by sjackman** [comment]
I can confirm this bug. I'll try to fix it up this weekend. Sorry for the gaff.

**Comment by dongz9** [comment]
Thanks!

**Comment by sjackman** [comment]
This issue will soon be resolved by Linuxbrew/homebrew-core#1231.

**Comment by alexanderadam** [comment]
Awesome. The merged stuff works like charm. :tada: 

IMHO this issue can be closed now.

**Comment by sjackman** [comment]
Thanks for the follow up, Alexander.
