### ISSUE TITLE
portable ruby for armhf

### ISSUE THREAD

**Issue by jperon** [Linuxbrew/brew#206]
Hello,

While trying to install linuxbrew on a nokia n900, it fails with message `Failed to install vendor ruby`. I tried to manually launch `brew vendor-install ruby`, and so I saw that it tried to install [that version of portable ruby](https://homebrew.bintray.com/bottles-portable/:portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz), which evidently failed. Does an arm version exist, or are there guidelines so I could try creating one myself ?

Thank you !

**Comment by sjackman** [comment]
Hi, @jperon. No, a portable ruby bottle does not exist for `arm`. You can however install a version of `ruby` 2.0 or greater in your `PATH`, and Linuxbrew will use it. I like to use Traveling Ruby, but I don't know whether they support ARM. https://github.com/phusion/traveling-ruby
