### ISSUE TITLE
Need a way to override march=native in CFLAGS

### ISSUE THREAD

**Issue by rsdubtso** [Linuxbrew/brew#208]
Hi, I'm using linuxbrew on a bunch of x86-64 machines w/ different Linux versions and CPUs, and with $HOME shared via NFS. In order to be able to use the same install on all the machines, and to be able to build packages (from source) on any machine, I need a way to set arch-specific option to the minimal supported across all the machines (sse2 would be a safe bet). However, I see from the source code that actually linuxbrew overrides all the march settings, so I wonder if such a feature would be deemed useful. A knob which forces linuxbrew to always install its own glibc would be useful too.

**Comment by sjackman** [comment]
`export HOMEBREW_ARCH=core2` should do what you want.

> A knob which forces linuxbrew to always install its own glibc would be useful too.

Right after a fresh installation of Linuxbrew, run `brew install glibc gcc`
This might work with an existing installation of Linuxbrew, but it's not heavily tested.

**Comment by rsdubtso** [comment]
Sorry for a delay. As far as I can tell, HOMEBREW_ARCH=core2 worked.
