### ISSUE TITLE
test-bot: Repeated timeouts on Circle CI during brew uses

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#211]
See for example https://github.com/Linuxbrew/homebrew-core/pull/1430, https://github.com/Linuxbrew/homebrew-core/pull/1436, https://github.com/Linuxbrew/homebrew-core/pull/1438, and https://github.com/Linuxbrew/homebrew-core/pull/1448.

Similar in both cause and symptom to https://github.com/Linuxbrew/legacy-linuxbrew/issues/939

**Comment by sjackman** [comment]
Should be fixed by https://github.com/Linuxbrew/brew/pull/217
