### ISSUE TITLE
Creating formulae that work for both homebrew and linuxbrew

### ISSUE THREAD

**Issue by caarlos0** [Linuxbrew/brew#220]
Currently, I'm doing it in the following way:

```ruby
class Antibody < Formula
  desc "A faster and simpler antigen written in Golang."
  homepage "http://getantibody.github.io"
  url "https://github.com/getantibody/antibody/releases/download/v2.2.2/antibody_#{%x(uname -s).gsub(/\n/, '')}_#{%x(uname -m).gsub(/\n/, '')}.tar.gz"
  head "https://github.com/getantibody/antibody.git"
  version "v2.2.2"

 # etc
end
```

I find this **very** hacky and ugly. Is there any better way of doing this?

**Comment by bw-yuhogg** [comment]
In cases where the URL is different for Linux and Mac, I usually prefer to do this:

```ruby
if OS.mac?
  url "..."
elsif OS.linux?
  url "..."
end
```

That also allows you to have different SHA-256's for each download and works for all the different things people might call macOS releases (I've variously seen "darwin", "osx", "mac", etc. For Linux it's pretty reliably just "linux").

Still, I agree that it's not great. If it's just one link to update every time you need to bump the formula, it's no big deal; if it's several, it can quickly become a pain.

@sjackman, any better suggestions?

**Comment by caarlos0** [comment]
@rwhogg that will solve the `uname -s` part, but not the `uname -m` (x86_64, i386, etc)...

But, yeah, looks better already...
