### ISSUE TITLE
SSL error when downloading ruby

### ISSUE THREAD

**Issue by staticfloat** [Linuxbrew/brew#222]
Trying to run the installation script or manually `git clone`'ing and then running `brew` results in the same error:

```
$ brew -v
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
```

It looks like although `wget` is happy to download the file, `curl` is [throwing some kind of SSL error](https://gist.github.com/staticfloat/e6decfd4fd68cd55c909e8e7e1976794).  This is on a fully updated Ubuntu 14.04 machine.

**Comment by staticfloat** [comment]
I should say that I bootstrapped this by manually downloading the `portable-ruby` bottle to `~/.cache/Homebrew`, then running `brew install -s` for each dependency of `curl` until I was able to just run `brew install -s curl`.  Now things are working okay, I assume because the TLS stack I'm using is now completely new (installing `openssl` has downloaded new certificate chains, my `curl` version is the latest `7.52` now, instead of the `7.47` that `trusty` comes with).

**Comment by sjackman** [comment]
Thanks for the bug report, Elliot. I don't have a fix for you, thanks for the workaround. I'll leave this issue open, in case it affects other people.

**Comment by sjackman** [comment]
I thought that I recalled an environment variable for either `openssl` or `curl` that allows it to use an insecure connection without giving an error similar to `curl -k,--insecure` but I'm not finding it now with a quick Google.

**Comment by trusktr** [comment]
Maybe the solution is to switch to wget, if that works?

**Comment by sjackman** [comment]
My suggested work around is:
```sh
HOMEBREW_BOTTLE_DOMAIN=https://homebrew.bintray.com brew fetch homebrew/portable/portable-ruby
```
or
```sh
curl -kLo `brew --cache portable-ruby` https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
brew -v
```
See also https://github.com/Linuxbrew/brew/issues/255
