### ISSUE TITLE
use linuxbrew/homebrew-X or homebrew/homebrew-X ? (for X not core)

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/brew#230]
@sjackman 

* is https://github.com/Linuxbrew/homebrew-science used at all? I only see very few issues (7 total)
* how do we even use it? Just filed a serious bug https://github.com/Homebrew/brew/issues/1855 that shows that `brew install linuxbrew/science/opencv3` leads to `Error: Formulae found in multiple taps` even though path is fully qualified
* could we have clearer guidelines for where to send PR's for non-core formula? https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md is not very clear on that: `Homebrew is merged into Linuxbrew roughly once per week` (is that homebrew-core only?)
* was https://github.com/Homebrew/homebrew-science/pull/4834 (fix vtk) filed in the right place, given that it was fixing an issue specific to linux, not mac?
* on linuxbrew, `brew tap --list-official` shows:
```
homebrew/apache
homebrew/completions
homebrew/dupes
homebrew/emacs
homebrew/fuse
homebrew/games
homebrew/gui
homebrew/nginx
homebrew/php
homebrew/python
homebrew/science
homebrew/tex
homebrew/x11
```
shouldn't it instead show overridden ones like `linuxbrew/science`? 

* if `linuxbrew/science` is not used, why is it listed in pinned repositories in https://github.com/Linuxbrew ?

* are linuxbrew/science and homebrew/science (and other official taps) also synced on same schedule as core?
* is continuous integration running at all homebrew-science (linuxbrew or homebrew)?
eg, https://github.com/Homebrew/homebrew-science/pull/4834 shows no travis/jenkins/circle info. This last question is related to https://github.com/Linuxbrew/homebrew-core/issues/1568

**Comment by sjackman** [comment]
> is https://github.com/Linuxbrew/homebrew-science used at all? I only see very few issues (7 total)

Only by me to build bottles for Homebrew/homebrew-science. It's not used by users.

> was Homebrew/homebrew-science#4834 (fix vtk) filed in the right place, given that it was fixing an issue specific to linux, not mac?

Yes.

> could we have clearer guidelines for where to send PR's for non-core formula? https://github.com/Linuxbrew/brew/blob/master/CONTRIBUTING.md is not very clear on that
> Homebrew is merged into Linuxbrew roughly once per week (is that homebrew-core only?)

brew, core, dupes and science are supported on Linuxbrew. Homebrew/science accepts Linux patches. Other patches should be sent to Linuxbrew/*. 

> are linuxbrew/science and homebrew/science (and other official taps) also synced on same schedule as core?

Yes, roughly weekly.

> shouldn't it instead show overridden ones like linuxbrew/science?

Yes, I think that makes sense. A PR would be welcome, at least to further the discussion.

>  is continuous integration running at all homebrew-science (linuxbrew or homebrew)?
eg, Homebrew/homebrew-science#4834 shows no travis/jenkins/circle info. This last question is related to Linuxbrew/homebrew-core#1568

Yes it's running on Circle, though the badge is not shown because the logs are not public and many non-bioinformatics formula fail. It would be helpful to also run Travis on Linux and show the badge, if it were possible to indicate that Linux is an allowable failure (until all the formula are known to build).

**Comment by timotheecour** [comment]
@sjackman my PR https://github.com/Homebrew/homebrew-fuse/pull/107 (fix s3fs for linuxbrew) was rejected by @ilovezfs in https://github.com/Homebrew/homebrew-fuse/pull/107#issuecomment-282461050 because:

> This will need to go in a Linuxbrew fork.

However, I see no linuxbrew fork for https://github.com/Homebrew/homebrew-fuse.
* could you please create a fork?
* How to deal with this case more generally?

**Comment by ylluminate** [comment]
@timotheecour huge help, thanks for looking into this and beating it down!

**Comment by sjackman** [comment]
There is no Linuxbrew fork for `Homebrew/fuse`.
(correction: ~~@maxim-belkin~~) @rwhogg has a PR that makes it so that on Linuxbrew `depends_on :osxfuse` is equivalent to `depends_on "libfuse"`. Hopefully that'll make much of `Homebrew/fuse` usable without forking.

**Comment by maxim-belkin** [comment]
phew

**Comment by sjackman** [comment]
At least I thought Bob did, but I can't seem to find the PR now.  The relevant code is here:
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/requirements/osxfuse_requirement.rb#L25

**Comment by bw-yuhogg** [comment]
> At least I thought Bob did

Sorry, it's work-in-progress and I haven't sent the PR yet.

**Comment by sjackman** [comment]
No worries. Thanks, Bob.

**Comment by ylluminate** [comment]
Any updates on this?

**Comment by bw-yuhogg** [comment]
Still working on it upstream. I'm sorry, my kernel died during my work on it, which slowed down progress.

**Comment by ylluminate** [comment]
@rwhogg sorry to hear about your kernel problems. I feel yer pain bro. :)
