### ISSUE TITLE
Improve error message for "Error: parent directory is world writable but not sticky"

### ISSUE THREAD

**Issue by dlukes** [Linuxbrew/brew#234]
Hi everyone,

I know `brew doctor` tells you how to resolve this issue (see e.g. [#477](https://github.com/Homebrew/brew/issues/477)), but still:

1. The message is slightly cryptic for someone not that well acquainted with *nix file permissions, plus it's not even clear *which* directory it's about. If a novice encounters it, they may not have the reflex to run `brew doctor` to discover more. I think it would be more newbie-friendly if this error message got expanded to include the guidelines to solve the issue.

2. The advice provided by `brew doctor` is the following:

```
Warning: /tmp is world-writable but does not have the sticky bit set.
Please execute `sudo chmod +t /tmp` in your Terminal.
```

This is true but incomplete, in the sense that you might be on a machine where you don't have an admin account (this is a frequent use case with Linuxbrew, at least for me), in which case you can't fool around with the permissions on `/tmp`, but the issue can still be solved by setting a custom `HOMEBREW_TEMP` . I think it would be a good idea to include this as an alternate fix, both in the output of `brew doctor` and under 1 above -- something along the lines of:

```
Alternatively, point HOMEBREW_TEMP to a directory you control,
e.g. `mkdir ~/tmp; export HOMEBREW_TEMP=~/tmp`.
```

I tried [reporting this upstream](https://github.com/Homebrew/brew/issues/1907), but the issue was closed on the grounds that it's not a big pain point with users and the non-admin use case argument is moot because Homebrew (unlike Linuxbrew) doesn't allow it. I still think such an improved message would be useful, especially for Linuxbrew users, hence this :)

**Comment by maxim-belkin** [comment]
I agree with you, David. Feel free to open a PR that does that. There is no guarantee that it will be accepted but it's worth trying.

**Comment by dlukes** [comment]
OK, thanks for the encouragement, I'll have a look at it tonight :)
