### ISSUE TITLE
Check ~/.bash_profile and ~/.profile in instructions for adding brew to PATH

### ISSUE THREAD

**Issue by nickjhathaway** [Linuxbrew/brew#235]
So in your instructions for installing linuxbrew and then to add linuxbrew to PATH you have

`echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile`

But the default on Ubuntu is ~/.profile to set up various things for bash. The problem is that bash actually has preference for ~/.bash_profile over ~/.profile and when both exists it will only source ~/.bash_profile and will not source ~/.profile by default. This means after running the above command to add linuxbrew to the PATH on login it will make it so that anyone who has ~/.profile will suddenly no longer have what they had set up in ~/.profile run by default. 

So if you changed your command to check for the existence of ~/.profile and add to that instead if it exists, this problem will no longer happen. 

`if [ -f ~/.profile ]; then echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.profile; else echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile; fi`

I only suggest the change because I tell a lot of people to install linuxbrew and I have had several people tell me that after they installed it their previous set ups for bash are broken and they aren't aware of this behavior with bash and ~/.profile and ~/.bash_profile.  

Thanks for you time!
Nick

**Comment by sjackman** [comment]
That's annoying. If the user has `~/.bash_profile` and we write to `~/.profile` it has no effect.
If the user has `~/.profile` and we write to `~/.bash_profile` it effectively replaces their configuration.
Ugh.

How about this?
```sh
echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.profile
test -e ~/.bash_profile && echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
```

Please submit a PR if you agree.

@Linuxbrew/core Review this please.

**Comment by maxim-belkin** [comment]
I don't think we can know in advance which files are sourced by user's shell. The safest solution would be to find all `~/.*profile` files and say something like:
```text
In order to use Homebrew, you have to make the following changes to your environment variables:

export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH"

To make these changes permanent, record them in the file that your shell calls when you start a new terminal. We've found the following files in your home directory:

    1. `.profile`
    2. `.bash_profile`
```

**Comment by sjackman** [comment]
If at all possible, it's easier to provide a command to effect the desired change that handles the most common cases (not necessarily all possible situations) than to describe it in English, which can be difficult for inexperienced users. It's safe for example to assume the user is using bash, because if they're not, they probably know that and know which file to edit.

**Comment by maxim-belkin** [comment]
then we should:
1. get the value of `$SHELL` env var.
2. check if `~/.profile` and `~/.bash_profile` exist. If they do, append `PATH=...` line to each of them and see how it affects the environment:
```
alias | wc -l
declare -F | wc -l
typeset -F | wc -l
compgen -A variable | grep -v HOMEBREW
compgen -A function | wc -l
```

**Comment by sjackman** [comment]
Perhaps if we provide a script for this purpose, such as in the installer script. Right now we're discussing instructions for the `README.md`. I suggest:
```sh
echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.profile
test -e ~/.bash_profile && echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
```
It doesn't have to address every case, just the typical case of a user running `bash` on a stock Ubuntu or Fedora/CentOS system.

**Comment by maxim-belkin** [comment]
I don't think `~/.profile` deserves a special treatment.
```sh
test -f ~/.profile && echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.profile
test -f ~/.bash_profile && echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
```

**Comment by sjackman** [comment]
If the user is using `bash` (or any shell that reads `~/.profile`) but has neither a `~/.profile` nor a `~/.bash_profile` (that is, relying on the system defaults), then the above won't add anything to their `PATH`.

**Comment by maxim-belkin** [comment]
> When  bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists.  After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order,  and  reads  and  executes  commands  from  the  first  one that exists and is readable.  The --noprofile option may be used when the shell is started to inhibit this behavior.

So, to be 100% correct, we have to do the following:
```sh
if test -e ~/.bash_profile
then
  echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >> ~/.bash_profile
elif test -e ~/.bash_login
then
  echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >> ~/.bash_login
else
  echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >> ~/.profile
fi 
```

**Comment by sjackman** [comment]
Do we know of any distros that use`~/.bash_login`? I'm fine looking for only `~/.profile` and `~/.bash_profile`.

**Comment by maxim-belkin** [comment]
it's not the distro problem. As you can see, that's standard bash approach.

**Comment by sjackman** [comment]
I mean that I don't know of any distributions that create `~/.bash_login` file by default. They seem to primarily use either `~/.bash_profile` or `~/.profile`.

**Comment by tseemann** [comment]
RHEL/Centos skeleton uses `.bash_profile` and Ubuntu is `.profile`.

The RHEL one also contains:
```
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
```
which itself has
```
# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
```

**Comment by sjackman** [comment]
We can fix this logic in `linuxbrew/install` to correctly give instructions to modify either `~/.bash_profile` if it exists or `~/.profile` otherwise
https://github.com/Linuxbrew/install/blob/master/install#L195

**Comment by waldyrious** [comment]
Reading this thread, I'm a bit confused. Is @maxim-belkin's code from [this comment](https://github.com/Linuxbrew/brew/issues/235#issuecomment-278177457) the consensual solution for this issue, or are there other unresolved factors? I'm willing to submit a PR, but I'd like to be sure I'm be heading in the right direction.

**Comment by maxim-belkin** [comment]
@waldyrious, I think the "correct" solution for Bash is the one below. However, I don't know if Shaun ( @sjackman ) wanted it in the "install" script. Let's check with him first.  
```sh
if test -e ~/.bash_profile
then
  echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >> ~/.bash_profile
elif test -e ~/.bash_login
then
  echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >> ~/.bash_login
elif test -e ~/.profile
then
  echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >> ~/.profile
else
  echo 'No Bash profile files have been found.'
  echo 'Please create one and add the following line to that file:'
  echo 'export PATH="$HOME/.linuxbrew/bin:$PATH'
fi 
```

**Comment by sjackman** [comment]
The only two bash `profile` scripts in common use by distributions with which I'm familiar are `~/.bash_profile` by RHEL/Centos and `~/.profile` by CentOS as @tseemann pointed out in https://github.com/Linuxbrew/brew/issues/235#issuecomment-305654154

My recommended fix is to modify https://github.com/Linuxbrew/install/blob/master/install#L195
```ruby
  when %r{/(ba)?sh} then "~/.bash_profile"
```
to report `~/.bash_profile` if it exists and `~/.profile` otherwise.

Additionally, line https://github.com/Linuxbrew/install/blob/master/install#L198
```ruby
  else "~/.bash_profile"
```
should be modified to
```ruby
  else "~/.profile"
```

**Comment by maxim-belkin** [comment]
agree on both of the suggestions.
@waldyrious, go! :)

**Comment by nickjhathaway** [comment]
Also, I don't if this is an issue to bring up with the core linuxbrew or maybe should be taken up whoever is managing the specific formula but certain formulas also report to put lines into `~/.bash_profile` regardless of what current profiles files are present,  e.g. bash-completion formula which has the following comment after installing. 

```bash
Add the following line to your ~/.bash_profile:
  [ -f /data/home/hathawan/.linuxbrew/etc/bash_completion ] && . /data/home/hathawan/.linuxbrew/etc/bash_completion

```

Also, I don't know if you want to go through the trouble of changing it but on your install website, http://linuxbrew.sh/, it also has instructions to modify `~/.bash_profile` and might be helpful to mention the possibility of different bash profile files especially for the novice bash users (a lot of the novices I teach will just ignore whatever is reported on the commandline haha and so they might just follow the instructions on the site). 

Thanks for the change! 
Nick

**Comment by maxim-belkin** [comment]
Notes in formulae are specific to Homebrew (not Linuxbrew). Changing that for each formula would mean a LOT of possible conflicts down the road so I don't think we'll do it unless upstream (Homebrew) does.

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/brew/pull/421 to modify the web page.

**Comment by sjackman** [comment]
Resolved by PR #421.

**Comment by waldyrious** [comment]
> We can fix this logic in linuxbrew/install to correctly give instructions to modify either ~/.bash_profile if it exists or ~/.profile otherwise
https://github.com/Linuxbrew/install/blob/master/install#L195

@sjackman I don't know Ruby, so the following may not be correct or idiomatic. Would you say this change could address your remark quoted above?

```diff
 # return the shell profile file based on users' preference shell
 def shell_profile
+  bp = "~/.bash_profile"
+  zp = "~/.zprofile"
   case ENV["SHELL"]
-  when %r{/(ba)?sh} then "~/.bash_profile"
-  when %r{/zsh} then "~/.zshrc"
-  when %r{/ksh} then "~/.kshrc"
-  else "~/.bash_profile"
+  when %r{/bash} && File.exist?(bp) && File.writable?(bp) then bp
+  when %r{/zsh} then zp
+  else "~/.profile"
   end
 end
```

Note: I'm basing the change to the zsh line on [this SuperUser answer](https://superuser.com/a/187673/112593), and the omission of the ksh line to [this documentation](http://osr507doc.sco.com/en/OSUserG/_The_Korn_shell_profile_and_kshrc.html).

**Comment by sjackman** [comment]
Nicely done, Waldir, and great research. I like your approach. Please do open a PR.

Two comments:
`.exists?` and `.writable?` is redundant, since if it's writeable, then it exists.
Please remove the `bp` and `zp` variables and expand them.

**Comment by sjackman** [comment]
I've noticed an issue with Ubuntu. When you open a new terminal from the GUI, that bash shell started by that terminal is *not* a login shell, and so does not read `~/.bash_profile` or `~/.profile`, but reads only `~/.bashrc`. That means that when you modify the `~/.bash_profile`, that change doesn't take effect until the user logs out and back in from the GUI. For many people, particularly on laptops, that doesn't ever happen. I'm curious which common Linux distros are affected by this issue. Does it affect Debian and Fedora?

One workaround is instructing the user to `source ~/.profile` after installing Linuxbrew. That almost makes things worse. They install Linuxbrew. It's working. They're 😃. They close that terminal. The next day they open a terminal, and Linuxbrew is no longer working. They're 😢. They would have to log out and log back in to get it to work again, but they don't know that, and it's not clear why that's necessary.

A workaround is to modify `~/.bashrc` and friend instead of `~/.profile` and friends, but I'm not super happy with that hack either.

**Comment by waldyrious** [comment]
Does the rest of the code work, then? I was wondering if I had committed some syntax mistake. Can I send a PR with the following, then?

```diff
 # return the shell profile file based on users' preference shell
 def shell_profile
   case ENV["SHELL"]
-  when %r{/(ba)?sh} then "~/.bash_profile"
-  when %r{/zsh} then "~/.zshrc"
-  when %r{/ksh} then "~/.kshrc"
-  else "~/.bash_profile"
+  when %r{/bash} && File.writable?("~/.bash_profile") then "~/.bash_profile"
+  when %r{/zsh} then "~/.zprofile"
+  else "~/.profile"
   end
 end
```

As for the shell's behavior: I was under the impression that changes to environment variables were preserved throughout an entire user session (not just the shell session), which was why it's recommended to add such edits to the profile startup script, rather than the `.bashrc`, which is executed on every new interactive shell. Am I missing something here? If environment variable definitions only last a single shell session, then why not add them to `.bashrc` indeed?

**Comment by sjackman** [comment]
On Ubuntu, it appears that `~/.profile` is sourced once when the user the logs in. When they open a new terminal, it sources `~/.bashrc`. When we modify `~/.profile`, that change doesn't take effect until they log out and back in. If we ask them to `source ~/.profile`, it works for that one shell, but once they close it and open a new shell, it won't work, until they log out and back in.

**Comment by sjackman** [comment]
I'd be curious to test the behaviour on other Linux distros and on macOS.

**Comment by sjackman** [comment]
Your above code looks good. Open a PR and we can continue the discussion there.
