### ISSUE TITLE
Failure tapping homebrew/apache while upgrading PHP 7.1

### ISSUE THREAD

**Issue by axiac** [Linuxbrew/brew#238]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with Homebrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new

The issue
------------
The following listing should speak for itself. I tried to upgrade PHP 7.1 and it failed installing the tap `homebrew/apache`. 

```
axiac@home ~ $ brew outdated
homebrew/php/php71 (7.1.0_11) < 7.1.1_12

axiac@home ~ $ brew upgrade php71
==> Upgrading 1 outdated package, with result:
homebrew/php/php71 7.1.1_12
==> Tapping homebrew/apache
Cloning into '/home/axiac/.linuxbrew/Library/Taps/homebrew/homebrew-apache'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 7), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Error: Invalid formula: /home/axiac/.linuxbrew/Library/Taps/homebrew/homebrew-apache/mod_suexec.rb
formulae require at least a URL
Error: Cannot tap homebrew/apache: invalid syntax in tap!

axiac@home ~ $ ls -l /home/axiac/.linuxbrew/Library/Taps/homebrew/
total 24
drwxr-xr-x 7 axiac axiac  4096 Jan 25 12:41 homebrew-core
drwxr-xr-x 3 axiac axiac  4096 Jan 11 11:35 homebrew-dupes
drwxr-xr-x 9 axiac axiac  4096 Jan 16 11:42 homebrew-php
drwxr-xr-x 4 axiac axiac 12288 Jan 23 17:18 homebrew-versions
```

There are two possible issues here:
1. Linuxbrew fails to install the `homebrew/apache` tap; I tried to run `brew tap homebrew/apache` and it failed with the same error messages. I cannot tell if the error is in Homebrew or in Linuxbrew (I don't have a macOS at hand). Other taps can be installed without problems. If I manually `git clone https://github.com/Homebrew/homebrew-apache.git` to the correct directory the upgrade of PHP7.1 works without problems.
2. The `homebrew/apache` tap was not needed by Linuxbrew before in order to install PHP (I have versions 5.4, 5.5, 5.6, 7.0 and 7.1 installed on this computer since May 2016 and I kept them up to date by running `brew upgrade` at least twice a week.) I uninstalled all of them now and, for some reason I don't understand, all of them require now `homebrew/apache`. This issue probably belongs to [`Homebrew/homebrew-php`](https://github.com/Homebrew/homebrew-php)

The output of `brew config`
----------------------------------
```
axiac@home ~ $ brew config
HOMEBREW_VERSION: 1.1.6
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 98e06da6124e92192c14b02ae383fcd8010b19a3
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 72349992f3f8c6d47ed76ee26d854e63e7550d42
Core tap last commit: 2 days ago
HOMEBREW_PREFIX: /home/axiac/.linuxbrew
HOMEBREW_REPOSITORY: /home/axiac/.linuxbrew
HOMEBREW_CELLAR: /home/axiac/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit 0x65e
Homebrew Ruby: 2.0.0-p648 => /home/axiac/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.11.0 => /usr/bin/git
Perl: /usr/bin/perl
Python: /home/axiac/.linuxbrew/bin/python => /home/axiac/.linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: openjdk version "1.8.0_121"
Kernel: Linux 4.4.0-59-generic x86_64 GNU/Linux
OS: Linux Mint 18.1 Serena
Codename: serena
OS glibc: 2.23
OS gcc: 5.4.0
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
```

The output of `brew doctor`
----------------------------------
```
axiac@home ~ $ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/axiac/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile
```
(Adding Homebrew's share to `XDG_DATA_DIRS` as suggested has undesired effects: the session
terminates immediately after login. It shouldn't affect the issue at hand, anyway.)

Additional info
-----------------
```
axiac@home ~ $ brew info php71
homebrew/php/php71: stable 7.1.1, HEAD
PHP Version 7.1
https://php.net
Conflicts with: php53, php54, php55, php56, php70
/home/axiac/.linuxbrew/Cellar/php71/7.1.0_11 (336 files, 28.5M) *
  Built from source on 2016-12-05 at 18:39:20 with: --without-fpm --without-ldap --without-legacy-mysql
From: https://github.com/Homebrew/homebrew-php/blob/master/Formula/php71.rb
==> Dependencies
Required: curl ✔, freetype ✔, gettext ✔, icu4c ✔, jpeg ✔, libpng ✔, libxml2 ✔, unixodbc ✔, readline ✔, openssl ✔
Optional: enchant ✘, gmp ✘, homebrew/apache/httpd24 ✘, homebrew/apache/httpd22 ✘
==> Requirements
Optional: postgresql ✔
==> Options
...
```
I stripped the rest of the text produced by `brew info` because it is fixed and not relevant to the issue at hand.

**Comment by bw-yuhogg** [comment]
The reason `homebrew/apache` doesn't tap properly is that mod_suexec lacks a URL. This is a Linux-specific issue; mod_suexec has different URL's for different macOS versions but nothing for Linux. This doesn't cause any major problems in my experience (except for the obvious inability to install mod_suexec).

Correct me if I'm wrong, but my understanding is that PHP (regardless of version) does not build the Apache module by default any more. It taps homebrew/apache, but does not try to install Apache.

Just to clarify: is this issue preventing you from upgrading PHP, or is it merely something you noticed while doing the upgrade?

**Comment by axiac** [comment]
This issue prevents installing or upgrading PHP no matter if the `with-httpd2x` flags are present or not in the command line. Without them it should not depend on `homebrew/apache` and it should not try to install it (but it does).

I investigated the recent changes on `homebrew/php` and discovered the source of the problem in Homebrew/homebrew-php#3834. However, installing and updating PHP works fine in Homebrew (it doesn't install `homebrew/apache` if it's not needed). I think the issue is in Linuxbrew. Maybe some changes on Homebrew should be ported to Linuxbrew.

**Comment by sjackman** [comment]
`homebrew/apache` and `homebrew/php` are not supported by the Linuxbrew team. You may if you like ask their maintainers if they'd be willing to accept from you to fix the issue on Linux.

**Comment by axiac** [comment]
@sjackman I think I didn't expose the issue correctly. It's not about `homebrew/php` or `homebrew/apache`; it's about Linuxbrew that cannot install PHP CLI (and possibly other packages) because it doesn't handle the dependencies the same way Homebrew does.

It used to work until one or two months ago then something changed in the way the PHP dependencies are defined in the PHP formulae and, on the same time, I guess the Homebrew code changed accordingly. Linuxbrew, unfortunately, didn't catch up yet.

I just installed a fresh copy of Linuxbrew on a fresh Linux machine and then I tried to install PHP 7.1 CLI only. Please take a look at the output:

```
vagrant@xenial-php7: ~
$ brew tap
homebrew/core
homebrew/dupes
homebrew/php

vagrant@xenial-php7: ~
$ brew install homebrew/php/php71 --without-fpm --without-ldap --without-legacy-mysql --without-unixodbc
==> Installing php71 from homebrew/php
==> Tapping homebrew/apache
Cloning into '/home/vagrant/.linuxbrew/Library/Taps/homebrew/homebrew-apache'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 7), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.
Error: Invalid formula: /home/vagrant/.linuxbrew/Library/Taps/homebrew/homebrew-apache/mod_suexec.rb
formulae require at least a URL
Error: Cannot tap homebrew/apache: invalid syntax in tap!
```

The same install command works fine on Homebrew and it doesn't attempt to install `homebrew\apache` because there is no need for it. Apache is an optional dependency that is needed when one of `--with--httpd22` or `--with-httpd24` options is used in the `brew install` command line. None of them is present here.

I agree this is not a major issue and I guess there are very few users affected.

---

For anyone that has the same issue, there is a simple workaround: install `homebrew/apache` manually by running the following command:

    $ git clone https://github.com/Homebrew/homebrew-apache $(brew --prefix)/Library/Taps/homebrew/homebrew-apache

After that you can install PHP CLI versions 5.4, 5.5, 5.6, 7.0 and 7.1.

**Comment by sjackman** [comment]
Without further troubleshooting, I can't say why `homebrew/php/php71` requires tapping `homebrew/apache`. Fixing `homebrew/apache/mod_suexec` to provide an `url` on Linux would at least stop the tap from failing.
