### ISSUE TITLE
astyle does not build

### ISSUE THREAD

**Issue by mushanyoung** [Linuxbrew/brew#239]
### Bug reports:

astyle foes not build. It does not have a valid bottle for linux as well.

**Comment by bw-yuhogg** [comment]
I've opened Linuxbrew/homebrew-core#1633 to resolve this.

While it was trivial to figure out what was wrong in this case, in the future please
a) Report issues with individual formulae to Linuxbrew/homebrew-core (or other repos as appropriate) and
b) run `brew gist-logs <formula>` and paste the link you get into the issue description.

Thanks a bunch!

**Comment by bw-yuhogg** [comment]
I've merged Linuxbrew/homebrew-core#1633, so this should now be resolved.

Please feel free to reopen this issue if it continues to be an issue for you.
