### ISSUE TITLE
utils/analytics.sh: line 38: uuidgen: command not found

### ISSUE THREAD

**Issue by Mikaela** [Linuxbrew/brew#24]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?

I ran `brew update` and `brew upgrade` and started seeing this error with all commands afterwards.

```
/home/users/mikaela/.local/Library/Homebrew/utils/analytics.sh: line 38: uuidgen: command not found
```
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

It told me that I am missing bzip2 which I installed which didn't change anythig.
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

I don't and I am not root.
### Bug reports:

```
% brew update
/home/users/mikaela/.local/Library/Homebrew/utils/analytics.sh: line 38: uuidgen: command not found
Already up-to-date.
```

I see this same error with all brew commands I run.

**Comment by bw-yuhogg** [comment]
Hey @Mikaela, can you please try doing a `brew install util-linux` please? `uuidgen` is a binary provided by that package.  (You can do a `git checkout` of an earlier version of Linuxbrew to temporarily make that error go away and allow the install to succeed, then return to where you were previously).

It's worth noting that on Ubuntu (not sure what OS in particular you're on), `/usr/bin/uuidgen` is provided by `uuid-runtime`, which, though it comes from the same source package as `util-linux`, is not installed by the `util-linux` binary package. I might need to look into the list of host dependencies to see if that needs to be added.

Would you mind telling me what OS you're on, so I can do the search for that as well? Thanks!

**Comment by bw-yuhogg** [comment]
I can confirm that `uuid-runtime` is not installed by any of the packages required [here](https://github.com/Linuxbrew/brew#debian-or-ubuntu).

@sjackman, would you rather make that (and whatever the equivalent is for rpm-based distros) a dependency, or would you rather fix the script so that it works gracefully in the absence of `uuidgen`?

The code in question is

``` bash
HOMEBREW_ANALYTICS_USER_UUID="$(git config --file="$git_config_file" --get homebrew.analyticsuuid)"
 if [[ -z "$HOMEBREW_ANALYTICS_USER_UUID" ]]
 then
   HOMEBREW_ANALYTICS_USER_UUID="$(uuidgen)"
   git config --file="$git_config_file" --replace-all homebrew.analyticsuuid "$HOMEBREW_ANALYTICS_USER_UUID"
 fi
```

Which fails if `uuidgen` does not exist. One obvious solution would be to check if `uuidgen` is available and return the same way we do if $HOMEBREW_NO_ANALYTICS is set if it isn't, since we need a reasonable way to distinguish users without sending personally identifiable information. Personally, I think fixing the script is better than adding a dependency solely for the benefit of analytics.  I don't use the analytics though, so it's your call on this.

**Comment by sjackman** [comment]
> @sjackman, would you rather make that (and whatever the equivalent is for rpm-based distros) a dependency, or would you rather fix the script so that it works gracefully in the absence of uuidgen?

Both!

> One obvious solution would be to check if uuidgen is available and return the same way we do if $HOMEBREW_NO_ANALYTICS is set if it isn't, since we need a reasonable way to distinguish users without sending personally identifiable information.

Agreed. If `uuidgen` is not available, behave as though `HOMEBREW_NO_ANALYTICS` were set without making it permanent.

**Comment by Mikaela** [comment]
> Hey @Mikaela, can you please try doing a brew install util-linux please? 

Done and the error disappears, but I don't see where I need it as it wasn't required in the past.

> Would you mind telling me what OS you're on, so I can do the search for that as well? Thanks!
- Debian GNU/Linux 8.4 (jessie)

**Comment by sjackman** [comment]
`util-linux` is only needed once to run `uuidgen` for analytics. You can remove it now. It shouldn't be necessary dependency for installation of Linuxbrew. We're working on it.

**Comment by aks** [comment]
Agree that the absence of `uuidgen` should not cause a problem.

However, for those who might want to enable brew analytics, `uuidgen` can be installed (on Debian) with:

```
sudo apt-get install uuid-runtime
```
