### ISSUE TITLE
Brew does not create symbolic links to libraries in Cellar/<package>/<version>/lib64 

### ISSUE THREAD

**Issue by octoflar** [Linuxbrew/brew#243]
On SUSE Linux (I use openSUSE 13.2) the default library directory seems to be `lib64`. Anyway, libraries build in the process of `brew install ...` are (sometimes or always) put into

    <linuxbrewroot>/Cellar/<package>/<version>/lib64

Symbolic links into the

    <linuxbrewroot>/lib

directory are *not* created. The symbolic links are missing after `brew install ...` has completed. No issues are reported. Many packages, however, fail to build or work, because libraries built by dependencies (they can be found in the `Cellar`) are not linked into the root `lib`.

Packages that put libraries into 

    <linuxbrewroot>/Cellar/<package>/<version>/lib

are properly linked and do not cause problems.

**Comment by sjackman** [comment]
This issue (`lib64` vs `lib`) is resolved on a formula-by-formula basis. Please submit an issue to the `Linuxbrew/homebrew-core` repository specifying which formula is affected.
