### ISSUE TITLE
Differences from Homebrew and long-term plan?

### ISSUE THREAD

**Issue by baldurthoremilsson** [Linuxbrew/brew#245]
I've tried to find information about the differences between Homebrew and Linuxbrew and what the long-term plan is regarding this project. The only thing I've found is the description `Experimental Linux version` in `Interesting-Taps-&-Forks.md`.

Is the plan to merge Linuxbrew into Homebrew at some point in the future? Is there anything in particular that is stopping that from happening, such as technical reasons? Or is the idea to keep the two projects separated indefinitely? Whatever the answer is I think it might be a good idea to include it on the homepage so it's obvious to people what the reason for the fork is, rather than focusing the effort on a first-class Linux support in Homebrew :)

**Comment by sjackman** [comment]
The plan is to merge the Linuxbrew/brew repository into Homebrew/brew and decommission Linuxbrew/brew. There is no plan to merge Linuxbrew/homebrew-core; it will remain separate. There is no technical limitation, just the hours and manpower required to submit the patches upstream to Homebrew.
