### ISSUE TITLE
is 'export' a part of the required text to add to .bashrc?

### ISSUE THREAD

**Issue by HughP** [Linuxbrew/brew#250]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

I am looking for some guidance... I see in the linuxbrew instructions that it say `echo 'export...` with the following commands...

`export PATH="$HOME/.linuxbrew/bin:$PATH" `

`export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH" `

`export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"`

So I am wondering should I copy these commands to my .basrc file? and if I should (which I am pretty sure I do need to do), do I also need to include the `export` portion in the `.bashrc` file? or is export supposed to be a terminal command and the part added to the .bashrc file is `PATH="$HOME/.linuxbrew/bin:$PATH"`?

**Comment by bw-yuhogg** [comment]
> So I am wondering should I copy these commands to my .basrc file?

Yes, you should.

> do I also need to include the export portion in the .bashrc file?

`.bashrc` should include the `export`. So your `.bashrc` should include lines like

```
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
```

Hope that helps!

**Comment by HughP** [comment]
Thanks. That is very clear... I'm off and rolling now. Thanks.
