### ISSUE TITLE
`brew gist-logs` wrongly gives warning: Warning: /usr/bin occurs before $homebrew_D/bin

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/brew#251]
EG: https://gist.github.com/timotheecour/09b2dea789f2462583d6db706348b4fa
says:
Warning: /usr/bin occurs before /katrina/home/timothee/m/katrina/brew/bin
but echo $PATH shows the opposite.

**Comment by sjackman** [comment]
Please report the output of
```sh
echo $PATH
sh -c 'echo $PATH'
brew sh <<<'echo $PATH'
```
