### ISSUE TITLE
Can't install any package on Raspberry Pi (gcc error)

### ISSUE THREAD

**Issue by akz92** [Linuxbrew/brew#252]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

I can't install any package on my Raspberry Pi, this is the error I'm facing:
```
*** Error in `/usr/bin/gcc-4.9': double free or corruption (top): 0x00438718 ***
Last 15 lines from /home/pi/.cache/Homebrew/Logs/hello/01.configure:
--prefix=/home/pi/.linuxbrew/Cellar/hello/2.10

configure: WARNING: unrecognized options: --disable-debug
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... /usr/bin/gcc-4.9
checking whether the C compiler works... no
configure: error: in `/tmp/hello-20170204-8082-5hp44w/hello-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

I've already tried changing gcc version to `4.7` and `4.8` but the error persists. I tested this on the latest Raspbian release (2017-01-11) and on an older release I had already downloaded (2016-09-23).

Output of `brew config`:
```
HOMEBREW_VERSION: 1.1.8
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: d6371b24895cb4eca83ecedf5f1dbf12743a89a2
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 845eba0dc311e65855068671a292bc038e3be727
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/pi/.linuxbrew
HOMEBREW_REPOSITORY: /home/pi/.linuxbrew
HOMEBREW_CELLAR: /home/pi/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 32-bit arm
Homebrew Ruby: 2.1.5 => /usr/bin/ruby2.1
Clang: N/A
Git: 2.1.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.1
Java: N/A
Kernel: Linux 4.4.38-v7+ armv7l GNU/Linux
OS: Raspbian GNU/Linux 8.0 (jessie)
Codename: jessie
OS glibc: 2.19
OS gcc: 4.9.2
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
```

Is there any known solution to this? I can provide any other details if needed.

**Comment by sjackman** [comment]
Here's the upstream bug report: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=139091&p=922980

> Similarly where -march=native is you change to -march=armv8-a for RPi3 only or -march=armv6 (or just remove -march=native option) to build for all RPis.

The work around is
+ Any RPi `export HOMEBREW_ARCH=armv6`
+ RPi3 `export HOMEBREW_ARCH=armv8-a`

A PR to fix this issue would be welcome.
