### ISSUE TITLE
Error: Failed to install vendor Ruby.

### ISSUE THREAD

**Issue by trusktr** [Linuxbrew/brew#255]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?

```
> brew update
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
```

- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

```
> brew doctor
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
```

- [x] Confirmed this is problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

It happens with every single `brew` command.

### Bug reports:

After running the script from http://linuxbrew.sh and then adding `~/.linuxbrew/bin` to my PATH, running any `brew` command results in

```
> brew <anything>
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
```

**Comment by trusktr** [comment]
Maybe brew can detect this and give . more useful warning. I'm not familiar with Ruby dev at all, so it's probably something simple to fix, but I've no idea what yet.

**Comment by trusktr** [comment]
I'm on Ubuntu Precise.

**Comment by trusktr** [comment]
Seems I might have this issue: https://github.com/Linuxbrew/brew/issues/222

**Comment by trusktr** [comment]
Ruby version on the system:

```
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
```

So why does it need to get Ruby?

**Comment by bw-yuhogg** [comment]
> So why does it need to get Ruby?

Support for Ruby < 2.0 was removed, so brew should download a newer Ruby if it detects that the system version isn't new enough.

**Comment by sjackman** [comment]
I can confirm this failure. Frankly, I'm not sure why it ever worked.
```
$ brew fetch homebrew/portable/portable-ruby
==> Fetching portable-ruby from homebrew/portable
==> Downloading https://linuxbrew.bintray.com/bottles-portable/portable-ruby-2.0

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "portable-ruby"
Download failed: https://linuxbrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
```

The workaround is:
```sh
HOMEBREW_BOTTLE_DOMAIN=https://homebrew.bintray.com brew fetch homebrew/portable/portable-ruby
```
or if that fails for some reason:
```sh
curl -Lo `brew --cache portable-ruby` https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
```

**Comment by trusktr** [comment]
@sjackman I get:

```
~ ❯ HOMEBREW_BOTTLE_DOMAIN=https://homebrew.bintray.com brew fetch homebrew/portable/portable-ruby
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
```

**Comment by sjackman** [comment]
Then
```sh
curl -Lo `brew --cache portable-ruby` https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
brew -v 
```

**Comment by trusktr** [comment]
@sjackman 

```
~ ❯ curl -Lo `brew --cache portable-ruby` https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

~ ❯ curl -kLo `brew --cache portable-ruby` https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information

~ ❯ brew -v
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.

~ ❯ brew --cache portable-ruby
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor Ruby.
```

**Comment by trusktr** [comment]
Can I download that file manually and stick it somewhere?

**Comment by sjackman** [comment]
Ugh. Sorry.
```sh
curl -Lo ~/.cache/Homebrew/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
```

**Comment by trusktr** [comment]
@sjackman Sorry to bother, but now `curl` complains about security:

```
> curl -Lo ~/.cache/Homebrew/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

Any suggestions on how to get it securely?

**Comment by sjackman** [comment]
The certificates bundled with your `curl` are too old. To ignore the certificate:
```
curl -kLo ~/.cache/Homebrew/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz https://homebrew.bintray.com/bottles-portable/portable-ruby-2.0.0-p648.x86_64_linux.bottle.tar.gz
```
Alternatively download updated certificates from
https://curl.haxx.se/ca/cacert-2017-01-18.pem

**Comment by dragon788** [comment]
I worked around this by using `wget` to download that file and then moving it into the `~/.cache/Homebrew/` directory and running any other `brew` command like `brew doctor`. I'll report a bug to my hosting company that has this outdated curl/certificates in their image but thought I'd let others know how I worked around it.

I'm doing a similar thing for updating curl, it appears the patchelf tar.gz didn't want to come down nicely via `brew fetch`, but after manually grabbing it to the cache the rest of the packages installed perfectly fine??? Maybe I just kept getting a bad Akamai mirror from Bintray.

Even setting the `CURL_CA_BUNDLE='/path/to/cacert.pem'` didn't fix the SSL issues I was having.

**Comment by sjackman** [comment]
This issue came up upstream at Homebrew as well recently: http://discourse.brew.sh/t/is-there-any-way-to-allow-curl-to-run-as-insecure/629

**Comment by dragon788** [comment]
Excellent, and after I fixed my temp directory issues and got the brew curl installed it gives the PROPER way to add a new certificate to the trust in the post install output.

```
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  ~/.linuxbrew/etc/openssl/certs

and run
  ~/.linuxbrew/opt/openssl/bin/c_rehash
```

**Comment by dragon788** [comment]
@trusktr Did my previous comments with the environment variables using the .pem file sjackman recommended work?

**Comment by trusktr** [comment]
@dragon788 I didn't get to test it before moving from Ubuntu 12 to 14. All works now.
