### ISSUE TITLE
Error: Unable to determine the system's glibc version

### ISSUE THREAD

**Issue by VidJa** [Linuxbrew/brew#256]
I continue to have trouble with glibc version determination.

When ever I try to run brew install or even brew doctor I get the following error message:
Error: Unable to determine the system's glibc version

I've checked the contents of 
~.linuxbrew/Library/Homebrew/requirements/glibc_requirement.rb

and checked if any of the libc files are presents. /lib/x86_64-linux-gnu/libc.so.6 is present on my ubuntu 14.01.1 system.

what can I do to fix this?

**Comment by bw-yuhogg** [comment]
Can you run /lib/x86_64-linux-gnu/libc.so.6 and paste the output here? Thanks!

**Comment by VidJa** [comment]
I get this output, but only if I run as root. I cannot run it as normal user.

```
GNU C Library (Ubuntu EGLIBC 2.19-0ubuntu6.9) stable release version 2.19, by Roland McGrath et al.
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.4.
Compiled on a Linux 3.13.11 system on 2016-05-26.
Available extensions:
	crypt add-on version 2.1 by Michael Glad and others
	GNU Libidn by Simon Josefsson
	Native POSIX Threads Library by Ulrich Drepper et al
	BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/eglibc/+bugs>.
```

**Comment by sjackman** [comment]
> I get this output, but only if I run as root. I cannot run it as normal user.

That's the issue, and an error on your system, I believe. Please report
```sh
ls -l /lib/x86_64-linux-gnu/libc.so.6
ls -lH /lib/x86_64-linux-gnu/libc.so.6
```

Changing the permissions should fix it:
```sh
sudo chmod +rx /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by VidJa** [comment]
it turned out not to be the permissions, but a LD_PRELOAD  setting in /etc/environment.

**Comment by sjackman** [comment]
Thanks for following up.
