### ISSUE TITLE
npm: Error: Unsupported special dependency :perl

### ISSUE THREAD

**Issue by salmasamiei** [Linuxbrew/brew#261]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Confirmed this is problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this section with a brief summary of your issue **AND** the output of `brew config` and `brew doctor`. Please note we may immediately close your issue without comment if you do not fill out the issue template and provide the requested information.

### Propose a feature:

Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered. Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by bw-yuhogg** [comment]
Hi @salmasamiei: can you please run `brew gist-logs npm` and paste the output here please? Thanks!

**Comment by salmasamiei** [comment]
Hi @rwhogg  ,
this is the output of running brew gist-logs npm
Error: No logs.
 as you can see there is no logs.

**Comment by bw-yuhogg** [comment]
Hmm, that's unfortunate :frowning: 

Can you try `brew doctor` and `brew config`?

**Comment by sjackman** [comment]
Please report the exact and complete output of `brew install node`
You may wish to install Linuxbrew in the directory `/home/linuxbrew/.linuxbrew` so that you can make use of the precompiled binary bottle of `node`.

**Comment by jzfdav** [comment]
Do `brew update` twice.
Then do `brew install node`
Solved by using info [here](https://github.com/Linuxbrew/homebrew-core/issues/1415)
