### ISSUE TITLE
brew install formula_w_bug gives error that ignores the formula exists 

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/brew#271]
@sjackman 
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

##
- [ ] brew install formula_w_bug gives error that ignores the formula exists
see full description + way to repro here https://github.com/Homebrew/homebrew-science/pull/5187

**Comment by sjackman** [comment]
Sorry, I don't know why this affects Linuxbrew but not Homebrew. :man_shrugging:

**Comment by timotheecour** [comment]
@sjackman 

-[ ] Not sure if related but https://github.com/Linuxbrew/homebrew-core/issues/1818 shows a particularly unfriendly error `Error: wrong number of arguments (0 for 1..3)` that shows absolutely no context: we should at least have a stacktrace showing the offending file and line (which I'm guessing is `depends_on :osxfuse`). (regardless of whether this particular formula is fixed, this is a general linuxbrew bug IMO)

On this note, could you please shed some light on that error message? it doesn't happen on osx. Where in the code is osxfuse expecting these arguments? 

for ref: https://github.com/caskroom/homebrew-cask/blob/master/Casks/osxfuse.rb

**Comment by sjackman** [comment]
>  that shows absolutely no context: we should at least have a stacktrace showing the offending file and line

The stack trace is immediately below the error message, no? Perhaps the comment was edited.
https://github.com/Linuxbrew/homebrew-core/issues/1818#issue-208598623
```
==> Installing s3fs from homebrew/fuse
Error: wrong number of arguments (0 for 1..3)
Please report this bug:
  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
/home/admin/.linuxbrew/Library/Homebrew/requirement.rb:58:in `instance_eval'
```

If there's a bug in `depends_on :osxfuse` then the relevant code is
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/requirements/osxfuse_requirement.rb#L25
