### ISSUE TITLE
curl: (60) server certificate verification failed

### ISSUE THREAD

**Issue by satrioaw** [Linuxbrew/brew#275]
If Homebrew was updated on Aug 10-11th 2016 and `brew update` always says `Already up-to-date.` you need to run: `cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update`.

# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

### Bug reports:
I found the problem when installing erlang which error is server certificate verification failed, I already tried solution enabling the 

> -k

 option as uninstall and reinstalled linux brew, but I still got same error, like here
```
==> Downloading https://www.erlang.org/download/otp_doc_man_19.2.tar.gz
/usr/bin/curl --remote-time --location --user-agent Linuxbrew/1.1.10 (Linux; x86_64 elementary OS 0.4 Loki) curl/7.47.0 --fail https://www.erlang.org/download/otp_doc_man_19.2.tar.gz -C 0 -o /home/satrio/.cache/Homebrew/erlang--man-19.2.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
Error: Failed to download resource "erlang--man"
Download failed: https://www.erlang.org/download/otp_doc_man_19.2.tar.gz

```

any solution for this ?

**Comment by sjackman** [comment]
You can update your out-of-date certs file `/etc/ssl/certs/ca-certificates.crt` if you have root access.
Try `brew install curl`

**Comment by satrioaw** [comment]
I already try update certs in ubuntu but still same result message
`
sudo update-ca-certificates --fresh`

**Comment by sjackman** [comment]
Odd. I would have expected that to resolve the issue. You can try downloading the certs manually from https://curl.haxx.se/docs/caextract.html and then setting the `SSL_CERT_FILE` environment variable. Although I can't now seem to find any documentation for `SSL_CERT_FILE`.

**Comment by sjackman** [comment]
Did `brew install curl` work? It downloads the CA certs as part of its installation.

**Comment by satrioaw** [comment]
yes, there is no problem with `brew install curl`
 and I also copied and replace on 
`.linuxbrew/etc/openssl/`

just wondering, did you have a problem or not when `brew install erlang ` on your computer ? just feeling like only me have this problem so that you close this issues.

**Comment by bw-yuhogg** [comment]
> just wondering, did you have a problem or not when brew install erlang on your computer ?

I can verify that this issue affects me as well.

**Comment by sjackman** [comment]
Sorry that I didn't try reproducing your issue earlier. It affects me as well, and it doesn't affect Safari on my system, so it's specific to Linuxbrew.

**Comment by sjackman** [comment]
Here's a PR to update cacert from version 2016-04-20 to 2017-01-18, but it does not unfortunately resolve the issue.
https://github.com/Linuxbrew/homebrew-core/pull/1918

**Comment by sjackman** [comment]
As a workaround you can run `brew edit erlang` and replace all `https` with `http`.

**Comment by sjackman** [comment]
Here's a PR attempting to reproduce the issue on CI: https://github.com/Linuxbrew/homebrew-core/pull/1919

**Comment by sjackman** [comment]
I'm not able to reproduce the issue with `brew fetch erlang` with Homebrew on a Mac.

**Comment by sjackman** [comment]
Another workaround: `brew install --without-docs erlang`

**Comment by sjackman** [comment]
Here's another ticket reporting this same issue a year ago:
https://github.com/Linuxbrew/legacy-linuxbrew/issues/981

**Comment by satrioaw** [comment]
> As a workaround you can run brew edit erlang and replace all https with http

working with this solution


.

**Comment by sjackman** [comment]
I was able to reproduce this issue on a Mac with `openssl`, but not with the default DarwinSSL.
```
❯❯❯ brew install curl --with-openssl
❯❯❯ /usr/local/opt/curl/bin/curl https://www.erlang.org/
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

With DarwinSSL
```
❯❯ /usr/bin/curl -v https://www.erlang.org/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 31.172.186.60...
* Connected to www.erlang.org (31.172.186.60) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: www.erlang.org
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
```

I find `VeriSign Class 3 Public Primary Certification Authority - G5` in `cacert-2017-01-18.pem`, but I don't find `Symantec Class 3 Secure Server CA - G4`. Is that a problem? I don't know much about CA certs.

**Comment by satrioaw** [comment]
`$   brew uninstall --ignore-dependencies curl`

```
 $  brew install curl --with-openssl
Warning: curl: this formula has no --with-openssl option so it will be ignored!
==> Downloading https://curl.haxx.se/download/curl-7.53.1.tar.bz2
Already downloaded: /home/satrio/.cache/Homebrew/curl-7.53.1.tar.bz2
==> ./configure --disable-silent-rules --prefix=/home/satrio/.linuxbrew/Cellar/curl/7.53.1 --with-ssl=/home/satrio/.linuxbrew/opt/openssl --with-ca-bundle=/home/satrio/.linuxbrew/etc/
==> make install
🍺  /home/satrio/.linuxbrew/Cellar/curl/7.53.1: 391 files, 3.0M, built in 46 seconds
```
there is no problem with curl just when install erlang there had problem

**Comment by sjackman** [comment]
I've reported this issue upstream at https://github.com/openssl/openssl/issues/2833

**Comment by sjackman** [comment]
The secure URL `https://www.erlang.org/download/otp_doc_man_19.2.tar.gz` redirects to the insecure URL `http://erlang.org/download/otp_doc_man_19.2.tar.gz` so the simple solution is to use the insecure URL. `https://erlang.org/download/otp_doc_man_19.2.tar.gz` hangs indefinitely.

```
❯❯❯ curl -v https://www.erlang.org/download/otp_doc_man_19.2.tar.gz 2>&1 | grep Location
< Location: http://erlang.org/download/otp_doc_man_19.2.tar.gz
```

**Comment by sjackman** [comment]
I've changed the https URLs to http in PR https://github.com/Linuxbrew/homebrew-core/pull/1919

**Comment by sjackman** [comment]
Resolved by https://github.com/Linuxbrew/homebrew-core/pull/1919
