### ISSUE TITLE
use docker containers for non-relocatable bottles or hard to build dependencies

### ISSUE THREAD

**Issue by timotheecour** [Linuxbrew/brew#280]
@sjackman @rwhogg

Why not use docker for certain dependencies, eg:
* hard to build (or hard to build on all systems)
* non relocatable bottles, eg rust which takes 40mn (see https://github.com/Linuxbrew/homebrew-core/pull/1762#issuecomment-279288652)

This would be an alternative when building bottles (eg via `docker run sjackman/linuxbrew-standalone sh -c 'brew install --build-bottle hello && brew bottle hello`) is not appropriate, eg because they're not relocatable etc. Instead of building a bottle (maybe via a docker container) followed by copying over the generated libraries/executables, we would directly run the formula from a docker container.

Example: from https://github.com/fnichol/docker-rust:
> To compile, but not run your app inside the instance, you can write something like this:
```
docker run --rm -v $(pwd):/src fnichol/rust:1.15.1 cargo build --release
```

(other use cases possible)

the formula could look like:

```
class Rust < Formula
   #...
   depends_on "docker" => :build
   def install
     system "docker", "run", ...
   end
 end
```

Another advantage: this would circumvent the need for having to have multiple bottles (one per architecture)

NOTE for reference: this was related but different: https://github.com/Linuxbrew/legacy-linuxbrew/issues/380

**Comment by bw-yuhogg** [comment]
> Why not use docker for certain dependencies, eg:

We do have a new, easier way to build bottles with Docker: `brew test-bot-docker`, available from the linuxbrew/developer tap. I'm not sure how well it works for people without Bintray upload credentials, but I'd happily accept PR's to make it better for that case.

Strictly my opinion, but I don't think we should use Docker inside of formulae. Not only would that diverge significantly from macOS, but Docker itself is undesirable in some use cases. An example is shared hardware where Docker is not already running as a service; in that case running the Docker daemon requires root.

You may wish to take a look at [whalebrew](https://github.com/bfirsh/whalebrew); while I haven't tried it it seems to be using some of the same ideas.
