### ISSUE TITLE
trans_proteomics_pipeline: Makefile.pwiz.incl: no such file

### ISSUE THREAD

**Issue by yzhzu** [Linuxbrew/brew#283]
Dear friend:
          sorry for interrupt you. today, I want to install trans_proteomics_pipeline, but I failed and don't know how to deal with it. can you help me?thank you very much.
 
error information:
brew install trans_proteomic_pipeline
==> Installing trans_proteomic_pipeline from homebrew/science
==> Downloading https://github.com/iracooke/tpp/archive/v4.8.0p9.tar.gz
Already downloaded: /home/rcmm/.cache/Homebrew/trans_proteomic_pipeline-4.8.0.tar.gz
==> make
Last 15 lines from /home/rcmm/.cache/Homebrew/Logs/trans_proteomic_pipeline/01.make:
2017-02-28 14:54:23 +0800

make

Makefile.incl:454: /home/rcmm/../extern/ProteoWizard/Makefile.pwiz.incl: no such file
make: *** no rules to make target“/home/rcmm/../extern/ProteoWizard/Makefile.pwiz.incl”。 stop。

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

[rcmm@localhost ~]$  https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
-bash: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting: no such file

**Comment by sjackman** [comment]
I get the same error with `brew install trans_proteomic_pipeline`. You can open an issue at https://github.com/Homebrew/homebrew-science/ if you like. Good luck.
