### ISSUE TITLE
Possible for "@@HOMEBREW_PREFIX@@" to get embedded in binary RPATH's

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#287]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

### Bug reports:

It's possible (I do not yet know the circumstances that can lead to such a case) for the hardcoded string '@@HOMBREW_PREFIX@@' to get embedded into binaries' RPATH's on keg relocation.

This was quite easily reproducible using (for example) `perl`, `ruby`, `python`, `emacs`, and `vim` in the linuxbrew/ubuntu Docker image.

The symptom is that, without setting LD_LIBRARY_PATH or similar, many brewed executables will fail due to an inability to find necessary shared libraries.

On said Docker image:

```bash
% patchelf --print-rpath ~/.linuxbrew/bin/python
@@HOMEBREW_PREFIX@@/lib
# and similarly for all the other executables
```

The string '@@HOMEBREW_PREFIX@@' corresponds to a constant named `PREFIX_PLACEHOLDER`; how it is getting embedded I have yet to determine.

This likely represents a misconfiguration in the Docker image, but nonetheless that this is possible at all IMO represents a bug in `brew` as well.

Note that setting the HOMEBREW_PREFIX environment variable during installation does not help.

**Comment by sjackman** [comment]
My money is on `file` not being installed or too old. Linuxbrew fails in weird and wonderful ways when that's the case. I'd like to remove the dependency on `file`, but until then, we ought to check that it's installed and fail if not. It needs to be new enough to support the option `file --print0`.

**Comment by bw-yuhogg** [comment]
> My money is on file not being installed or too old.

Yep, that's it.

I'll file PR's against both docker and brew today to add `file` as a dependency.

I don't really have the time to implement checking code right now, but I agree that that's a good idea as a stopgap measure until we can remove the dependency (unless it's actually really easy to remove).

**Comment by sjackman** [comment]
> unless it's actually really easy to remove

Not really easy, but probably a day's work.
