### ISSUE TITLE
brewlinux has any desktop, like gnome？xfce？etc

### ISSUE THREAD

**Issue by wuliang142857** [Linuxbrew/brew#297]
I wanna install a desktop by brewlinux, it has any bottle like gnome? xface?

**Comment by DoomHammer** [comment]
Hi!

I think you might be a bit mistaken. The name of the project is Linuxbrew and it is a package manager, not a Linux distribution (like brewlinux might suggest). As such it focuses mostly on command-line tools, but some GUI ones are available as well.

Having full-featured desktop environments like XFCE or GNOME is beyond the scope, though, I think.

**Comment by sjackman** [comment]
There's no desktop environment currently in Linuxbrew. There are GUI applications in Linuxbrew, such as `gedit` the GNOME text editor. It would be reasonable I think to package `xfce` or `gnome` for Linuxbrew. It could possibly go in an existing tap, like `linuxbrew/extra`, but I'd be inclined to put it in a new tap, perhaps named `linuxbrew/desktop`. This depends on someone volunteering to maintain that tap.

Here's a Mac Homebrew tap for KDE: https://github.com/adymo/homebrew-kde
