### ISSUE TITLE
Implementing `brew services` (Fixing #99)

### ISSUE THREAD

**Issue by blockloop** [Linuxbrew/brew#300]
I'm working on implementing `brew services` for Linux. I want to keep track of the progress and Q/A here. I plan on implementing this with `systemd` because I believe it is the most commonly used. 

Most of the changes will be in a [forked version](https://github.com/blockloop/homebrew-services) of homebrew-services but some changes will have to be made to this repo and possibly some to [Linuxbrew/homebrew-core](https://github.com/Linuxbrew/homebrew-core). Linuxbrew services will not require root access, but have the option (like launchd on macOS). Unit files can be executed from `~/.config/systemd/user` using the `systemctl` command with the `--user` flag. If root is provided then we can install the service files into `/etc/systemd/system`. 

## Linuxbrew/brew
- [ ] replace `plist` definitions in [formula.rb](https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/formula.rb) with `systemd` equivalents. **Assumption:** *It's safe to remove the plist definitions altogether without breaking any code*.
- [ ] replace references to `plist` with `service` or `systemd`.
- [ ] add example .service file to the new `def service`

## blockloop/homebrew-services
- [ ] replace `launchctl` with `systemctl` equivalents cmd/brew-services.rb in homebrew-services)

## Homebrew/homebrew-core
- [ ] add `def systemd` to some formula over time which currently implement `plist` and could also implement `systemd`. By implementing `def systemd` in Linuxbrew/brew the default value will be nil (like that of `def plist` in the mac version).

**Comment by sjackman** [comment]
Sounds like a good plan, Brett! Other users have asked for this feature.

Does `linuxbrew/services` require `root` access?

> Assumption: It's safe to remove the plist definitions altogether without breaking any code.

Please keep the `plist` but armoured inside `if OS.mac?`

> replace references to plist with service or systemd

s/replace/augment/. The changes should be limited as much as possible to the directories `Library/Homebrew/os/linux` and `Library/Homebrew/extend/os/linux`.

**Comment by sjackman** [comment]
The upstream repository Homebrew/brew is now accepting patches for Linux. We're working on merging all the Linuxbrew patches into Homebrew/brew this year. If your work does not depend on any of the features in Linuxbrew/brew that are not currently found in Homebrew/brew, you may consider submitting this work directly upstream to Homebrew/brew. Your work is welcome here otherwise.

**Comment by blockloop** [comment]
> Does linuxbrew/services require root access?

Good question. I updated the OP on requiring root access:
> Unit files can be executed from ~/.config/systemd/user using the systemctl command with the --user flag. If root is provided then we can install the service files into /etc/systemd/system.

--- 

> Please keep the plist but armoured inside if OS.mac?

That works for me.

**Comment by blockloop** [comment]
Would it be easier to make the changes here and have them part of the upstream merge rather than trying to merge separately? I'll see if I can make the changes to upstream directly. I'm glad to hear about this honestly. A unified codebase is pretty great. 

I imagine we can just extend the Formula class with `systemd` functions and leave the plist functions as is. In the case of a unified codebase (as you said) we can switch on OS.linux or OS.mac. It might be cleaner to have OS specific ServiceCli/etc classes though rather than having a bunch of if OS.linux and if OS.mac comments.

**Comment by sjackman** [comment]
> In the case of a unified codebase (as you said) we can switch on OS.linux or OS.mac.

The Homebrew maintainers specifically want to avoid the use of `OS.mac?` scattered throughout files. They need to be isolated inside the OS demuxers. See for example 
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/extend/os/hardware.rb

> It might be cleaner to have OS specific ServiceCli/etc classes though rather than having a bunch of if OS.linux and if OS.mac comments.

:+1:
