### ISSUE TITLE
Allow installation of specific Python version e.g. 2.7.x, 3.3.x, 3.4.x, 3.5.x, 3.6.x

### ISSUE THREAD

**Issue by ssteinerx** [Linuxbrew/brew#306]
As per a conversation in: #303.

It is necessary, when creating libraries for general distribution to test under multiple Python versions e.g. 2.7.x, 3.4.x, 3.5.x, 3.6.x.

The specific use case is creation of a Jenkins Docker image to be used as a CI server to test an open source library against all supported Python versions.  The Docker image should contain all current versions of Python in common use (2.6.x...3.6.x) with the Jenkins tests themselves deciding which versions to test against.

I'm not sure what mechanism is appropriate for switching out the specific version to be installed but it wouldn't seem to require duplicating the entire formula.  The main variant is the download url, and it may vary by a dependency or two.

**Comment by sjackman** [comment]
Hi, Steve. I'm not inclined to add these many versions of Python to Linuxbrew itself. Your easiest path forward I think would be to create your own tap `ssteinerx/homebrew-python-versions` and create a formula for each version of Python, named `python@2.7`, `python3@3.6` et c. These formula could if you like all inherit from one master formula, to reduce code duplication.

**Comment by ssteinerx** [comment]
@sjackman Understood.  That's far beyond my ken at the moment but I may have to figure it out as I need the capability.
