### ISSUE TITLE
sphinx-doc: sphinx-build uses /usr/bin/python

### ISSUE THREAD

**Issue by eyzhao** [Linuxbrew/brew#313]
I'm trying to install pandoc, which requires ghc.
While installing ghc, I run into the following error:
```
make -C utils/haddock/doc html SPHINX_BUILD=/home/ezhao/.linuxbrew/opt/sphinx-doc/bin/sphinx-build
/home/ezhao/.linuxbrew/opt/sphinx-doc/bin/sphinx-build -b html . .build-html
Error: Sphinx requires at least Python 2.7 or 3.4 to run.
make[2]: *** [html] Error 1
make[1]: *** [html_utils/haddock/doc] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

as per the second line, the contents of `/home/ezhao/.linuxbrew/opt/sphinx-doc/bin/sphinx-build` are as follows
```
#!/bin/bash
 PYTHONPATH="/home/ezhao/.linuxbrew/Cellar/sphinx-doc/1.5.1/libexec/lib/python2.7/site-packages:/home/ezhao/.linuxbrew/Cellar/sphinx-doc/1.5.1/  libexec/vendor/lib/python2.7/site-packages" exec "/home/ezhao/.linuxbrew/Cellar/sphinx-doc/1.5.1/libexec/bin/sphinx-build" "$@"
```

It appears that sphinx is throwing an error when attempting to generate documentation. However, I believe I do have the correct version of python installed:
```
$ which python
~/.linuxbrew/bin/python

$ python
Python 2.7.13 (default, Feb 27 2017, 17:44:30)
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

My question is twofold:
1. Is there a suggested fix for this?
2. Alternatively, is it possible to install GHC without haddock documentation by setting the flag HADDOCK_DOCS = NO in mk/build.mk, as suggested [here](https://ghc.haskell.org/trac/ghc/wiki/Building/Docs)?  I'm not sure how to do this within the context of linuxbrew.

Thank you for your help!

**Comment by sjackman** [comment]
Hi, Eric.
```
❯❯❯ head -n1 /home/ezhao/.linuxbrew/Cellar/sphinx-doc/1.5.1/libexec/bin/sphinx-build
#!/usr/bin/python
```
`#!/usr/bin/python` should be `#!/usr/bin/env python`. That's a bug in the `sphinx-doc` formula.
As a quick workaround, I'd suggest editing that file:
```sh
sed -i 's~#!/usr/bin/python~#!/usr/bin/env python~' /home/ezhao/.linuxbrew/Cellar/sphinx-doc/1.5.1/libexec/bin/sphinx-build
```

A proper fix for the `sphinx-doc` formula would look something like
```ruby
inreplace Dir[libexec/"bin/*"], "#!/usr/bin/python", "#!/usr/bin/env python"
```

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/2214 to fix this issue.
Thanks for the bug report, Eric!

**Comment by sjackman** [comment]
This bug is fixed. The following should resolve the issue for you.
```sh
brew update
brew postinstall sphinx-doc
```

**Comment by eyzhao** [comment]
Thank you for the fix, Shaun. Got pandoc installed succesfully :)

**Comment by sjackman** [comment]
No worries! Glad we got it working.
