### ISSUE TITLE
Can't do anything -- "bad file descriptor" in lock.sh

### ISSUE THREAD

**Issue by purag** [Linuxbrew/brew#314]
`~/.linuxbrew/Library/Homebrew/utils/lock.sh` generates the following error for any `brew` command:

```
~/.linuxbrew/Library/Homebrew/utils/lock.sh: line 27: 200: Bad file descriptor
-e:1:in `initialize': Bad file descriptor (Errno::EBADF)
        from -e:1:in `new'
        from -e:1
Error: Another active Homebrew vendor-install-ruby process is already in progress.
Please wait for it to finish or terminate it to continue.
Error: Failed to install vendor Ruby.
```

I've tried `usr/bin/pkill ruby` and removing `~/.linuxbrew/var/homebrew/locks` to no avail.

I've traced this to the `setup-ruby-path` call at `~/.linuxbrew/Library/Homebrew/brew.sh:354`, so I guess it's trying to update Ruby. Commenting out the call leads to Ruby errors when running `brew.rb` so my version of Ruby seems too old.

Any help is appreciated!

**Comment by sjackman** [comment]
I don't usually say this, but have you tried rebooting your machine? 🙃

```
  # close FD first, this is required if parent process holds a different lock.
  exec 200>&-
  # open the lock file to FD, so the shell process can hold the lock.
  exec 200>"$lock_file"
```
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/utils/lock.sh#L27

I know you said you deleted the `locks` directory. Can you try at the command line:
```sh
ls -l ~/.linuxbrew/var/homebrew/locks/vendor-install-ruby
sh -c 'exec 200>&-; exec 200>~/.linuxbrew/var/homebrew/locks/vendor-install-ruby; echo good'
ls -l ~/.linuxbrew/var/homebrew/locks/vendor-install-ruby
rm -f ~/.linuxbrew/var/homebrew/locks/vendor-install-ruby
```

**Comment by purag** [comment]
I'm on a shared hosting server (hence my desire to use linuxbrew!) So unfortunately can't reboot. :(

For your suggested commands, the second one fails with 200: Bad file descriptor.

I think this might be an isolated problem on my system but I figured I'd ask here in case you've seen it before!

**Comment by sjackman** [comment]
Can you please report:
```sh
ulimit -a
ulimit -n
for i in 200 128 64 32 16 8 4 3; do
    bash -c "exec $i>&-; exec $i>~/.linuxbrew/var/homebrew/locks/vendor-install-ruby; echo good $i"
done
```

**Comment by purag** [comment]
Okay, you were on the right track! My system only allowed 100 open files. I went into lock.sh and changed `200` to `99` and all is well!

Thanks for the help -- are there any other parts of linuxbrew that might be affected by this limit?

**Comment by sjackman** [comment]
Great! Glad that we got it working!

> are there any other parts of linuxbrew that might be affected by this limit?

Not that I'm aware of.

**Comment by sjackman** [comment]
Note to self: if this bug comes up again, we should consider reducing `200` to some smaller value such as `99`.

**Comment by sjackman** [comment]
Two random systems that I tested at work have this limit set to `1024` (Linux HPC) and `2560` (macOS desktop).
@purag You may want to ask your systems group to increase the `ulimit -n` limit to say 1024.
Does `ulimit -n 1024` work, or do you need privileges for that?

**Comment by purag** [comment]
Yeah, it failed with "operation not permitted."

I wonder if there's any harm in changing that to 99 now. `flock`'s own man page example uses 200 so I'd bet it won't collide with other programs using `flock`. I could find out whether using FDs below 100 is any more risky than 200+.

In any case I'll ask if they can increase the limit, though they've been pretty uncooperative in the past. 😛

**Comment by sjackman** [comment]
> flock's own man page uses 200

Can you point me to that man page?

The only risk is that 99 file descriptors are already open, and fd 99 is already in use, which seems unlikely. If you'd like to submit a PR to decrease 200 to 99, I'd feel pretty comfortable merging it.

**Comment by purag** [comment]
[This](https://linux.die.net/man/1/flock) is the one I had on my system. Reproduced the example:

> The third form is convenient inside shell scripts, and is usually used the following manner:
> 
>     (
>       flock -s 200
>       # ... commands executed under lock ...
>     ) 200>/var/lock/mylockfile

Sure, I'll submit the PR!
