### ISSUE TITLE
`brew link` fails on formulae within multiple taps

### ISSUE THREAD

**Issue by theopolis** [Linuxbrew/brew#315]
Same as https://github.com/Homebrew/brew/issues/2288

Can you pull in https://github.com/Homebrew/brew/pull/2290?

**Comment by sjackman** [comment]
We typically only merge stable release of Homebrew into Linuxbrew. This fix will be included in Linuxbrew with the next stable release of Homebrew. Does applying this patch to your local copy work for you in the mean time?

**Comment by theopolis** [comment]
Ok cool, will do, thanks!
