### ISSUE TITLE
shellscript only formula fails to install, because of missing c-compiler even with --ignore-dependencies

### ISSUE THREAD

**Issue by mulle-nat** [Linuxbrew/brew#317]
I have a formula that installs a couple of shell scripts with no dependencies outside of bash. Unfortunately it won't install, if a C-compiler is missing.

## How to reproduce

On a fairly pristine linux `Linux terodde 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux` do:

```
sudo apt install linuxbrew-wrapper
```

and then

```
brew install --ignore-dependencies mulle-kybernetik/alpha/mulle-bootstrap
```
This fails with:

```
Error: mulle-kybernetik/alpha/mulle-bootstrap cannot be built with any available compilers.
Install Clang or brew install gcc
```

Here is the [formula](https://github.com/mulle-kybernetik/homebrew-alpha/blob/master/mulle-bootstrap.rb):

```
class MulleBootstrap < Formula
  homepage "http://www.mulle-kybernetik.com/software/git/mulle-bootstrap"
  desc "Dependency manager for cross-platform projects"
  url "http://www.mulle-kybernetik.com/software/git/mulle-bootstrap/tarball/3.1.0"
  version "3.1.0"
  sha256 "b40ed8ccabed9c01408f9507d28085079d47b46dbcb93a913bc3ba4b48d266e5"

  def install
     system "./install.sh", "#{prefix}"
  end

  test do
  end
end
# FORMULA mulle-bootstrap.rb
```

**Comment by sjackman** [comment]
Interesting. Currently there's no way to override the dependency of requiring a C compiler.
Does your host system have a C compiler? If so follow these instructions:
https://github.com/Linuxbrew/brew/wiki/Symlink-GCC

**Comment by mulle-nat** [comment]
It's not a problem, just unexpected, superflous and annoying. :)

**Comment by sjackman** [comment]
The assumption I guess is that eventually you'll install a package that requires a C compiler, so you may as well get that configuration over sooner rather than later. Is that true in your case, or do you never plan to install a formula that requires a C compiler?

**Comment by mulle-nat** [comment]
It would be true in my current case. But in a case, where I am just firing up a container it could not be so.

**Comment by sjackman** [comment]
Since formulae don't annotate whether they require a C compiler or not, I see no easy fix for this issue. A working C compiler will remain a strict dependency of Linuxbrew.
