### ISSUE TITLE
List of essential formula

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#32]
I'd like to create a list of essential formula, with which it's possible to replace the `PATH` entirely with `PATH=$(brew --prefix)/bin` and Linuxbrew will still work to install formula. I'd also like to make it easy to install those essential formula with something like `brew install essentials`

```
bash
binutils
coreutils
curl
file-formula
findutils
gawk
gcc
git
gnu-sed
gnu-tar
gnu-which
grep
make
ruby
util-linux
```

**Comment by DoomHammer** [comment]
Will add `linux-headers` to the list as well

**Comment by sjackman** [comment]
The above formula and their deps have all been bottled.

**Comment by DoomHammer** [comment]
Which formula provides `make`?

**Comment by DoomHammer** [comment]
Same question about `file`? Maybe we should have something like http://packages.debian.org that shows which formula owns which files? Maybe we do and I have no idea about it?

**Comment by sjackman** [comment]
> Will add linux-headers to the list as well

No need to specify formula that are dependencies of other essential formula. We can do the recursive deps at the end.

**Comment by sjackman** [comment]
> Maybe we should have something like http://packages.debian.org that shows which formula owns which files? Maybe we do and I have no idea about it?

We don't have that resource, but it would nice. Relatively easy to do too. Extract each bottle, and build a database of the contents. I wouldn't be surprised if someone on the net has already done this.

**Comment by sjackman** [comment]
> Which formula provides make?
> Same question about file?

`homebrew/dupes/make` and `homebrew/dupes/file-formula`

**Comment by DoomHammer** [comment]
Been searching in wrong places it seems :D

**Comment by DoomHammer** [comment]
`openssl` not bottled as yet (dep for `curl`)

**Comment by sjackman** [comment]
On a custom-prefix (non-`/home/linuxbrew/.linuxbrew`) installation, installing all of the above software takes 25 min wall clock (with pre-cached downloads).

**Comment by sjackman** [comment]
There's an open PR for `openssl`: https://github.com/Linuxbrew/homebrew-core/pull/204
but it needs some fixes, likely core fixes related to https://github.com/Linuxbrew/linuxbrew/pull/1024

**Comment by DoomHammer** [comment]
As for `linux-headers`: they are not a dep of `glibc` as yet, therefore won't be installed with said formulae. This is probably a bug for `glibc`, though.

**Comment by DoomHammer** [comment]
What is even more funny is `gcc` does not depend on `glibc`. After installation, even though compiler is installed, it won't do much as headers are missing.

**Comment by sjackman** [comment]
> What is even more funny is `gcc` does not depend on `glibc`

`gcc` depends on `GlibcRequirement`. If the host provides `glibc` ≥ 2.19, it uses that, otherwise it depends on `gcc` provided by Linuxbrew.

```
  depends_on "glibc" => Formula["glibc"].installed? || (OS.linux? && !GlibcRequirement.new.satisfied?) ? :recommended : :optional
```

https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/gcc.rb#L52

**Comment by DoomHammer** [comment]
Still, this leaves `linux-headers` potentially uninstalled. Scenario: host-provided `glibc`, no host provided `linux-headers` => no brewed `glibc` => no brewed `linux-headers` => no `linux-headers`.

**Comment by sjackman** [comment]
`gcc` definitely should not have a hard dependency on `glibc`. I think it makes sense that `glibc` should have a hard dependency on `linux-headers`. Perhaps `gcc` should have a Requirement that checks whether the host's glibc and Linux headers are installed (provided by `libc6-dev` on Debian), and if not `depends_on "glibc"`.

**Comment by DoomHammer** [comment]
Seems like a good idea to me.
