### ISSUE TITLE
findutils: /usr/bin/sort: No such file or directory

### ISSUE THREAD

**Issue by parsibox** [Linuxbrew/brew#322]
hi
updatedb has error and locate show no results
[parsibox@localhost VSCode-linux-x64]$ updatedb
/home/parsibox/.linuxbrew/Cellar/findutils/4.6.0/libexec/bin/updatedb: line 323: /usr/bin/sort: No such file or directory

[parsibox@localhost VSCode-linux-x64]$ which sort
~/.linuxbrew/bin/sort

**Comment by bw-yuhogg** [comment]
The sort program appears to be controlled by an autoconf variable for `findutils`, so we could probably make `findutils` depend on `coreutils` and rebuild the bottle.

Can you run `brew config` and paste the output here please? `/usr/bin/sort` is provided by `coreutils` on Debian/Ubuntu, and presumably by a similar package other systems. While coreutils isn't strictly speaking a dependency of Linuxbrew, other stuff could likely break if it's not available.

**Comment by bw-yuhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#2263
