### ISSUE TITLE
Fails to install pkg-config

### ISSUE THREAD

**Issue by psubnwell** [Linuxbrew/brew#335]
I need to install `python3` and `htop` with Linuxbrew under an Ubuntu server (no sudo priviledge), however, both of them failed when installing the required dependency `pkg-config`. It reports:

```
dyhu@mit232:~$ brew install pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar
Already downloaded: /home/dyhu/.cache/Homebrew/pkg-config-0.29.2.tar.gz
==> ./configure --prefix=/home/dyhu/.linuxbrew/Cellar/pkg-config/0.29.2 --disabl
Last 15 lines from /home/dyhu/.cache/Homebrew/Logs/pkg-config/01.configure:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /home/dyhu/.linuxbrew/bin/gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/pkg-config-20170409-8714-1made2m/pkg-config-0.29.2':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

`brew update`, `brew upgrade` are passed, and the complete `brew gist-logs pkg-config` reports are here:
https://gist.github.com/anonymous/f0c2b95c3daa4ae2435ce066396267a4

I browsed nearly all similar issue posts on web, but still couldn't solve it. I think it's the error of `gcc`. But the error report is still a little bit complicated and confusing for me (not very familiar with `gcc`). Really thank you if you can help me!

(I notice another bug when I install homebrew-version `git` or `curl`, whose dependencies contain both `openssl` and `pkg-config`. This time the installation of `openssl` also fails and reports error: `Failure while executing: patch -g 0 -f -p1 -i /tmp/openssl--patch-20170409-7300-1uxdf88/1524.patch`. I don't know whether these two bugs are related or not, so I just post here for your reference, really thanks!)

**Comment by psubnwell** [comment]
I uninstalled then reinstalled the Linuxbrew in order to reproduce the bug and to figure out the reason. (This time I install the Linuxbrew with `git clone` instead of `ruby` method, but I don't think this matters.)

I found that, maybe it was because the post-install step of `glibc` and `gcc` did not complete successfully. Strangely, `brew postinstall` didn't work:
```
$ brew postinstall gcc
Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
```
So I just `brew uninstall` and `brew install --force-bottle` them until they reported no errors and warnings (I means the warnings about incomplete installation). Then all packages can be compiled and installed normally.

So here are my solutions and suggestions to those friends who encounter the similar problem (I don't think all of them are neccessary):
* Use `brew uninstall <formula>` and `brew install --force-bottle <formula>` to make sure that your dependencies (especially `gcc` and `glibc`) are installed **COMPLETELY**.
* Or just reinstall the Linuxbrew.

I am not very proficient in using Linux, so **I am not sure it's the true reason**. Above are just my experience and hope that it can help you. If you find the **deeper reason** please tell me, thanks!

**Comment by sjackman** [comment]
I'm glad to hear that you got it working.
```
Inconsistency detected by ld.so: get-dynamic-info.h: 134: elf_get_dynamic_info: Assertion `info[15] == ((void *)0)' failed!
```
Possibly you have the environment variable `LD_LIBRARY_PATH` set. Check the output of `brew doctor`
