### ISSUE TITLE
Git version requirement

### ISSUE THREAD

**Issue by da-steve101** [Linuxbrew/brew#338]
Should add a git version check as I had git 1.7.1 installed which didn't have the --local flag used in brew

**Comment by bw-yuhogg** [comment]
Does `brew doctor` not warn that you have an outdated Git?

**Comment by sjackman** [comment]
`brew doctor` will warn if you're git version is less than the required version. With `brew` 1.1.12 the minimum `git` version is 1.8.5. See https://github.com/Homebrew/brew/releases/tag/1.1.12
Linuxbrew is at 1.1.11 right now.
