### ISSUE TITLE
Can't install mkvtoolnix

### ISSUE THREAD

**Issue by paradox460** [Linuxbrew/brew#339]
I've been trying to install `mkvtoolnix`, and it keeps failing, with what appears to be a docbook related compile step.

Here's the gist of the output:  
https://gist.github.com/anonymous/d074fe4340506a13cc5fd886221e0b43

I've verified that its not the formula by installing it on OS X and it works fine.

**Comment by bw-yuhogg** [comment]
https://gist.github.com/anonymous/d074fe4340506a13cc5fd886221e0b43#file-01-configure-L150-L151

```
checking for xsltproc... no
configure: error: xsltproc wasn't found
```

This appears to be a formula-specific issue with `mkvtoolnix`. Would you like to create a PR to Linuxbrew/homebrew-core to add

```
depends_on "libxslt" unless OS.mac?
```

**Comment by bw-yuhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#2338
