### ISSUE TITLE
glibc fails to build -  cannot compute suffix of object files: cannot compile

### ISSUE THREAD

**Issue by philippbayer** [Linuxbrew/brew#340]
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Confirmed this is a problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

### Bug reports:

Glibc fails to build with this error on my cluster:

```configure: error: cannot compute suffix of object files: cannot compile```

Looking at the config.log, this is the actual error:

```
configure:2716: checking for C compiler version
configure:2725: gcc-5 --version >&5
/RDS/Q0196/linuxbrew/Library/Homebrew/shims/linux/super/gcc-5:352:in `exec': No such file or directory - gcc-5 (Errno::ENOENT)
        from /RDS/Q0196/linuxbrew/Library/Homebrew/shims/linux/super/gcc-5:352:in `<main>'
```

But the symlink gcc-5 definitely exists:

```
$ ll `which gcc-5`
/RDS/Q0196/linuxbrew/bin/gcc-5 -> /sw/GCC/5.3.0/bin/gcc
$ /sw/GCC/5.3.0/bin/gcc
gcc: fatal error: no input files
compilation terminated.
```

It's rather weird, it looks like it cannot 'see' gcc-5, and I have no clue why. I put the 01.configure output and the config.log [here](https://gist.github.com/philippbayer/b11b142fda844b7f5ec3f7b0a5457b5a)

Edit start:

### Workaround 

Just found out that passing  `--env=std` circumvents the issue since then it skips the whole super-stuff. This fixes my problem but the issue remains, I guess?

Edit end

### Things I tried:

- Ran `brew doctor`, no real problem (cannot update git as glibc installation fails)

- linked the system's gcc 5.3 into brew via

```
ln -s $(which gcc) `brew --prefix`/bin/gcc-$(gcc -dumpversion |cut -d. -f1,2)
ln -s $(which g++) `brew --prefix`/bin/g++-$(g++ -dumpversion |cut -d. -f1,2)
ln -s $(which gfortran) `brew --prefix`/bin/gfortran-$(gfortran -dumpversion |cut -d. -f1,2)
```
and setting HOMEBREW_CC to gcc-5.3. 

That broke as gcc-5.3 was an 'invalid value for HOMEBREW_CC', so as described [here](https://github.com/Linuxbrew/legacy-linuxbrew/issues/425) I changed the symlinks to point from gcc-5 not gcc-5.3. Same error as above, cannot find gcc-5.

- unset HOMEBREW_CC, got 

```
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
```

- tried various older gccs also installed on this cluster (4.9.2, 4.8.4)

Here are some minor details:

<details> 
<summary>brew install output</summary>

```
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/RDS/Q0196/linuxbrew/Cellar/glibc/2.19 --enable-obsolete-rpc --without-selinux --with-binutils=/RDS/Q0196/linuxbrew/
Last 15 lines from /home/pbayer/.cache/Homebrew/Logs/glibc/01.configure:
--disable-debug
--disable-dependency-tracking
--disable-silent-rules
--prefix=/RDS/Q0196/linuxbrew/Cellar/glibc/2.19
--enable-obsolete-rpc
--without-selinux
--with-binutils=/RDS/Q0196/linuxbrew/opt/binutils/bin
--with-headers=/RDS/Q0196/linuxbrew/opt/linux-headers/include

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc-5
checking for suffix of object files... configure: error: in `/tmp/glibc-20170410-16706-bd9e8d/glibc-2.19/build':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
```
</details>

<details>
<summary>brew config output</summary>

```
HOMEBREW_VERSION: >1.1.0 (no git repository)
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 59c9ddbc1d9b9dfdeb0514768e0efd0112c63b25
Last commit: 34 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 1916543d40f317042ba5a0c027e05f98153d69f4
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /RDS/Q0196/linuxbrew
HOMEBREW_REPOSITORY: /RDS/Q0196/linuxbrew
HOMEBREW_CELLAR: /RDS/Q0196/linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit 0x1501
Homebrew Ruby: 2.0.0-p648 => /RDS/Q0196/linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 1.7.1 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: openjdk version "1.8.0_111"
Kernel: Linux 2.6.32-642.6.2.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.8 (Final)
Codename: Final
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
```
</details>

**Comment by sjackman** [comment]
You just blew my mind. I've never seen `<details>` before. Whoah.

**Comment by sjackman** [comment]
Hmm. This may be a bug related to bootstrapping with `--env=super`, which hasn't been heavily tested. If you want to try some debugging/troubleshooting try print the value of `PATH` at the line
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/shims/linux/super/cc#L346

Your workaround is a good one
```sh
brew install --env=std glibc && brew install gcc
```

I'm swamped this week, but I'll look for a better solution next week.

**Comment by philippbayer** [comment]
I wanted to play around with `<details>` :) it's not perfect, doesn't work on older browsers as it's HTML5 and for formatting like the triple quotes to work you have to add a nonsensical linebreak.

I'll have to wait for the playing around once the student has finished his work as I'll have to delete glibc again. Might take a while, but I can bet a beer that it'll probably be PATH related as you say

**Comment by jbadomics** [comment]
+1 for Shaun's suggestion. I was running into the same glibc error above on CentOS 6.8. I also needed this [workaround](https://github.com/Linuxbrew/legacy-linuxbrew/issues/517#issuecomment-206515497) before installing glibc and gcc:

```
ln -s $(which gcc) `brew --prefix`/bin/gcc-$(gcc -dumpversion |cut -d. -f1,2)
ln -s $(which g++) `brew --prefix`/bin/g++-$(g++ -dumpversion |cut -d. -f1,2)
ln -s $(which gfortran) ./.linuxbrew/bin/gfortran-4.4
```

After creating those symlinks this worked just fine for me:

```
brew install --env=std glibc && brew install gcc
rm ~/.linuxbrew/bin/*-4.4
brew test gcc
```

**Comment by sjackman** [comment]
The symlink GCC workaround is documented at https://github.com/Linuxbrew/brew/wiki/Symlink-GCC
Linuxbrew really should handle creating those symlinks itself when it finds that it has no compiler.

The default build environment for `glibc` is now `--env=std`:
https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/glibc.rb#L22

**Comment by philippbayer** [comment]
In that case I vote for this issue to be closed 👍 

I can confirm that on the affected system since running

    brew uninstall glibc
    brew install glibc

works with a few warnings but that's to be expected since I'm ripping out an essential part.

<details>
<summary>Installation output</summary>

```
$ brew uninstall glibc
Uninstalling /RDS/Q0196/linuxbrew/Cellar/glibc/2.19... (1,406 files, 42.7MB)
$ brew install glibc
Warning: git-2.12.2 already installed
Error: Git must be installed and in your PATH!
/RDS/Q0196/linuxbrew/opt/gcc/bin/gcc-5: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /RDS/Q0196/linuxbrew/opt/gcc/bin/gcc-5)
==> Downloading https://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
Already downloaded: /home/pbayer/.cache/Homebrew/glibc-2.19.tar.bz2
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/RDS/Q0196/linuxbrew/Cellar/glibc/2.19 --enable-obsolete-r
==> make
==> make install
==> /RDS/Q0196/linuxbrew/Cellar/glibc/2.19/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
🍺  /RDS/Q0196/linuxbrew/Cellar/glibc/2.19: 1,371 files, 38.9MB, built in 6 minutes 4 seconds

```
</details>

**Comment by sjackman** [comment]
😮 I've never been brave enough to remove `glibc`. Glad too see that it works!
