### ISSUE TITLE
/home/travis/.linuxbrew/Library/ENV/scm/git: No such file or directory

### ISSUE THREAD

**Issue by dpo** [Linuxbrew/brew#346]
On TravisCI/Linux, I keep getting
```
/home/travis/.linuxbrew/Library/Homebrew/cmd/update.sh: line 6: /home/travis/.linuxbrew/Library/ENV/scm/git: No such file or directory
```
The error message seems related to https://github.com/Homebrew/brew/issues/557 but the [fix suggested there](https://github.com/Homebrew/brew/issues/557#issuecomment-233710397),
```
cd "$(brew --repository)" && git fetch && git reset --hard origin/master
```
doesn't appear to resolve the issue. I don't have this problem on TravisCI/OSX.

Example:
* fix applied [here](https://travis-ci.org/optimizers/homebrew-cutest/jobs/222179119#L426)
* error message [here](https://travis-ci.org/optimizers/homebrew-cutest/jobs/222179119#L517)

Any ideas?

**Comment by sjackman** [comment]
Your `brew` seems quite out of date. How are you installing Linuxbrew on Travis? Please include a link to the relevant line in your `.travis.yml`.

**Comment by dpo** [comment]
Ah, I see. Here's what I've been using for a long time: https://github.com/optimizers/homebrew-cutest/blob/master/setup_travis_linux.sh#L7 but I haven't keept up with Linuxbrew lately. I see that things have changed. Thanks!

**Comment by sjackman** [comment]
Ah, yep. That's super old. Really super old. =) Changing that line to the following should fix it:
```sh
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
```
 See http://linuxbrew.sh

**Comment by dpo** [comment]
=). Thanks! That fixed that. Now I'm not understanding why `brew test` isn't a recognized command: https://travis-ci.org/optimizers/homebrew-cutest/jobs/222357491#L663

Sorry for the hassle.

**Comment by sjackman** [comment]
No worries, Dominique. Glad that we sorted it out.

**Comment by dpo** [comment]
Thanks Shaun! Any idea why [`brew test` fails](https://travis-ci.org/optimizers/homebrew-cutest/jobs/222555258#L585) though?

**Comment by sjackman** [comment]
`Error: cannot load such file -- test/unit/assertions`
https://travis-ci.org/optimizers/homebrew-cutest/jobs/222555258#L585

I've seen this error before. I think it means some Ruby package is missing. I couldn't tell you which. Sorry I can't be more helpful. Here's the `.travis.yml` of `Linuxbrew/brew`:
https://github.com/Linuxbrew/brew/blob/master/.travis.yml#L9
