### ISSUE TITLE
Kraken fails to build on CentOS release 6.6

### ISSUE THREAD

**Issue by ACharbonneau** [Linuxbrew/brew#352]
I can get Kraken to successfully install on my laptop with homebrew, but not on my HPC. 
I've tried update/upgrade several times and uninstalling/reinstalling dependencies.
I cannot get `brew install fontconfig` to run either, but I'm not sure if that's relevant.

https://gist.github.com/anonymous/af9a8a78c4d215e1990ebcbc782a29b0

**Comment by ACharbonneau** [comment]
I just got it running on an EC2 instance, at which point I found that kraken doesn't seem to be supported/updated anymore. So nevermind I guess :/

**Comment by sjackman** [comment]
Hi, Amanda.

```
Error: expecting string instruction after `rep' 
```
https://gist.github.com/anonymous/af9a8a78c4d215e1990ebcbc782a29b0#file-01-install_kraken-sh-L12

It looks as though it's using your host's assembler`as`, which is causing it to fail. Try…
```sh
brew install binutils
brew install --env=std kraken
```
