### ISSUE TITLE
Error: glibc cannot be built with any available compilers

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/brew#353]
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Confirmed this is a problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

### Bug reports:

I am receiving the following error with backtrace.

```
% brew install -d glibc
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/linux-headers.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/gmp.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/libmpc.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/mpfr.rb
/tmp/brew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/isl.rb
/tmp/brew/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
/tmp/brew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/tmp/brew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb
/tmp/brew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/linux-headers.rb
/tmp/brew/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /tmp/brew/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
/tmp/brew/Library/Homebrew/compilers.rb:127:in `compiler'
/tmp/brew/Library/Homebrew/compilers.rb:109:in `select_for'
/tmp/brew/Library/Homebrew/extend/ENV/shared.rb:171:in `compiler'
/tmp/brew/Library/Homebrew/extend/ENV/std.rb:74:in `setup_build_environment'
/tmp/brew/Library/Homebrew/build.rb:92:in `install'
/tmp/brew/Library/Homebrew/build.rb:201:in `<main>'

```

`brew config`
```
% brew config
HOMEBREW_VERSION: 1.1.11-7-g6db39d7
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 6db39d7080dfb5dd5449f39f254d7972099bf9f7
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 2db0e34bb146e0d5a655f9f44cecc6bfff1f5fd5
Core tap last commit: 74 minutes ago
HOMEBREW_PREFIX: /tmp/brew
HOMEBREW_REPOSITORY: /tmp/brew
HOMEBREW_CELLAR: /tmp/brew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648 => /tmp/brew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 2.4.6 => /usr/local/x64/git-2.4.6/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_121
Kernel: Linux 2.6.32-642.15.1.el6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Workstation release 6.8 (Santiago)
Codename: Santiago
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
```

`brew doctor`
```
% brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /usr/local/bin/libmcrypt-config

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/librfftw.la
  /usr/local/lib/liba2ps.la
  /usr/local/lib/libpdf_java.la
  /usr/local/lib/libdvi2bitmap.la
  /usr/local/lib/libpdf.la
  /usr/local/lib/libmp4v2.la
  /usr/local/lib/libmhash.la
  /usr/local/lib/libfftw.la
  /usr/local/lib/libmcrypt.la
  /usr/local/lib/libfaad.la
  /usr/local/lib/libsndfile.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libsndfile.a
  /usr/local/lib/libmfhdf.a
  /usr/local/lib/librx.a
  /usr/local/lib/libnetcdf-3.5.1_nf95.a
  /usr/local/lib/libfreq.a
  /usr/local/lib/libmp4v2.a
  /usr/local/lib/libmhash.a
  /usr/local/lib/libdvi2bitmap.a
  /usr/local/lib/libnetcdf-3.5.1_pgi.a
  /usr/local/lib/libxvidcore.a
  /usr/local/lib/libsx.a
  /usr/local/lib/libudport.a
  /usr/local/lib/libpdf_java.a
  /usr/local/lib/libdf.a
  /usr/local/lib/libnetcdf-3.5.1_gnu.a
  /usr/local/lib/libfaad.a
  /usr/local/lib/libpdf.a
  /usr/local/lib/libnetcdf-3.5.1_lf95.a
  /usr/local/lib/liba2ps.a
  /usr/local/lib/libnetcdf_c++-3.5.1.a
  /usr/local/lib/libudunits.a
  /usr/local/lib/libnetcdf-3.5.1_ifort.a
```

**Comment by sjackman** [comment]
See https://github.com/Linuxbrew/brew/wiki/Symlink-GCC

**Comment by carlorosati** [comment]
Is this something that the installer script should do?

When did this become necessary? I used to be able to simply clone brew and brew install gcc.

**Comment by sjackman** [comment]
It should no longer be necessary once Linuxbrew 1.1.12 is released. It'll create the symlinks for you automatically.

**Comment by 1-61803** [comment]
@sjackman, on `CentOS` 6.9 I tried (these steps)[http://linuxbrew.sh/#install-linuxbrew] and got this same error. Then I found (these others)[https://github.com/Linuxbrew/brew/wiki/CentOS6#install-linuxbrew-on-centos-6-without-sudo] in the wiki with unexpected results.
```
[linuxbrew@centos6 ~]$ HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc --without-glibc
which: no ruby in (/usr/bin:/bin:/usr/sbin:/sbin)
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
Error: The following formula:
  gcc
cannot be installed as a binary package and must be built from source.
Install Clang or brew install gcc
```
but if I run it without the vars it does install `glibc` and then `gcc` as deps for `git`.
```
brew install gcc --without-glibc
```
Am I missing something?

**Comment by 1-61803** [comment]
@sjackman, on `CentOS` 6.9 I tried [these steps](http://linuxbrew.sh/#install-linuxbrew) and got this same error. Then I found [these others](https://github.com/Linuxbrew/brew/wiki/CentOS6#install-linuxbrew-on-centos-6-without-sudo) in the wiki with unexpected results.
```
[linuxbrew@centos6 ~]$ HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc --without-glibc
which: no ruby in (/usr/bin:/bin:/usr/sbin:/sbin)
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
Error: The following formula:
  gcc
cannot be installed as a binary package and must be built from source.
Install Clang or brew install gcc
```
but if I run it without the vars it does install `glibc` and then `gcc` as deps for `git`.
```
brew install gcc --without-glibc
```
Am I missing something?

**Comment by sjackman** [comment]
Do you have `sudo` access, and is Linuxbrew installed in `/home/linuxbrew/.linuxbrew`? If so, follow these instructions:
https://github.com/Linuxbrew/brew/wiki/CentOS6#install-linuxbrew-on-centos-6-with-sudo

**Comment by 1-61803** [comment]
Ok, it installs if user is in `sudoers`. What's the alternative if it's not?

NB `brew doctor` warned about the `git` version, installing it with `brew` succeeded although it showed `Error: Failure while executing: git config --local --replace-all homebrew.analyticsmessage true`.

**Comment by sjackman** [comment]
The alternative without `sudo` is the installation instructions that you followed. https://github.com/Linuxbrew/brew/wiki/CentOS6#install-linuxbrew-on-centos-6-without-sudo
This error `cannot be installed as a binary package and must be built from source.` shouldn't be shown if you have a compiler installed at `/usr/bin/gcc`.

**Comment by 1-61803** [comment]
Now I cannot reproduce that error. I restored the snapshot for this `CentOS` 6.9 VM and it doesn't have `gcc`, so I can just do `brew install gcc` right away. I don't know if previous versions did, but maybe those instructions might need an update.

**Comment by sjackman** [comment]
Looks like a different-than-expected result perhaps because `/usr/bin/git` is not present in your system, causing Linuxbrew to try to install `git`, which happens to also install `gcc`. Thanks for the bug report and work around. Sounds like you have it working now though?

**Comment by 1-61803** [comment]
I restored the snapshot for this plain `CentOS` 6.9 VM and it doesn't have `gcc`, so I can just do `brew install gcc` right away. I don't know if previous versions did, but maybe those instructions might need an update.

**Comment by 1-61803** [comment]
Yeah, I got it working. No `gcc` no `git` on 6.9.

**Comment by sjackman** [comment]
No `/usr/bin/gcc` is fine if you have `sudo`, but if you don't, you'll need a compiler provided by the host to bootstrap `glibc`.

**Comment by 1-61803** [comment]
I found this to be most straightforward on `CentOS` 6.9, further reducing the overhead and hassle from 2.1G installing deps with `yum`, to 1.6G by handling everything with `brew`.
```
useradd -d /home/linuxbrew linuxbrew
passwd linuxbrew
su - linuxbrew
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
test -d /home/linuxbrew/.linuxbrew && PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH" && echo $PATH
test -r ~/.bash_profile && echo "export PATH='$(brew --prefix)/bin:$(brew --prefix)/sbin'":'"$PATH"' >>~/.bash_profile && printf "${PATH//:/\\n}"\\n
brew install hello && brew test hello && brew doctor  # portable-ruby, git, glibc, gcc
```

A couple of observations that might need separate issues.

After running the script I have this `PATH`
```
[linuxbrew@centos6 ~]$ printf "${PATH//:/\\n}"\\n
/usr/local/bin
/bin
/usr/bin
/usr/local/sbin
/usr/sbin
/sbin
/home/linuxbrew/bin  <-----
```

Trying to install multiple formulas doesn't report progress until I abort.
```
[linuxbrew@centos6 ~]$ brew install git hello
Updating Homebrew...
^CWarning: git 2.16.2 is already installed
Warning: hello 2.10 is already installed
```

Also, root can not even simple commands like `brew ls`?

**Comment by sjackman** [comment]
`/home/linuxbrew/bin` should be `/home/linuxbrew/.linuxbrew/bin` to use non-relocatable bottles.

> Trying to install multiple formulas doesn't report progress until I abort.

Try `brew update && brew install git hello`

> Also, root can not even simple commands like brew ls?

Correct. Linuxbrew must be run as a non-priveleged user.

**Comment by 1-61803** [comment]
Just **after** running `install.sh` but **before** I add `/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin`, the `PATH` includes `/home/linuxbrew/bin`. After a quick look at the script I couldn't trace where in the code this happens. Bug?

Re multiple formulas, `brew update` stalls for some reason, without autoupdate this works.
```
[linuxbrew@centos6 ~]$ HOMEBREW_NO_AUTO_UPDATE=1 brew install git hello
Warning: git 2.16.2 is already installed
Warning: hello 2.10 is already installed
```

Couldn't `linuxbrew` override `homebrew` in order to run some commands like `brew info` or `brew ls` as root, but not `brew install`?

**Comment by sjackman** [comment]
> Just after running install.sh but before I add /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin, the PATH includes /home/linuxbrew/bin.

Assuming that you've installed Linuxbrew in `/home/linuxbrew/.linuxbrew` and not in `/home/linuxbrew`, I believe it's your host's default bashrc that's adding `/home/linuxbrew/bin` to your PATH, not Linuxbrew.

>  Couldn't linuxbrew override homebrew in order to run some commands like brew info or brew ls as root, but not brew install?

We do not support running Linuxbrew as root. I would be a security hazard.

**Comment by 1-61803** [comment]
Yeah, it wasn't `~/.bashrc` but `~/.bash_profile` that set it.
Also, I haven't tested in other systems but `brew update` takes around 5', and without `-v` it can be misleading when installing with autoupdate enabled.

**Comment by 1-61803** [comment]
Maybe autoupdate could be verbose depending on the last time it run.

**Comment by sjackman** [comment]
Five minutes? That's a long time. It should only take that long the first time that it is run. Subsequent runs should be much faster. A message that it's updating would be helpful.

**Comment by 1-61803** [comment]
Yeah, `HEAD` at `69ecf7d`, 4 days ago, still it downloads 130 MB.

**Comment by sjackman** [comment]
Yipes. That sounds like an awful lot. I wonder why…

**Comment by sjackman** [comment]
```
❯❯❯ du -sh $(brew --repo homebrew/core)/.git
211M
```
The entire history is 211 MB. It's supposed to use a shallow clone by default.

**Comment by 1-61803** [comment]
I ran `du` for `linuxbrew` 4.7M (last update 4 days ago) and for `homebrew` 5.7M (last update 13 days ago). When I then updated `homebrew` it took less than a minute. Can you try updating `linuxbrew` on a machine that hasn't been recently updated?

**Comment by sjackman** [comment]
`brew update` can take quite a while if it hasn't been recently updated. It runs `git pull` to update.

**Comment by 1-61803** [comment]
I reran `brew update` and retook the VM snapshot. I'll let it sit for a while and report back if this happens again. Resolving the deltas took quite a while.

**Comment by tasdemir** [comment]
Warning: Building gcc from source: 

The bottle needs the Xcode CLT to be installed. xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun Error: gcc cannot be built with any available compilers. Install GNU's GCC brew install gcc


OK
I need to install the latest xcode command line tools.

xcode-select --install

Then I was able to run Yarn install

brew install yarn

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This issue is for Linuxbrew, running Homebrew on Linux.
