### ISSUE TITLE
python3: build error

### ISSUE THREAD

**Issue by seanjensengrey** [Linuxbrew/brew#36]
It reliably takes two invocations of 

```
brew install python3
```

to install python3. The first invocation only installs the dependencies. The second invocation actually installs `python3`

platform: Ubuntu 14.04 LTS installed via

```
echo "export HOMEBREW_MAKE_JOBS=4" >> ~/.profile

# linuxbrew
echo | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
echo 'PATH=~/.linuxbrew/bin:$PATH' >> ~/.profile

. $HOME/.profile

brew update
brew install python3
```

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-core#239
