### ISSUE TITLE
Extremely slugging performance on WSL

### ISSUE THREAD

**Issue by tnguyen14** [Linuxbrew/brew#361]
I just set up a new WSL environment, and trying to install some software with linuxbrew. However, I've noticed that it's very very slow. For example, installing node (even with the download cached) took almost 30 minutes!

```
02:42 tri ~
:; brew install node
nice: cannot set niceness: Permission denied
==> Downloading https://nodejs.org/dist/v7.9.0/node-v7.9.0.tar.xz
Already downloaded: /home/tri/.cache/Homebrew/node-7.9.0.tar.xz
==> ./configure --prefix=/home/tri/.linuxbrew/Cellar/node/7.9.0 --without-npm --with-intl=system-icu --without-snapshot
==> make install
==> Downloading https://registry.npmjs.org/npm/-/npm-4.2.0.tgz
Already downloaded: /home/tri/.cache/Homebrew/node--npm-4.2.0.tgz
==> ./configure --prefix=/home/tri/.linuxbrew/Cellar/node/7.9.0/libexec/npm
==> make install
nice: cannot set niceness: Permission denied
==> Caveats
Bash completion has been installed to:
  /home/tri/.linuxbrew/etc/bash_completion.d

==> Summary
🍺  /home/tri/.linuxbrew/Cellar/node/7.9.0: 3,077 files, 40.6MB, built in 27 minutes 21 seconds
03:16 tri ~
```

Is this the expected behavior? Is there a way to debug what might be causing the slowness? I noticed that it spent the bulk of the time on the `make install` step.

**Comment by sjackman** [comment]
Hi, Tri. Installing Linuxbrew in `/home/linuxbrew/.linuxbrew` will speed it up greatly.
See https://github.com/Linuxbrew/brew/wiki/FAQ#why-install-in-homelinuxbrewlinuxbrew

**Comment by tnguyen14** [comment]
Hi, the link you mentioned doesn't really explain the issue that I'm seeing.

And how do I install Linuxbrew in that directory? The default ruby installation script puts in the current user's home direectory.

**Comment by sjackman** [comment]
Compiling `node` from source takes half an hour.
See for example https://travis-ci.org/Linuxbrew/homebrew-core/builds/221877938
and https://circleci.com/gh/Linuxbrew/homebrew-core/4938
Using a precompiled binary bottle will be much faster.

To install in a different directory
See http://linuxbrew.sh/#installation
```sh
mkdir /home/linuxbrew
git clone https://github.com/Linuxbrew/brew /home/linuxbrew/.linuxbrew
PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
brew update
brew install node
```

**Comment by tnguyen14** [comment]
@sjackman why would installing it in `/home/linuxbrew/.linuxbrew` make it use a pre-built binary?

**Comment by tnguyen14** [comment]
Nevermind. I think I understand it now. It was prebuilt with that path in mind.

**Comment by tnguyen14** [comment]
Do you know why I keep seeing these messages?

```
nice: cannot set niceness: Permission denied
```

**Comment by sjackman** [comment]
No, I don't. But you could open an issue at https://github.com/Microsoft/BashOnWindows
Did installing in `/home/linuxbrew/.linuxbrew` work for you, and was it faster to install `node`?

**Comment by ghost** [comment]
@sjackman 
> Hi, Tri. Installing Linuxbrew in /home/linuxbrew/.linuxbrew will speed it up greatly.

why is it then not the default? (I certainly have to build a lot myself but thought this was because of the ARM chip)

this is my config which was just paste and go from your hp
```
HOMEBREW_PREFIX: /home/pi/.linuxbrew
HOMEBREW_REPOSITORY: /home/pi/.linuxbrew
HOMEBREW_CELLAR: /home/pi/.linuxbrew/Cellar
```

thanks

**Comment by sjackman** [comment]
@monouser7dig There are no prebuilt bottles for ARM, so you'll have to build everything from source.

> why is it then not the default?

The plan is for it to be the default. We haven't made that switch yet.

**Comment by ghost** [comment]
So for me it wońt change anything anyway but thanks anyway!

**Comment by sjackman** [comment]
I'm glad to see that you're using Linuxbrew on the Raspberry Pi! @xu-cheng was looking for beta testers for ARM.

**Comment by ghost** [comment]
yeah works reasonable well, installed nano, vim, htop, ruby and some stuff though it 
also using it on my Mac

dunno if I can help in some way I'd gladly do as far as I can 
I read quite a bit into home-brew but don't think am really ready for doing something to the code itself
