### ISSUE TITLE
Travis and Circle CIs are broken for C++14 (Ubuntu 14.04 libs)

### ISSUE THREAD

**Issue by rakhimov** [Linuxbrew/brew#366]
On CI builds, cxx14 builds are failing with linking ABI issues gcc 5 vs. gcc 4.

Upgrade the platform to Ubuntu 16.04 with docker builds.

Moreover, what is the point of having two CI systems doing the same thing?
Either circle or travis is redundant.

**Comment by sjackman** [comment]
> On CI builds, cxx14 builds are failing with linking ABI issues gcc 5 vs. gcc 4.

Please give a specific example.

> Upgrade the platform to Ubuntu 16.04 with docker builds.

That is the plan when we migrate to CircleCI 2.0.

> Moreover, what is the point of having two CI systems doing the same thing?

We run Ubuntu 12 with GCC 5.3 on TravisCI and Ubuntu 14 with GCC 4.8 on CircleCI.

**Comment by rakhimov** [comment]
Example builds failing with cxx14 linuxbrew only: https://github.com/Homebrew/homebrew-science/pull/5263

Does linuxbrew consider the compiler abi versions when using the system libraries?

**Comment by sjackman** [comment]
Homebrew/homebrew-science#5263 has no CI failures. Do you have an example of one with CI failures?

> Does linuxbrew consider the compiler abi versions when using the system libraries?

No, it does not check the ABI of host libraries. It does check the ABI of brewed dependencies.

**Comment by rakhimov** [comment]
The failures are shown in the CI build histories. I added a workaround to exclude linuxbrew.
Anyway, I pushed the script again with the workaround removed;
this should show the linker failures.

**Comment by sjackman** [comment]
You can use `depends_on :macos` if you want the CI to "pass" on Linux. If you do, please include a comment like
```
# C++14 uses GCC 5.3, which is not ABI compatible with GCC 4.8
depends_on :macos
```

**Comment by sjackman** [comment]
It should be possible to build this formula on Linuxbrew if you build it and all of its dependencies from source using `g++-5`.
