### ISSUE TITLE
Disable brew cask

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#37]
Display a message that `brew cask` distributes Mac applications and is not available for Linuxbrew.

**Comment by sjackman** [comment]
```
$ brew cask install google-chrome
Error: Permission denied @ dir_s_mkdir - /Library
  Most likely, this means you have an outdated version of homebrew-cask.
```

Not very helpful.

**Comment by jbcpollak** [comment]
This would be great, we use homebrew-bundle to install a bunch of programs through a `Brewfile`, and a bunch of them are Mac casks. It would be nice to ignore those instead of throwing errors.

**Comment by sjackman** [comment]
I'd be happy to accept a PR that improves the above error message and ignores casks in the Brewfile (probably two separate PRs).

**Comment by jbcpollak** [comment]
@sjackman should the PR be for this project or homebrew-bundle? Maybe this should be bug in that project?

Or should it just be in this project to ignore all attempts at cask execution?

**Comment by sjackman** [comment]
You can ask `https://github.com/Homebrew/homebrew-bundle` whether they would like to support Linux; my guess would be no, but I could be wrong. Linuxbrew does not yet have a fork of `homebrew-bundle`. I don't have the time myself to maintain that fork. Someone else could step up, if they wanted to fill that role. Linuxbrew/brew could definitely use a patch to give an informative message whenever a `brew cask` command is run saying that Linuxbrew does not yet support casks.

**Comment by bw-yuhogg** [comment]
I fixed this [here](https://github.com/Linuxbrew/brew/commit/fe7caf7cd8a413fb1118f6149ac2cf3acafd63de) but forgot to close this issue when I did so.
