### ISSUE TITLE
Updating Homebrew main gcc to 7.1

### ISSUE THREAD

**Issue by eiennohito** [Linuxbrew/brew#374]
It is a very scary thing, but I believe it should be done someday. What do you think?

Probably this task lies near #264

**Comment by sjackman** [comment]
Hi, Arseny. Yes it is a very scary thing. 😬
My plan is for Linuxbrew to follow the Ubuntu LTS releases. Ubuntu 16.04LTS Xenial uses gcc 5.3.1, so we'll stay with GCC 5 as the default, and add `gcc@6` and `gcc@7` formulae and bottles.
Your thoughts?

**Comment by eiennohito** [comment]
The plan seems good, I like it, still it needs to be documented somewhere, I believe.

**Comment by sjackman** [comment]
I created a wiki page: https://github.com/Linuxbrew/brew/wiki/Bottles

**Comment by eiennohito** [comment]
So the next release will drop support of CentOS 5? 

I really like the fact that it is possible to use a creatively set up nfs share of Linuxbrew on a zoo of different linux distros...

**Comment by sjackman** [comment]
> So the next release will drop support of CentOS 5?

It'll drop support for running binary bottles on CentOS 5. It'll still be supported on a best-effort basis for installations entirely from source. Xenial uses glibc 2.23, which requires Linux kernel 2.6.32 or later, and CentOS 5 has Linux kernel 2.6.18.

**Comment by ghost** [comment]
If you could bottle gcc7 for Arm I could compile stuff using gcc7 on my pi myself, otherwise compiling gcc7 on a pi would be pretty nasty I guess.

**Comment by sjackman** [comment]
We're not currently bottling for ARM, and have no plans to. We just don't have the time to support ARM to that degree. You could trying building GCC on ARM. A day (or possibly a few) of compile time perhaps.

**Comment by eiennohito** [comment]
I'm okay with compile the world installation, however I wonder how glibc situation will be handled in that case. I really like the fact that the binaries can work both glibc versions both higher and lower than linuxbrew's if you use e.g. docker to emulate CentOS 5 for installation of everything.

**Comment by ghost** [comment]
https://github.com/Linuxbrew/brew/issues/361#issuecomment-298667789

I thought you were looking into arm in some way?

You mean you don't have the resources to compile all the things? Would a subset of the top 100 packages be acceptable? I read that there are some statistics available for developers of homebrew. 

Thanks anyway

**Comment by sjackman** [comment]
We do support source builds on ARM on a best-effort basis. We accept PRs that fix ARM issues. We don't bottle anything for ARM. We haven't set up the CI infrastructure for it.

**Comment by ghost** [comment]
Ok
It is still a great tool for arm as well, thanks

**Comment by sjackman** [comment]
I'm glad to hear that! I was wondering how much use Linuxbrew on ARM gets.
