### ISSUE TITLE
GUI login loop after solving warning

### ISSUE THREAD

**Issue by ghost** [Linuxbrew/brew#377]
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
- [x] Confirmed this is a problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

- What you were trying to do (and why)
I was trying to solve warning about `XDG_DATA_DIRS` and insert 
```export XDG_DATA_DIRS="$HOME/.linuxbrew/share:$XDG_DATA_DIRS"``` 
to .profile.

- What happened (include command output)
I can not login through GUI on elementary OS 0.4 loki.

- What you expected to happen
Without `brew` warning,  login through GUI. 

- Step-by-step reproduction instructions (by running `brew` commands)
```
echo 'export XDG_DATA_DIRS="/home/<my-name>/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.profile
reboot
``` 
  
  
  
- ~/.xsession-errors
```
openConnection: connect: No such file or directory
cannot connect to brltty at :0
No schemas installed
```

- ```brew doctor``` output
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!


Warning: Homebrew's share was not found in your XDG_DATA_DIRS but you have
this variable set to include other locations.
Some programs like `vapigen` may not work correctly.
Consider setting the XDG_DATA_DIRS for example like so
    echo 'export XDG_DATA_DIRS="/home/<my-name>/.linuxbrew/share:$XDG_DATA_DIRS"' >> ~/.bash_profile
```

- ```brew config``` output
```
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: bceb8f873e29e05b9faf028c066a9deb8f77cc1e
Last commit: 5 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 297c5481b087df9d333d6f1a6a093e9101fe756d
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/<my-name>/.linuxbrew
HOMEBREW_REPOSITORY: /home/<my-name>/.linuxbrew
HOMEBREW_CELLAR: /home/<my-name>/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: openjdk version "1.8.0_121"
Kernel: Linux 4.4.0-77-generic x86_64 GNU/Linux
OS: elementary OS 0.4 Loki (loki)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
```

**Comment by sjackman** [comment]
@DoomHammer Any thoughts on this issue?

**Comment by ghost** [comment]
`/etc/X11/Xsession.d/60x11-common_xdg_path ` may be related to this issue,

```
$ cat /etc/X11/Xsession.d/60x11-common_xdg_path 
# This file is sourced by Xsession(5), not executed.
# Add additionnal xdg paths depending on selected desktop session

DEFAULT_XDG_CONFIG_DIRS='/etc/xdg'
DEFAULT_XDG_DATA_DIRS='/usr/local/share/:/usr/share/'
if [ -n "$DESKTOP_SESSION" ]; then
  # readd default if was empty
  if [ -z "$XDG_CONFIG_DIRS" ]; then
    XDG_CONFIG_DIRS="$DEFAULT_XDG_CONFIG_DIRS"
  fi
  XDG_CONFIG_DIRS="$DEFAULT_XDG_CONFIG_DIRS"/xdg-"$DESKTOP_SESSION":"$XDG_CONFIG_DIRS"
  export XDG_CONFIG_DIRS
  # gnome is already added if gnome-session installed
  if [ "$DESKTOP_SESSION" != "gnome" ]; then
     if [ -z "$XDG_DATA_DIRS" ]; then
       XDG_DATA_DIRS="$DEFAULT_XDG_DATA_DIRS"
     fi
     XDG_DATA_DIRS=/usr/share/"$DESKTOP_SESSION":"$XDG_DATA_DIRS"
     export XDG_DATA_DIRS
  fi
fi
```
so I insert 
```
XDG_DATA_DIRS='/usr/local/share/:/usr/share/'
export XDG_DATA_DIRS="$HOME/.linuxbrew/share:$XDG_DATA_DIRS"
```
to `~/.profile`. After the change, I tried to login through GUI and  succeeded in login.

# outputs after the login
```
$ brew doctor
Your system is ready to brew.
$ echo $XDG_DATA_DIRS
/usr/share/pantheon:/home/<my-name>/.linuxbrew/share:/usr/local/share/:/usr/share/
```

**Comment by sjackman** [comment]
I'm glad that you were able to find a solution! Thanks for posting the solution here.

**Comment by DoomHammer** [comment]
It's still worth addressing, though. We recommend setting `XDG_DATA_DIRS` with Homebrew as preferred source. Clearly this does not work well with Pantheon. I wonder how can we make sure things are always splendid...

**Comment by sjackman** [comment]
This problem is similar to the `LD_LIBRARY_PATH` issue. Setting `LD_LIBRARY_PATH` globally doesn't work because it affects both host and Linuxbrew executables. Instead we encode the `RPATH` in the Linuxbrew executables. Setting `XDG_DATA_DIRS` will have issues for the same reason. The same solution would work here I think. Encode the `XDG_DATA_DIRS` in the brewed executable, probably using a `./configure` option or equivalent.

**Comment by DoomHammer** [comment]
I didn't even know it was possible to compile them. BTW: this would make all apps using `XDG_` bound to the specified Cellar, wouldn't it?

**Comment by sjackman** [comment]
Perhaps it's not possible. I'm afraid I'm not terribly familiar with XDG. And yes, you're right, that would tie it to that specific Cellar, which is a big downside. One possible solution is to use a shell wrapper for each executable to set `XDG_DATA_DIRS`. `brew` has helper code to do that and move the real executable to a different directory, usually `libexec`.

**Comment by DoomHammer** [comment]
Yes. But we don't know up front which application uses those envs and which does not. We could scan the source code of course, but I believe this is a little bit beyond our scope.
