### ISSUE TITLE
Pkg-config not in path when installing formula

### ISSUE THREAD

**Issue by paulhybryant** [Linuxbrew/brew#379]
Trying to install a formula and was getting error about ncurses not installed.

Investigate further it shows pkg-config is the one at /usr/bin

~/.linuxbrew/bin is not in the path of the shell (by entering the shell using brew install --debug)

How should I debug this?

Thanks!

**Comment by sjackman** [comment]
Which formula are you trying to install?
That formula should use…
```ruby
depends_on "pkg-config" => :build
```

**Comment by paulhybryant** [comment]
Thanks. The formula I am trying to install is progress and it is not using what you mentioned here.
