### ISSUE TITLE
pkg-config: glib/glib/gcharset.c:119: undefined reference to `_g_locale_charset_unalias'

### ISSUE THREAD

**Issue by sebma** [Linuxbrew/brew#381]
Hi, I cannot build pkg-config on Debian Jessie : I get 3 undefined reference in glib/glib/gcharset.c

Here are the details : 

- [ ] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?

```
$ brew update 
Already up-to-date.
```

- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

I did

- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

```
$  brew config
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 5f808f9919f1752cee09b520b08f6d6605f7b732
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: b18b61a314a41cf7c1d98bda3c1f2a84afe348c4
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /cal/homes/mansfeld/.linuxbrew
HOMEBREW_REPOSITORY: /cal/homes/mansfeld/.linuxbrew
HOMEBREW_CELLAR: /cal/homes/mansfeld/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit sandybridge
Homebrew Ruby: 2.1.5 => /usr/bin/ruby2.1
Clang: 3.5 build 
Git: 2.1.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.1
Java: 1.7.0_121
Kernel: Linux 3.16.0-4-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 8.8 (jessie) (jessie)
Host glibc: 2.19
/usr/bin/gcc: 4.9.2
glibc: N/A
gcc: N/A
xorg: N/A
```

- [x] Confirmed this is a problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

I don't have this problem with Homebrew on MacOSX : 
```
$ brew reinstall pkg-config
==> Reinstalling pkg-config 
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2.sierra.bottle.tar.gz
Already downloaded: /Users/mansfeld/Library/Caches/Homebrew/pkg-config-0.29.2.sierra.bottle.tar.gz
==> Pouring pkg-config-0.29.2.sierra.bottle.tar.gz
==> Using the sandbox
🍺  /usr/local/Cellar/pkg-config/0.29.2: 11 files, 627KB
$ echo $?
0
```

To help us debug your issue please explain:
- What you were trying to do (and why)

I am trying to build pkg-config. 
Because it is a needed dependency for many packages.

- What happened (include command output)

```
 brew install pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
######################################################################## 100.0%
==> ./configure LD=/cal/homes/mansfeld/.linuxbrew/bin/ld --prefix=/cal/homes/mansfeld/.linuxbrew/Cellar/pkg-config/0.29.2 --disabl
==> make
Last 15 lines from /cal/homes/mansfeld/.cache/Homebrew/Logs/pkg-config/02.make:
./glib/glib/.libs/libglib-2.0.a(libglib_2_0_la-gcharset.o): In function `get_alias_hash':
/tmp/pkg-config-20170512-25944-s31hch/pkg-config-0.29.2/glib/glib/gcharset.c:54: undefined reference to `_g_locale_get_charset_aliases'
./glib/glib/.libs/libglib-2.0.a(libglib_2_0_la-gcharset.o): In function `g_get_charset':
/tmp/pkg-config-20170512-25944-s31hch/pkg-config-0.29.2/glib/glib/gcharset.c:193: undefined reference to `_g_locale_charset_raw'
./glib/glib/.libs/libglib-2.0.a(libglib_2_0_la-gcharset.o): In function `g_utf8_get_charset_internal':
/tmp/pkg-config-20170512-25944-s31hch/pkg-config-0.29.2/glib/glib/gcharset.c:119: undefined reference to `_g_locale_charset_unalias'
collect2: error: ld returned 1 exit status
Makefile:571: recipe for target 'pkg-config' failed
make[2]: *** [pkg-config] Error 1
make[2]: Leaving directory '/tmp/pkg-config-20170512-25944-s31hch/pkg-config-0.29.2'
Makefile:707: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/pkg-config-20170512-25944-s31hch/pkg-config-0.29.2'
Makefile:463: recipe for target 'all' failed
make: *** [all] Error 2
```

- What you expected to happen

```
🍺  /cal/homes/mansfeld/.linuxbrew/Cellar/pkg-config/0.29.2: 11 files, 627KB
$ echo $?
0
```
:)

- Step-by-step reproduction instructions (by running `brew` commands)

`$ brew install pkg-config`

**Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered.
Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `pkg-config`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sebma** [comment]
```
$ mkdir -pv /home/linuxbrew/.linuxbrew/
mkdir: cannot create directory ‘/home/linuxbrew’: Permission denied
```
:(

**Comment by sebma** [comment]
Do you have another idea ?

**Comment by sjackman** [comment]
Is this your own computer that you have administrator privilege on? If so, try
```sh
sudo mkdir /home/linuxbrew
sudo chown $USER: /home/linuxbrew
git clone https://github.com/Linuxbrew/brew /home/linuxbrew/.linuxbrew
PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
brew install pkg-config
```

**Comment by sebma** [comment]
Unfortunately, I am not : 
```
$ groups | egrep -w "sudo|admin"
$
```

**Comment by sebma** [comment]
Can you help creating an issue at [pkg-config site](https://freedesktop.org/wiki/Software/pkg-config/) to tell them their package is not relocatable ?

**Comment by sjackman** [comment]
```
❯❯❯ brew list pkg-config
/home/linuxbrew/.linuxbrew/Cellar/pkg-config/0.29.2/bin/pkg-config
/home/linuxbrew/.linuxbrew/Cellar/pkg-config/0.29.2/share/aclocal/pkg.m4
/home/linuxbrew/.linuxbrew/Cellar/pkg-config/0.29.2/share/doc/pkg-config/pkg-config-guide.html
/home/linuxbrew/.linuxbrew/Cellar/pkg-config/0.29.2/share/man/man1/pkg-config.1
```
I've got a feeling that the bottle would work just fine. I don't see any data files in there that `pkg-config` would need to find. You can try
```sh
brew install --force-bottle pkg-config
brew test pkg-config
```
Can you please report whether that works?

**Comment by sebma** [comment]
Thanks a LOT !

```
==> Downloading https://linuxbrew.bintray.com/bottles/pkg-config-0.29.2.x86_64_linux.bottle.tar.gz
######################################################################## 100,0%
==> Pouring pkg-config-0.29.2.x86_64_linux.bottle.tar.gz
🍺  /cal/homes/mansfeld/.linuxbrew/Cellar/pkg-config/0.29.2: 11 files, 640.3KB
$ brew test pkg-config
Testing pkg-config
==> /cal/homes/mansfeld/.linuxbrew/Cellar/pkg-config/0.29.2/bin/pkg-config --libs openssl
$ echo $?
0

```

**Comment by sjackman** [comment]
No worries. I'm glad that it worked!
