### ISSUE TITLE
Installing on a Linux box being not in sudoers breaks the install.

### ISSUE THREAD

**Issue by giupo** [Linuxbrew/brew#384]
I'm trying to install Linuxbrew on a system where I'm not in sudoers (and I don't want/can't be), but the install script (https://raw.githubusercontent.com/Linuxbrew/install/master/install) is full of sudo invocations which collides with what is stated in the README.md (https://github.com/Linuxbrew/brew/blob/master/README.md#features) 

Further inspection of commits on Linuxbrew/install shows that several checks have been recently chunked out https://github.com/Linuxbrew/install/commit/acc72841d05030e645ab806b88fd65de0843aedc?diff=unified#diff-19ad89bc3e3c9d7ef68b89523eff1987L217 , maybe this is the root cause

HTH.

**Comment by sjackman** [comment]
Thanks for the bug report, Giuseppe. The installer is not intended to require `sudo`. I'll take a look at it. In the mean time, you can install without `sudo` using…
```sh
git clone https://github.com/Linuxbrew/brew ~/.linuxbrew
```
or if you do have `sudo`
```sh
sudo mkdir /home/linuxbrew
sudo chown $USER: /home/linuxbrew
git clone https://github.com/Linuxbrew/brew /home/linuxbrew/.linuxbrew
PATH=/home/linuxbrew/.linuxbrew/bin:$PATH
brew install hello
```

**Comment by sjackman** [comment]
I've merged PR https://github.com/Linuxbrew/install/pull/12 to resolve this issue.
