### ISSUE TITLE
No such file or directory - curl

### ISSUE THREAD

**Issue by speedcell4** [Linuxbrew/brew#388]
# Please always follow these steps:
- [x] Confirmed this is a problem with Homebrew/brew and not one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Homebrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
- [x] Confirmed this is a problem with Linuxbrew/brew and not specific formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new

To help us debug your issue please explain:
- What you were trying to do (and why)
install folly
- What happened (include command output)
```bash
[basil302-(~)] brew install folly
==> Installing dependencies for folly: m4, autoconf, automake, libtool, pkg-config, bzip2, openssl, curl, ncurses, cmake, double-conversion, gflags, glog, boost, libevent, xz, snappy, lz4
==> Installing folly dependency: m4
==> Downloading https://linuxbrew.bintray.com/bottles/m4-1.4.18.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring m4-1.4.18.x86_64_linux.bottle.tar.gz
🍺  /mnt/berry/home/yiran/.linuxbrew/Cellar/m4/1.4.18: 13 files, 1.1MB
==> Installing folly dependency: autoconf
==> Downloading https://linuxbrew.bintray.com/bottles/autoconf-2.69.x86_64_linux.bottle.4.
######################################################################## 100.0%
==> Pouring autoconf-2.69.x86_64_linux.bottle.4.tar.gz
==> Caveats

Emacs Lisp files have been installed to:
  /mnt/berry/home/yiran/.linuxbrew/share/emacs/site-lisp/autoconf
==> Summary
🍺  /mnt/berry/home/yiran/.linuxbrew/Cellar/autoconf/2.69: 70 files, 3.0MB
==> Installing folly dependency: automake
==> Downloading https://linuxbrew.bintray.com/bottles/automake-1.15.x86_64_linux.bottle.2.
######################################################################## 100.0%
==> Pouring automake-1.15.x86_64_linux.bottle.2.tar.gz
🍺  /mnt/berry/home/yiran/.linuxbrew/Cellar/automake/1.15: 130 files, 2.9MB
==> Installing folly dependency: libtool
==> Downloading https://linuxbrew.bintray.com/bottles/libtool-2.4.6_2.x86_64_linux.bottle.
######################################################################## 100.0%
==> Pouring libtool-2.4.6_2.x86_64_linux.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.

==> Summary
🍺  /mnt/berry/home/yiran/.linuxbrew/Cellar/libtool/2.4.6_2: 73 files, 3.7MB
==> Installing folly dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Error: No such file or directory - curl
```
and then I tried to install `curl` but I got the same result

```bash
[basil302-(~)] brew install curl
==> Installing dependencies for curl: openssl, pkg-config
==> Installing curl dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2k.tar.gz
Error: No such file or directory - curl
```

- What you expected to happen
no such error

- Step-by-step reproduction instructions (by running `brew` commands)
```bash
brew update
brew install folly
```

**Please note we may immediately close your issue without comment if you do not fill out the issue template and provide ALL the requested information.**

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it and alternatives considered.
Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by sjackman** [comment]
How strange that it was happily downloading before it got to `pkg-config` and then suddenly failed. Please report
```sh
which -a curl
curl --version
brew fetch pkg-config
brew install pkg-config
brew gist-logs pkg-config
```

**Comment by speedcell4** [comment]
What funny is that I found if I repeat that install command, it will successfully be done.

```shell
[basil302-(~)] brew install nvm
==> Downloading https://github.com/creationix/nvm/archive/v0.33.2.tar.gz
######################################################################## 100.0%
Error: No such file or directory - curl
[basil302-(~)] brew install nvm
==> Downloading https://github.com/creationix/nvm/archive/v0.33.2.tar.gz
Already downloaded: /home/yiran/.linuxbrew/cache/nvm-0.33.2.tar.gz
==> Caveats
Please note that upstream has asked us to make explicit managing
nvm via Homebrew is unsupported by them and you should check any
problems against the standard nvm install method prior to reporting.

You should create NVM's working directory if it doesn't exist:

  mkdir ~/.nvm

Add the following to ~/.zshrc or your desired shell
configuration file:

  export NVM_DIR="$HOME/.nvm"
  . "/mnt/berry/home/yiran/.linuxbrew/opt/nvm/nvm.sh"

You can set $NVM_DIR to any location, but leaving it unchanged from
/mnt/berry/home/yiran/.linuxbrew/opt/nvm will destroy any nvm-installed Node installations
upon upgrade/reinstall.

Type `nvm help` for further information.

Bash completion has been installed to:
  /mnt/berry/home/yiran/.linuxbrew/etc/bash_completion.d

==> Summary
🍺  /mnt/berry/home/yiran/.linuxbrew/Cellar/nvm/0.33.2: 7 files, 125KB, built in 1 second
```

I installed `curl` by this method, and here is the [report](https://gist.github.com/anonymous/e7f763a886876759cf6e364bddf6fed8) you asked.

**Comment by sjackman** [comment]
> What funny is that I found if I repeat that install command, it will successfully be done.

I really have no idea what's going on here. Sorry. ¯\_(ツ)_/¯

**Comment by carlorosati** [comment]
I encountered this issue or a very similar one. curl turned out to be looking for certificates installed by the openssl formula but they didn't exist. I ended up having to set an environment variable (I can't remember off the top of my head) to point to the system certificate locations.

**Comment by sjackman** [comment]
You can download the certificates for the `openssl` formula using…
```sh
brew postinstall openssl
```

**Comment by carlorosati** [comment]
That was failing for me. Whatever state brew was in was remedied by uninstalling OpenSSL and curl, then reinstalling with the environment variable set. I no longer have it set

**Comment by sjackman** [comment]
These instructions may help: https://github.com/Linuxbrew/brew/wiki/FAQ#why-does-curl-fail

**Comment by bw-yuhogg** [comment]
I wonder if https://github.com/Homebrew/brew/pull/2683 will be able to fix issues like this in the future.

**Comment by sjackman** [comment]
Providing an `http` mirror for both `openssl` and `curl` may actually resolve the issue. e.g.
http://artfiles.org/openssl.org/source/openssl-1.0.2l.tar.gz
http://curl.askapache.com/download/curl-7.54.0.tar.bz2
