### ISSUE TITLE
Don’t have permissions to use system GCC, so how do I install Linuxbrew GCC?

### ISSUE THREAD

**Issue by Linguista** [Linuxbrew/brew#390]
I just installed Linuxbrew to my user directory on a shared server, and now I need to install `gcc` in order to be able to do anything else. The problem is, I have no permissions to write or execute anything outside my home directory, including `/usr/bin/gcc`. So when I run `brew install gcc` I get the following:

`Error: Permission denied - /usr/bin/gcc`

And this is where I'm stuck. I can't use `sudo`, so it's impossible for me to change permissions or ownership of the system's `gcc` -- or anything else for that matter. I can't run the system `gcc`. And  I can't install Brew's `gcc` because... I don't already have access to `gcc`. A real Catch 22!

I'm sure I'm not the first person to run into this problem, but I haven't had any luck searching for a solution. How can I install `gcc` so that I can install `gcc`?

Here's some system information from `brew config`:

    HOMEBREW_VERSION: 1.1.13
    ORIGIN: https://github.com/Linuxbrew/brew
    HEAD: 1d16368a177807663e1b3146d71fcd69e2061e27
    Last commit: 9 days ago
    Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
    Core tap HEAD: 501c656e81770ff64f12131a20535795e9229e44
    Core tap last commit: 2 days ago
    HOMEBREW_PREFIX: /home/myuseracct/.linuxbrew
    HOMEBREW_REPOSITORY: /home/myuseracct/.linuxbrew/Homebrew
    HOMEBREW_CELLAR: /home/myuseracct/.linuxbrew/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
    CPU: 24-core 64-bit ivybridge
    Homebrew Ruby: 2.0.0-p648 => /home/myuseracct/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
    Clang: N/A
    Git: 2.8.0 => /usr/bin/git
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/local/bin/ruby => /usr/local/rubies/ruby-1.9.3/bin/ruby
    Java: N/A
    Kernel: Linux 3.10.0-427.36.1.lve1.4.45.el6h.x86_64 x86_64 GNU/Linux
    OS: N/A
    Host glibc: 2.12
    /usr/bin/gcc: N/A
    glibc: N/A
    gcc: N/A
    xorg: N/A

And here's my `brew doctor`  output:

    $ brew doctor
    Please note that these warnings are just used to help the Homebrew maintainers
    with debugging if you file an issue. If everything you use Homebrew for is
    working fine: please don't worry and just ignore them. Thanks!

    Warning: "config" scripts exist outside your system or Homebrew directories.
    `./configure` scripts often look for *-config scripts to determine if
    software packages are installed, and what additional flags to use when
    compiling and linking.

    Having additional scripts in your path can confuse software installed via
    Homebrew if the config script overrides a system or Homebrew provided
    script of the same name. We found the following "config" scripts:
      /usr/local/bin/php-config
      /usr/local/bin/passenger-config

    Warning: No developer tools installed.
    Install Clang or brew install gcc

Thanks in advance!

**Comment by sjackman** [comment]
Hi, Scott. Please report
```sh
which -a gcc
ls -l /usr/bin/gcc*
```

Do you have access to an C compiler on your system? To install in your home directory, you need access to a C compiler to bootstrap Linuxbrew.

Alternatively you can ask your systems group to create a Linuxbrew user with home directory `/home/linuxbrew`, in which case you do not need a C compiler to bootstrap Linuxbrew.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ https://github.com/Linuxbrew/brew/wiki/FAQ#why-install-in-homelinuxbrewlinuxbrew
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by Linguista** [comment]
No permissions to acces any compiler. It's a shared hosting box, so I'm not going to get them either. I also can't get another user account, unfortunately. 

I did install Linuxbrew locally, in `/home/me/.linuxbrew`, but from what you say, that's not sufficient. is there no static binary compiled with relative rather than absolute links to libraries and whatever else it needs (e.g.  `~/.linuxbrew/something.so` rather than `/home/linuxbrew/.linuxbrew/something.so`? (In other words, a relocatable, um, flask or bottle or whatever? (Sorry, I'd really need to `s///g` the brew terminology to follow it properly). Or some other way to get around this?

I understand a lot of software is simply not engineered with this goal in mind, and that there are more than a few developers that still use programming techniques that break on something as common as spaces in directory or file names. But if there's one piece of software that's both essential (no Linuxbrew without it) and that just *has* to be put together very rigorously, it's the `gcc`.

**Comment by sjackman** [comment]
Linuxbrew's precompiled binary bottles are compiled against `glibc` 2.19. Your host has `glibc` 2.12, so Linuxbrew is attempting to install `glibc`. `glibc` is not relocatable. `gcc` however is relocatable. If your host had `glibc` 2.19, you could install the `gcc` bottle and presto, you'd have a compiler. If you're feeling experimental, try…

```sh
brew install --force-bottle glibc
brew install gcc
```

**Comment by Linguista** [comment]
Well, I gave it a shot, but it didn't work unfortunately. In case anyone's interested, this is the error message:

```
Last 15 lines from /home/me/.cache/Homebrew/Logs/glibc/post_install.01.localedef:
2017-05-29 04:09:43 -0400

/home/me/.linuxbrew/Cellar/glibc/2.19/bin/localedef
-i
en_US
-f
UTF-8
en_US.UTF-8

Error: No such file or directory - getconf
```

Thanks for trying!

**Comment by sjackman** [comment]
Thanks for giving it a shot, Scott. I believe you can ignore that error, and proceed with `brew install gcc`
