### ISSUE TITLE
Remove Homebrew forum in README

### ISSUE THREAD

**Issue by FranklinYu** [Linuxbrew/brew#391]
I think https://discourse.brew.sh in ["Community" section of README](https://github.com/Linuxbrew/brew/tree/1.1.13#community) should be removed, because the administrator there [doesn't seem to like](https://discourse.brew.sh/t/dont-have-permissions-to-use-system-gcc-so-how-do-i-install-linux-brew-gcc/794/2) discussing Linuxbrew there.

**Comment by sjackman** [comment]
Done in 4d7d34d0ad389e2079d7abc21cbd544af1d76275
Thanks for the bug report, Franklin.
