### ISSUE TITLE
Warning: "config" scripts exist outside your system or Homebrew directories.

### ISSUE THREAD

**Issue by sulthonzh** [Linuxbrew/brew#399]
> Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry and just ignore them. Thanks!
> 
> Warning: "config" scripts exist outside your system or Homebrew directories.
> `./configure` scripts often look for *-config scripts to determine if
> software packages are installed, and what additional flags to use when
> compiling and linking.
> 
> Having additional scripts in your path can confuse software installed via
> Homebrew if the config script overrides a system or Homebrew provided
> script of the same name. We found the following "config" scripts:
>   /usr/local/bin/powerline-config
>   /home/habib/miniconda3/bin/python3-config
>   /home/habib/miniconda3/bin/python3.6m-config
>   /home/habib/miniconda3/bin/python3.6-config

hi after install brew i have this warning, how to solve it? thanks.

**Comment by sjackman** [comment]
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

You can, if you like, remove the offending files.
