### ISSUE TITLE
curl: (77) error setting certificate verify locations

### ISSUE THREAD

**Issue by nooitaf** [Linuxbrew/brew#401]
I got linuxbrew installed for quite some time now. 
But today i got these errors with `brew upgrade` (every package)
```
curl: (77) error setting certificate verify locations:
  CAfile: /home/nooitaf/.linuxbrew/etc/openssl/cert.pem
  CApath: /home/nooitaf/.linuxbrew/etc/openssl/certs
Error: Failed to download resource...
```
I have seen the insecure workaround..
https://github.com/Linuxbrew/brew/wiki/FAQ#why-does-curl-fail
.. but isn't there a better ... secure way? 

```
HOMEBREW_VERSION: 1.2.0
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b973a6c525ce9cd7a6d6f81344323df2c33b32e7
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 611c84a8acfcda8496585087840abf70296537e6
Core tap last commit: 17 hours ago
HOMEBREW_PREFIX: /home/nooitaf/.linuxbrew
HOMEBREW_REPOSITORY: /home/nooitaf/.linuxbrew
HOMEBREW_CELLAR: /home/nooitaf/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.3.4 => /usr/bin/ruby2.3
Clang: 3.8 build 
Git: 2.7.4 => /usr/bin/git
Perl: /home/nooitaf/.linuxbrew/bin/perl => /home/nooitaf/.linuxbrew/Cellar/perl/5.24.1/bin/perl
Python: /home/nooitaf/.linuxbrew/bin/python => /home/nooitaf/.linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: openjdk version "1.8.0_131"
Kernel: Linux 4.4.0-53-generic x86_64 GNU/Linux
OS: Linux Mint 18.1 Serena (serena)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: 20170115
```

**Comment by sjackman** [comment]
You only have to install openssl insecure. Once that's done, you can undo those instructions and install the rest securely. There's no better way of which I'm aware.

**Comment by nooitaf** [comment]
Awesome!
i got a bit confused about `.linuxbrew/etc/openssl/certs` staying empty after reinstall, but that seems to be the normal state. mybad ^^

So i ended up doing (overkill):
```
echo insecure >> ~/.curlrc
git config --global http.sslVerify false

brew uninstall --force openssl --ignore-dependencies
rm -rf .linuxbrew/etc/openssl/
rm -rf .cache/Homebrew/

brew install openssl

sed -i '/^insecure$/d' ~/.curlrc
git config --global http.sslVerify true

brew upgrade
```
Maybe add the part about openssl being the only thing to reinstall to the faq?

**Comment by sjackman** [comment]
Yes, that's a good idea. The FAQ is publicly editable. Would you like to make that change?

**Comment by nooitaf** [comment]
I'm honored, edited. :)

**Comment by sjackman** [comment]
Thanks, Ralf! I revised it to simplify the instructions. `brew reinstall openssl` should work in most situations.

**Comment by nooitaf** [comment]
Thanks, that's much nicer indeed. I wasn't sure and couldn't reproduce it, so i went with what i knew/did :D

**Comment by sjackman** [comment]
No worries. Thanks for your contribution to the documentation, Ralf!

**Comment by timotheecour** [comment]
> You only have to install openssl insecure. Once that's done, you can undo those instructions and install the rest securely. There's no better way of which I'm aware.

That wasn't needed a few weeks ago; do you have any idea what changed? This is not ideal (eg when installing multiple linuxbrew configs etc), so maybe we should keep this bug open until a better solution is found?

**Comment by sjackman** [comment]
As I understand it https://curl.haxx.se does not accept outdated SSL protocols and outdated certificates, so old `curl` programs from old distros will not be able to download curl source code from that domain using https. New curl program from new distros should have no trouble. I've since discovered that the better solution seems to be to add a `http` mirror (as opposed to `https`) to the `openssl` and `curl` formulae.

**Comment by sjackman** [comment]
The `insecure` workaround doesn't even work for `curl` any more.
```
❯❯❯ echo insecure >> ~/.curlrc
❯❯❯ brew fetch curl
==> Downloading https://curl.haxx.se/download/curl-7.54.0.tar.bz2
curl: (35) Peer reports incompatible or unsupported protocol version.
Error: Failed to download resource "curl"
Download failed: https://curl.haxx.se/download/curl-7.54.0.tar.bz2
```

**Comment by sjackman** [comment]
I've opened PR https://github.com/Linuxbrew/homebrew-core/pull/2875 to address this issue by adding an `http` mirror to `curl`.
