### ISSUE TITLE
Problems installing under Docker project

### ISSUE THREAD

**Issue by lfilho** [Linuxbrew/brew#403]
Hello. Thanks for your awesome work!

I'm trying to use install Linuxbrew in a docker image (making it my official package manager instead of apt-get), but it fails.

When executing `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"`, I get the following error:

```
-e:68:in `block in shell_s': undefined method `gsub' for nil:NilClass (NoMethodError)
	from -e:68:in `map'
	from -e:68:in `shell_s'
	from -e:73:in `ohai'
	from -e:96:in `sudo'
	from -e:315:in `<main>'
```

Seems like some `arg` is `nil` when it shouldn't? Something to do with tty?

Here's my `Dockerfile`:

```dockerfile
FROM ubuntu:16.04
LABEL maintainer="Luiz Filho <lfilho@gmail.com>"

# Let the container know that there is no tty
ENV DEBIAN_FRONTEND noninteractive
ENV TERM xterm-256color

# Bootstrapping packages needed for installation
RUN \
  apt-get update && \
  apt-get install -yqq locales software-properties-common

# Set locale to UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
RUN localedef -i en_US -f UTF-8 en_US.UTF-8 && \
  /usr/sbin/update-locale LANG=$LANG && \
  useradd -m -s /bin/bash nonrootuser && \
	echo 'nonrootuser ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

# Install dependencies
# `security` is needed for fontconfig and fc-cache
RUN \
  add-apt-repository "deb http://archive.ubuntu.com/ubuntu xenial security" && \
  apt-get update && \
  apt-get -yqq install curl file fontconfig g++ git make ruby2.3 ruby2.3-dev uuid-runtime && \
  apt-get clean && \
  ln -sf ruby2.3 /usr/bin/ruby && \
  ln -sf gem2.3 /usr/bin/gem && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install dotfiles (as regular, non-root user)
COPY . /home/nonrootuser/.yadr
RUN chown -R nonrootuser: /home/nonrootuser
USER nonrootuser
RUN cd /home/nonrootuser/.yadr && rake install

CMD [ "/bin/bash" ]
```

`rake install` runs a Rakefile which eventually executes the `ruby + curl` install line...

I tried removing the `ENV DEBIAN_FRONTEND noninteractive` but it didn't help.

Is this somehow known? Can I actually install Linuxbrew in a Docker container like this or should I use the alternative installation (git clone + manual PATH setting)?

Thank you

**Comment by lfilho** [comment]
Ok, I managed to get past that. I had to add the following line:

```Dockerfile
ENV USER nonrootuser
```
before running `rake install` and it worked. But now it seems it fails at cloning the repo:

```
From https://github.com/Linuxbrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.0.1    -> 1.1.0.1
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.10     -> 1.1.10
 * [new tag]         1.1.11     -> 1.1.11
 * [new tag]         1.1.12     -> 1.1.12
 * [new tag]         1.1.13     -> 1.1.13
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.2.1    -> 1.1.2.1
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
 * [new tag]         1.1.6      -> 1.1.6
 * [new tag]         1.1.7      -> 1.1.7
 * [new tag]         1.1.8      -> 1.1.8
 * [new tag]         1.1.9      -> 1.1.9
 * [new tag]         1.2.0      -> 1.2.0
Cloning into '/home/nonrootuser/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
```
and that's the last message there is. The next command in the Rakefile is a `brew update` which fails with:

```
rake aborted!
Errno::ENOENT: No such file or directory - brew
```

**Comment by sjackman** [comment]
This `Dockerfile` should be helpful to you: https://github.com/Linuxbrew/brew/blob/master/Dockerfile
You can if you want base your image on `linuxbrew/linuxbrew`, but it's using Ubuntu 14 rather than Ubuntu 16.

Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` so that you can use precompiled binary packages (known as bottles) for non-relocatable formula.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by lfilho** [comment]
Hey @sjackman thanks for the quick reply.

Thanks for pointing that Dockerfile out. I had seen it before and based my Dockerfile on it.

My question was just why wouldn't the install script work and whether manually git cloning the repo was my only option. I infere from your comment that that's the case, although I don't understand why.

Will change my code accordingly then.

Thanks again

**Comment by lfilho** [comment]
Just another quick question. Does is indeed have to be
>/home/**linuxbrew**/.linuxbrew

? Or could it be

>/home/**myuser**/.linuxbrew

? Thanks

**Comment by sjackman** [comment]
It indeed has to be `/home/linuxbrew/.linuxbrew` to make use of non-relocatable precompiled bottles.

**Comment by sjackman** [comment]
```
Errno::ENOENT: No such file or directory - brew
```

Add `/home/linuxbrew/.linuxbrew/bin` to your `PATH` before running `brew update`. See for example
https://github.com/Linuxbrew/brew/blob/master/Dockerfile#L19-L21

**Comment by sjackman** [comment]
> My question was just why wouldn't the install script work

Yes, the install script should work. Without an error message, it'll be tricky to troubleshoot. I'd suggest running the same commands interactively inside the container, to see if you can get an error message.
