### ISSUE TITLE
Add Michka to Linuxbrew maintainers

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#408]
+ [x] Add to Slack
+ [x] Add to the Slack `maintainers` channel
+ [x] Introduce to existing members
+ [x] Announce at [Linuxbrew Updates](https://github.com/Linuxbrew/brew/issues/1)
+ [x] Add to the [GitHub team](https://github.com/orgs/Linuxbrew/teams/core)
+ [x] Add to the [Bintray organization](https://bintray.com/linuxbrew/organization/edit)
+ [x] Add to [Google Analytics](https://analytics.google.com) if desired
+ [ ] Add name to *Who Are You?* in [README.md](https://github.com/Linuxbrew/brew/blob/master/README.md#who-are-you)

**Comment by sjackman** [comment]
See https://github.com/Linuxbrew/brew/issues/1#issuecomment-309870740

**Comment by bw-yuhogg** [comment]
Should we also add "Add to maintainer list on brew README" to the checklist?

**Comment by sjackman** [comment]
Yes, definitely. Good catch. I've updated the checklist.
@iMichka Would you please open a PR to add yourself to https://github.com/Linuxbrew/brew/blob/master/README.md#who-are-you ?

**Comment by sjackman** [comment]
A heads up that the CI for Linuxbrew/brew has been failing one test on macOS recently, so you can expect that failure. :100: points if you submit a PR to fix it. 😉

**Comment by iMichka** [comment]
I'll add myself on Thursday; not there today :)

**Comment by iMichka** [comment]
PR opened here: https://github.com/Linuxbrew/brew/pull/413
