### ISSUE TITLE
mlt: error: request for member ‘width’ in something not a structure or union

### ISSUE THREAD

**Issue by smac89** [Linuxbrew/brew#411]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?
https://gist.github.com/anonymous/e77c724065baa16a20876ff01968be8b

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to install `mlt`
- What happened (include command output)
The installation failed:

```
Last 15 lines from /home/casablanca/.cache/Homebrew/Logs/mlt/02.make:
                                                     ^
consumer_sdl_still.c:623:17: error: request for member ‘width’ in something not a structure or union
    *width = attr.width;
                 ^
consumer_sdl_still.c:624:18: error: request for member ‘height’ in something not a structure or union
    *height = attr.height;
                  ^
<builtin>: recipe for target 'consumer_sdl_still.o' failed
make[2]: *** [consumer_sdl_still.o] Error 1
make[2]: Leaving directory '/tmp/mlt-20170621-8507-p6y8o1/mlt-6.4.1/src/modules/sdl'
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/tmp/mlt-20170621-8507-p6y8o1/mlt-6.4.1/src/modules'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 1
```

- What you expected to happen
Finish installation without error

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install mlt`

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it, how it would be relevant to at least 90% of Linuxbrew users and alternatives considered.
Please note we may close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

I solved this issue and described the solution here:
https://github.com/mltframework/mlt/issues/239#issuecomment-310176554

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-core#3040
