### ISSUE TITLE
Rubocop configuration

### ISSUE THREAD

**Issue by palday** [Linuxbrew/brew#412]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and just `brew install`ing one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we may immediately close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
## What you were trying to do (and why)

Audit a changed formula for a [PR](Linuxbrew/homebrew-core#2938).

### openSUSE 13.2:

`brew audit --strict ncurses` installs `rubocop` successfully but then fails with `undefined method[]' for nil:NilClass` error.

### Linux Mint 18.1 (like Ubuntu 16,04):
`brew audit --strict ncurses` fails to install `rubocop` because it can't find `rake` in the system Ruby path. Manually installing the gems with `gem install --user rake` and `gem install --user rubocop` works and then `brew audit` completes successfully with no errors.

## What you expected to happen
Ruby gem dependencies for `brew` to be addressed automatically either at install time or the first time for a particular command, installing user-local copies if necessary. 

## Step-by-step reproduction instructions (by running `brew` commands)

see above.

# Configuration 

## OpenSuse
```
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 2e121544fb3671e2ae7ccfaff574ba313976b65b
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 17feec79173fe5a5cbaa21c49fd9d69917c4b4a0
Core tap last commit: 17 hours ago
HOMEBREW_PREFIX: /home/user/.linuxbrew
HOMEBREW_REPOSITORY: /home/user/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/user/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.1.3 => /usr/bin/ruby.ruby2.1
Clang: N/A
Git: 2.2.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /home/user/.linuxbrew/bin/python => /home/user/.linuxbrew/Cellar/python/2.7.13/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby.ruby2.1
Java: 1.8.0_112
Kernel: Linux 4.5.0-4.gece3ff2-default x86_64 GNU/Linux
OS: openSUSE 13.2 (Harlequin) (x86_64) (Harlequin)
Host glibc: 2.19
/usr/bin/gcc: 4.8.3
glibc: N/A
gcc: 5.3.0
xorg: N/A
```
## Linux Mint
```
​
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 2e121544fb3671e2ae7ccfaff574ba313976b65b
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 7cf3fbe770155c6ec927220a7db72f219634ccc3
Core tap last commit: 6 days ago
HOMEBREW_PREFIX: /home/user/.linuxbrew
HOMEBREW_REPOSITORY: /home/user/.linuxbrew
HOMEBREW_CELLAR: /home/user/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit 0x64e
Homebrew Ruby: 2.3.1 => /usr/bin/ruby2.3
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: openjdk version "1.8.0_131"
Kernel: Linux 4.8.0-30-generic x86_64 GNU/Linux
OS: Linux Mint 18.1 Serena (serena)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
```

**Comment by sjackman** [comment]
Adding `rake` and `rubocop` to `Library/Homebrew/test/Gemfile` may resolve this issue.

**Comment by palday** [comment]
`rubocop` is already in the gemfile. The source of the `undefined method '[]' for nil:NilClass` error seems to be this conditional (`Library/Homebrew/dev-cmd/audit.rb:1119`):

`formula.tap.to_s == "homebrew/core" && !formula.tap.remote[/linuxbrew/i] `

Commenting out the second half (`&& !formula.tap.remote[/linuxbrew/i]`) 'fixes' the issue (but of course adds in unnecessary errors from upstream about OS checks).

**Comment by sjackman** [comment]
Please report…
```sh
brew irb <<<'Formula["hello"].tap.remote'
brew irb <<<'Formula["hello"].tap.remote[/linuxbrew/i]'
git -C $(brew --repo homebrew/core) remote -v
```

**Comment by palday** [comment]
```bash
user@host:~$ brew irb <<<'Formula["hello"].tap.remote'                                 
/bin/stty: standard input: Inappropriate ioctl for device                                     
==> Interactive Homebrew Shell                 
Example commands available with: brew irb --examples                                          
Switch to inspect mode.                        
Formula["hello"].tap.remote                    
"https://github.com/Linuxbrew/homebrew-core"   

user@host:~$ brew irb <<<'Formula["hello"].tap.remote[/linuxbrew/i]'                   
/bin/stty: standard input: Inappropriate ioctl for device                                     
==> Interactive Homebrew Shell                 
Example commands available with: brew irb --examples                                          
Switch to inspect mode.                        
Formula["hello"].tap.remote[/linuxbrew/i]      
"Linuxbrew"            

user@host:~$ git -C $(brew --repo homebrew/core) remote -v                             
origin  https://github.com/Linuxbrew/homebrew-core (fetch)                                    
origin  https://github.com/Linuxbrew/homebrew-core (push)                                     
palday  git@github.com:palday/homebrew-core (fetch)                                           
palday  git@github.com:palday/homebrew-core (push)
```

**Comment by luceat-lux-vestra** [comment]
I added a comment on https://github.com/Linuxbrew/homebrew-core/issues/3106

I don't know https://github.com/Linuxbrew/homebrew-core/issues/3106 related with #412, but I hope this may help to solve some issue.

**Comment by sjackman** [comment]
@palday That's odd. I'm not sure why `Formula["ncurses"].tap.remote` is `nil` during `brew audit` but seems fine with the above `brew irb` test.

**Comment by palday** [comment]
There seems to be a more general issue on openSUSE 13.2 with the environment not being properly set up during install. On several source installs, the install fails on its own, but I'm able to step through the install with `-svd` by linking "missing" brewed libraries to `.linuxbrew/lib/` (and the same for `packagecfg`) and setting `LD_LIBRARY_PATH`  in the `brew` debug shell before continuing with `make` and `make install`. I've been unfortunately been too focused on just getting things running on this employer-provided machine without root access to keep a comprehensive list, but I remember it particularly vividly for Xorg and all of its dependencies.

Is there some debug environment / command where I could better trace where the setup process is failing?  Beyond the `brew irb` where everything seemed okay?

**Comment by sjackman** [comment]
Sorry to hear about the difficulty that you had installing Linuxbrew. If you're comfortable with Ruby and debugging using print statements, I'd suggest adding print statements to determine why `formula.tap.remote` is `nil`. Otherwise, if you can give precise instructions to replicate the issue in a publicly-avaialble Docker image, we can troubleshoot the issue ourselves.

**Comment by palday** [comment]
I would like to contribute more -- Linuxbrew seems like the perfect thing for thing for my setup at work where getting central IT to install additional software is difficult but compiling and installing user-local software is semi-encouraged. 

When these issues first started, I was able to replicate them on a clean VM of openSUSE 13.2 at home, which goes against weird configuration issues on the work machine. As far as I can tell, it's something related to the linker `ldd` and without root, I can't edit the settings for the system linker. Brewing `glibc` and `coreutils` helped with some things but not as much as I'd hoped.

Today, I tried doing things on the [openSUSE 13.2 (harlequin) docker image](https://hub.docker.com/_/opensuse/) running on [Play With Docker](http://play-with-docker.com) and that seemed to mostly work, failing at the installation of `gawk`.
```shell
$  docker pull opensuse:harlequin
$  docker container run -it opensuse:harlequin /bin/bash
root@docker $  useradd -p test -d /home/user -m user
root@docker $  zypper install -t pattern devel_basis # fails for some packages related to things like btrfs, but largely irrelevant for brew
root@docker $  zypper install curl fit git irb python-setuptools ruby
root@docker $  zypper install gcc-locale glibc-locale # the default docker image is missing some locale info needed for brew
root@docker $  su user
user@docker $  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
user@docker $  export PATH="/home/user/.linuxbrew/bin:$PATH"
user@docker $  brew install hello
user@docker $  brew audit --strict ncurses
user@docker $  brew install gcc
user@docker $  brew install byobu
user@docker $  brew install ruby
user@docker $  brew install python 
user@docker $  python # this was problematic on "real" system -- issues related to linking to system libs led to Unicode errors, installing glibc and using brewed ldd fixed those errors, but created issues with not finding libpython. works in docker image, but there is a readline config issue with /etc/inputrc 
user@docker $  brew tap linuxbrew/xorg
user@docker $  brew install xorg # fails at gawk
user@docker $  brew install gawk -svd # fails
```

My intuition is that the docker failure may not be related to the VM/real-machine failure.

**Comment by sjackman** [comment]
I created Linuxbrew for the same reason, local installation of software in my home directory on my institution's workstation. Can you please report `brew gist-logs gawk`?

**Comment by palday** [comment]
[Log for gawk](https://gist.github.com/anonymous/62c011d6480c213b55b56b2fdb9fc0ae)

**Comment by sjackman** [comment]
`gawk` is failing during `make check`
```
3 TESTS FAILED
  | Makefile:4128: recipe for target 'pass-fail' failed
  | make[2]: *** [pass-fail] Error 1
```
https://gist.github.com/anonymous/62c011d6480c213b55b56b2fdb9fc0ae#file-03-make-L506

Though I'm not entirely clear which tests failed. If you can replicate this gawk issue outside of Linuxbrew with `./configure && make && make check` then I'd suggest you report this bug upstream to the `gawk` developers. In the mean time, two possible work arounds are:
```
brew edit gawk
```
and delete or comment out the line `make check`
or
```
brew install --force-bottle gawk
```
which may or may not work, because the bottle is tagged as being non-relocatable, so no promises, but it's worth a shot.

**Comment by sjackman** [comment]
```
Host glibc: 2.19
/usr/bin/gcc: 4.8.3
```
https://gist.github.com/anonymous/62c011d6480c213b55b56b2fdb9fc0ae#file-00-config-out-L22-L23

That's the same `glibc` and `gcc` versions on Ubuntu 14 used by Linuxbrew to build precompiled binary bottles, so that should make your life easier.
