### ISSUE TITLE
unable to install php56

### ISSUE THREAD

**Issue by glensc** [Linuxbrew/brew#419]
i first reported this to https://github.com/Homebrew/homebrew-php/pull/4304

but i'm confused where it really should be fixed, as the root cause seems to be that there's no url defined for linux in mod_suexec which is dependency of php recipe.

do you plan to fork homebrew-php and homebrew-apache, or should try to submit to homebrew-apache something?

https://github.com/Homebrew/homebrew-apache/blob/d24da78c4ec53e0ffed0b1b5f89602099ccc4007/mod_suexec.rb#L4

**Comment by glensc** [comment]
aside, i was able to install php56 after installing `systemtap-sdt-devel-3.1-1.x86_64`

and running with:
```
➔ brew install --without-httpd24 --without-httpd22 --without-ldap php56
```

**Comment by sjackman** [comment]
The `Homebrew/apache` and `Homebrew/php` taps are not supported by the Linuxbrew maintainers.
They're currently not supported on Linuxbrew by anyone.

**Comment by glensc** [comment]
err. blah, what should i do with your answer exactly? asked opinion, and no answer:

> do you plan to fork homebrew-php and homebrew-apache, or i should try to submit to homebrew-apache something?

what would be the plan or optimal way to solve the problem? supported or not,  but you basically told me to stop using linuxbrew as that was the core interest for me to try linuxbrew.

**Comment by sjackman** [comment]
> do you plan to fork homebrew-php and homebrew-apache

I do not plan to fork homebrew-php and homebrew-apache myself. You could if you had the inclination start your own personal fork of these taps.

> should try to submit to homebrew-apache something?

@javian Would you consider accepting a PR to support `mod_suexec` on Linuxbrew?
