### ISSUE TITLE
Formula-Cookbook.md link broken

### ISSUE THREAD

**Issue by mercer** [Linuxbrew/brew#432]
http://linuxbrew.sh/ references http://linuxbrew.sh/docs/Formula-Cookbook.md#homebrew-terminology. However, it gives a 404 for me.

**Comment by sjackman** [comment]
The correct URL is https://github.com/Linuxbrew/brew/blob/master/docs/Formula-Cookbook.md
I don't it's published to a web site like linuxbrew.sh, though it should be.
You can also read http://docs.brew.sh/Formula-Cookbook.html

**Comment by yurikoles** [comment]
@mercer wrong repo. The site repo is [here](/Linuxbrew/linuxbrew.github.io/issues).

**Comment by sjackman** [comment]
I've corrected this dead link with commit https://github.com/Linuxbrew/linuxbrew.github.io/commit/53e9c40a0a03b35a398548730f05b5c95f5c8260

**Comment by sjackman** [comment]
Thanks for the bug report, Emilian!
