### ISSUE TITLE
linkage should consider recursive dependencies of the :x11 requirement

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#438]
Many X11-using formulae have their libraries flagged by `brew linkage` incorrectly, because they're not direct dependencies but rather dragged in by the :x11 requirement.

So, we basically need to implement #337, but for `linkage` rather than installing.

**Comment by bw-yuhogg** [comment]
Haven't gotten to this yet bot.

**Comment by sjackman** [comment]
@rwhogg Can you report the `brew linkage` output that you're seeing vs what you're expecting?

**Comment by bw-yuhogg** [comment]
`brew linkage gtk` is a representative example:

```
brew linkage gtk
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libatk-1.0.so.0 (atk)
  /home/linuxbrew/.linuxbrew/lib/libcairo.so.2 (cairo)
  /home/linuxbrew/.linuxbrew/lib/libfontconfig.so.1 (fontconfig)
  /home/linuxbrew/.linuxbrew/lib/libgdk_pixbuf-2.0.so.0 (gdk-pixbuf)
  /home/linuxbrew/.linuxbrew/lib/libgio-2.0.so.0 (glib)
  /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0 (glib)
  /home/linuxbrew/.linuxbrew/lib/libgmodule-2.0.so.0 (glib)
  /home/linuxbrew/.linuxbrew/lib/libgobject-2.0.so.0 (glib)
  /home/linuxbrew/.linuxbrew/Cellar/gtk+/2.24.31_1/lib/libgailutil.so.18 (gtk+)
  /home/linuxbrew/.linuxbrew/Cellar/gtk+/2.24.31_1/lib/libgdk-x11-2.0.so.0 (gtk+)
  /home/linuxbrew/.linuxbrew/Cellar/gtk+/2.24.31_1/lib/libgtk-x11-2.0.so.0 (gtk+)
  /home/linuxbrew/.linuxbrew/lib/libgdk-x11-2.0.so.0 (gtk+)
  /home/linuxbrew/.linuxbrew/lib/libgtk-x11-2.0.so.0 (gtk+)
  /home/linuxbrew/.linuxbrew/lib/libX11.so.6 (linuxbrew/xorg/libx11)
  /home/linuxbrew/.linuxbrew/lib/libXcomposite.so.1 (linuxbrew/xorg/libxcomposite)
  /home/linuxbrew/.linuxbrew/lib/libXcursor.so.1 (linuxbrew/xorg/libxcursor)
  /home/linuxbrew/.linuxbrew/lib/libXdamage.so.1 (linuxbrew/xorg/libxdamage)
  /home/linuxbrew/.linuxbrew/lib/libXext.so.6 (linuxbrew/xorg/libxext)
  /home/linuxbrew/.linuxbrew/lib/libXfixes.so.3 (linuxbrew/xorg/libxfixes)
  /home/linuxbrew/.linuxbrew/lib/libXinerama.so.1 (linuxbrew/xorg/libxinerama)
  /home/linuxbrew/.linuxbrew/lib/libXrandr.so.2 (linuxbrew/xorg/libxrandr)
  /home/linuxbrew/.linuxbrew/lib/libXrender.so.1 (linuxbrew/xorg/libxrender)
  /home/linuxbrew/.linuxbrew/lib/libpango-1.0.so.0 (pango)
  /home/linuxbrew/.linuxbrew/lib/libpangocairo-1.0.so.0 (pango)
  /home/linuxbrew/.linuxbrew/lib/libpangoft2-1.0.so.0 (pango)
Possible undeclared dependencies:
  fontconfig
  glib
  linuxbrew/xorg/libx11
  linuxbrew/xorg/libxcomposite
  linuxbrew/xorg/libxcursor
  linuxbrew/xorg/libxdamage
  linuxbrew/xorg/libxext
  linuxbrew/xorg/libxfixes
  linuxbrew/xorg/libxinerama
  linuxbrew/xorg/libxrandr
  linuxbrew/xorg/libxrender
```

None of those linuxbrew/xorg libraries should be on the list of "Possible undeclared dependencies" AIUI, as they should be covered by the XorgRequirement and they're all dependencies of `linuxbrew/xorg/xorg`.

Note that `gtk` itself doesn't depend on `:x11`, but rather that comes in through `cairo`, so that's possibly relevant too.

**Comment by sjackman** [comment]
Ah. That behaviour is by design. Whether it's good design or not is another matter. `Possible undeclared dependencies` doesn't result in an error status. The usual reason for these messages are libraries satisfied by recursive dependencies. If we choose to address this issue, I'd prefer to split `Possible undeclared dependencies` into `Recursive dependencies` and `Possible undeclared dependencies`. That patch should go upstream to `Homebrew/brew`. It's also reasonable to close this issue if we're happy accepting the current design. Your thoughts?

**Comment by bw-yuhogg** [comment]
If that's by design, I see no reason to change it.

I'd personally prefer not creating upstream work for ourselves when we have enough of it already to port the existing Linuxbrew changes.

So let's close this.
