### ISSUE TITLE
brew info displays error if linuxbrew/xorg is not tapped

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#440]
# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
Run `brew info r` (on a clean Debian or Ubuntu Docker image from linuxbrew/docker)

- What happened (include command output)

```
Error: No available formula with the name "linuxbrew/xorg/xorg"
```
- What you expected to happen
For the :x11 requirement to be displayed in the `brew info` output

- Step-by-step reproduction instructions (by running `brew` commands)
`brew info r` (or some other formula that has a :x11 requirement)

**Comment by sjackman** [comment]
It's possible to resolve this issue by tapping `linuxbrew/xorg` instead of display the message `Error: No available formula with the name "linuxbrew/xorg/xorg"`. That behaviour would be different though than upstream Homebrew/brew. It could possibly be a warning instead of an error. Linuxbrew installer could tap `linuxbrew/xorg` by default. Any other ideas?

**Comment by bw-yuhogg** [comment]
I personally think tapping it in the installer is a good idea.

**Comment by sjackman** [comment]
I'm happy with that solution if you'd like to submit a PR.

**Comment by sjackman** [comment]
This issue is resolved by https://github.com/Linuxbrew/install/pull/15.
