### ISSUE TITLE
Update bottling image to Ubuntu 16.04 LTS (Xenial Xerus)

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#451]
The currently bottling image is Ubuntu 14.04 LTS (Trusty Tahr). We plan to upgrade to the bottling image to Ubuntu 16.04 LTS (Xenial Xerus).

| Software | Trusty | Xenial |
|---|---|---|
| Linux kernel | 3.13.0 | 4.4.0 |
| Minimum kernel version | 2.6.16 | 2.6.32 |
| glibc | 2.19 | 2.23|
| gcc | 4.8.2 | 5.3.1 |
| C++ ABI | GCC 4 | GCC 5+ |

+ [x] glibc: Add `KernelVersionRequirement` ≥ 2.6.16 https://github.com/Linuxbrew/homebrew-core/pull/3728
+ [x] Upgrade `linux-headers` https://www.kernel.org
    + [x] 3.18.63 https://github.com/Linuxbrew/homebrew-core/pull/3745
    + [x] 4.1.43 https://github.com/Linuxbrew/homebrew-core/pull/3746
    + [x] 4.4.80 https://github.com/Linuxbrew/homebrew-core/pull/3759
+ [x] Update to CircleCI 2.0
+ [x] Bump `glibc` revision to 2.19_1 https://github.com/Linuxbrew/homebrew-core/pull/3762
+ [x] Identify all formulae that are linked against `libstdc++` https://github.com/Linuxbrew/brew/issues/467
+ [x] Tag and release `brew` 1.2.7
+ [x] Upgrade `glibc` to 2.23 https://github.com/Linuxbrew/homebrew-core/pull/3976
    + [x] Add `KernelVersionRequirement` ≥ 2.6.32
    + [x] Test upgrade from brewed glibc 2.19 to 2.23 on Ubuntu 12 Precise
    + [x] Test upgrade from host glibc to brewed 2.23 on Ubuntu 14 Trusty
+ [x] Change CircleCI and Docker image to Ubuntu 16 Xenial https://github.com/Linuxbrew/brew/pull/471
+ [x] Tag and release `brew` 1.3.0
+ [x] Add bottle comment `# glibc 2.19` https://github.com/Linuxbrew/homebrew-core/pull/4031
+ [x] Build bottles with `build-bottle-pr` for formulae that require C++ #467

**Comment by maxim-belkin** [comment]
how can we possibly identify all formulae that are linked against `libstdc++`?

**Comment by sjackman** [comment]
For each current `x86_64_linux` bottle…
```
❯❯❯ brew info --json=v1 boost | jq -r '.[0].bottle.stable.files.sierra.url'
https://homebrew.bintray.com/bottles/boost-1.65.0.sierra.bottle.tar.gz
❯❯❯ curl -sL 'https://homebrew.bintray.com/bottles/boost-1.65.0.el_capitan.bottle.tar.gz' | gtar -xO --occurrence=1 boost/1.65.0/INSTALL_RECEIPT.json | jq '.stdlib'
"libcxx"
```

**Comment by iMichka** [comment]
```
#!/bin/bash

FILES=/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/*.rb

for fullfile in $FILES
do
  sha="$(grep "=> :x86_64_linux" $fullfile)"
  if [ -n "$sha" ]; then
    filename=$(basename "$fullfile")
    filename="${filename%.*}"
    url="$(brew info --json=v1 $filename | jq -r '.[0].bottle.stable.files.x86_64_linux.url')"
    version="$(brew info --json=v1 $filename | jq -r '.[0].versions.stable')"
    revision="$(brew info --json=v1 $filename | jq -r '.[0].revision')"
    (( revision > 0 )) && dir="${version}_$revision" || dir="${version}"
    stdlib="$(curl -sL $url | tar zxO --occurrence=1 $filename/$dir/INSTALL_RECEIPT.json | jq -r .stdlib)"
    if [ "$stdlib" == "libstdcxx" ]; then
        echo $filename
    fi
  fi
done
```

**Comment by maxim-belkin** [comment]
Or this:
```bash
cd $(brew --repo linuxbrew/core)/Formula
for file in $(grep -l "=> :x86_64_linux" *.rb); do
	formula=${file%.rb};
	printf "\r%-30s" $formula
	json=$(brew info --json=v1 $formula)

	bottled=$(echo $json | jq '.[0].versions.bottle')
	[[ $bottled == "false" ]] && continue;

	url=$(echo $json | jq -r '.[0].bottle.stable.files.x86_64_linux.url');
	version=$(echo $json | jq -r '.[0].versions.stable');
	revision=$(echo $json | jq -r '.[0].revision')
	(( revision > 0 )) && dir="${version}_$revision" || dir=${version}
	output_json=$(curl -sL $url | tar xzO --occurrence=1  $formula/$dir/INSTALL_RECEIPT.json)
	[[ $? != "0" ]] && output_json=$(curl -sL $url | tar xO --occurrence=1 $formula/$dir/INSTALL_RECEIPT.json)
	output=$( echo $output_json | jq -r .stdlib);
	[[ $output != "libstdcxx" ]] && continue;
	echo "(libstdcxx)"
done
```

**Comment by iMichka** [comment]
Mmh forgot the revision in my version.

**Comment by sjackman** [comment]
```
# Remove "" from "stdlib"
```
Use `jq -r` to remove the quotes.

**Comment by iMichka** [comment]
Thanks, didn't check that parameter before. I updated my script, it is currently running on my computer, let's see what we will get

**Comment by bw-yuhogg** [comment]
One thing I forgot to ask until now: should we actually leave Travis at 14.04? If both Circle and Travis are on 16.04, then Travis is arguably redundant.

**Comment by iMichka** [comment]
Here is the raw list for libstdcxx: https://gist.github.com/iMichka/e65f9227cc3a06f1a6377fe8be34ef4b

**Comment by iMichka** [comment]
@rwhogg I would also move Travis to Xenial, it will be too much work to support both. And build time is limited to 1 hours so I feel that Travis is not so useful.

**Comment by sjackman** [comment]
[cxx.deps.unisolated.pdf](https://github.com/Linuxbrew/brew/files/1250272/cxx.deps.unisolated.pdf)

**Comment by sjackman** [comment]
![cxx deps unisolated](https://user-images.githubusercontent.com/291551/29689217-4697f15a-88d7-11e7-89c7-1bb46f4a7b08.png)

```
atkmm		flann		gpgme		libqalculate	notmuch
gtkmm		fltk		vte3		libtiff		pcre
boost		octave		gperftools	mikutter	plplot
librevenge	gdal		leveldb		opencv		protobuf
vtk		mapserver	graphicsmagick	opencv@2	snappy
libmwaw		geos		groonga		podofo		suite-sparse
libwpd		gflags		hdf5		poppler		xapian
libwps		glog		netcdf		wxmac
cairomm		grpc		imagemagick	vips
pangomm		glibmm		imagemagick@6	llvm
erlang@19	gnutls		jbig2enc	mobile-shell
```
