### ISSUE TITLE
My Linuxbrew is ignoring existing bottles and attempting source builds

### ISSUE THREAD

**Issue by telamonian** [Linuxbrew/brew#452]
# Please always follow these steps:
- [X] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config` and `brew doctor` and included their output with your issue?

I'm testing out some changes I made to the `pymol` formula on a Linux system. Starting from a fresh install of Linuxbrew, I ran `brew install pymol --verbose --debug --dependency-only`. Linuxbrew then tried to build all of the many `pymol` dependencies from source, ignoring the bottles that exist for most of them. The only way to get the bottles was to install each dependency directly and add the `--force-bottle` option to the install command.

I had already run similar tests on a couple of virtual machines without running into this problem. `brew doctor` reports no problems, and there's nothing obviously wrong with my environment variables. What could be causing this strange behavior?

Here's the dump of `brew config`
```
HOMEBREW_VERSION: 1.2.6-45-gf99078a
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: f99078a568e0b400fe886407bc3b474de6337c3c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 3f9f8d67f81f8de618c6b36921cb87f83241f852
Core tap last commit: 51 minutes ago
HOMEBREW_PREFIX: /home/cklein13/.linuxbrew
HOMEBREW_REPOSITORY: /home/cklein13/.linuxbrew
HOMEBREW_CELLAR: /home/cklein13/.linuxbrew/Cellar
HOMEBREW_BlOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648 => /usr/bin/ruby2.0
Clang: 4.0 build
Git: 2.7.4 => /usr/bin/git
Perl: /home/cklein13/.linuxbrew/bin/perl => /home/cklein13/.linuxbrew/Cellar/perl/5.26.0/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby2.0
Java: N/A
Kernel: Linux 4.4.0-89-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.1 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: 5.3.0
xorg: 20170115
```

**Comment by sjackman** [comment]
The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by telamonian** [comment]
Ah, I see. I thought it was just supposed to be ${HOME}/.linuxbrew
