### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by augmen** [Linuxbrew/brew#455]
I try to run the command as root user  `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"`

Got this error - Don't run this as root
![screen shot 2017-08-10 at 09 20 22](https://user-images.githubusercontent.com/11497036/29153804-4e8acdcc-7dad-11e7-8ce5-20c6e5f1274d.png)

then i created a sudo user and run again the command , got this error 

![screen shot 2017-08-10 at 09 19 49](https://user-images.githubusercontent.com/11497036/29153821-6f7e8398-7dad-11e7-9ca9-6592b8727cc5.png)

Please guide

**Comment by sjackman** [comment]
Try naming the user `linuxbrew` rather than swap. Install `ruby` using your host's package manager. For example, on Debian or Ubuntu
```sh
sudo apt-get install ruby
```
There are alternative installation instructions if you are not able to install `ruby`.
