### ISSUE TITLE
xcb-proto patch does not download: connection refused on port 80

### ISSUE THREAD

**Issue by LohitakshTrehan** [Linuxbrew/brew#458]
# Please always follow these steps:
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

**Please note we will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information.**

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

# Or propose a feature:
Please replace this section with a detailed description of your proposed feature, the motivation for it, how it would be relevant to at least 90% of Linuxbrew users and alternatives considered.
Please note we will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.\

ISSUE:****************************************************************************
==> Installing wine dependency: linuxbrew/xorg/xcb-proto
==> Downloading https://xcb.freedesktop.org/dist/xcb-proto-1.12.tar.bz2
Already downloaded: /home/lohitaksh/.cache/Homebrew/xcb-proto-1.12.tar.bz2
==> Downloading http://www.linuxfromscratch.org/patches/blfs/svn/xcb-proto-1.12-python3-1.patch

curl: (7) Failed to connect to www.linuxfromscratch.org port 80: Connection refused
Error: Failed to download resource "xcb-proto--patch"
Download failed: http://www.linuxfromscratch.org/patches/blfs/svn/xcb-proto-1.12-python3-1.patch

**Comment by bw-yuhogg** [comment]
The `xcb-proto` patch downloads fine for me. Is it just through Linuxbrew that you're unable to download it, or does it fail if you download it manually with `curl` or `wget` too?

**Comment by LohitakshTrehan** [comment]
By LinuxBrew, I also discovered that this issue was also reported by someone on xcb-proto github page.

**Comment by bw-yuhogg** [comment]
@LohitakshTrehan can you link to that bug report? I can't seem to find it and wasn't aware `xcb-proto` had a GitHub repo.
