### ISSUE TITLE
Proxy and Connection timed out errors

### ISSUE THREAD

**Issue by Neraste** [Linuxbrew/brew#49]
Hi Linuxbrew people. Thanks for this amazing tool! This is not a bug report, but more a note for people running Linuxbrew behind a proxy, who are stuck with a `Connection timed out - connect(2)` error.

The proxy environment variable (`all_proxy`, `http_proxy`...), which should be [lower case](https://wiki.archlinux.org/index.php/proxy_settings), has to be [upper case](http://squarism.com/2010/12/14/homebrew-behind-a-proxy/) (`ALL_PROXY`, `HTTP_PROXY`...) for some components of Linuxbrew (at least, Ruby or Curl).

Not a major discovery, but it may help some.

**Comment by sjackman** [comment]
Thanks for the comment, Neraste. It's nice to have workarounds documented and Googleable.

**Comment by Neraste** [comment]
Note also that for some tools such as `cabal` (a Haskell package manager), the proxy has to be set with `http_proxy`, not only with `all_proxy`, as said [here](https://mail.haskell.org/pipermail/haskell-cafe/2011-January/088649.html).
