### ISSUE TITLE
I am unable to run command line tools that I install using Linuxbrew.

### ISSUE THREAD

**Issue by ghost** [Linuxbrew/brew#493]
I am trying to run Bosh Bootloader (https://github.com/cloudfoundry/bosh-bootloader)

Here is the gist output for additional information:
https://gist.github.com/anonymous/fda4134ea097a9618d2ef11ba415102f

Error I get is: -`bash: /home/ubuntu/.linuxbrew/bin/bbl: Permission denied`

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula.

**Comment by sjackman** [comment]
```
bash: /home/ubuntu/.linuxbrew/bin/bbl: Permission denied
```
Please report the output of
```sh
ls -l /home/ubuntu/.linuxbrew/bin/bbl
file /home/ubuntu/.linuxbrew/bin/bbl
/home/ubuntu/.linuxbrew/bin/bbl --version
```
