### ISSUE TITLE
ARM: Installs Ruby for x86_64_linux [Raspberry Pi]

### ISSUE THREAD

**Issue by DblD** [Linuxbrew/brew#498]
To help us debug your issue please explain:
- What you were trying to do (and why)
Install linuxbrew on RiPy
- What happened (include command output)
```
dbld@ome:/home/pi $ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
==> Installing Ruby to /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 6393k  100 6393k    0     0   628k      0  0:00:10  0:00:10 --:--:--  840k
==> Installing successful
==> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
sh: 21: eval: ruby: Exec format error
```
- What you expected to happen
suceeeds installing linuxbrew
- Step-by-step reproduction instructions (by running `brew` commands)
did not suceed installlation.

**Comment by sjackman** [comment]
Do you have Ruby installed on your Raspberry Pi? Please report `which -a ruby`
It's unfortunately trying to install Ruby for x86_64 on your Raspberry Pi, which won't work. Here's the bug:
https://github.com/Linuxbrew/install/blob/master/install-ruby#L15

Try deleting your installation `rm -rf ~/.linuxbrew` and reinstalling Linuxbrew with this command:
```sh
sudo apt-get install ruby
ruby -e "`curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install`"
```
Note you'll need Ruby installed.

**Comment by sjackman** [comment]
A PR to fix this issue would be most welcome if you're interested in tackling it! I'm happy to answer any questions that you may have to help you get a fix working. It's Hacktoberfest! https://hacktoberfest.digitalocean.com

**Comment by deluks** [comment]
Ran into what appears to be the same issue with an previously installed linuxbrew on a NAS with 32bit ARM.
```
$ brew help
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.x86_64_linux.bottle.tar.gz
Already downloaded: /home/luk/.cache/Homebrew/portable-ruby-2.3.3.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.3.3.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor ruby.
Error: Failed to install vendor Ruby.
```
It worked fine up until recently with the Ruby version installed on the system.
```
 $ which -a ruby
/usr/bin/ruby
$ ruby --version
ruby 2.1.5p273 (2014-11-13) [arm-linux-gnueabi]
```
As far as I understand, linuxbrew 1.3.4 introduced an [Upgrade of the vendored Ruby to 2.3.3](https://github.com/Homebrew/brew/pull/3185/commits) but only provides a x86_64 but no ARM version for it.

Is Ruby 2.3.3 strictly necessary or can I somehow force the required Ruby version down to 2.1?

**Comment by iMichka** [comment]
> Is Ruby 2.3.3 strictly necessary or can I somehow force the required Ruby version down to 2.1?

The mac version of homebrew updated to 2.3.3, so we are using the same version. This means that the homebrew devs will write code that may not work with older ruby versions. Supporting ruby 2.1 is not something we plan to do. It may work, with more or less efforts, but you will not get support from us if you hit any problems.

The idea would be to build an ARM version of our portable 2.3.3 ruby version. I have a raspberry Pi 3 lying around, which may help. But I have not much time at the moment to work on this.

**Comment by sjackman** [comment]
There's instructions here on how to build a `portable-ruby` bottle for ARM. I haven't tried them myself.
https://github.com/homebrew/homebrew-portable#linux-32-bit-arm

In the mean time, try editing `$(brew --repo)/Library/Homebrew/utils/ruby.sh` and changing `minimum_ruby_version="2.3.3"` to `minimum_ruby_version="2.1.0"`. No promises that it'll work, but it may.

**Comment by iMichka** [comment]
Can this be built on a x86 hardware, using the docker container? If yes, then it is worth trying it out, should be quick.

**Comment by sjackman** [comment]
Yep, it sure can. I believe it uses QEMU to emulate the ARM hardware emulator.

**Comment by harper357** [comment]
I was just trying to set up a Pi2 and found just changing `minimum_ruby_version` didn't work, but that installing Ruby 2.4  (using https://gist.github.com/blacktm/8302741 ) does seem to get around this problem.

**Comment by sjackman** [comment]
Thanks for the workaround, @harper357.

**Comment by ahundt** [comment]
I've been able to reproduce this issue on the latest raspberry pi 3B+ version as of today.

I guess the ruby version is too old:
ruby 2.3.3p222 (2016-11-21) [arm-linux-gnueabihf]

here is [my attempt at a workaround script](https://github.com/ahundt/robotics_setup/blob/master/linuxbrew.sh):
```
# check if it is a raspberry pi, because we'll need a special ruby first
if [ -x "$(command -v python)" ] ; then
    R_PI=`python -c "import platform; print 'raspberrypi' in platform.uname()"`

    if [ "$R_PI" = "True" ] ; then
        # run ruby upgrade script from https://gist.github.com/blacktm/8302741
        yes | bash <(curl -s https://gist.githubusercontent.com/blacktm/8302741/raw/install_ruby_rpi.sh)
    fi
fi
# install linuxbrew http://linuxbrew.sh
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
```

This is totally insecure, so consider checking that the github ruby installer hasn't been messed with first... :-)

**Comment by ahundt** [comment]
@harper357 I was able to install the updated ruby:
```
ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [armv7l-linux-eabihf]
```
But it still tries to do the broken bottle:
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
==> Downloading and installing Linuxbrew...
HEAD is now at 330f27491 superenv: Use 02 optimization flag for Linux builds (#782)
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.3_2.armv6_linux.bottle.tar.gz
Already downloaded: /home/pi/.cache/Homebrew/portable-ruby-2.3.3_2.armv6_linux.bottle.tar.gz
==> Pouring portable-ruby-2.3.3_2.armv6_linux.bottle.tar.gz
Error: Failed to upgrade vendor ruby.
Error: Failed to install vendor Ruby.
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force
```

Did you change the install script as well to just use the local ruby? Could you advise on a good way to achieve that?

**Comment by harper357** [comment]
Im sorry, but I don't remember. I don't think I would have, though.

**Comment by sjackman** [comment]
I'm working on bottling `portable-ruby` 2.3.7 for ARM.

**Comment by ipatch** [comment]
@sjackman anything I can do to help with this?  Presently I'm trying to install linuxbrew on my Raspberry Pi 3 Model B, [specs](https://www.cyberciti.biz/hardware/raspberry-pi-3-model-b-released-specs-pricing/)

When I run the below command,

```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

I've tried installing linuxbrew into `/home/.linuxbrew` and in `/home/pi/.linuxbrew` and both installations fail in either directory, but moreover the install seems to be grabbing the wrong version of the portable ruby version for the wrong CPU architecture, ie. installing is trying to grab portable ruby for **armv6_linux.bottle.tar.gz** however I'm 99.9% sure the CPU arch on my Raspberry Pi 3 Model B is **v7+** ie.

```
uname -a
```

Outputs

```
Linux raspberrypi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux
```
---
```
cat /proc/cpuinfo
```

Outputs

```
model name      : ARMv7 Processor rev 4 (v7l)
```

**Comment by sjackman** [comment]
The ARMv6 bottle should work on both ARMv6 and ARMv7. We only build the one bottle.

This this suggested work around, until I bottle 2.3.7 for ARM. https://github.com/Linuxbrew/brew/issues/781#issuecomment-412292901
