### ISSUE TITLE
gcc versions change causing compilation issues?

### ISSUE THREAD

**Issue by ahundt** [Linuxbrew/brew#50]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

Installation on Ubuntu 14.04 of packages switches compilers halfway through leading to broken packages. Ubuntu comes with gcc 4.8.4. I installed linuxbrew on a fresh machine with the script on linuxbrew.sh. I also installed the packages recommended with apt-get on the same page, added the appropriate items to my ~/.bashrc and opened a new terminal window.

I then ran:

```
brew tap homebrew/science
brew tap ahundt/robotics
brew install grl
```

The second is one of my package sets that I most frequently run on OS X, and grl is a library in that package set. After installing quite a few packages it began installing gcc 5.2 and switched to that by default. I think that switch subsequently causes issues in compilation.

https://gist.github.com/d7463d0b445b9823c1c0522f2928f781

**Comment by ahundt** [comment]
Perhaps it would make sense for brew to have a way to set the desired gcc compiler?

**Comment by bw-yuhogg** [comment]
For the most part, I recommend making Homebrew's GCC one of the first packages you install. `brew install gcc --with-glibc` tends to make your whole life easier.

However, there is a way to make Homebrew pick what GCC version it uses. Suppose you wish to use your host's GCC (for demonstration purposes I'll say that's GCC 4.5). Then you can do

``` bash
$ ln -s /usr/bin/gcc-4.5 $HOMEBREW_PREFIX/bin
$ brew install some_c_program --cc=gcc-4.5
```

Making the symlink is necessary, because otherwise Homebrew will not recognize your specified compiler.

**Comment by sjackman** [comment]
I would agree that this is a bug, but I don't have an easy fix for now. I recommend Bob's suggested workaround in the mean time. The following one-liner should work for you:

``` sh
brew install gcc ahundt/robotics/grl
```

**Comment by sjackman** [comment]
There may be a bigger issue here if the `boost` bottle that is compiled with GCC 4.8 on Ubuntu 14 does not work with GCC 5.3.

**Comment by sjackman** [comment]
I'm curious which formula is pulling in `gcc` as a dependency.

**Comment by ahundt** [comment]
@sjackman I think it may be https://github.com/ahundt/homebrew-robotics/blob/ecbd5343927b7a617c732d42244b7128eed178bd/cisstnetlib.rb via `depends_on :fortran`.

**Comment by sjackman** [comment]
Ah, yes. Either `brew install gcc ahundt/robotics/grl` or

``` sh
sudo apt-get install gfortran
brew install ahundt/robotics/grl
```

should resolve your issue.

**Comment by ahundt** [comment]
sounds like that workaround might take care of my immediate problem until the bug is handled, thanks!

**Comment by ahundt** [comment]
Hmm, I also realized that I really need to be able to specify if system or homebrew dependencies are desirable for certain crucial low level deps like gcc and gfortran. On some platforms I use it is ok to do a full linuxbrew stack, but on others it is important for me to use the system gcc.

**Comment by sjackman** [comment]
That's usually handled with a `Requirement`, which is a conditional dependency, that checks whether the system provides the necessary dependency, and if not, installs the dependency with `brew`. See for example https://github.com/Homebrew/homebrew-science/blob/master/beagle.rb#L1
