### ISSUE TITLE
[DOCS] References to XCode?

### ISSUE THREAD

**Issue by rlue** [Linuxbrew/brew#505]
It appears that the documentation has not been modified to remove Mac-specific considerations. For example, the [Troubleshooting page](https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md) suggests:

> * Check that **Command Line Tools for Xcode (CLT)** and **Xcode** are up to date.

and the [Common Issues page]() suggests:

> ### `brew` complains about absence of "Command Line Tools"
>
> You need to have the Xcode Command Line Utilities installed (and updated): run `xcode-select --install` in the terminal. (In OS X prior to 10.9, the "Command Line Tools" package can alternatively be installed from within Xcode. `⌘,` will get you to preferences. Visit the "Downloads" tab and hit the install button next to "Command Line Tools".)

Until I realized that the Linuxbrew docs were a verbatim copy of the Homebrew docs, I was very confused, and spent about ten minutes Googling to find out if maybe there was some way that Xcode command line tools could somehow be installed on Linux.

I understand that maintaining two co-evolving versions of mostly similar documentation might be unduly burdensome, but is there any chance we could at least have a notice at the top of the page stating that the docs we're seeing are actually for the original version of Homebrew, and references to XCode or similar may not apply?

**Comment by sjackman** [comment]
Sorry for the confusion, Ryan. Linuxbrew can run on both Linux and macOS. Homebrew is gaining support for Linux. Any fix to this issue should keep that in mind. For the Troubleshooting doc, I'd suggest creating a new section `Check for common issues on macOS` and moving those macOS-specific items to that new section. A PR would be welcome if you'd like to contribute one.

**Comment by rlue** [comment]
Thanks for the speedy reply — all that is news to me. 

Given the shared set of documentation between two projects who's relationship I'm still not entirely clear on, I think I'll hold off on a PR for now. 

Thanks for all your work on this project!

**Comment by sjackman** [comment]
No worries, Ryan. Linuxbrew is a long-term fork of Homebrew. We merge Homebrew into Linuxbrew frequently. We contribute Linux-specific changes back to Homebrew with pull requests as we find the time.
