### ISSUE TITLE
Fixes needed for java_requirement

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/brew#509]
The jdk9 migration is under way in core, see
https://github.com/Homebrew/homebrew-core/issues/19696

We have some broken formulae, see for example that change:
https://github.com/Homebrew/homebrew-core/commit/5390b6f9065698b50e8c3951f7d6b9614442e991

This requires jdk8, but `brew deps ammonite-repl` gives `jdk`, which is jdk9 in Linuxbrew.
`brew deps ammonite-repl` should return  `jdk@8`
`brew test ammonite-repl` fails, because it is run with java 9, and not java 8.

@sjackman @maxim-belkin any thoughts on your side on how we want to tackle this?
Adding @ilovezfs to the discussion.

See also this table which may help setups something on our side:
https://github.com/Homebrew/brew/pull/3352

**Comment by iMichka** [comment]
For completeness:

> (bin/"amm").write_env_script libexec/"amm", Language::Java.java_home_env("1.8")

should give
```
$cat `which amm`
#!/bin/bash
JAVA_HOME="$(/usr/libexec/java_home --version 1.8)" exec "/usr/local/Cellar/ammonite-repl/1.0.3/libexec/amm" "$@"
```

Currently on Linuxbrew:
```
cat `which amm`
#!/bin/bash
exec "/home/linuxbrew/.linuxbrew/Cellar/ammonite-repl/1.0.3/libexec/amm" "$@"
```

So we have a double problem:
- the `jdk` dependency is wrong
- write_env_script does nothing

We may need also brew 1.3.6 first, see https://github.com/Homebrew/brew/pull/3333/files

**Comment by iMichka** [comment]
1.3.6 has been merged (but that does not help).

**Comment by sjackman** [comment]
Linux doesn't typically have `/usr/libexec/java_home`.
We can find a port of `java_home` to Linux and use/install that.
We can modify `java_requirement.rb` and possibly `Language::Java.java_home_env` to also search the versioned `jdk@*` formulae.

**Comment by sjackman** [comment]
See also this `rstudio-server` issue: https://github.com/Homebrew/homebrew-science/pull/6393#issuecomment-341990634

**Comment by sjackman** [comment]
I merged this PR https://github.com/Linuxbrew/brew/pull/629 which translates `depends_on :java` to `depends_on "jdk"` when the host does not provide a sufficiently new enough version of Java. It does not handle the case of `depends_on :java => "8"`, which could be translated to `depends_on "jdk@8"`.

**Comment by sjackman** [comment]
Further improvements to this issue at PR https://github.com/Linuxbrew/brew/pull/741

**Comment by sjackman** [comment]
This issue was addressed by PRs https://github.com/Homebrew/brew/pull/5310 and https://github.com/Homebrew/brew/pull/5333

**Comment by iMichka** [comment]
Thanks!
