### ISSUE TITLE
addition to the README: purpose of the project?

### ISSUE THREAD

**Issue by ghost** [Linuxbrew/brew#510]
Not sure what the purpose of this project is, it would be nice if that is noted in the readme, perhaps as a comparison to tools like apt or yum or some other package manager(s)?

**Comment by sjackman** [comment]
> It can be installed in your home directory and does not require root access. The same package manager can be used on both your Linux server and your Mac laptop. Installing a modern version of glibc and gcc in your home directory on an old distribution of Linux takes five minutes.

https://github.com/Linuxbrew/brew#linuxbrew

**Comment by ghost** [comment]
I guess this is the purpose?

>The same package manager can be used on both your Linux server and your Mac laptop. 

Thanks!

**Comment by sjackman** [comment]
No problem. Also:
> It can be installed in your home directory and does not require root access.
