### ISSUE TITLE
brew fails with 'Error: Failed to install vendor ruby

### ISSUE THREAD

**Issue by bottlehall** [Linuxbrew/brew#511]
# Please always follow these steps:
- [YES ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new
- [YES BUT GIVES THE ERROR AND TERMINATES ] Ran `brew update` and retried your prior step?
- [YES BUT GIVES THE ERROR AND TERMINATES ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ NO - SEE ABOVE] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

I want to install vapor on a raspberry pi so I was running:

brew install vapor/tap/vapor

Now, whatever brew command I do, it responds with:

```
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.x86_64_linux.bottle.tar.gz
Already downloaded: /home/npr/.cache/Homebrew/portable-ruby-2.3.3.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.3.3.x86_64_linux.bottle.tar.gz
Error: Failed to install vendor ruby.
Error: Failed to install vendor Ruby.
```

I have followed numerous threads and fiddled with permissions, ownerships, done manual downloads, you name it!

Thanks

**Comment by bottlehall** [comment]
Ooops! Just spotted that this is actually a duplicate of Issue #498!

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
No worries, Nick.
