### ISSUE TITLE
New Linuxbrew/brew needs ruby version 2.3.3 ? 

### ISSUE THREAD

**Issue by pathbox** [Linuxbrew/brew#520]
My Ubuntu installed the ruby-2.1.1, then when I run `sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
` , the error happend:
```
==> Downloading and installing Linuxbrew...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at 095d01f tap.rb: Remove defunct tap Linuxbrew/dupes (#513)
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz

curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Error: Download failed: https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
Error: Failed to install vendor Ruby.
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force
```

Then I run `rvm use 2.3.3`, then the ruby version is 2.3.3 in environment now, I installed successfully.

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
```
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
```
I'm not sure what's causing this error. A related upstream issue is https://github.com/curl/curl/issues/1689
Perhaps there's something off with your `curl` executable.
You can try `brew vendor-install ruby`
Glad to hear that you got it working.
