### ISSUE TITLE
Error: glibc cannot be built with any available compilers.

### ISSUE THREAD

**Issue by ACharbonneau** [Linuxbrew/brew#528]
- [X] Confirmed this is a problem with running a `brew` command 
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed all issues and retried your prior step?
- [X] Ran `brew config `https://gist.github.com/ACharbonneau/a20f9a349805b1ab0eee283c284ffb70 and `brew doctor` https://gist.github.com/ACharbonneau/99a9fd71ada844032ae48ffa47405223

To help us debug your issue please explain:
- **What you were trying to do (and why)**
My brew install was acting weird (insisting that it could not merge in an update, and repeatedly failing), and I assumed that I had broken git somehow, as I had been writing some custom formula and whatnot. So, I uninstalled to do a fresh re-install. The installation goes fine, but I can not get it to bootstrap gcc, and therefore can't install anything.

- **Things I've tried**
>$ brew install hello
==> Installing dependencies for hello: glibc, xz, m4, gmp, mpfr, libmpc, isl, gcc
==> Installing hello dependency: glibc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
$ brew install gcc
==> Installing dependencies for gcc: glibc, xz, m4, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: glibc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc

I do have a system gcc, and it's 4.4.7, which should be fine for bootstrapping:
>$ which gcc
/usr/bin/gcc
$ which g++
/usr/bin/g++

Linuxbrew is installed in the default place, and I'm also sure that the symlinks in linuxbrew are pointing to them:
>$ cd ~/.linuxbrew/bin/
$ ./gcc-4.4 --version
gcc-4.4 (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ ./g++-4.4 --version
g++-4.4 (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ ./gfortran-4.4 --version
GNU Fortran (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.

>GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

And, I'm sure that linuxbrew actually *can* see my system compiler, because I can manually use the hello formula to install successfully (selected output only):
>$ brew install hello --interactive
$ ./configure --prefix=/mnt/home/charbo24/.linuxbrew --disable-debug --disable-dependency-tracking --disable-silent-rules
checking for gcc... /usr/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to accept ISO C89... none needed
checking whether /usr/bin/gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of /usr/bin/gcc... none
checking how to run the C preprocessor... /usr/bin/gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for ld used by /usr/bin/gcc... 
$ make install
$ exit
$ hello
Hello, world!

However, the same trick won't work for gcc or glibc:
>$ brew install gcc --interactive
==> Installing dependencies for gcc: glibc, xz, m4, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: glibc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
$ brew install gcc --interactive --cc=gcc-4.4
==> Installing dependencies for gcc: glibc, xz, m4, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: glibc
Error: Homebrew GCC requested, but formula gcc@4.4 not found!

And even though hello is installed, and so all the dependencies must also be...I still can't install it normally:
>$ brew install hello
==> Installing dependencies for hello: glibc, xz, m4, gmp, mpfr, libmpc, isl, gcc
==> Installing hello dependency: glibc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc

I have no idea what else to try :(

**Comment by sjackman** [comment]
Hi, Amanda! Which distribution of Linux are you on? If it's CentOS 6, try a fresh installation with these instructions:
https://github.com/Linuxbrew/brew/wiki/CentOS6

**Comment by sjackman** [comment]
`glibc` 2.23 requires GCC ≥ 4.7 to compile it from source, which creates some grief.

If you can install Linuxbrew in the directory `/home/linuxbrew/.linuxbrew`, that can make life a lot easier, because you don't need to compile `glibc` from source then.

**Comment by ACharbonneau** [comment]
Thanks! I don't know how I missed that wiki page yesterday, but the centOS6 instructions fixed it :)

**Comment by sjackman** [comment]
Glad to hear it! It's a bit clunky, but it works.
