### ISSUE TITLE
Dependency resolver ignores disabled build dependencies during installation

### ISSUE THREAD

**Issue by name-route** [Linuxbrew/brew#529]
I'm trying to install `h2o` web server and due to `cmake` depending on `sphinx-doc` by default (build dependency) it is pulling in stuff that I do not needed, like readline, sqlite, berkleydb@4, gdbm, python.

I have installed cmake `--without-docs` all giddy that I have solved my issue. But no!, when I tried again to install `h2o` it is still trying to install python and friends, but not actual `sphinx-doc`.

**Comment by name-route** [comment]
It is an upstream issue: Homebrew/brew/issues/3033

**Comment by sjackman** [comment]
Thanks for the bug report, @name-route.
As a hack workaround, you can `brew edit cmake` and remove the dependency that you don't want.

Upstream issue: Homebrew/brew#3033

**Comment by name-route** [comment]
Upstream fixed issue: https://github.com/Homebrew/brew/commit/360d7bc6f4cdea996b55c14d885a8b78da5dd7ad

**Comment by sjackman** [comment]
Thanks for following up. 😁

**Comment by name-route** [comment]
Will that fix eventually come over here ? It is kind of big bug if you have to install so many things you don't need.

**Comment by iMichka** [comment]
It will come when we have time to update to 1.4.0 and 1.4.1. You can watch this issue to follow updates: https://github.com/Linuxbrew/brew/issues/1

**Comment by sjackman** [comment]
I'm currently working on resolving issues cause by `ENV_FILTERING`, which has been enabled by default for developers (including CI) for 1.3.9, and will be enabled for all users in 1.4.0, so it's important to get the wrinkles ironed out before tagging and releasing 1.3.9.
