### ISSUE TITLE
brew update no longer uses brewed ruby

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/brew#536]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new
- [ ] Ran `brew update` and retried your prior step? NA
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step? NA
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue? NA

To help us debug your issue please explain:
- What you were trying to do (and why)
```$ brew update```
- What happened (include command output)
```
$ brew update
which: no ruby in (/usr/bin:/bin:/usr/sbin:/sbin)
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
```
- What you expected to happen
I expected brew to use brew-installed ruby as it has done in the past.
```
$ which ruby
/home/linuxbrew/.linuxbrew/bin/ruby
```
- Step-by-step reproduction instructions (by running `brew` commands)
All of the following result in the same:
```$ brew update``` ```$ brew dr``` ```$ brew config```

**Comment by sjackman** [comment]
For running Linuxbrew itself, using `portable-ruby` 2.3.3 is better tested and less likely to break.
That being said, PR https://github.com/Linuxbrew/brew/pull/537 which addresses are related but different issue related to `git` will likely restore the previous behaviour that you prefer.
Out of curiosity, can you please report…
```sh
brew config | grep 'Homebrew Ruby'
HOMEBREW_NO_ENV_FILTERING=1 brew config | grep 'Homebrew Ruby'
```

**Comment by jwhite007** [comment]
Thanks for the response, Shaun. I sort of suspected that this was new behavior. I get what you're trying to do. It does make sense. I don't need to go back to the old way. I'll just adapt. Sorry for the trouble.

```
$ brew config | grep 'Homebrew Ruby'
which: no ruby in (/usr/bin:/bin:/usr/sbin:/sbin)
==> Downloading https://homebrew.bintray.com/bottles-portable/portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.3.x86_64_linux.bottle.1.tar.gz
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
```
```
$ HOMEBREW_NO_ENV_FILTERING=1 brew config | grep 'Homebrew Ruby'
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
```

**Comment by sjackman** [comment]
No worries. Thanks for following up.
