### ISSUE TITLE
brew cannot find GCC

### ISSUE THREAD

**Issue by doomedramen** [Linuxbrew/brew#538]
Since the most recent update brew is unable to find GCC.
Not sure if anyone else is having this issue.

```
Error: The following formula:
  node
cannot be installed as a binary package and must be built from source.
Install Clang or brew install gcc
```

`brew doctor` also reports that there is no compiler installed, there definitely is...

Setting this some how fixes the issue:
```
export HOMEBREW_NO_ENV_FILTERING=1
```

If there is any info I can give to help diagnose the issue and why the env filtering fixes it please let me know.

**Comment by sjackman** [comment]
Thanks for the bug report, Martin. With `ENV_FILTERING` enabled, `brew` isn't finding your compiler in `$HOMEBREW_PREFIX/bin`. I'll look into it.

**Comment by sjackman** [comment]
I believe this bug is fixed by PR https://github.com/Linuxbrew/brew/pull/546.
Thanks for the bug report, Martin.
