### ISSUE TITLE
Brew uses outdated system git version

### ISSUE THREAD

**Issue by jonaszierer** [Linuxbrew/brew#543]
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [x] Ran `brew config` and `brew doctor` and included their output with your issue?

I have brew installed on a HPC grid running CentOS 6.9. I have the most current version of git installed; `brew upgrade git` returns `git 2.15.1 already installed`. Also linuxbrew binary directories come first in my PATH, `which git` returns `HOME/.linuxbrew/bin/git` and `git --version` returns `git version 2.15.1`

Nonetheless, brew appears to use the system git, so when I run `brew doctor` I get 
`Warning: An outdated version (1.7.1) of Git was detected in your PATH.
Git 1.8.5 or newer is required to perform checkouts over HTTPS from GitHub and
to support the 'git -C <path>' option.
Please upgrade:
  brew upgrade git`

and `brew config` gives (amongst others) `Git: 1.7.1 => /usr/bin/git`

Due to this issue I get all the time `error: unknown option list` and `error: unknown option local` messages, which amonst otherse cause `brew update` to fail

Do you have any idea why brew doesn't use the brew git version even though everything else does?

**Comment by jonaszierer** [comment]
actually this appears to be the same as #534 and `export HOMEBREW_NO_ENV_FILTERING=1` does resolve the problem

**Comment by iMichka** [comment]
Hi. Yes, I think it is. I'll close this issue, you can follow the other issue.
