### ISSUE TITLE
jq: error while loading shared libraries: libonig.so.4

### ISSUE THREAD

**Issue by yschimke** [Linuxbrew/brew#549]
jq installed via linuxbrew doesn't work for me, but jq is usually available via existing platform repos.  

Is there a way to mark it as optional for linuxbrew, but not for osx brew?

```
$ jq
jq: error while loading shared libraries: libonig.so.4: cannot open shared object file: No such file or directory
```

**Comment by sjackman** [comment]
Hi, Yuri. Please report the output of…
```sh
brew config
brew doctor
brew list --versions oniguruma
brew info oniguruma
brew linkage jq
brew install oniguruma
brew link oniguruma
brew linkage jq
jq --version
```

**Comment by sjackman** [comment]
I am able to reproduce this issue.
```
❯❯❯ brew linkage jq
Homebrew libraries:
  /home/sjackman/.linuxbrew/lib/libc.so.6 (glibc)
  /home/sjackman/.linuxbrew/lib/libm.so.6 (glibc)
Missing libraries:
  libonig.so.4
❯❯❯ ls ~/.linuxbrew/opt/oniguruma/lib
libonig.a  pkgconfig
```

**Comment by sjackman** [comment]
@iMichka `libonig.so.4` has gone missing from the `oniguruma` bottle.

**Comment by sjackman** [comment]
@yschimke `brew reinstall -s oniguruma` should resolve your issue.

**Comment by sjackman** [comment]
I believe this issue has been resolved by https://github.com/Linuxbrew/homebrew-core/pull/5357
