### ISSUE TITLE
Make LinuxBrew install script have a non-interactive mode

### ISSUE THREAD

**Issue by 1ne** [Linuxbrew/brew#556]
Creating an Issue here as install script has no issue section. 

A little background, I'm trying to automate the process of LinuxBrew install and other packages through a bash script. When the install script runs it tries to create a /home/linuxbrew directory and 
subsequently asks for password for the user and halts on the screen.

Refer to line 220 in [Linuxbrew/install](https://github.com/Linuxbrew/install/blob/master/install#L220) where the authentication is triggered.

There are two challenges here for me here:
1. We don't have a password set for the user as we use SSH as the only login mechanism and we don't want to set a password as this is the only reason to do so.
2. Even if we set a password, since the password entry is an interactive shell that defeats the whole point of the automation we are trying to achieve.

I've already set the user sudoers config to the following to skip entering password when invoking sudo. But it doesn't seem to be working with the way brew install is invoking sudo.
`<user-name> ALL=(ALL) NOPASSWD:ALL`

I've tried this on with the same result:
RHEL and CentOS 7.x
Ubuntu 16.04+
Arch Linux

I'm looking for either a solution or a workaround for this scenario or want to see if I'm missing anything.

**Comment by sjackman** [comment]
Setting `sudo` to `NOPASSWD` should work; it's works for me. See…
https://github.com/Linuxbrew/docker/blob/master/centos6/Dockerfile#L10
```sh
echo "$USER ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers
```
Also try…
```sh
yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```
though that `yes` probably won't help with `sudo`.

**Comment by sjackman** [comment]
Closing for now, but feel free to comment.
