### ISSUE TITLE
Set up Circle CI to run Linux for the install repo

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#57]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Currently, Travis builds for the linuxbrew/install repo are only run against OS X. We should fix that by having it run against Linux.

**Comment by sjackman** [comment]
Let's instead set up Circle to run Linux and leave Travis running Mac OS to test both OS.
