### ISSUE TITLE
Fail to install util-linux

### ISSUE THREAD

**Issue by pengyubio** [Linuxbrew/brew#571]
I got the following error. Does anybody know what is wrong? Thanks.

```
$ brew install util-linux
==> Downloading https://www.kernel.org/pub/linux/utils/util-linux/v2.30/util-linux-2.30.1.tar.xz
Already downloaded: /home/py/.cache/Homebrew/util-linux-2.30.1.tar.xz
==> ./configure --disable-silent-rules --prefix=/home/py/.linuxbrew/Cellar/util-linux/2.30.1 --disable-use-tty-group --disable-kill --disable-cal --disable-ul --without-systemd --with-bashcompletiondir=/home/py/.linuxbrew/Cellar/ut
==> make install
Last 15 lines from /home/py/.cache/Homebrew/Logs/util-linux/02.make:
/home/py/.linuxbrew/bin/ld: /usr/local/lib/libpython2.7.a(getplatform.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/py/.linuxbrew/bin/ld: /usr/local/lib/libpython2.7.a(getversion.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/py/.linuxbrew/bin/ld: /usr/local/lib/libpython2.7.a(structmember.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/py/.linuxbrew/bin/ld: /usr/local/lib/libpython2.7.a(parser.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/py/.linuxbrew/bin/ld: /usr/local/lib/libpython2.7.a(myreadline.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/py/.linuxbrew/bin/ld: /usr/local/lib/libpython2.7.a(bytes_methods.o): relocation R_X86_64_32S against symbol `_Py_ctype_table' can not be used when making a shared object; recompile with -fPIC
/home/py/.linuxbrew/bin/ld: /usr/local/lib/libpython2.7.a(getcompiler.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/py/.linuxbrew/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [pylibmount.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/tmp/util-linux-20180119-7321-1p5dnme/util-linux-2.30.1'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/tmp/util-linux-20180119-7321-1p5dnme/util-linux-2.30.1'
make: *** [install] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.

```

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

**Comment by sjackman** [comment]
`util-linux` doesn't currently have a dependency on `python`. Perhaps it should.

**Comment by pengyubio** [comment]
@sjackman Multiple users use the same machine. I'd like to have linuxbrew installation spearated from each user. So I don't want to use `/home/linuxbrew/.linuxbrew/`. What is purpose of having `/home/linuxbrew/.linuxbrew` and `~/.linuxbrew` seperately.

**Comment by sjackman** [comment]
The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by pengyubio** [comment]
@sjackman Why not allow each user to have their own directory for `/home/linuxbrew/.linuxbrew`?

**Comment by sjackman** [comment]
Yes, each user can use `~/.linuxbrew`, that's fine. They won't be able to use non-relocatable bottles though, and will have to compile those non-relocatable formulae from source.
Did `brew install --force-bottle util-linux` work for you?

**Comment by pengyu** [comment]
@sjackman 

Yes. It works. What does `--force-bottle` do? What is a `bottle` (I tried to find its definition, but failed)?

```
~$ brew install --force-bottle util-linux
==> Downloading https://linuxbrew.bintray.com/bottles/util-linux-2.30.1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring util-linux-2.30.1.x86_64_linux.bottle.tar.gz
==> Caveats
Some commands were moved to the bsdmainutils formula.
You may wish to install it as well.

Bash completion has been installed to:
  /home/py/.linuxbrew/etc/bash_completion.d
==> Summary
🍺  /home/py/.linuxbrew/Cellar/util-linux/2.30.1: 350 files, 33MB
```

**Comment by sjackman** [comment]
A bottle is Brew terminology for a precompiled binary package. The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below, but wherever it reads `/usr/local`, which is for macOS, read instead `/home/linuxbrew/.linuxbrew`.
+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by fuzzy76** [comment]
I have an old linuxbrew install where ~/.linuxbrew was the only option (as far as I can remember). It this the reason upgrades suddenly started breaking for me?

**Comment by sjackman** [comment]
Likely not. Please open a new issue and report the error message.
