### ISSUE TITLE
[question]How to delete unused dependencies?

### ISSUE THREAD

**Issue by fcying** [Linuxbrew/brew#573]
like apt-get autoremove?

**Comment by ghost** [comment]
there is [this](https://github.com/Homebrew/brew/pull/1881) attempt from a maintainer but failed

maybe this guy can help us at some point, [he did some other good work already](https://github.com/Homebrew/brew/pull/3526) (brew cask upgrade)

the maintainers do for some reason not seem to have interest in fixing that shortcoming which to me seems like the last major missing thing in homebrew 😞 now that cask upgrade is finally 'resolved'

**Comment by sjackman** [comment]
No. Since Linuxbrew/brew is a fork of Homebrew/brew, we don't add new features to Linuxbrew that aren't first added to Homebrew. We're in the process of merging Linuxbrew/brew into Homebrew/brew so that Linuxbrew/brew can be discontinued, once Homebrew/brew supports Linux.

**Comment by sjackman** [comment]
Try…
```sh
brew bundle dump
brew bundle --force cleanup
```

**Comment by fcying** [comment]
> Try…
> brew bundle dump
> brew bundle --force cleanup

It can work, thanks~
