### ISSUE TITLE
Can't find any compiler when install gcc.

### ISSUE THREAD

**Issue by platinhom** [Linuxbrew/brew#579]
- [ ] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new
- [ x ] Ran `brew update` and retried your prior step?
- [ x ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

Normal with `brew update` and `brew doctor`.

```
HOMEBREW_VERSION: 1.5.0
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: e51af2acc89d27d09ade0fd148d1cdcaf30560d2
Last commit: 6 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: c0108276ea37dadc512dc75c4825c59764777d57
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /mnt/home/zhaozx/.linuxbrew
HOMEBREW_REPOSITORY: /mnt/home/zhaozx/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /mnt/home/zhaozx/.linuxbrew/Cellar
HOMEBREW_CACHE: /mnt/home/zhaozx/.cache/Homebrew
HOMEBREW_CELLAR: /mnt/home/zhaozx/.linuxbrew/Cellar
HOMEBREW_GIT: /opt/software/git/2.9.0/bin/git
HOMEBREW_PREFIX: /mnt/home/zhaozx/.linuxbrew
HOMEBREW_REPOSITORY: /mnt/home/zhaozx/.linuxbrew/Homebrew
CPU: 28-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /mnt/home/zhaozx/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.9.0 => /opt/software/git/2.9.0/bin/git
Curl: 7.19.7 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.6.0_40
Kernel: Linux 2.6.32-642.11.1.el6.x86_64 x86_64 GNU/Linux
OS: CentOS release 6.8 (Final) (Final)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: N/A
gcc: N/A
xorg: N/A
```

To help us debug your issue please explain:
- What you were trying to do (and why)
I just install linuxbrew and want to install gcc, but failed all the way.
- What happened (include command output)
```
## It has symbol link gcc-4.4 g++-4.4 also gfortran in bin, such as  
> ll .linuxbrew/bin/
gcc-4.4 -> /usr/bin/gcc
.....

> brew install gcc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc
> brew installl --cc=gcc-4.4 gcc
Error: Homebrew GCC requested, but formula gcc@4.4 not found!
> brew install --cc=gcc-4.4 --env=std gcc
Error: Homebrew GCC requested, but formula gcc@4.4 not found!

> brew tap homebrew/versions
> ln -s /opt/software/GCC/5.4/bin/gcc .linuxbrew/bin/gcc-5.4
> brew install --cc=gcc-5.4 gcc
Error: Invalid value for --cc: gcc-5.4

> brew irb <<<'Formula["gcc"].installed?'
fasle
> brew irb <<<'Formula["gcc"].any_version_installed?
false
```
- What you expected to happen
Install normally.
- Step-by-step reproduction instructions (by running `brew` commands)

# Features

I'm using the HPC in our university, in a SUSE system. I want to install tensorflow but it failed because of out-of-date glibc. The HPCC has a solution for it, using LinuxBrew.  HPC has gcc-4.4.7 as default, and can change to other compiler by `module load GNU/5.4`. 

I try to install LinuxBrew, but it failed to install gcc. I followed many instructions online, but it seems like that the linuxbrew can't identify the compiler at all. Plz help.

We will close this issue or ask you to create a pull-request if it's something we're not actively planning to work on.

**Comment by platinhom** [comment]
I have solved this. I follow [https://github.com/Linuxbrew/brew/issues/528](https://github.com/Linuxbrew/brew/issues/528) to use `brew install hello --interactive` to check the details. I found it can use gcc4.4 to compile it.   

I tried to `ln -s /opt/software/GCC/5.4/bin/gcc .linuxbrew/bin/gcc-5`, not `gcc-5.4`. now `brew install gcc --interactive` can work! (But `brew install gcc --cc=gcc-5` can't work).

**Comment by sjackman** [comment]
Glad to hear that you got this working, Hom.
