### ISSUE TITLE
x11 Requirements do not resolve correctly

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/brew#580]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

I'm trying to install formulas, which include a `:x11` requirement in them. Brew tells me that the x11 requirement cannot be satisfied even though libraries used to build with a similar dependency.

- What happened (include command output)

```bash
# Running the install
$ brew reinstall pango
pango: X11 is required to install this formula, either Xorg 1.12.2 or xdpyinfo 1.3.0, or newer. X11Requirement unsatisfied!

# Checking xdpyinfo
$ xdpyinfo -version
xdpyinfo 1.3.2

# Checking Xorg
$ Xorg -version
(EE)
Fatal server error:
(EE) PAM authentication failed, cannot start X server.
	Perhaps you do not have console ownership?
(EE)
(EE)
Please consult the The X.Org Foundation support
	 at http://wiki.x.org
 for help.
(EE)
```

- What you expected to happen

It seems I have an Xorg binary (a system one from `/usr/bin/Xorg`) and xpdyinfo from Linuxbrew. The current x11 requirements is unable to detect a situation where my system Xorg isn't functional (I don't know why) but x11 requirements are being satisfied from linuxbrew.

- Step-by-step reproduction instructions (by running `brew` commands)

I edited `Library/Homebrew/requirements/x11_requirement.rb` to inject some `puts` statements into `satisfy build_env: false do`. Because we have an `Xorg` binary the `which Xorg` succeeds meaning we never get to check if there is a `xdpyinfo` binary available.

# Features
Please replace this section with:
- a detailed description of your proposed feature

That the `satisfy` block is expanded to test if `Xorg` *or* `xdpyinfo` is available. This requires no use of `next false unless STATEMENT` and passing back a variable to evaluate. I've created a suggested bit of code below but am not sure how well this fits into brew style

```ruby
  satisfy build_env: false do
    x11_available= false
    if which_xorg = which("Xorg")
      version = Utils.popen_read which_xorg, "-version", err: :out
      if $CHILD_STATUS.success?
        version = version[/X Server (\d+\.\d+\.\d+)/, 1]
        if version
          x11_available = Version.new(version) >= min_version
        end
      end
    end
    if ! x11_available && (which_xdpyinfo = which("xdpyinfo"))
      version = Utils.popen_read which_xdpyinfo, "-version"
      if $CHILD_STATUS.success?
        version = version[/^xdpyinfo (\d+\.\d+\.\d+)/, 1]
        if version
          x11_available = Version.new(version) >= min_xdpyinfo_version
        end
      end
    end
    x11_available
  end
```

- the motivation for the feature

The feature would allow the compilation of libraries dependent on x11 if there is a valid x11 library available and not bail if one is available but not working.

- how the feature would be relevant to at least 90% of Linuxbrew users

Not sure but there must be others suffering from a similar issue with this I'd hope

- what alternatives to the feature you have considered

There's not a lot else I can suggest. A version of the routine, which is closer to the original would be fine but still it needs to be able to eval the existence and version of multiple x11 providers not just one.

**Comment by andrewyatz** [comment]
I should say on my local brew version the routine works and I can install x11 dependent formulas again.

**Comment by sjackman** [comment]
Thanks for the bug report, Andrew. Does this (untested) code work for you?
```ruby
  satisfy build_env: false do
    if which_xorg = which("Xorg")
      version = Utils.popen_read(which_xorg, "-version", err: :out)[/X Server (\d+\.\d+\.\d+)/, 1]
      next true if $CHILD_STATUS.success? && version && Version.new(version) >= min_version
    end

    if which_xdpyinfo = which("xdpyinfo")
      version = Utils.popen_read(which_xdpyinfo, "-version")[/^xdpyinfo (\d+\.\d+\.\d+)/, 1]
      next true if $CHILD_STATUS.success? && version && Version.new(version) >= min_xdpyinfo_version
    end

    false
  end
```

**Comment by andrewyatz** [comment]
Pasted in and seems to behave :). For reference this is what is in my requirements x11 file

```ruby
  satisfy build_env: false do
    if which_xorg = which("Xorg")
      version = Utils.popen_read(which_xorg, "-version", err: :out)[/X Server (\d+\.\d+\.\d+)/, 1]
      next true if $CHILD_STATUS.success? && version && Version.new(version) >= min_version
    end

    if which_xdpyinfo = which("xdpyinfo")
      version = Utils.popen_read(which_xdpyinfo, "-version")[/^xdpyinfo (\d+\.\d+\.\d+)/, 1]
      next true if $CHILD_STATUS.success? && version && Version.new(version) >= min_xdpyinfo_version
    end

    false
  end
```

Works like a charm. I did encounter another error later on with `xcb-shm` but that feels more like a formula issue

**Comment by sjackman** [comment]
Glad to hear it worked, Andrew! I'll submit a PR to Homebrew/brew to resolve this issue.
