### ISSUE TITLE
Include albert launcher

### ISSUE THREAD

**Issue by black-snow** [Linuxbrew/brew#582]
I'd like to see a formula for the [albert launcher](https://github.com/albertlauncher/albert).
I don't know how to write a formula for this on my own (yet) so I'll propose this as a feature.
Currently it's not so handy to install albert. You'll either have to build it yourself, or add a ppa (unless you're on arch).

I don't actually know how popular alber is but at least it's got >2k stars on github. It's my linux alternative for alfred (mac) or launchy (win).

I'm willing to do this myself, just gotta take a look at how to do it first.

---- edit
I'm sorry, should I have created this issue in the brew-core project?

**Comment by sjackman** [comment]
Hi, Ronald. Here's the instructions to a create a formula:
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md
You could submit this formula to Linuxbrew/extra: https://github.com/Linuxbrew/homebrew-extra
Good luck!

**Comment by sjackman** [comment]
You could also try creating a Snapcraft package if you liked: https://snapcraft.io
It's more intended for GUI apps, where Linuxbrew is more intended for command line apps.
