### ISSUE TITLE
Is x11_requirement.rb overly strict?

### ISSUE THREAD

**Issue by wshanks** [Linuxbrew/brew#584]
When I try to install `linuxbrew/xorg/mesa`, I get the error message from https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/requirements/x11_requirement.rb:

> X11 is required to install this formula, either Xorg #{min_version} or xdpyinfo #{min_xdpyinfo_version}, or newer. #{super}

which seems to imply either Xorg or xdpyinfo could satisfy the requirement. However, the conditional in that file seems to check the `Xorg` version first (and error out if it doesn't satisfy the requirement) and then the `xdpyinfo` version. On my system (CentOS 6), the `Xorg` version is too old, but I have the brewed version of `xdpyinfo` that should be new enough. Should this be sufficient to satisfy the x11 requirement, or do I misunderstand the message?

I don't see a place other than GitHub recommended to ask general questions, so I hope you don't mind if I add this on here (is there a place?): My goal was to install `gtk+3`, so I could run applications that require GTK 3, like recent versions of Firefox. Do you know if that is possible with the formulas that currently exist? If I install `gtk+3` and other libraries and set my path variables, can I run the pre-compiled Linux version of Firefox? I tried editing x11_requirement.rb to get past the Xorg check, but then installing `systemd` failed looking for `libaudit` which it seems not packaged in a formula, so as with the `Xorg` check I am a little confused about how self-contained Linuxbrew is vs. relying on packages installed on the host system.

**Comment by sjackman** [comment]
Yes, GitHub is the right place to ask questions like this one.

Yes, this check is too strict. PR https://github.com/Linuxbrew/brew/pull/581 should likely resolve your issue. I expect to include it with Linuxbrew 1.5.3. In the mean time, install the brewed version of Xorg with `brew install linuxbrew/xorg/xorg`.

**Comment by wshanks** [comment]
Thanks. I had done `brew install linuxbrew/xorg/xorg` but that didn't provide anything on the path named `Xorg` to satisfy the Xorg version check. Should it have?

**Comment by sjackman** [comment]
`linuxbrew/xorg/xorg` provides only `xdpyinfo`, no `Xorg`. The workaround for now would be to apply the patch in PR #581. Do you know how to do that?

**Comment by iMichka** [comment]
@sjackman I opened a PR here for `mesa`: https://github.com/Linuxbrew/homebrew-xorg/pull/347
If it builds correctly I will merge that because I have a bunch of pull request waiting on a working `mesa` bottle.

**Comment by wshanks** [comment]
> The workaround for now would be to apply the patch in PR #581. Do you know how to do that?

Yes, I can do that, thanks! I just wasn't sure if your previous comment was implying that installing `linuxbrew/xorg/xorg` was an alternative to the patch.

**Comment by sjackman** [comment]
I had thought it may work, but after re-reading your issue, I see that it doesn't help you.
