### ISSUE TITLE
Symlinked standard location /home/linuxbrew/.linuxbrew being ignored when installing non-relocatible bottles

### ISSUE THREAD

**Issue by Char-Aznable** [Linuxbrew/brew#586]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

My linuxbrew is installed in /scratch/.linuxbrew and I create a symlink /home/linuxbrew -> /scratch in order to install the non-relocatible bottles. However, I find recently that I have to --force-bottle to install them and this option is not passed down the dependency chain so that I have to manually pass  --force-bottle to every single install. For example:
```
==> Installing iso-codes dependency: ncurses
Warning: Building ncurses from source:
  The bottle needs a /home/linuxbrew/.linuxbrew/Cellar Cellar (yours is /scratch/.linuxbrew/Cellar).
```
Somehow linuxbrew ignores the /home/linuxbrew/.linuxbrew path as if  the symlink is followed. Is there a way to relax this path check so that it's OK even if the standard location is a symlink? Or is there a way to force bottle to be installed in a dependency tree?

**Comment by sjackman** [comment]
Symlinking HOMEBREW_PREFIX in this way is not supported. It mostly works, but a couple of formula break, in particular `python` and `python3`. Those are in fact the only two that I've encountered to break. Here's a hack that I use to use Homebrew on macOS with a symlinked `Cellar`. https://github.com/sjackman/homebrew/commit/6a97bf5ce6d0bd47f2053e74bd6f06b7eee8c215
You could adapt this for Linuxbrew by changing `/usr/local` to `/home/linuxbrew/.linuxbrew`, and changing it to look for a PREFIX symlink rather than a CELLAR symlink. For example, get rid of the `if` statement and add
```ruby
HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
```
Good luck!

**Comment by Char-Aznable** [comment]
What did you mean when you said the python was broken by symlinking this way? Why not incorporate the hack you mentioned into the codes? I think a lot of people can benefit from this because symlinking this way might be the only solution when one doesn't have permission to the hard-coded prefix, which I believe is the main reason why people choose to use linuxbrew in the first place.

**Comment by sjackman** [comment]
`brew postinstall python` fails because a symlink to `site-library` is incorrect. I haven't had time to look into the issue. If it were fixed, the above hack could possible be incorporated into Linuxbrew.
