### ISSUE TITLE
brew-test-bot fails to upload bottles in some cases

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/brew#592]
In this merge (https://github.com/Linuxbrew/homebrew-core/pull/5979/files), the `dub` formula does not need a new bottle. There is no change in version and no change in the sha256 for the bottle.
The was log shows the following:

```
==> dub
git push --force git@github.com:LinuxbrewTestBot/homebrew-core.git master:master :refs/tags/pr-5979
/usr/bin/curl --show-error --user-agent Linuxbrew/1.5.1-1-g279e66d (Linux; x86_64 4.9.77-31.58.amzn1.x86_64) curl/7.51.0 --fail --silent -I --output /dev/null https://linuxbrew.bintray.com/bottles/dub-1.7.1.x86_64_linux.bottle.tar.gz
Already on 'master'
Error: --keep-old was passed but there are changes in:
sha256 => x86_64_linux
Error: Kernel.exit
Could not create directory '/home/sbx_user1060/.ssh'.
Failed to add the host to the list of known hosts (/home/sbx_user1060/.ssh/known_hosts).
remote: warning: Deleting a non-existent ref. 
To git@github.com:LinuxbrewTestBot/homebrew-core.git
+ 34c0869...bffb640 master -> master (forced update)
- [deleted] pr-5979
Error: dub-1.7.1.x86_64_linux.bottle.tar.gz is already published. Please remove it manually from
https://bintray.com/linuxbrew/bottles/dub/view#files
```

**Comment by sjackman** [comment]
For a merge commit `test-bot` is only supposed to test those formulae whose bottle was updated.
See https://github.com/Linuxbrew/homebrew-test-bot/blob/d980a2d2d3719e0f75bb6694548acd34c63f932f/cmd/brew-test-bot.rb#L549
Yet `test-bot` still tried to build a bottle for `dub`, which did not update its bottle.
https://circleci.com/gh/Linuxbrew/homebrew-core/12849

Let me know if you see this issue a second time.

**Comment by iMichka** [comment]
I think I already saw this in the last days, but I had no time to report it and did not note down the PR. I'll add a second example once this happens again.

**Comment by iMichka** [comment]
Another example: https://github.com/Linuxbrew/homebrew-core/pull/5997

It built a ffmpeg@2.8-2 bottle, but it should have not.

**Comment by iMichka** [comment]
Bot, go away, this is still an issue
