### ISSUE TITLE
Requirements that are never satisfied after 1.5.1

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/brew#594]
- [x] `depends_on :java`
- [ ] `depends_on :osxfuse`

Just documenting this so that we keep track of this.

https://github.com/Linuxbrew/homebrew-core/pull/5972

```
==> SKIPPING: dislocker
libfuse is required to install this formula.
Run "brew install libfuse" to install it.
```

https://github.com/Linuxbrew/homebrew-core/pull/5899
```
==> SKIPPING: jhipster
Java 1.8+ is required to install this formula.
JavaRequirement unsatisfied!
You can download from:
 https://www.oracle.com/technetwork/java/javase/downloads/index.html
```

**Comment by iMichka** [comment]
Go away bot

**Comment by iMichka** [comment]
The java requirement has been fixed with a newer version of linuxbrew.

**Comment by sjackman** [comment]
One possible fix is to change in Homebrew/core `depends_on :osxfuse`
to
```ruby
if OS.mac?
  depends_on :osxfuse
else
  depends_on "libfuse"
end
```
which makes some sense, given the name of `:osxfuse`. Does that work for you, Michka? We could also fix it in Linuxbrew/brew, as I did for `depends_on :java`.
