### ISSUE TITLE
brew installation fails : -e:276:in `<main>': undefined method `odie' for main:Object (NoMethodError)

### ISSUE THREAD

**Issue by sebma** [Linuxbrew/brew#595]
Hi,

It is not possible to create issues for your Linuxbrew/install project at https://github.com/Linuxbrew/install/issues/new

Therefore, I'm creating this issue here.

Can you please forward this issue to the Linuxbrew/install project people and ask them to enable issue creation for your Linuxbrew/install project ?

Thank you for your comprehension for this special request.
# Please always follow these steps:
To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to install Linuxbrew
- What happened (include command output)
```
id: cannot find name for group ID 1234567
./install:276:in `<main>': undefined method `odie' for main:Object (NoMethodError)
```

- What you expected to happen
A proper installation
- Step-by-step reproduction instructions : 
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"
==> Select the Linuxbrew installation directory
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /users/EtuY/1234567/.linuxbrew
- Press Control-C to cancel installation

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for 1234567: 
==> This script will install:
/users/EtuY/1234567/.linuxbrew/bin/brew
/users/EtuY/1234567/.linuxbrew/share/doc/homebrew
/users/EtuY/1234567/.linuxbrew/share/man/man1/brew.1
/users/EtuY/1234567/.linuxbrew/share/zsh/site-functions/_brew
/users/EtuY/1234567/.linuxbrew/etc/bash_completion.d/brew
/users/EtuY/1234567/.cache/Homebrew/
/users/EtuY/1234567/.linuxbrew/Homebrew
id: cannot find name for group ID 1234567
-e:276:in `<main>': undefined method `odie' for main:Object (NoMethodError)
```

On our university workstations, my homedir is on NFS and the user management used is LDAP.

BTW : `id -gn` shows : 
```
$ id -gn
id: cannot find name for group ID 1234567
1234567
$ echo $?
1
```

Can you help ?

**Comment by sjackman** [comment]
> It is not possible to create issues for your Linuxbrew/install project at https://github.com/Linuxbrew/install/issues/new

Fixed. Thanks for bringing this to my attention! It was not intentional.

**Comment by sebma** [comment]
@sjackman Thanks :-) I've just created this issue in the [Linuxbrew/install project](https://github.com/Linuxbrew/install/issues/24)

**Comment by sjackman** [comment]
Moved to https://github.com/Linuxbrew/install/issues/24
