### ISSUE TITLE
brew man: git: Unknown option: -C

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/brew#596]
Old distro has new git in PATH
```
% git --version
git version 2.4.6
```
but has old system git
```
% /usr/bin/git --version
git version 1.7.1
```
The brew man command [calls git through ruby](https://github.com/Linuxbrew/brew/blob/279e66d5753ac201ad510157b7d51f3225c5d01c/Library/Homebrew/dev-cmd/man.rb#L30), thus not affected by [the git function](https://github.com/Homebrew/brew/blob/b4443e1cc0b41d2b25ca15b87c3d4cb2ab65837f/Library/Homebrew/brew.sh#L54) defined to use the shims. Therefore, I see the following error when brew uses the older git.
```sh
% brew man
Writing markdown to /path/to/brew/docs/Manpage.md
Writing man page to /path/to/brew/manpages/brew.1
Writing man page to /path/to/brew/manpages/brew-cask.1
git -C /path/to/brew diff --quiet docs/Manpage.md manpages
Unknown option: -C
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]
```
Is there a similarly defined set of shims functions for ruby that I could use? I only see shims for bash.
```
% find . -name git  | xargs -L1 -I% sh -c 'file $(readlink -f %)'
/path/to/brew/Library/Homebrew/shims/scm/git: Bourne-Again shell script text executable
/path/to/brew/Library/Homebrew/shims/scm/git: Bourne-Again shell script text executable
/path/to/brew/Library/Homebrew/shims/scm/git: Bourne-Again shell script text executable
```
If not, what direction should I go in to fix this? For example I could try to create a set of ruby shims or maybe just prepend git to that PATH.

Furthermore, I would like to fix this upstream, but in my experience they don't want to discuss issues not found on macOS. @sjackman Suggestions?

Note: workarounds are just to set `HOMEBREW_NO_ENV_FILTERING` but this still seems like an issue. There's [one more place](https://github.com/Homebrew/brew/blob/b4443e1cc0b41d2b25ca15b87c3d4cb2ab65837f/Library/Homebrew/brew.rb#L65) not using the git shim too.

**Comment by sjackman** [comment]
Off the top of my head, I think the best path forward is to add `~/.linuxbrew/Homebrew/Library/Homebrew/shims/scm` to the front of the `PATH` on Linux here:
https://github.com/Linuxbrew/brew/blob/8ccb999ac04fa9fcb4df521004be5eeff9fd8ba6/bin/brew#L69

That may have unintended consequences that I have not yet considered, but it's worth a shot. Let me know if you do try this out.

On macOS I guess that Brew simply assumes that `/usr/bin/git` is new enough.

**Comment by carlorosati** [comment]
@sjackman That worked!

**Comment by sjackman** [comment]
Glad to hear it! I may propose that fix upstream to Homebrew/brew.

**Comment by sjackman** [comment]
I believe this issue is still relevant.
