### ISSUE TITLE
Create list of core Perl and Python modules for brew doctor

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#6]
_From @sjackman on April 3, 2016 20:24_

There's a few core Perl and Python modules that are installed on a base Mac OS system that are expected to be installed by Homebrew formula. See for example `XML::Parser` in #1036, and Python's `setuptools` in about a dozen different issues. There should be a `brew doctor` check to confirm that these modules are installed on Linux.
# Python

```
matplotlib
numpy
setuptools
```
# Perl

```
List::MoreUtils
Moo
XML::Parser
```

_Copied from original issue: Linuxbrew/linuxbrew#1038_

**Comment by sjackman** [comment]
_From @DoomHammer on April 5, 2016 18:32_

As for checks there already is #973 . List would still be needed, though.

**Comment by sjackman** [comment]
_From @tseemann on April 5, 2016 23:2_

Perl installs a bunch of "Core" modules, but these change with each version of Perl.

I'm assuming OSX has the set of core modules for the version it has installed, plus some extras perhaps?

My laptop has gone through 4 version of OSX via upgrades and I don't think I've ever used CPAN to install any Perl modules on it. Here's what folders I have:

```
ls /Library/Perl/
5.16    5.18    Updates
```

How would we go about finding a list of the modules in a virgin OSX install?

If you have a fresh OSX image I think `cpan -l` will do it.

**Comment by sjackman** [comment]
The list of Perl modules is rather longer than I had expected.
El Capitan https://gist.github.com/f39b8b95e3215458609dbe572b6a0a9d

```
❯❯❯ cpan -l | grep -v undef | sort -u | gist
```

**Comment by sjackman** [comment]
Perhaps we can just add to the list as people report bugs. I've started the list in the description of this issue above.

**Comment by sjackman** [comment]
_From @DoomHammer on April 7, 2016 8:16_

Some of them might just be "standard" Perl libs as I see them on a Linux box as well.

**Comment by DoomHammer** [comment]
What about Python? We already know about `setuptools`, what else?

**Comment by sjackman** [comment]
That's the only one that I've run into so far that's required by Linuxbrew.

**Comment by DoomHammer** [comment]
OK, I have a hackish but almost-working prototype. Question is: should such `perl` modules be available on Linuxbrew as a separate formula or be a part of `perl` itself (eg. `--with-modules`)?

**Comment by sjackman** [comment]
I guess it would be nice if `brew install perl` also included all the modules that were expected by Linuxbrew/Homebrew to be installed. I could see `postinstall` installing these formula on Linux. I'd like to restrict the list of installed modules to those that fix actual observed build failures.

**Comment by DoomHammer** [comment]
So, do we have a list of those? :)

**Comment by sjackman** [comment]
Yep! Top of this page. Just one package for each `perl` and `python` so far.

**Comment by sjackman** [comment]
I've added `matplotlib` and `numpy` to Python and `Moo` and `List::MoreUtils` to Perl.
The Python deps are common requirements of science formula.
The Perl deps are for https://github.com/Linuxbrew/homebrew-science/pull/142

**Comment by DoomHammer** [comment]
Wait, does it mean every Mac comes with `numpy` installed?

**Comment by sjackman** [comment]
Yep, at least the last three releases of Mac OS. Previously, no.

**Comment by sjackman** [comment]
I have closed this issue because it has not had recent activity.
