### ISSUE TITLE
How to install from a downloaded package?

### ISSUE THREAD

**Issue by fuzihaofzh** [Linuxbrew/brew#60]
I am using linux brew, but it seems the network seems unstable. So I downloaded the zip package by hand, and want to know how to make linux brew install it automatically.

**Comment by sjackman** [comment]
Which software are you trying to install? What's the URL of the package that you downloaded? What command did you run? What error message did it give you?

**Comment by fuzihaofzh** [comment]
I want to install opencv, because I'm in China, so some url cannot connect directly. No error message, Just have no speed.

**Comment by DoomHammer** [comment]
A workaround for sure, but you may try moving the file to `$HOME/.cache/Homebrew` and try `brew install opencv` then.

A wild idea @sjackman: `brew` subcommand that would take a tarball as a parameter, find out if it has an appropriate formula for that tarball and install it then?

**Comment by sjackman** [comment]
An interesting idea… yes. Hmm. There's not much of a use case though, outside of this one.
@maplewizard 
As Piotr suggested, move the tarball that you downloaded to the location and name specified by

``` sh
brew --cache opencv
```

Then run

``` sh
brew install opencv
```
