### ISSUE TITLE
Newbie question: Does linuxbrew use the same formula as mac os x brew?

### ISSUE THREAD

**Issue by ipstone** [Linuxbrew/brew#601]
Hi folks, linux brew is very cool - one newbie question I couldn't find a quick answer, is that whether linux brew uses the same formula as homebrew. If not, then we are just another package manager? (perhaps source code manager/compiler etc.)

Thanks,
Isaac

**Comment by sjackman** [comment]
Yes, Linuxbrew uses the same formulae as Homebrew, with some patches. Homebrew/core is merged into Linuxbrew/core daily.
