### ISSUE TITLE
linuxbrew must use vendor-ruby?

### ISSUE THREAD

**Issue by okhowang** [Linuxbrew/brew#602]
i got below after brew update
```
which: no ruby in (/usr/bin:/bin:/usr/sbin:/sbin)
Error: Cannot find a vendored version of ruby for your i686
processor on Linuxbrew!
Error: Failed to install vendor Ruby.
```
i found that it relate to `Library/Homebrew/utils/ruby.sh`
if there is no vendor-ruby then install vendor-ruby
but there is no vendor-ruby for x86
or
should i set `HOMEBREW_DEVELOPER=1` and set `HOMEBREW_RUBY_PATH` manually

**Comment by sjackman** [comment]
Linuxbrew doesn't officially support 32-bit x86. It should be possible to get it up and running without too much trouble, if you're willing to do some work. Linuxbrew can use any Ruby in your PATH if it's version 2.3.3 or greater. You can also set `HOMEBREW_RUBY_PATH` as you mentioned.
Just for my curiosity, what type of system are your running with a 32-bit x86 processor?

**Comment by okhowang** [comment]
i have ruby in my path, but according to ruby.sh, my ruby will not be used.
my system is suse10

**Comment by sjackman** [comment]
Try setting `export HOMEBREW_NO_ENV_FILTERING=1`. It may ignore your `PATH` otherwise. `HOMEBREW_RUBY_PATH` is your best bet though.
