### ISSUE TITLE
test-bot issue

### ISSUE THREAD

**Issue by randy3k** [Linuxbrew/brew#606]
Please forgive me if it is not the right place for asking questions related to `test-bot`.
(the issue tab of `homebrew-test-bot` is disabled)

It is about running `test-bot` for my formula [rstudio-server](https://github.com/randy3k/homebrew-rstudio-server). I was trying to run `test-bot` on circle-ci for it and circle-ci reported [this error](https://circleci.com/gh/randy3k/homebrew-rstudio-server/157)

```
==> brew readall --aliases randy3k/rstudio-server
==> brew uses randy3k/rstudio-server/rstudio-server
.
Error: No available formula with the name "linuxbrew/extra/linux-pam" 
Please tap it and then try again: brew tap linuxbrew/extra
Exited with code 1
```

`linuxbrew/extra/linux-pam` is one of the dependencies of `rstudio-server`
https://github.com/randy3k/homebrew-rstudio-server/blob/b355b3861b89cee8bafa3a6413d55d179db75544/rstudio-server.rb#L22

I also tried adding `brew tap linuxbrew/extra` before `brew test-bot`. But it seems that `test-bot` would untap any additional taps at first.

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-test-bot#74
