### ISSUE TITLE
Bottle dependencies not handled correctly when main formula installed from source

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/brew#61]
# Please follow the general troubleshooting steps first:
- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

On a clean `linuxbrew/linuxbrew` Docker image running `brew install --build-from-source glibc` fails as bottles has not been relocated properly. This happens as `patchelf` is unavailable on such system.

Output:

```
==> Installing dependencies for glibc: zlib, binutils, linux-headers
==> Installing glibc dependency: zlib
==> Downloading http://zlib.net/zlib-1.2.8.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.8
==> make install
/home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.8: 11 files, 395.9K, built in 37 seconds
==> Installing glibc dependency: binutils
==> Downloading http://ftpmirror.gnu.org/binutils/binutils-2.26.tar.gz
==> Downloading from http://ftp.task.gda.pl/pub/gnu/binutils/binutils-2.26.tar.gz
######################################################################## 100.0%
==> ./configure  --with-sysroot=/ --prefix=/home/linuxbrew/.linuxbrew/Cellar/binutils/2.26 --infodir=/home/linuxbrew/.linuxbrew/Cellar/binutils/2.26/share/info --mandir=/home/lin
==> make
==> make install
/home/linuxbrew/.linuxbrew/Cellar/binutils/2.26: 3,178 files, 192.4M, built in 10 minutes 20 seconds
==> Installing glibc dependency: linux-headers
==> Downloading https://cdn.kernel.org/pub/linux/kernel/v3.x/linux-3.18.27.tar.gz
######################################################################## 100.0%
==> make headers_install INSTALL_HDR_PATH=/home/linuxbrew/.linuxbrew/Cellar/linux-headers/3.18.27
/home/linuxbrew/.linuxbrew/Cellar/linux-headers/3.18.27: 742 files, 3.5M, built in 1 minute 57 seconds
==> Installing glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
==> Downloading from http://ftp.task.gda.pl/pub/gnu/glibc/glibc-2.19.tar.bz2
######################################################################## 100.0%
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cellar/glibc/2.19 --enable-obsolete-rpc --without-selinu
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/glibc/01.configure:
checking for gnumake... no
checking for gmake... no
checking for make... make
checking version of make... 3.81, ok
checking for gnumsgfmt... no
checking for gmsgfmt... no
checking for msgfmt... no
checking for makeinfo... no
checking for sed... sed
checking version of sed... 4.2.2, ok
checking for gawk... no
checking for nm... nm
configure: error: 
*** These critical programs are missing or too old: gawk
*** Check the INSTALL file for required versions.
```

**Comment by sjackman** [comment]
Are you looking at the `gawk` error here, or a different error? Are you concerned that `patchelf` hasn't been installed?

**Comment by DoomHammer** [comment]
It doesn't matter what do you want to install. If you only use `--build-from-source` `patchelf` is not installed and therefore all bottled formulae fail to install correctly.

**Comment by sjackman** [comment]
The behaviour of `--build-from-source` changed recently. It used to install the formula and its dependencies from source. Now bottles of the dependencies are installed, but the formula listed on the command line are installed from source. It seems that we have to fix the Linuxbrew logic to account for this change. You can instead use `HOMEBREW_BUILD_FROM_SOURCE=1` which install both dependencies and the requested formula from source. See `brew install --help`

**Comment by DoomHammer** [comment]
I know how to work around this, but thanks for the tips anyway :)

By submitting this issue I wanted to document a bug in Linuxbrew logic that may hit other users but is probably (I hope so) not very hard to fix. Somehow when `--build-from-source` is present `patchelf` is not installed. Question remains: why?

Didn't have time to further investigate it, but thought maybe you have some rough ideas where the problem may lie?

**Comment by sjackman** [comment]
Thanks for the documenting the bug, Piotr. The relevant function is `bottle_dependencies` at https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/formula_installer.rb#L398

It is supposed to be triggered if the formula being installed or any of its dependencies are installed from bottle.

**Comment by sjackman** [comment]
The above log doesn't show any dependencies being poured, so `patchelf` won't be installed. Do you have an example where a dependency is poured, but `patchelf` is not installed?

**Comment by DoomHammer** [comment]
Ha, you are right. This is not the log file we are looking for. I must have posted wrong one, silly me.

**Comment by DoomHammer** [comment]
Cannot reproduce anymore. Guess it's good, then.
