### ISSUE TITLE
inconsistent "super" environment: system locale in path instead of brew locale

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/brew#622]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
>- [x] Confirmed this is a problem with running a `brew` command and not `brew install`ing or the post-install behaviour of one or more formulae? If it's a formulae-specific problem please file this issue at the relevant tap e.g. for Linuxbrew/homebrew-core https://github.com/Linuxbrew/homebrew-core/issues/new

Actually, this could be construed as a homebrew-core issue, but it's not. If the "super" environment were configured with the brewed `locale` to be in the `PATH`, `brew install pcre` would not fail. The issue is that the system locale (in my case) has the fr_FR (french) locale but the brewed locale does not. The `make test` part of the pcre build sees the fr_FR available and attempts to use it with setlocale(3) in pcretest.c and fails because the brewed glibc does not actually have the fr_FR locale. 
- [x] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed all issues and retried your prior step?
- [ ] Ran `brew config` and `brew doctor` and included their output with your issue?

>To help us debug your issue please explain:
>- What you were trying to do (and why)

`brew install pcre`
>- What happened (include command output)
```
==> make test
make  check-am
make[1]: Entering directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make  
make[2]: Entering directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make  all-am
make[3]: Entering directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make[3]: Leaving directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make[2]: Leaving directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make  check-TESTS
make[2]: Entering directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make[3]: Entering directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
PASS: pcre_jit_test
PASS: pcrecpp_unittest
PASS: pcre_scanner_unittest
PASS: pcre_stringpiece_unittest
FAIL: RunTest
PASS: RunGrepTest
============================================================================
Testsuite summary for PCRE 8.41
============================================================================
# TOTAL: 6
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/tmp/pcre-20180222-14866-1lpw4oj/pcre-8.41'
make: *** [check] Error 2
```
```
> cat RunTest.log
...
Test 3: Locale-specific features (using 'fr_FR' locale)
** Locale test did not run successfully. The output did not match
   ./testdata/testoutput3, ./testdata/testoutput3A or ./testdata/testoutput3B.
   This may mean that there is a problem with the locale settings rather
   than a bug in PCRE.
FAIL RunTest (exit status: 1)
```
>- What you expected to happen
>- Step-by-step reproduction instructions (by running `brew` commands)

To work around this, I `brew install`ed with `--env=std` so that the brew locale would appear in the PATH.

To fix this permanently should we create a locale shim or something like that?

**Comment by sjackman** [comment]
I believe this issue is a bug in Linuxbrew. A possible workaround may be…
```sh
HOMEBREW_NO_ENV_FILTERING=1 brew postinstall glibc
brew install pcre
```

**Comment by sjackman** [comment]
I believe this issue is still relevant.
