### ISSUE TITLE
Question: How to prefer brewed perl when building from source?

### ISSUE THREAD

**Issue by carlorosati** [Linuxbrew/brew#623]
I am having trouble building intltool from source on a system without XML::Parser installed. 

Now I have tried using  --env=std and HOMEBREW_NO_ENV_FILTERING=1 to prefer the brewed perl but no matter what combination of --env={std,super} with/without HOMEBREW_NO_ENV_FILTERING I use, the system bin directories are always put before brew in the PATH. 

Is this possible? Or do I have to modify the brew source code?

**Comment by sjackman** [comment]
As a workaround try `brew edit intltool` and add `depends_on "perl"`. Alternatively edit the following line and add `perl` to this list. https://github.com/Linuxbrew/brew/blob/eda9e367ae8d2da4b0cd998e6e4a2ec216b642be/Library/Homebrew/extend/os/linux/extend/ENV/super.rb#L19
@iMichka Is `perl` a build dep or run-time dep of `intltool`?

**Comment by denis-sumin** [comment]
> As a workaround try `brew edit intltool` and add `depends_on "perl"`

Didn't help

> Alternatively edit the following line and add `perl` to this list.

After doing this, brew started to complain about old `intltool`:
```
checking for intltool >= 0.40.0...  found
configure: error: Your intltool is too old.  You need intltool 0.40.0 or later.
```
Although both system and brew intltoolize are 0.5.x

**Comment by sjackman** [comment]
> I am having trouble building intltool from source on a system without XML::Parser installed.

There's a relocatable bottle for `intltool`. Why are you building it from source? I'd suggest installing the precompiled bottle with `brew install intltool`

**Comment by carlorosati** [comment]
I'll have to try, but I was having some issues with linking issues and I kept having to manually patchelf the brew library path and the interpreter into every shared object. I figured I'd try from source so I wouldn't have such problems. I can't install in the home dir due to quota limitations.

**Comment by sjackman** [comment]
> I kept having to manually patchelf the brew library path and the interpreter into every shared object.

That shouldn't happen.

> I can't install in the home dir due to quota limitations.

Although `/home/linuxbrew/.linuxbrew` is preferred, any directory is fine.
