### ISSUE TITLE
Error:  Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/brew#635]
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
```$ brew search <formula>```
- What happened (include command output)
```
$ brew search <formula>
==> Searching local taps...
<formula>
==> Searching taps on GitHub...
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes they need: none
Scopes it has:
Create a new personal access token: https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: curl failed!
curl: (35) SSL connect error
curl: (3) <url> malformed
```
- What you expected to happen
```$ brew search <formula>``` has always worked in the past with my the token that I am using for Linuxbrew. Has github changed the scope requirements for this type of query? My token has all in the "repo" section checked and "gist" checked. This should be sufficient, and I'm really confused by the output ```Scopes they need: none```.
- Step-by-step reproduction instructions (by running `brew` commands)
```$ brew search <formula>```

```
$ brew config
HOMEBREW_VERSION: 1.5.7-1-g312344f
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 312344fa067247c2ea7490364fc5a5b727bf455f
Last commit: 18 minutes ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 8c3ca23d255a2f734f8257c90ccabcbbb3fec3d8
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LOGS: /home/linuxbrew/.logs/Homebrew
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_RUBY_WARNINGS: -W0
HOMEBREW_TEMP: /home/linuxbrew/.temp
HOMEBREW_VISUAL: /usr/bin/env vim
CPU: octa-core 64-bit merom
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 5.0 build
Git: 2.16.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.19.7 => /usr/bin/curl
Perl: /home/linuxbrew/.linuxbrew/bin/perl => /home/linuxbrew/.linuxbrew/Cellar/perl/5.26.1_1/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/2.7.14_5/bin/python2.7
Ruby: /home/linuxbrew/.linuxbrew/bin/ruby => /home/linuxbrew/.linuxbrew/Cellar/ruby/2.5.0_2/bin/ruby
Java: N/A
Kernel: Linux 2.6.32-504.el6.x86_64 x86_64 GNU/Linux
OS: Red Hat Enterprise Linux Server release 6.6 (Santiago) (Santiago)
Host glibc: 2.12
/usr/bin/gcc: 4.4.7
glibc: 2.23
gcc: 5.5.0_1
xorg: 20170115_1
```

```
$ brew dr
Your system is ready to brew.
```

**Comment by sjackman** [comment]
I believe `HOMEBREW_GITHUB_API_TOKEN` needs no privileges at all for `brew search`, since it's searching public data. It's only being used as an identifier. Perhaps your token has somehow expired or been invalidated. I suggest creating a new token.

**Comment by maxim-belkin** [comment]
It says right there:
> Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes they need: none
Scopes it has:
Create a new personal access token: https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.

**Comment by sjackman** [comment]
It does give instructions on how to create a new token. It's not clear to me or James why the previous token no longer works.

**Comment by maxim-belkin** [comment]
This might be an intermittent issue:

> Error: curl failed!
curl: (35) SSL connect error
curl: (3) <url> malformed

I can make `curl` fail only if I disconnect from the internet completely but even then it gives me `Could not resolve host: api.github.com` and not `SSL connect error`

**Comment by sjackman** [comment]
`SSL connect error` may be due to your host system's `curl` being too old. Please report…
```sh
which -a curl
curl --version
/usr/bin/curl --version
```
and try
```sh
export HOMEBREW_FORCE_BREWED_CURL=1
brew search foo
```

**Comment by maxim-belkin** [comment]
But https://github.com/Linuxbrew/brew/issues/635#issue-302420174
> Curl: 7.19.7 => /usr/bin/curl

**Comment by sjackman** [comment]
Is that new enough? Curl versions 7.29.0 on CentOS 7.4 and 7.43.0 on macOS 10.11 El Capitan work for me, assuming that `brew search` is using the host `curl`, which I believe it is.

**Comment by maxim-belkin** [comment]
> Is that new enough?

It's pretty young - only 9 y.o.! From: https://curl.haxx.se/changes.html
> 7.19.7 - November 4 2009

**Comment by sjackman** [comment]
Hah. I suspect that's the root cause of the problem then. The real problem is probably that OpenSSL is too old. These versions work for me:
```
❯❯❯ /usr/bin/curl --version
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.28.4 zlib/1.2.7 libidn/1.28 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets
❯❯❯ /usr/bin/openssl <<<version
OpenSSL> OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by maxim-belkin** [comment]
we need a test for this.

**Comment by sjackman** [comment]
Agreed. We first need to figure out which version of `curl` and/or `openssl` does / does not work.

**Comment by sjackman** [comment]
@jwhite007 Please report…
```
/usr/bin/openssl <<<version
/usr/bin/curl --version
/usr/bin/curl --sslv2
/usr/bin/curl --sslv3
/usr/bin/curl --tlsv1.0 --tlsv1.1 --tlsv1.2 --tlsv1.3
```

**Comment by jwhite007** [comment]
Ok. ```$ export HOMEBREW_FORCE_BREWED_CURL=1``` fixed it which is weird. The system brew has not changed, and shouldn't brewed curl be used anyhow?
```
$ brew search miniconda
==> Searching local taps...
==> Searching taps on GitHub...
Error: Your HOMEBREW_GITHUB_API_TOKEN does not have sufficient scope!
Scopes they need: none
Scopes it has:
Create a new personal access token: https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
and then set the new HOMEBREW_GITHUB_API_TOKEN as the authentication method instead.
Error: curl failed!
curl: (35) SSL connect error
curl: (3) <url> malformed
```

```
$ which -a curl
/home/linuxbrew/.linuxbrew/bin/curl
/usr/bin/curl

$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.0.2n zlib/1.2.11
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy

$ /usr/bin/curl --version
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.15.3 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz
```

```
$ export HOMEBREW_FORCE_BREWED_CURL=1
```

```
$ brew info miniconda
Error: No available formula with the name "miniconda"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
```

**Comment by sjackman** [comment]
> The system brew has not changed, and shouldn't brewed curl be used anyhow?

This behaviour changed recently as we're trying to merge Homebrew/brew and Linuxbrew/brew together into a single repo. It's supposed to detect whether the host curl is new enough, and use it if so. That's not working in this case.

**Comment by sjackman** [comment]
@jwhite007 Please report…
```
/usr/bin/openssl <<<version
/usr/bin/curl --sslv2
/usr/bin/curl --sslv3
/usr/bin/curl --tlsv1.0 --tlsv1.1 --tlsv1.2 --tlsv1.3
```

**Comment by jwhite007** [comment]
@sjackman 

```
$ /usr/bin/openssl version
OpenSSL 1.0.1e-fips 11 Feb 2013
```
```
$ /usr/bin/curl --sslv2
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```
```
$ /usr/bin/curl --sslv3
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```
```
$ /usr/bin/curl --tlsv1.0 --tlsv1.1 --tlsv1.2 --tlsv1.3
curl: option --tlsv1.0: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by sjackman** [comment]
Hmm. I was hoping that it was something as easy as `--sslv3` not being supported, but that doesn't seem to be the case, since it does appear to be supported. Perhaps the CA Certs are out of date.

**Comment by maxim-belkin** [comment]
@jwhite007 could you please also report (just in case...):

    $ /usr/bin/curl --tlsv1.1
    $ /usr/bin/curl --tlsv1.2
    $ /usr/bin/curl --tlsv1.3

**Comment by jwhite007** [comment]
@maxim-belkin same output as when all three flags are used at once.

**Comment by jwhite007** [comment]
@maxim-belkin 

```
$ /usr/bin/curl --tlsv1.1
curl: option --tlsv1.1: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

```
$ /usr/bin/curl --tlsv1.2
curl: option --tlsv1.2: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

```
$ /usr/bin/curl --tlsv1.3
curl: option --tlsv1.3: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by maxim-belkin** [comment]
thank you very much!

**Comment by sjackman** [comment]
Perhaps this is related
Weak cryptographic standards removed
https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/
and https://github.com/Homebrew/brew/pull/3837

**Comment by mbinge** [comment]
you could try https://gitlab.com/davidjpeacock/kurly.git to replace curl by default
