### ISSUE TITLE
brew doctor complains of untracked assets in /usr/local/include and /usr/local/lib

### ISSUE THREAD

**Issue by rjray** [Linuxbrew/brew#638]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [ x] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew config` and `brew doctor` and included their output with your issue?

Upon installing linuxbrew, the first thing I ran was "brew doctor". I get the following output:

```
Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/xar/xar.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libxar.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
  /usr/local/lib/libxar.a
```

This seems odd, since I've installed linuxbrew under /home/linuxbrew/.linuxbrew.

Output from "brew config":

```
HOMEBREW_VERSION: 1.5.8
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 0da98e625677eeff4b772be3508d9528e56ca686
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 5276527244d7a00fcaa81d2d751e7d6077521aa4
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/rjray/.cache/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_RUBY_WARNINGS: -W0
CPU: 12-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 1.9.1 => /usr/bin/git
Curl: 7.35.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: N/A
Kernel: Linux 3.13.0-141-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.5 LTS (trusty)
Host glibc: 2.19
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_1
xorg: N/A
```

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by rjray** [comment]
Sorry, my mistake. Fixed.

**Comment by sjackman** [comment]
This behaviour is intentional. Header files and library files in `/usr/local` can muddle up and get confused with brewed versions of the same libraries. It's best not to install anything in `/usr/local` if possible. `brew doctor` is only a warning. You can ignore it if you like, if your system is working fine for you.
