### ISSUE TITLE
analytics enabling during update: invalid git option "--local" (old git version)

### ISSUE THREAD

**Issue by draeath** [Linuxbrew/brew#639]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue? (brew is busy with a long compile, referenced current checkout hash below. brew doctor reports no issues)

brew version: 0da98e6 (branch" stable)

Even with git installed via brew (so theoretically up to date), whenever brew update is run on our RHEL6 environment git reports back the following error output:

    Updating Homebrew...
    ==> Homebrew has enabled anonymous aggregate user behaviour analytics.
    Read the analytics documentation (and how to opt-out) here:
      https://docs.brew.sh/Analytics
    
    error: unknown option `local'
    usage: git config [options]
    
    Config file location
        --global              use global config file
        --system              use system config file
        -f, --file <FILE>     use given config file
    
    Action
        --get                 get value: name [value-regex]
        --get-all             get all values: key [value-regex]
        --get-regexp          get values for regexp: name-regex [value-regex]
        --replace-all         replace all matching variables: name value [value_regex]
        --add                 adds a new variable: name value
        --unset               removes a variable: name [value-regex]
        --unset-all           removes all matches: name [value-regex]
        --rename-section      rename section: old-name new-name
        --remove-section      remove a section: name
        -l, --list            list all
        -e, --edit            opens an editor
        --get-color <slot>    find the color configured: [default]
        --get-colorbool <slot>
                              find the color setting: [stdout-is-tty]
    
    Type
        --bool                value is "true" or "false"
        --int                 value is decimal number
        --bool-or-int         value is --bool or --int
        --path                value is a path (file or directory name)
    
    Other
        -z, --null            terminate values with NUL byte
    
    Error: Failure while executing: git config --local --replace-all homebrew.analyticsmessage true

This is due to two quirks:
* during this process the system's git is used, and not the brew-installed git (if installed).
* RHEL6's git is sufficiently old that the `--local` argument doesn't exist.

I suggest instead of `--local`, `--file` should be used, and pointed at the `.git/gitconfig` file specifically. This is forwards-compatible with modern versions of git, and requires the least amount of change to implement.

**Comment by draeath** [comment]
Commenting to defer the stalebot.

**Comment by jhdub23** [comment]
I ran into git issues during installation, as well, and found that you can set the `GIT` environment variable to force brew to use the updated git.

**Comment by sjackman** [comment]
Thanks for the tip. I didn't know about that feature of the installer. See https://github.com/Linuxbrew/install/blob/04a18ba610d087d8b3a0662ad65f18d7361ae85d/install#L154
