### ISSUE TITLE
Keep access to system manual files (setting MANPATH)

### ISSUE THREAD

**Issue by azrdev** [Linuxbrew/brew#65]
The README says you should add to your profile `export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"`
This makes all the previous manual pages inaccessible, see http://askubuntu.com/a/693612
The solution is to add `:` at the beginning of the MANPATH variable.

Dunno if the same holds true for `INFOPATH`.

**Comment by sjackman** [comment]
Thanks for the tip! I'll move the colon to the end. I think that has a similar effect but will give priority to Linuxbrew man pages.

**Comment by sjackman** [comment]
Fixed. Thanks for the bug report!

**Comment by bw-yuhogg** [comment]
I've filed a PR (shown right above this comment) to also fix this in the installation script.

**Comment by azrdev** [comment]
> Thanks for the tip! I'll move the colon to the end. I think that has a similar effect but will give priority to Linuxbrew man pages.

This seems to do exactly as you wish.

Thx for fixing!

**Comment by maxim-belkin** [comment]
I'm not sure I understand the problem. Let's have a look at what the default export statement (`export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"`) does in the two possible situations.

(1) MANPATH is empty.
Then `MANPATH="$HOME/.linuxbrew/share/man:` &mdash; that is with the desired colon at the end.

(2) MANPATH is not empty.
Then `MANPATH="$HOME/.linuxbrew/share/man:$MANPATH`, that is linuxbrew's path is prepended to whatever MANPATH has been previously set.

So, I'm not sure that this change is necessary.

**Comment by sjackman** [comment]
@azrdev Please report…

``` sh
echo x"$MANPATH"x
echo x"$HOME/.linuxbrew/share/man:$MANPATH"x
```

**Comment by azrdev** [comment]
You're right, I didn't consider the case when MANPATH is empty before. However, a MANPATH starting or ending with `::` seems to yield the same result as (the standard) single `:`.

> (2) MANPATH is not empty.
> Then `MANPATH="$HOME/.linuxbrew/share/man:$MANPATH`, that is linuxbrew's path is prepended to whatever MANPATH has been previously set.

We need the colon at one end, for system manpages to be considered (see http://askubuntu.com/a/693612). You're assuming here whoever might have set MANPATH before should have appended the colon at the end, so brew shouldn't care about doing it?

**Comment by maxim-belkin** [comment]
Users can set MANPATH so we have no right to assume that what they did with it was wrong or unintentional. Previous behavior was correct because it was only adding Linuxbrew's manpath, it was not overriding it.

**Comment by sjackman** [comment]
@azrdev Do you have an example where the previous code did not have the expected or desired behaviour?

**Comment by azrdev** [comment]
@sjackman quoting from my first comment here:

> The README says you should add to your profile export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
> This makes all the previous manual pages inaccessible

Actually, this is correct for both cases: (1) previously empty -> colon at the end. (2) previously set correctly (with colon at the end) -> still colon at the end.

The case it breaks is if it previously had a colon (only) at the beginning, or none at all. This might be intended by the user, but I assume most users expect less complexity. I was confused when setting MANPATH did hide the system files, even though the default value was empty. So at least a warning & explanation would be helpful at this point.

**Comment by maxim-belkin** [comment]
When colon is at the beginning of MANPATH, the end result of the previous change would be:
`MANPATH=$HOME/.linuxbrew/share/man::OTHER:PATHS`. Note the two colons there. Because environment variables are split based on colons, this MANPATH means that the following directories are included:
1.  $HOME/.linuxbrew/share/man
2. `<empty>`
3. OTHER
4. PATHS

The second (`<empty>`) directory makes sure that default man pages are searched.

**Comment by sjackman** [comment]
Hi, @azrdev. I'm not able to duplicate the failure that you describe with a colon only at the beginning. Can you please give an exact example? The following works for me.

``` sh
$ export MANPATH=:$HOME/man
$ echo $MANPATH
:/home/sjackman/man
$ man -w ab # some man page provided by host but not by Linuxbrew
/usr/share/man/man1/ab.1.gz
$ MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
$ echo $MANPATH
/home/sjackman/.linuxbrew/share/man::/home/sjackman/man
$ man -w ab
/usr/share/man/man1/ab.1.gz
```

So as Maxim points out, you can have a colon at the beginning or at the end, or a double colon in the middle, and it will still search the system `MANPATH`.

**Comment by azrdev** [comment]
> So as Maxim points out, you can have a colon at the beginning or at the end, or a double colon in the middle, and it will still search the system MANPATH.

Confirmed by looking at `man 1 manpath`, so I was wrong again. I didn't know, just relied on said askubuntu link. :)

As it stands there was never a bug, only a pitfall we could (imho should) warn the user of.

**Comment by sjackman** [comment]
No worries. Glad we sorted it out. I've reverted both commits (`brew` and `install`).
