### ISSUE TITLE
Crash on upgrade

### ISSUE THREAD

**Issue by thedrow** [Linuxbrew/brew#654]
# Please fill out the issue checklist below, and provide all of the requested information.

# Please always follow these steps:
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [] ran `brew doctor`, fixed all issues and can still reproduce the problem? I don't want linuxbrew's bin path before my own /usr/bin/.
- [x] ran `brew config` and `brew doctor` and included their output with your issue?
HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: cfdfb7edf3a1ac1ef3cc3620fe20562f2ac09c32
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 118366aedb5646fcb8e2e4dacc26a79d4a6e4d8e
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/omer/.cache/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_RUBY_WARNINGS: -W0
CPU: octa-core 64-bit 0x69e
Homebrew Ruby: 2.3.3 => /usr/bin/ruby2.3
Clang: 4.0 build 
Git: 2.16.2 => /usr/bin/git
Curl: 7.55.1 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /home/linuxbrew/.linuxbrew/opt/python/libexec/bin/python => /home/linuxbrew/.linuxbrew/Cellar/python/3.6.4_5/bin/python3.6
Ruby: /usr/bin/ruby => /usr/bin/ruby2.3
Java: N/A
Kernel: Linux 4.13.0-37-generic x86_64 GNU/Linux
OS: Ubuntu 17.10 (artful)
Host glibc: 2.26
/usr/bin/gcc: 7.2.0
glibc: N/A
gcc: 5.5.0_3
xorg: 20170115_1

/usr/bin occurs before /home/linuxbrew/.linuxbrew/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:
  zipgrep
  captoinfo
  javah
  glib-compile-schemas
  gettext
  setarch
  python2.7
  cpp
  pod2usage
  gencnval
  xzegrep
  xzless
  rmic
  podselect
  java
  x86_64
  renice
  rmid
  setsid
  autoconf
  python3.6-config
  gcc
  png-fix-itxt
  python3.6
  addr2line
  appletviewer
  xz
  msguniq
  lzcat
  xml2-config
  dwp
  tset
  derb
  xjc
  pcre-config
  lslocks
  funzip
  unshare
  jinfo
  linux32
  curl
  uuidgen
  msgcomm
  jrunscript
  objdump
  python2-config
  ipcrm
  fc-scan
  ld.bfd
  tic
  python3.6m-config
  i386
  flex++
  gold
  unzipsfx
  javapackager
  c_rehash
  fc-cache
  h2ph
  json_pp
  gapplication
  genbrk
  jstatd
  lsipc
  cpan
  msgconv
  lastb
  h2xs
  python3.6m
  infotocap
  gio-querymodules
  msginit
  xgettext
  gio
  setterm
  python2.7-config
  msgexec
  docker
  jhsdb
  msgen
  autopoint
  autoreconf
  jlink
  reset
  libpng16-config
  freetype-config
  nsenter
  gprof
  bison
  cpack
  readelf
  msgattrib
  msgcat
  c++filt
  ionice
  dialog
  autom4te
  javadoc
  gsettings
  nm
  javaws
  script
  xzfgrep
  gencfu
  autoupdate
  jcmd
  makeconv
  logger
  fc-pattern
  jmap
  msgcmp
  schemagen
  pydoc3.6
  ctest
  xzcmp
  lzmore
  perlthanks
  jstack
  getopt
  g++
  tabs
  cc
  xsltproc
  ld
  msgunfmt
  fallocate
  jarsigner
  msgfilter
  jweblauncher
  easy_install
  wsgen
  xzgrep
  utmpdump
  ipcs
  automake
  gettext.sh
  namei
  python2
  toe
  fc-query
  pod2text
  idlj
  ifnames
  python-config
  unzip
  yacc
  genrb
  jdeprscan
  mcookie
  cmake
  jimage
  objcopy
  fc-validate
  pkgdata
  lsmem
  lsns
  rev
  ptar
  jar
  lzma
  ar
  lzmainfo
  javap
  xmllint
  jjs
  perlivp
  gdbus
  strings
  prove
  orbd
  perl
  rmiregistry
  lscpu
  msggrep
  envsubst
  msgfmt
  lex
  gendict
  autoheader
  zipdetails
  fc-cat
  xsubpp
  lzless
  unxz
  curl-config
  servertool
  javac
  unlzma
  ptargrep
  fc-list
  lzgrep
  podchecker
  lzdiff
  taskset
  fc-match
  xzcat
  zipinfo
  2to3-3.6
  pydoc3
  infocmp
  ptardiff
  m4
  libpng-config
  elfedit
  openssl
  chmem
  scriptreplay
  pkg-config
  jq
  size
  wsimport
  python3
  lzcmp
  strip
  jaotc
  eject
  chrt
  icu-config
  instmodsh
  jcontrol
  tificc
  pngfix
  lzfgrep
  transicc
  clear
  xdpyinfo
  update-mime-database
  last
  autoscan
  ld.gold
  ngettext
  msgmerge
  linkicc
  pod2html
  gdk-pixbuf-thumbnailer
  python3-config
  libnetcfg
  jdeps
  serialver
  flex
  jps
  xmlcatalog
  prlimit
  wish8.6
  tclsh8.6
  c++
  gettextize
  piconv
  enc2xs
  uconv
  ipcmk
  encguess
  shasum
  gresource
  jstat
  lslogins
  jpgicc
  mesg
  python
  jmod
  pack200
  perlbug
  glib-compile-resources
  aclocal
  brew
  unpack200
  pl2pm
  linux64
  tnameserv
  recode-sr-latin
  splain
  ranlib
  keytool
  corelist
  psicc
  whereis
  jdb
  as
  flock
  wish
  policytool
  lzegrep
  jshell
  pod2man
  perldoc
  libtoolize
  xzdiff
  wall
  pydoc
  xzmore
  tput
  jconsole
  icuinfo
  jmc
  tclsh

Consider setting your PATH so that /home/linuxbrew/.linuxbrew/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"' >> ~/.bash_profile

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /home/linuxbrew/.linuxbrew/sbin.
Consider setting the PATH for example like so
  echo 'export PATH="/home/linuxbrew/.linuxbrew/sbin:$PATH"' >> ~/.bash_profile

To help us debug your issue please explain:
- What you were trying to do (and why): Run brew upgrade
- What happened (include command output)
```
○ → brew upgrade
==> Upgrading 1 outdated package, with result:
pipenv 11.8.0
Error: undefined method `installed?' for OS::Mac::CLT:Module
Did you mean?  instance_of?
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python.rb:91:in `block (2 levels) in <class:Python>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:121:in `install_bottle_for?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:500:in `block in expand_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:109:in `block in action'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:107:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:107:in `action'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:86:in `block in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:83:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:83:in `expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:494:in `expand_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:381:in `compute_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:136:in `verify_deps_exist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:129:in `prelude'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:128:in `upgrade_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:84:in `block in upgrade'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:81:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/upgrade.rb:81:in `upgrade'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```
- What you expected to happen
Upgrade should complete.
- Step-by-step reproduction instructions (by running `brew` commands)
brew upgrade

**Comment by thedrow** [comment]
Note that this reproduces with multiple formulas.

**Comment by thedrow** [comment]
A `git reset --hard` on the homebrew-core tap resolved the issue.

**Comment by iMichka** [comment]
If it is fixed for you, you may close this issue.
Not sure why it was in a broken state.

You can also run « brew update-reset », which does ans equivalent cleanup.

**Comment by axiac** [comment]
Neither `git reset --hard` nor `brew update-reset` solved the problem:

```
$ brew install -v node
Error: undefined method `installed?' for OS::Mac::CLT:Module
Did you mean?  instance_of?
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/python@2.rb:82:in `block (2 levels) in <class:PythonAT2>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:121:in `install_bottle_for?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:500:in `block in expand_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:109:in `block in action'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:107:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:107:in `action'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:86:in `block in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:83:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dependency.rb:83:in `expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:494:in `expand_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:381:in `compute_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:136:in `verify_deps_exist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:129:in `prelude'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:378:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:232:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:230:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:230:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by TiZ-HugLife** [comment]
This seems to be the same issue as what's still got me having problems in the aftermath of #652.

**Comment by sjackman** [comment]
Should be fixed now by https://github.com/Linuxbrew/brew/pull/655
