### ISSUE TITLE
dockerhub linuxbrew/linuxbrew the docker-compose example 

### ISSUE THREAD

**Issue by goooglethink** [Linuxbrew/brew#657]
https://hub.docker.com/r/linuxbrew/linuxbrew/

i can't find docker-compose , anyone can show the docker-compose example for linuxbrew/linuxbrew

i cannot not write :(

**Comment by sjackman** [comment]
I'm afraid that I don't understand your question. Here's the Docker-Compose `docker.test.yml` file:
https://github.com/Linuxbrew/brew/blob/master/docker.test.yml
