### ISSUE TITLE
curl is limited by superenv

### ISSUE THREAD

**Issue by bukzor** [Linuxbrew/brew#658]
Migrated from https://github.com/Homebrew/brew/issues/3947

I have a problem wherein I have curl installed but brew isn't using it. Looking at the code, brew falls back to `which("brew")` but that's not finding my curl because the superenv $PATH has already been set up. This leads to the curl shown by `brew config` not being the curl used by superenv, even though both are computed by [the same code](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/curl.rb#L4).

Should superenv use the curl that's shown by `brew config`? That seems to be the policy for other tools.

**Comment by sjackman** [comment]
Hi, Buck. Do you mean the `curl` used by `brew fetch`? `brew` will use `/usr/bin/curl` by default if it's available. We inherit this behaviour from Homebrew on macOS. Is that causing an error for you? If so, please post the command you ran and the error message. If you are getting an error `export HOMEBREW_FORCE_BREWED_CURL=1` would likely work around the issue.

**Comment by bukzor** [comment]
Yes. The command was `brew install hello`, the error was "no executable curl was found" while brew was trying to get the source tarball. There is no /usr/bin/curl on this machine, and `brew config` shows `Curl: 7.59.0 => /data/data/com.termux/files/home/prefix/brew/bin/curl` and `HOMEBREW_PREFIX: /data/data/com.termux/files/home/prefix/brew`.

```
$ brew install hello
==> Downloading https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
Error: no executable curl was found

$ brew config | grep -i curl
Curl: 7.59.0 => /data/data/com.termux/files/usr/bin/curl

$ which -a curl
/data/data/com.termux/files/usr/bin/curl
```

**Comment by sjackman** [comment]
That's a bug. Would you be up for submitting a PR upstream to Homebrew/brew? On a system without `/usr/bin/curl`, then `brew` should behave as though `HOMEBREW_FORCE_BREWED_CURL=1` is specified.

If you want to take it one step further, on a system where `/usr/bin/curl` is to old to communicate with GitHub (see https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/), it should also use brewed curl.

**Comment by bukzor** [comment]
Homebrew folk seemed pretty certain it was strictly a Linuxbrew bug, since osx will always have a /usr/bin/curl.

**Comment by sjackman** [comment]
`curl` is a pretty fundamental dependency of `brew`. It can't do pretty much anything without it. How did you get `brew` working on a system without `curl`? Did you download the bottles manually to the cache using `wget`?

**Comment by sjackman** [comment]
Ah you reported an issue upstream. The Homebrew maintainers don't troubleshoot Linux issues. They do accept PRs that address Linux issues.

**Comment by bukzor** [comment]
I haven't gotten it working yet :P  See https://github.com/Linuxbrew/brew/wiki/Android
How will `HOMEBREW_FORCE_BREWED_CURL=1` help a system that doesn't have curl?

How would everyone feel about a fourth fallback that uses non-superenv path search?

The system does have a (busybox) wget. Would wget support be acceptable?

**Comment by sjackman** [comment]
> How will HOMEBREW_FORCE_BREWED_CURL=1 help a system that doesn't have curl?

It really won't. It'll try to use `curl` to try to download `curl`. That won't work out so well. 😉

**Comment by sjackman** [comment]
> How would everyone feel about a fourth fallback that uses non-superenv path search?

I'd suggest fixing this logic to set `HOMEBREW_CURL` to the brewed curl when `/usr/bin/curl` is not executable.
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L129

**Comment by sjackman** [comment]
> The system does have a (busybox) wget. Would wget support be acceptable?

I'm not terribly keen to add support for `wget` to either Linuxbrew/brew or Homebrew/brew.
Here's the instructions to bootstrap Linuxbrew using `wget`:
https://github.com/Linuxbrew/brew/wiki/Bootstrap-with-wget
Note: the version numbers need to be updated. You can edit the wiki page yourself to do that.

I'd suggest adding those instructions to your Linuxbrew for Android installer instructions and script.

**Comment by bukzor** [comment]
> I'd suggest fixing this logic to set HOMEBREW_CURL to the brewed curl when /usr/bin/curl is not executable.
> https://github.com/Homebrew/brew/blob/master/Library/Homebrew/brew.sh#L129

Doesn't that have the same [chicken-and-egg problem](#issuecomment-374792381) as `HOMEBREW_FORCE_BREWED_CURL=1`? The scenario at hand is a system with no brewed curl and no /usr/bin/curl, but a perfectly serviceable curl in the (original, un-superenv'd) $PATH.

What if I split the [final fallback for curl](https://github.com/Homebrew/brew/blob/15f01bdd14f531ff33e451a81aed433653eaf4a1/Library/Homebrew/brew.sh#L135) into more cases: https://github.com/bukzor/brew/commit/48ebc9edfa2400088312f5d7f7d310bc08d39c9b

This does change the behavior, but only when 1) using osx 2) curl has been brewed and 3) FORCE_BREWED_CURL is unset. Where it would have used the brewed curl in that specific case, it would now use /usr/bin/curl.

---
Edit: From what I see of how FORCE_BREWED_CURL is used, the intent was to only used the bottled curl when the /usr/bin/curl was unworkable. If so, this change would bring things strictly closer to intended behavior, I believe.

**Comment by bukzor** [comment]
> Here's the instructions to bootstrap Linuxbrew using wget:
> https://github.com/Linuxbrew/brew/wiki/Bootstrap-with-wget
> I'd suggest adding those instructions to your Linuxbrew for Android installer instructions and script.

The strategy of using Linuxbrew bottles won't work. Android is sufficiently different from Linux that things will fail (e.g. the ld.so interpreter doesn't exist). Also, the two Android environments i'm developing with are both i686.

**Comment by sjackman** [comment]
> The strategy of using Linuxbrew bottles won't work.

Ah, rats. If you're sufficiently motivated, it could be possible to bottle just enough formulae for i686 to permit bootstrapping an Android system. The only non-x86_64 bottle that we have so far is a bottle of `portable-ruby` for 32-bit ARM, intended for Raspberry PI and phones.

**Comment by sjackman** [comment]
If you have `curl` in your `PATH`, you should be able to bootstrap a system with…

```sh
HOMEBREW_NO_ENV_FILTERING=1 HOMEBREW_FORCE_BREWED_CURL=1 brew install curl
```

After which you can use the brewed `curl`. That should work now.

**Comment by sjackman** [comment]
Checking both `/usr/bin/curl` and `command -pv curl` seems redundant to me. I think we could do just one or the other, either `-x "/usr/bin/curl"` or `command -pv curl`.
```
❯❯❯ command -pv curl
/usr/bin/curl
❯❯❯ command -v curl
/usr/local/bin/curl
```

https://github.com/bukzor/brew/commit/48ebc9edfa2400088312f5d7f7d310bc08d39c9b looks good to me. Thanks, Buck! Send it upstream to Homebrew/brew, and see what Mike thinks.

**Comment by sjackman** [comment]
Correction! The above output was with `zsh`. `brew` uses `bash`, and it is different!

```
$ command -pv curl
/usr/local/bin/curl
$ command -v curl
/usr/local/bin/curl
```

So I think we can drop `command -pv curl` in favour of `-x /usr/bin/curl`.

**Comment by bukzor** [comment]
For linux and osx that's true, but for me it gives /data/data/com.termux/bin/curl with command -pv and not otherwise.

**Comment by bukzor** [comment]
Actually the "command - pv" oviates any need for the "user default" case, for me.

Can you clarify this for me? I had previously assumed that "brewed curl" referred to `$HOMEBREW_PREFIX/bin/curl` but it instead refers to `$HOMEBREW_PREFIX/opt/curl/bin/curl`. What is the relationship between these two curls? When is one meant to be used and not the other?

**Comment by sjackman** [comment]
Both `$HOMEBREW_PREFIX/bin/curl` and `$HOMEBREW_PREFIX/opt/curl/bin/curl` are symlinks to the brewed `curl` ``$HOMEBREW_CELLAR/curl/7.59.0/bincurl`. Running `brew unlink curl` removes the former symlink, but not the latter.

**Comment by sjackman** [comment]
I'd prefer to use `command -v` over `command -pv`. Both should find `/data/data/com.termux/bin/curl` on Android.

**Comment by sjackman** [comment]
Does this work for you?
```sh
HOMEBREW_FORCE_BREWED_CURL=1 HOMEBREW_NO_ENV_FILTERING=1 brew install curl
HOMEBREW_FORCE_BREWED_CURL=1 brew install hello
```

**Comment by bukzor** [comment]
`command -v` will find whatever weird curl is on the users path, which isn't something homebrew historically tolerates. `command -pv` is the behavior we want: find the system-default curl, but without hard-coding /usr/bin/curl.

> Does this work for you?

No :) I can't get [berkeley-db](https://github.com/termux/termux-packages/issues/2273) or [libbsd](https://gist.github.com/bukzor/74bb3872a7155319e763d4e950e747a1) to compile. Yet!

**Comment by maxim-belkin** [comment]
tough cookies!

**Comment by bukzor** [comment]
I went to port the patch to machomebrew, but noticed that my use case already works in on that branch.
What is the difference that makes linuxbrew set a much smaller $PATH?

**Comment by sjackman** [comment]
> What is the difference that makes linuxbrew set a much smaller $PATH?

Without `HOMEBREW_NO_ENV_FILTERING=1` both Homebrew and Linuxbrew set PATH to `/usr/bin:/bin:/usr/sbin:/sbin`. They should behave the same.
See https://github.com/Homebrew/brew/blob/49927ed72ed00d12c50580ed1e9f26bdd592e897/bin/brew#L65
