### ISSUE TITLE
brew standalone: "invalid instruction"

### ISSUE THREAD

**Issue by jrevillard** [Linuxbrew/brew#66]
Hi,

I'm trying to do something perhaps a bit tricky for you but here is my use case.
I'm using linuxbrew to provide software on our plateform.
- The software repository is distributed to all the servers using the CernVM-FS file system (https://cernvm.cern.ch/portal/filesystem). 
- it's always mount to the same directory into the servers (/cvmfs/neugrid.egi.eu/software/x86_64/).
- All the servers are running Scientific Linux release 6 (64bit)

In order to properly build the softwares, I'm using a Docker image based on "centos:6.7" into which I install all the needed requirements to start with linuxbrew. I want a fully standalone installation to prevent issues.

I started the installation like this:

``` sh
brew install gcc --with-glibc
brew install git
brew install coreutils findutils gawk gnu-sed gnu-which grep make bash ruby
export PATH=$LINUXBREW_PATH/bin:$LINUXBREW_PATH/sbin
brew install hello --build-from-source --verbose && brew test hello; 
```

and of course I installed many more things.

Everything is working fine inside my docker image but when I try to use it inside one of the real final server everything is broken:

``` sh
[jerome@srv16 ~]$ brew
Error: No Ruby found, cannot proceed.
[jerome@srv16 ~]$ env
invalid instruction
[jerome@srv16 ~]$ cat /etc/redhat-release 
invalid instruction
```

Could you please advise me ?

Best,
Jerome

**Comment by sjackman** [comment]
Determine the oldest CPU architecture that you want to support and specify

``` sh
export HOMEBREW_ARCH=core2
```

`core2` is really old, but will support any x86-64 machine. Pick a more recent one from [this list](https://en.wikipedia.org/wiki/List_of_Intel_CPU_microarchitectures#x86_microarchitectures) with the help of `brew config | grep CPU` on your oldest machine.

**Comment by sjackman** [comment]
Your use case is very common with HPC. I do the same thing at work and use

``` sh
export HOMEBREW_ARCH=nehalem
```

**Comment by sjackman** [comment]
The default is `HOMEBREW_ARCH=native` which optimizes for the machine on which you're building.

**Comment by jrevillard** [comment]
Great I will test it with with `export HOMEBREW_ARCH=core2` and let you know if it solves my issue!

Best,
Jerome

**Comment by sjackman** [comment]
Linuxbrew bottles are built for `core2`. I'm curious, what is your oldest machine? `core2` is nearly ten years old. I'm wondering whether we should optimize for newer hardware.

**Comment by jrevillard** [comment]
Just a quick unrelated question because I'm not really familiar with bottles.
As we are using Linuxbrew in some of our infrastructure, I preferred to "fix" a working version using a fork of your repos (I update only when necessary on production). With the bottle mechanism, if you update a bottle, will the previous one still be available so that the old fork still work ?

Best,
Jerome

**Comment by jrevillard** [comment]
My older hardware reports:

```
[jerome@srv16 ~]$ brew config | grep CPU
CPU: 8-core 64-bit penryn
```

But the problem is not the bottles perhaps but perhaps glibc which is compiled from sources ?

**Comment by sjackman** [comment]
Yep, `glibc` and anything else compiled from source. `penryn` is `core2`, so that's a vote in favour of not changing the default hardware optimization for bottles.

**Comment by jrevillard** [comment]
Hi @sjackman , everything compiled properly and is working using "HOMEBREW_ARCH=core2".

thanks!

**Comment by sjackman** [comment]
Great! Glad to hear it.
