### ISSUE TITLE
brew does not find curl even though it is installed

### ISSUE THREAD

**Issue by P-HD** [Linuxbrew/brew#664]
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a tap problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

I was trying to install R using linuxbrew with the command `brew install R` and got the following output. 

> /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 496: curl: command not found
/home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 496: curl: command not found
/home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 496: curl: command not found
/home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 496: curl: command not found
/home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 496: curl: command not found
/home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/update.sh: line 496: curl: command not found
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

> ==> Installing dependencies for R: ncurses, gettext, jpeg, pcre, freetype, automake, gdbm, berkeley-db, perl, openssl, sqlite, python@2, glib, linuxbrew/xorg/xcb-proto, gawk, linuxbrew/xorg/libxcb, linuxbrew/xorg/libxaw3d, linuxbrew/xorg/xdpyinfo, linuxbrew/xorg/xorg, cairo, curl
==> Installing R dependency: ncurses
/home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/utils/analytics.rb:52:in `exec': No such file or directory - curl (Errno::ENOENT)
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/utils/analytics.rb:52:in `block in report'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/utils/analytics.rb:51:in `fork'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/utils/analytics.rb:51:in `report'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/utils/analytics.rb:62:in `report_event'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:288:in `install'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:597:in `install_dependency'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:559:in `block in install_dependencies'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:559:in `each'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:559:in `install_dependencies'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:262:in `install'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:387:in `install_formula'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:240:in `block in install'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:238:in `each'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:238:in `install'
        from /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
==> Downloading https://ftp.gnu.org/gnu/ncurses/ncurses-6.1.tar.gz
Error: no executable curl was found

At the end, the installation fails because no executable curl was found. 
Strangely enough, I am able to use curl, so I don't understand why it cannot find it. Typing `curl` returns 
> curl: try 'curl --help' or 'curl --manual' for more information
and typing `curl --help` returns the help instructions. Also, it is deposited in its own directory.

Getting around the issue by running brew update did not work. 

brew config and brew doctor results are below. 

Thanks you for your help! 

Philipp

`brew config`
> HOMEBREW_VERSION: 1.5.12
> ORIGIN: https://github.com/Linuxbrew/brew
> HEAD: ea3ed5c7e458644cb5d45115a04c3e30f4489e36
> Last commit: 3 days ago
> Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
> Core tap HEAD: 1c3970a3ed9d1a17e6095870361d8f7db1f4f537
> Core tap last commit: 18 minutes ago
> HOMEBREW_PREFIX: /home/bq_aguse/.linuxbrew
> HOMEBREW_REPOSITORY: /home/bq_aguse/.linuxbrew/Homebrew
> HOMEBREW_CELLAR: /home/bq_aguse/.linuxbrew/Cellar
> HOMEBREW_CACHE: /home/bq_aguse/.cache/Homebrew
> HOMEBREW_CELLAR: /home/bq_aguse/.linuxbrew/Cellar
> HOMEBREW_PREFIX: /home/bq_aguse/.linuxbrew
> HOMEBREW_REPOSITORY: /home/bq_aguse/.linuxbrew/Homebrew
> HOMEBREW_RUBY_WARNINGS: -W0
> CPU: 16-core 64-bit 0xf21
> Homebrew Ruby: 2.3.3 => /home/bq_aguse/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
> Clang: N/A
> Git: 2.15.0 => /home/bq_aguse/.linuxbrew/bin/git
> Curl: N/A
> Perl: /usr/bin/perl
> Python: /home/bq_aguse/.linuxbrew/opt/python/libexec/bin/python => /home/bq_aguse/.linuxbrew/Cellar/python/2.7.14/bin/python2.7
> Ruby: /usr/bin/ruby => /usr/bin/ruby2.1
> Java: N/A
> Kernel: Linux 3.16.0-5-amd64 x86_64 GNU/Linux
> OS: Debian GNU/Linux 8.8 (jessie) (jessie)
> Host glibc: 2.19
> /usr/bin/gcc: 4.9.2
> glibc: 2.23
> gcc: 5.5.0_3
> xorg: 20170115

`brew doctor`

>  Please note that these warnings are just used to help the Homebrew maintainers
> with debugging if you file an issue. If everything you use Homebrew for is
> working fine: please don't worry or file an issue; just ignore this. Thanks!
> Warning: "config" scripts exist outside your system or Homebrew directories.
> `./configure` scripts often look for *-config scripts to determine if
> software packages are installed, and what additional flags to use when
> compiling and linking.
> Having additional scripts in your path can confuse software installed via
> Homebrew if the config script overrides a system or Homebrew provided
> script of the same name. We found the following "config" scripts:
>   /usr/local/bin/pbs-config
>   /home/bq_aguse/miniconda2/bin/krb5-config
>   /home/bq_aguse/miniconda2/bin/curl-config
>   /home/bq_aguse/miniconda2/bin/python-config
>   /home/bq_aguse/miniconda2/bin/gsl-config
>   /home/bq_aguse/miniconda2/bin/icu-config
>   /home/bq_aguse/miniconda2/bin/ncurses5-config
>   /home/bq_aguse/miniconda2/bin/ncursesw5-config
>   /home/bq_aguse/miniconda2/bin/pcre-config
>   /home/bq_aguse/miniconda2/bin/libpng-config
>   /home/bq_aguse/miniconda2/bin/libpng16-config
>   /home/bq_aguse/miniconda2/bin/xml2-config
>   /home/bq_aguse/miniconda2/bin/freetype-config
> 
> Warning: Unbrewed header files were found in /usr/local/include.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
>   Unexpected header files:
>   /usr/local/include/attr_node_func.h
>   /usr/local/include/chk_file_sec.h
>   /usr/local/include/common_cmds.h
>   /usr/local/include/lib_ifl.h
>   /usr/local/include/lib_net.h
>   /usr/local/include/lib_utils.h
>   /usr/local/include/libcmds.h
>   /usr/local/include/license_pbs.h
>   /usr/local/include/log_event.h
>   /usr/local/include/pbs_cmds.h
>   /usr/local/include/pbs_constants.h
>   /usr/local/include/pbs_error.h
>   /usr/local/include/pbs_error_db.h
>   /usr/local/include/pbs_ifl.h
>   /usr/local/include/pbs_log.h
>   /usr/local/include/pbsnodes.h
>   /usr/local/include/qsub_functions.h
>   /usr/local/include/rm.h
>   /usr/local/include/rpp.h
>   /usr/local/include/setup_env.h
>   /usr/local/include/tcp.h
>   /usr/local/include/tm.h
>   /usr/local/include/tm_.h
>   /usr/local/include/trq_auth_daemon.h
>   /usr/local/include/u_hash_map_structs.h
>   /usr/local/include/u_lock_ctl.h
>   /usr/local/include/u_memmgr.h
>   /usr/local/include/uthash.h
> 
> Warning: Unbrewed .la files were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected .la files:
>   /usr/local/lib/libtorque.la
> 
> Warning: Unbrewed static libraries were found in /usr/local/lib.
> If you didn't put them there on purpose they could cause problems when
> building Homebrew formulae, and may need to be deleted.
> 
> Unexpected static libraries:
>   /usr/local/lib/libtorque.a
> 
> Warning: Some installed formulae are missing dependencies.
> You should `brew install` the missing dependencies:
>   brew install libxaw3d xdpyinfo python@2
> 
> Run `brew missing` for more details.
>

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Please report the output of `which -a curl`.
Try…
```sh
export HOMEBREW_FORCE_BREWED_CURL=1
HOMEBREW_NO_ENV_FILTERING=1 brew install curl
brew install r
```

**Comment by P-HD** [comment]
`which -a curl`
```
/home/bq_aguse/.linuxbrew/bin/curl
/home/bq_aguse/miniconda2/bin/curl
```
```
export HOMEBREW_FORCE_BREWED_CURL=1
HOMEBREW_NO_ENV_FILTERING=1 brew install curl
```
returned that curl was already installed, so I updated it instead with `HOMEBREW_NO_ENV_FILTERING=1 brew update curl`
I then proceeded to install r using `brew install R`
It installed a bunch of dependencies, but there was an error in the installation of R itself. 
```
==> Installing R
==> Downloading https://cran.r-project.org/src/base/R-3/R-3.4.4.tar.gz
########################################################################### 100.0%
Error: Will not overwrite /home/bq_aguse/.cache/Homebrew/Logs/r/00.options.out
```
so I renamed the file to `00.options.out.old` and ran `brew install r` again, resulting in the following: 
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
cmake           htop            node@4          node@6          node

==> Downloading https://cran.r-project.org/src/base/R-3/R-3.4.4.tar.
Already downloaded: /home/bq_aguse/.cache/Homebrew/r-3.4.4.tar.gz
==> ./configure --prefix=/home/bq_aguse/.linuxbrew/Cellar/r/3.4.4 --
==> make
Last 15 lines from /home/bq_aguse/.cache/Homebrew/Logs/r/02.make:
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C"
2: Setting LC_COLLATE failed, using "C"
3: Setting LC_TIME failed, using "C"
4: Setting LC_MESSAGES failed, using "C"
5: Setting LC_MONETARY failed, using "C"
6: Setting LC_PAPER failed, using "C"
7: Setting LC_MEASUREMENT failed, using "C"
* DONE (codetools)
make[2]: Leaving directory '/tmp/r-20180329-16925-1s30k9x/R-3.4.4/srmmended'
Makefile:39: recipe for target 'recommended-packages' failed
make[1]: *** [recommended-packages] Error 2
make[1]: Leaving directory '/tmp/r-20180329-16925-1s30k9x/R-3.4.4/srmmended'
Makefile:77: recipe for target 'stamp-recommended' failed
make: *** [stamp-recommended] Error 2

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, wacOS only.
```
R installation did not succeed. I tried googling for these issues (` Makefile:39: recipe for target 'recommended-packages' failed` and `Makefile:77: recipe for target 'stamp-recommended' failed`), but could not find any threads on them. 
Any idea what is going on here?


To avoid the problem that curl is not found in the future, should I simply remove `/home/bq_aguse/miniconda2/bin/curl`?

**Comment by sjackman** [comment]
`curl` should work from now on.
Please open a new issue to report the issue with `r` at https://github.com/Linuxbrew/homebrew-core/issues/new and please report the output of
```sh
brew install r
brew gist-logs r
```

**Comment by P-HD** [comment]
Thanks for the help! 

Best, 
Philipp
