### ISSUE TITLE
gosu does not install on Debian Sid

### ISSUE THREAD

**Issue by russel** [Linuxbrew/brew#669]
Gist of data is at 
https://gist.github.com/russel/b33cf00b06247811e8bef481ce521ad6

Let me know what other experiments/data to provide to help sort this out and I shall provide.

**Comment by sjackman** [comment]
Linuxbrew does not currently have proper support for Java 8. See https://github.com/Linuxbrew/brew/issues/509
Your best bet forward would be to ask the upstream developers of `gosu` to add support for Java 9.
You can try…
```
brew unlink jdk
brew install jdk@8
brew link --force jdk@8
brew install gosu
```
which may get you further, but no promises.

**Comment by russel** [comment]
Understood. Wilco.

BTW Java 10 is the current version of Java! So if Gosu requires Java 8, it is so far behind the line, it is become irrelevant.

**Comment by russel** [comment]
Issue posted at https://github.com/gosu-lang/gosu-lang/issues/131

**Comment by rsmckinney** [comment]
From [#131](https://github.com/gosu-lang/gosu-lang/issues/131):

We have a private experimental branch for Gosu supporting Java 9 (and 10). This branch replaces Gosu's internal Java interop support with [Manifold](http://manifold.systems/), which among other things provides Java 9 modular support. Manifold also provides a host of other features Gosu gets for free like Java meta-programming, Extensions to Java classes, and Structural Interfaces.

The release date for Java 9 support in Gosu is not yet available, but the experimental branch will likely become public soon.
