### ISSUE TITLE
Using linuxbrew like easybuild to maintain an application tree.

### ISSUE THREAD

**Issue by hartzell** [Linuxbrew/brew#67]
I'm not sure where to bring this up, this seems to be the best place to start.

I'm helping to set up a new HPC cluster environment (second prize is getting to set up _two_ such environments...).  I'm thinking through how to provide applications.

One traditional approach is to install stuff into subdirectories of `/yada-yada/apps`, each app gets a directory and each version of the app gets a subdirectory.  Users can pick and choose their environment via e.g. [Lmod](https://www.tacc.utexas.edu/research-development/tacc-projects/lmod).  In most settings, each app directory is a handcrafted snowflake.  If one is lucky, there are REAMDE's [SIC], etc...

The use case (community, tradition,...) is different from the standard _brew_ setup, where the canonical version of everything is linked into a common directory (`~/.linuxbrew`, `/usr/local`, ...).

[EasyBuild](https://github.com/hpcugent/easybuild) brings a bit of sanity into this world, providing scripted builds and automagically generating modulefiles (for e.g. Lmod).  They're very HPC-centric, worrying about building with multiple compiler toolchains and etc....  Their "recipe" database isn't as diverse or as current as it might be and their recipe support is primitive compared to what I'm used to in brew (e.g. I see no support for signatures for tarballs).

It seems that linuxbrew could be a nice alternative:
- We could tap (see what I did there???) into all of the existing Formulas.
- Recipes are easy to write, testing is well supported, etc...
- Multiple versions can be installed simultaneously.
- Modulefiles could be simple, just put the appropriate `Cellar/{app}/bin` dir onto PATH, perhaps set MANPATH, _et viola_ [SIC].

There are questions though:
- Is there a way to just skip the "linking things to `/usr/local`  (or `~/.linuxbrew`, or wherever), and if so will apps be able to find their prerequisites?
- Updates could be crazymaking, but I think that the complexity is inherent in the world, not added by linuxbrew (if I want to install recently added app _blah_, does that mean I update the git repo, if so, how/when do I update the rest of the apps, etc...
- What happens to the outdated Formula (my users _need_ FooBar-2000, even though the rest of the world has moved on and the FooBar formula now stands at FooBar-2019)?

I'd love to see a discussion of people wanting/doing similar things, but not sure where to ask.

**Comment by sjackman** [comment]
I also use Linuxbrew to manage the apps used on our HPC cluster. Here's some tips
- Don't use the symlinks in `$HOMEBREW_PREFIX/bin`. Just pretend they don't exist
- Create a simple script to add the `bin` directory of a requested keg to `PATH` as you suggested (see below) `require bwa/0.7.13` adds `$HOMEBREW_PREFIX/Cellar/bwa/0.7.13/bin` to `PATH`

``` sh
# Add Homebrew kegs to the PATH
require()
{
    cellar=`brew --cellar`
    for i; do
        case $i in
            */*)
                bin=$cellar/$i/bin
                ;;
            *)
                keg=`brew --prefix $i`
                bin=`realpath $keg`/bin
                ;;
        esac
        if [ -r $bin ]; then
            PATH=$bin:$PATH
        fi
    done
}
```

Sorry I'm short on time now, but we can discuss this more later.

**Comment by hartzell** [comment]
Our team wants to have multiple versions of things available, bowtie v2.2.7 and 2.2.8 and ... (not sure if that's sensible, just grabbed a likely candidate out of homebrew-science.

I think that the least painful way to support that is to set up our own tap and clone/steal/write formulas for each version of each thing that we want to support (along the lines of homebrew-versions).

I'm a little worried about chasing the rapidly evolving {home,linux}brew foundation, but otherwise it doesn't seem too complex.

Have you done anything similar?

**Comment by sjackman** [comment]
Previously installed versions of formula remain around forever. Upgrading to a newer version does not remove the older version. Installing older versions is not supported. I have thoughts on this, at least for installing bottles of older versions, which is pretty straight forward.

You can checkout the git repository to an arbitrary date and install whatever old software you want.

**Comment by hartzell** [comment]
Thanks for the thoughts!

**Comment by sjackman** [comment]
Here's the brew evolution proposal to support installing old bottles.
https://github.com/Homebrew/brew-evolution/pull/6/files
