### ISSUE TITLE
Dependency is installed but again downloading dependency from core

### ISSUE THREAD

**Issue by nitinet** [Linuxbrew/brew#68]
1. Tap a new repo and pin it on top of core. 
2. install formula

Error: dependencies are still loaded from code repo.
Also installed dependency from tap and showing in list. But again installing.

Attached Screenshot.
![image](https://cloud.githubusercontent.com/assets/1055173/16472309/c471a730-3e80-11e6-9a16-8a14bf4f7d06.png)

**Comment by sjackman** [comment]
Hi, Nitin. Sorry I don't have time to look into this issue myself right now. If you have access to a Mac and are able to reproduce the bug on a Mac, please open an issue at https://github.com/Homebrew/brew
