### ISSUE TITLE
mpv needs lua 5,1

### ISSUE THREAD

**Issue by jney** [Linuxbrew/brew#681]
running `brew install mpv` i've got the following error

```
[433/439] Linking build/mpv
/home/linuxbrew/.linuxbrew/bin/ld: cannot find -llua.5.1
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/tmp/mpv-20180407-12409-80xkha/mpv-0.27.2/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
```

**Comment by sjackman** [comment]
`lua@5.1` has not yet been patched to support Linux. A PR would be welcome.
See https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/lua@5.1.rb

**Comment by iMichka** [comment]
It has been patched (yesterday) :) And shared libraries have been built. But the error is still there.

**Comment by iMichka** [comment]
I found out that there is no `lua.pc` file:

```
ls -l /home/linuxbrew/.linuxbrew/Cellar/lua@5.1/5.1.5_7/lib/pkgconfig/
-r--r--r-- 1 linuxbrew linuxbrew 699 Apr  8 12:56 lua-5.1.pc
lrwxrwxrwx 1 linuxbrew linuxbrew  10 Feb 13  2012 lua5.1.pc -> lua-5.1.pc
```

This fixes the lua detection problem:
```
cp /home/linuxbrew/.linuxbrew/Cellar/lua@5.1/5.1.5_7/lib/pkgconfig/lua-5.1.pc /home/linuxbrew/.linuxbrew/Cellar/lua@5.1/5.1.5_7/lib/pkgconfig/lua.pc
```

The `lua` formula has:
`(lib/"pkgconfig/lua.pc").write pc_file`

The `lua@5.1` formula does not have that file. But I am unsure we should add it, upstream did not add it. Would there be a clash if there are two files called `lua.pc`? And why does it work for upstream and not on Linux.

**Comment by maxim-belkin** [comment]
```
# on a mac:
$ brew list -v lua@5.1 | grep "\.pc"
/usr/local/Cellar/lua@5.1/5.1.5_7/libexec/lib/pkgconfig/lua.pc
/usr/local/Cellar/lua@5.1/5.1.5_7/lib/pkgconfig/lua-5.1.pc
/usr/local/Cellar/lua@5.1/5.1.5_7/lib/pkgconfig/lua5.1.pc

# on a linux:
$ brew list -v lua@5.1 | grep "\.pc"
/home/linuxbrew/.linuxbrew/Cellar/lua@5.1/5.1.5_7/lib/pkgconfig/lua-5.1.pc
/home/linuxbrew/.linuxbrew/Cellar/lua@5.1/5.1.5_7/lib/pkgconfig/lua5.1.pc
/home/linuxbrew/.linuxbrew/Cellar/lua@5.1/5.1.5_7/libexec/lib/pkgconfig/lua.pc
```

**Comment by iMichka** [comment]
I added `ENV.prepend_path "PKG_CONFIG_PATH", Formula["lua@5.1"].opt_libexec/"lib/pkgconfig"` to the formula, like it is done in the `gnuplot@4` formula. This did not help. Actually the `gnuplot@4` fails to build with the same problem.

Adding `-vvv` to the `waf install` call, I can see the command line that is failing:

> ['gcc-5', '-rdynamic', '-Wl,-z,noexecstack', '-pthread', '-rdynamic', '-Wl,-version-script', '-Wl,mpv.def', 'osdep/main-fn-unix.c.19.o', 'audio/audio.c.18.o', 'audio/audio_buffer.c.18.o', 'audio/chmap.c.18.o', 'audio/chmap_sel.c.18.o', 'audio/fmt-conversion.c.18.o', 'audio/format.c.18.o', 'audio/aframe.c.18.o', 'audio/decode/ad_lavc.c.18.o', 'audio/decode/ad_spdif.c.18.o', 'audio/decode/dec_audio.c.18.o', 'audio/filter/af.c.18.o', 'audio/filter/af_channels.c.18.o', 'audio/filter/af_equalizer.c.18.o', 'audio/filter/af_format.c.18.o', 'audio/filter/af_lavcac3enc.c.18.o', 'audio/filter/af_lavfi.c.18.o', 'audio/filter/af_lavrresample.c.18.o', 'audio/filter/af_pan.c.18.o', 'audio/filter/af_scaletempo.c.18.o', 'audio/filter/af_volume.c.18.o', 'audio/filter/tools.c.18.o', 'audio/out/ao.c.18.o', 'audio/out/ao_lavc.c.18.o', 'audio/out/ao_null.c.18.o', 'audio/out/ao_oss.c.18.o', 'audio/out/ao_pcm.c.18.o', 'audio/out/pull.c.18.o', 'audio/out/push.c.18.o', 'common/av_common.c.18.o', 'common/av_log.c.18.o', 'common/codecs.c.18.o', 'common/encode_lavc.c.18.o', 'common/common.c.18.o', 'common/tags.c.18.o', 'common/msg.c.18.o', 'common/playlist.c.18.o', 'common/recorder.c.18.o', 'common/version.c.18.o', 'demux/codec_tags.c.18.o', 'demux/cue.c.18.o', 'demux/demux.c.18.o', 'demux/demux_cue.c.18.o', 'demux/demux_disc.c.18.o', 'demux/demux_edl.c.18.o', 'demux/demux_lavf.c.18.o', 'demux/demux_mf.c.18.o', 'demux/demux_mkv.c.18.o', 'demux/demux_mkv_timeline.c.18.o', 'demux/demux_null.c.18.o', 'demux/demux_playlist.c.18.o', 'demux/demux_raw.c.18.o', 'demux/demux_rar.c.18.o', 'demux/demux_timeline.c.18.o', 'demux/ebml.c.18.o', 'demux/packet.c.18.o', 'demux/timeline.c.18.o', 'input/cmd_list.c.18.o', 'input/cmd_parse.c.18.o', 'input/event.c.18.o', 'input/input.c.18.o', 'input/ipc.c.18.o', 'input/ipc-unix.c.18.o', 'input/keycodes.c.18.o', 'misc/bstr.c.18.o', 'misc/charset_conv.c.18.o', 'misc/dispatch.c.18.o', 'misc/json.c.18.o', 'misc/node.c.18.o', 'misc/ring.c.18.o', 'misc/rendezvous.c.18.o', 'misc/thread_pool.c.18.o', 'options/m_config.c.18.o', 'options/m_option.c.18.o', 'options/m_property.c.18.o', 'options/options.c.18.o', 'options/parse_commandline.c.18.o', 'options/parse_configfile.c.18.o', 'options/path.c.18.o', 'player/audio.c.18.o', 'player/client.c.18.o', 'player/command.c.18.o', 'player/configfiles.c.18.o', 'player/external_files.c.18.o', 'player/loadfile.c.18.o', 'player/main.c.18.o', 'player/misc.c.18.o', 'player/lavfi.c.18.o', 'player/lua.c.18.o', 'player/javascript.c.18.o', 'player/osd.c.18.o', 'player/playloop.c.18.o', 'player/screenshot.c.18.o', 'player/scripting.c.18.o', 'player/sub.c.18.o', 'player/video.c.18.o', 'stream/ai_oss.c.18.o', 'stream/cache.c.18.o', 'stream/cache_file.c.18.o', 'stream/cookies.c.18.o', 'stream/rar.c.18.o', 'stream/stream.c.18.o', 'stream/stream_avdevice.c.18.o', 'stream/stream_edl.c.18.o', 'stream/stream_file.c.18.o', 'stream/stream_cb.c.18.o', 'stream/stream_lavf.c.18.o', 'stream/stream_memory.c.18.o', 'stream/stream_mf.c.18.o', 'stream/stream_null.c.18.o', 'stream/stream_rar.c.18.o', 'sub/ass_mp.c.18.o', 'sub/dec_sub.c.18.o', 'sub/draw_bmp.c.18.o', 'sub/img_convert.c.18.o', 'sub/lavc_conv.c.18.o', 'sub/osd.c.18.o', 'sub/osd_libass.c.18.o', 'sub/sd_ass.c.18.o', 'sub/sd_lavc.c.18.o', 'sub/filter_sdh.c.18.o', 'video/csputils.c.18.o', 'video/fmt-conversion.c.18.o', 'video/image_loader.c.18.o', 'video/image_writer.c.18.o', 'video/img_format.c.18.o', 'video/hwdec.c.18.o', 'video/mp_image.c.18.o', 'video/mp_image_pool.c.18.o', 'video/sws_utils.c.18.o', 'video/decode/dec_video.c.18.o', 'video/decode/hw_cuda.c.18.o', 'video/decode/vd_lavc.c.18.o', 'video/filter/refqueue.c.18.o', 'video/filter/vf.c.18.o', 'video/filter/vf_buffer.c.18.o', 'video/filter/vf_crop.c.18.o', 'video/filter/vf_dsize.c.18.o', 'video/filter/vf_expand.c.18.o', 'video/filter/vf_flip.c.18.o', 'video/filter/vf_format.c.18.o', 'video/filter/vf_gradfun.c.18.o', 'video/filter/vf_lavfi.c.18.o', 'video/filter/vf_mirror.c.18.o', 'video/filter/vf_noformat.c.18.o', 'video/filter/vf_pullup.c.18.o', 'video/filter/vf_rotate.c.18.o', 'video/filter/vf_scale.c.18.o', 'video/filter/vf_stereo3d.c.18.o', 'video/filter/vf_sub.c.18.o', 'video/filter/vf_yadif.c.18.o', 'video/out/aspect.c.18.o', 'video/out/bitmap_packer.c.18.o', 'video/out/dither.c.18.o', 'video/out/filter_kernels.c.18.o', 'video/out/opengl/common.c.18.o', 'video/out/opengl/context.c.18.o', 'video/out/opengl/cuda_dynamic.c.18.o', 'video/out/opengl/formats.c.18.o', 'video/out/opengl/gl_utils.c.18.o', 'video/out/opengl/hwdec.c.18.o', 'video/out/opengl/hwdec_cuda.c.18.o', 'video/out/opengl/lcms.c.18.o', 'video/out/opengl/osd.c.18.o', 'video/out/opengl/ra.c.18.o', 'video/out/opengl/ra_gl.c.18.o', 'video/out/opengl/shader_cache.c.18.o', 'video/out/opengl/user_shaders.c.18.o', 'video/out/opengl/utils.c.18.o', 'video/out/opengl/video.c.18.o', 'video/out/opengl/video_shaders.c.18.o', 'video/out/vo.c.18.o', 'video/out/vo_image.c.18.o', 'video/out/vo_lavc.c.18.o', 'video/out/vo_null.c.18.o', 'video/out/vo_opengl.c.18.o', 'video/out/vo_opengl_cb.c.18.o', 'video/out/vo_tct.c.18.o', 'video/out/win_state.c.18.o', 'osdep/terminal-unix.c.18.o', 'osdep/io.c.18.o', 'osdep/timer.c.18.o', 'osdep/timer-linux.c.18.o', 'osdep/threads.c.18.o', 'osdep/semaphore_osx.c.18.o', 'osdep/subprocess.c.18.o', 'osdep/subprocess-posix.c.18.o', 'osdep/path-unix.c.18.o', 'ta/ta.c.18.o', 'ta/ta_talloc.c.18.o', 'ta/ta_utils.c.18.o', '-o/tmp/mpv-20180410-7731-1hm0fs4/mpv-0.27.2/build/mpv', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/usr/local/lib', '-L/home/linuxbrew/.linuxbrew/Cellar/little-cms2/2.9/lib', '-L/home/linuxbrew/.linuxbrew/Cellar/libass/0.14.0_1/lib', '-L/home/linuxbrew/.linuxbrew/Cellar/ffmpeg/3.4.2/lib', '-L/home/linuxbrew/.linuxbrew/Cellar/ffmpeg/3.4.2/lib', '-L/home/linuxbrew/.linuxbrew/Cellar/ffmpeg/3.4.2/lib', '-L/home/linuxbrew/.linuxbrew/lib', '-lmujs', '-llcms2', '-lass', '-lavcodec', '-lavutil', '-lavcodec', '-lavformat', '-lswscale', '-lavfilter', '-lswresample', '-lavdevice', '-ljpeg', '-lm', '-lrt', '-llua.5.1', '-lm', '-ldl', '-lz']

So the paths to `libass`, `little-cms2` and `ffmpeg` are passed with `-L`, but not the one for `lua5.1`.
I though the `-L` and `-I` paths would be read from the `.pc` files, but this is not the case, I think they are set by Brew. Maybe the library path is missing because `lua5.1` is a versioned formula and the paths are not added?

**Comment by iMichka** [comment]
I opened that patch to prevent a conflict between `lua` and `lua@5.1`: https://github.com/Linuxbrew/homebrew-core/pull/7113

This was not really a problem for this case and does not help fix this problem; but it will avoid conflicts if you want to have both luas installed.

**Comment by sjackman** [comment]
On macOS the libraries installed by `lua@5.1` are named…
```
liblua.5.1.5.dylib
liblua.5.1.dylib
liblua5.1.dylib
```
In particular, there is a library named `liblua.5.1.dylib`
On Linuxbrew, there ought to be a library named `liblua.5.1.so` for `-llua.5.1` to work.

**Comment by sjackman** [comment]
In the Linux bottle, the libraries are named…
```
liblua.so.5.1
liblua.so.5.1.5
```
The library named `liblua.5.1.so` is missing.

**Comment by iMichka** [comment]
Good catch. That was a typo from me. That's when you start hacking manually around in Makefiles :(
I opened a patch: https://github.com/Linuxbrew/homebrew-core/pull/7123

**Comment by iMichka** [comment]
Working on building `mpv` here: https://github.com/Linuxbrew/homebrew-core/pull/7152

Closing this issue, we can continue the discussion on the pull request.
