### ISSUE TITLE
graphicsmagick installation failed using brew

### ISSUE THREAD

**Issue by anaspa** [Linuxbrew/brew#690]
When I install graphicsmagick using the command 'brew install graphicsmagick'. It shows following error

Error: undefined method `sdk_path' for OS::Mac:Module
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/ubuntu/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jasper.rb:18:in `block in install'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:93:in `block in mkdir'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:92:in `mkdir'
/home/ubuntu/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jasper.rb:15:in `install'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/build.rb:153:in `block (2 levels) in install'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1097:in `block in brew'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1895:in `block (2 levels) in stage'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1894:in `block in stage'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:119:in `block in unpack'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:13:in `block in mktemp'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `block in run'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `chdir'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:73:in `run'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/extend/fileutils.rb:12:in `mktemp'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:114:in `unpack'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/resource.rb:92:in `stage'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1872:in `stage'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1092:in `brew'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/build.rb:124:in `block in install'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:556:in `with_env'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/build.rb:121:in `install'
/home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/build.rb:202:in `<main>'

brew doctor
Your system is ready to brew.

 brew config
HOMEBREW_VERSION: 1.6.0
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 8bd8aa231cf2812ba7538f2e74b6c32e5fb567b8
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: efd9dff9493480938f9be4723a20d9678dbfa68f
Core tap last commit: 16 hours ago
HOMEBREW_PREFIX: /home/ubuntu/.linuxbrew
HOMEBREW_REPOSITORY: /home/ubuntu/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/ubuntu/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/ubuntu/.cache/Homebrew
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /home/ubuntu/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: N/A
Git: 2.7.4 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.4.0-1052-aws x86_64 GNU/Linux
OS: Ubuntu 16.04.3 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: 20170115_1

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-core#7270
