### ISSUE TITLE
brew could use --depth=1 to speed up Git clone operations

### ISSUE THREAD

**Issue by gastaldi** [Linuxbrew/brew#692]
It would be nice if Linuxbrew used `git clone --depth=1` to speed up installations when a repository is cloned. 

More info: https://www.perforce.com/blog/git-beyond-basics-using-shallow-clones

**Comment by sjackman** [comment]
Hi, George. It does already.
https://github.com/Linuxbrew/brew/blob/64d5cb51032e4f303bea33d88d02cad0f7327d33/Library/Homebrew/tap.rb#L261
