### ISSUE TITLE
HTTPS support for Github Pages

### ISSUE THREAD

**Issue by codysherman** [Linuxbrew/brew#702]
Github has rolled out HTTPS for custom domains, please enable it for http://linuxbrew.sh/

Instructions can be found here: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Switching will also put the hosted website on the faster CDN.

**Comment by sjackman** [comment]
I've tried, but so far no luck. I updated the DNS A records for http://sjackman.ca (another site of mine), but it does not yet support https.

**Comment by codysherman** [comment]
The feature has rolled out to everyone at this point, you should be able to do it. After switching your A records to the new IP, you do have to go into GitHub and turn off the GitHub Pages and then turn it back on. This triggers it to issue you your certificate, it will tell you that it's "not available because your certificate is still being issued". This took about 2 minutes for most of my pages, but over a day for my biggest one.

**Comment by sjackman** [comment]
It doesn't look like I can disable GitHub Pages because it's a `*.github.io` user page. The `Source` drop-down box is disabled. The GitHub settings page says…
```
User pages must be built from the master branch.
```

**Comment by codysherman** [comment]
Hmm. You could try reaching out to GitHub, they have helped others with similar problems, I'm also part of the main ticket on GitHub that lead up to the HTTPS support. They've helped individuals when contacted. 

You could however also look into switching to the newer method of using GitHub hosting using a /docs folder in your master branch. I did that for all of my projects as it just seemed way more convenient and less "hacky" than having a weird branch unrelated to the project. All of my page though were custom made, I wasn't using the Jekyll thing, so if you are double check that, but I would assume that would still all work just fine inside /docs.

**Comment by codysherman** [comment]
Yeah just went back and saw people stuck waiting for their certificate to be issued said just emailing GitHub had their issue resolved within minutes. They said to check here: https://github.com/contact

**Comment by sjackman** [comment]
Thanks for the suggestion. I've contacted GitHub support just now.

**Comment by sjackman** [comment]
🍾 Success! https://linuxbrew.sh

**Comment by codysherman** [comment]
Awesome! Congrats!

**Comment by sjackman** [comment]
Thanks for the nudge!

**Comment by codysherman** [comment]
Don't forget to update links in documentation, readme, etc. And also, that
link that appears at the top of the GitHub repo.

**Comment by sjackman** [comment]
I'll probably do that piece-meal as it comes up, rather than one big audit. Fixed the link at the top of the GitHub repo though.
