### ISSUE TITLE
Error: undefined method `version_scheme' for #<Class:0x00564e76500e40>

### ISSUE THREAD

**Issue by maxrodkin** [Linuxbrew/brew#703]
```
==> Installation successful!
==> Next steps
Install the Linuxbrew dependencies:

Debian, Ubuntu, etc.:
  `sudo apt-get install build-essential`

Fedora, Red Hat, CentOS, etc.:
  `sudo yum groupinstall 'Development Tools'`

See http://brew.sh/linuxbrew/#dependencies for more information.

Run `brew doctor` before you install anything
Run `brew help` to get started
Error: undefined method `version_scheme' for #<Class:0x00564e76500e40>
```

**Comment by sjackman** [comment]
Please report the output of
```
brew --version
brew config
```

**Comment by maxrodkin** [comment]
$ brew --version
Homebrew 0.9.8 (git revision 53204; last commit 2017-09-28)
Homebrew/homebrew-core (git revision 6690; last commit 2018-05-08)
$ brew config
HOMEBREW_VERSION: 0.9.8
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: 532040391bb984e410b7ad73bdd0c518f945cc0b
Last commit: 8 months ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 669038e1dea01dfa66258aa8d410a5174b44820b
Core tap last commit: 9 days ago
HOMEBREW_PREFIX: /home/maxi4/.linuxbrew
HOMEBREW_REPOSITORY: /home/maxi4/.linuxbrew
HOMEBREW_CELLAR: /home/maxi4/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit 0x1570
Kernel: Linux 4.13.0-41-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.4 LTS
Codename: xenial
OS glibc: 2.23
OS gcc: 5.4.0
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 2.4.1 => /home/maxi4/.rbenv/versions/2.4.1/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /home/maxi4/.rbenv/versions/2.4.1/bin/ruby
Java: N/A

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
I'm not sure what cause your original error `Error: undefined method 'version_scheme' for #<Class:0x00564e76500e40>`. Is `brew` working for you now? Does `brew install hello` work?
