### ISSUE TITLE
libvirt is not building on Debian 9.4

### ISSUE THREAD

**Issue by ipatch** [Linuxbrew/brew#704]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  - trying to install `libvirt` on Debian 9.4
- What happened (include command output)
  - [output](https://gist.github.com/ipatch/7d599679346bfa270ec5f7345c2150ea) of `brew gist-logs --config --doctor libvirt`
- What you expected to happen
  - a successful install of `libvirt`
- Step-by-step reproduction instructions (by running `brew` commands)
  - `brew install -v libvirt`

**Comment by sjackman** [comment]
```
configure: error: libnl-devel >= 1.1 is required for macvtap support
```
https://gist.github.com/ipatch/7d599679346bfa270ec5f7345c2150ea#file-01-configure-L964

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-core#7673
