### ISSUE TITLE
Better implementation of dpkg

### ISSUE THREAD

**Issue by JL2210** [Linuxbrew/brew#708]
I believe there is a better implementation of dpkg that you could use, check out skycocker/chromebrew for an example. Thank you!

**Comment by sjackman** [comment]
Hi, James. You're referring to https://github.com/skycocker/chromebrew/blob/master/packages/dpkg.rb
and https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/dpkg.rb ?

**Comment by JL2210** [comment]
In dpkg.rb from 
https://github.com/skycocker/chromebrew/blob/master/packages/dpkg.rb
dselect is enabled and the root directory to install packages is /usr/local.
In https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/dpkg.rb
dselect is disabled altogether and you can only build packages and extract then

**Comment by iMichka** [comment]
Pull requests are welcome to change that.

If the changes are useful for mac, they need to be done in the mac repo first: https://github.com/Homebrew/homebrew-core/blob/master/Formula/dpkg.rb.

**Comment by sjackman** [comment]
What should the root directory to install packages be on Linux? On a Debian/Ubuntu system, `/` makes sense. On a non-Debian system, I'm not sure. `$HOMEBREW_PREFIX/something` ?
