### ISSUE TITLE
Fail to fetch gnu-getopt

### ISSUE THREAD

**Issue by hanxue** [Linuxbrew/brew#709]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

I am trying to install `gnu-getopt`, and fetching from the server fails

```
$ brew install asciidoc
==> Installing dependencies for asciidoc: gnu-getopt, libxslt, xmlto
==> Installing asciidoc dependency: gnu-getopt
==> Downloading http://frodo.looijaard.name/system/files/software/getopt/getopt-

curl: (7) Failed to connect to frodo.looijaard.name port 80: Connection refused
Error: Failed to download resource "gnu-getopt"
Download failed: http://frodo.looijaard.name/system/files/software/getopt/getopt-1.1.6.tar.gz
```

The server seems down https://downforeveryoneorjustme.com/frodo.looijaard.name

brew doctor output

```
$ brew doctor
Your system is ready to brew.
```

**Comment by hanxue** [comment]
The bottles are fine, but the url for source tarball is not working. Adding fossies.org as mirror at https://github.com/Homebrew/homebrew-core/pull/28069

**Comment by iMichka** [comment]
Cool, thanks. Yes this should be fixed by https://github.com/Homebrew/homebrew-core/pull/28069. Closing here.
