### ISSUE TITLE
Installing formula with HOMEBREW_TEMP does not work

### ISSUE THREAD

**Issue by hanxue** [Linuxbrew/brew#714]
- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new. If it's a `brew cask` problem please file this issue at https://github.com/caskroom/homebrew-cask/issues/new. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

`/tmp` on my root partition is too small that when I brew some formulas, I run out of disk space. I have attached a larger disks and use `HOMEBREW_TEMP` to use that mounted disk. Unfortunately, all brewing when `HOMEBREW_TEMP` is set does not work. 

```
$ HOMEBREW_TEMP=/mnt/vol1 brew upgrade isl -s
==> Upgrading 1 outdated package, with result:
isl 0.18 -> 0.19                                                     
==> Upgrading isl                         
==> Downloading http://isl.gforge.inria.fr/isl-0.19.tar.xz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cella
Last 15 lines from /home/hanxue/.cache/Homebrew/Logs/isl/01.configure:
2018-05-24 03:20:06 +0000

./configure
--disable-dependency-tracking
--disable-silent-rules
--prefix=/home/linuxbrew/.linuxbrew/Cellar/isl/0.19
--with-gmp=system
--with-gmp-prefix=/home/linuxbrew/.linuxbrew/opt/gmp


READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core, which support macOS only.
```

The gist logs are at https://gist.github.com/hanxue/9defdd2428196d8499fd8b308cece551

Here is another brewing that failed

```
$ HOMEBREW_TEMP=/mnt/vol1 CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=2048" brew install mongodb@3.4 --verbose
```

And the gist logs https://gist.github.com/hanxue/32850cdf1447687b050cf9b124a5dc71

Output of `brew doctor` and `brew config` 

```
$ brew doctor
Your system is ready to brew.                
$ brew config       
HOMEBREW_VERSION: 1.6.3
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: b67917c837f1fb9c5bf2494cfd89b4eee6802802
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 39727d7baac2521bea099b60bf5985d97c95cced
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/hanxue/.cache/Homebrew 
HOMEBREW_GITHUB_API_TOKEN: set
CPU: single-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: N/A
Git: 2.1.4 => /usr/bin/git
Curl: 7.38.0 => /usr/bin/curl 
Java: N/A 
Kernel: Linux 3.16.0-4-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 8.7 (jessie) (jessie)
Host glibc: 2.19
/usr/bin/gcc: 4.9.2
glibc: 2.23
gcc: 5.5.0_4
xorg: 20170115_1
```

**Comment by sjackman** [comment]
Please report the output of
```sh
HOMEBREW_TEMP=/mnt/vol1 brew doctor
```

**Comment by hanxue** [comment]
The output of running `HOMEBREW_TEMP=/mnt/vol1 brew doctor` is 

```
$ HOMEBREW_TEMP=/mnt/vol1 brew doctor
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/diagnostic.rb:59:in `check_tmpdir_executable'
Or, even better, submit a PR to fix it!
`

**Comment by hanxue** [comment]
I found out via https://github.com/Linuxbrew/legacy-linuxbrew/issues/775#issuecomment-178201026 that a simple test is to make sure you can execute a script on the `HOMEBREW_TEMP` directory. 

The cause of my problem is because external disks are mounted with `nosuid` and `noexec` by default. 

```
$ mount | grep vol1                           
/dev/sda on /mnt/vol1 type ext4 (rw,nosuid,nodev,noexec,relatime,data=ordered,us
er)         
```

`mount`ing the disk with `exec` and `suid` solved the problem

```
$ sudo mount -o exec,suid,nofail,relatime,noauto /dev/disk/by-id
/scsi-0DO_Volume_volume-sgp1-01 /mnt/vol1
$ mount|grep vol1
/dev/sda on /mnt/vol1 type ext4 (rw,relatime,data=ordered)
$ HOMEBREW_TEMP=/mnt/vol1 brew doctor
Your system is ready to brew. 
$ HOMEBREW_TEMP=/mnt/vol1 brew upgrade isl -s
Updating Homebrew...
^C==> Upgrading 1 outdated package, with result:
isl 0.18 -> 0.19
==> Upgrading isl 
==> Downloading http://isl.gforge.inria.fr/isl-0.19.tar.xz
Already downloaded: /home/hanxue/.cache/Homebrew/isl-0.19.tar.xz
==> ./configure --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cella
==> make check
```


I think there should be a better error message for `check_tmpdir_executable` though

**Comment by sjackman** [comment]
If you remount `/mnt/vol1` as `noexec` and run
```sh
brew update
HOMEBREW_TEMP=/mnt/vol1 brew doctor
```
you should see a helpful and information error message.

Glad to hear that you got it working.
