### ISSUE TITLE
Not an issue, I just want to say thanks!

### ISSUE THREAD

**Issue by petercunha** [Linuxbrew/brew#722]
This isn't actually an issue. I just wanted to say thank you to the contributors for creating and maintaining this project.

I work for a large government contractor where software developers are never given `sudo` access, so installing and managing packages is a huge pain. Linuxbrew has greatly sped up my workflow, and now I don't have to email the sysadmin every time I need something installed! Being able to easily install packages without `sudo` is seriously amazing.

Thanks  :smile:
Peter

**Comment by sjackman** [comment]
Thank you very much for the positive feedback! My motivation is really boosted by hearing lovely comments such as yours. ❤️

**Comment by sjackman** [comment]
P.S. I also work at a government institution without sudo access, which is why I created Linuxbrew!
