### ISSUE TITLE
docker no engine installed.

### ISSUE THREAD

**Issue by pinkfrog9** [Linuxbrew/brew#723]
try

> brew install docker

and then run,

> docker run hello-word

docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

**Comment by sjackman** [comment]
`brew install docker` installs the Docker client. It does not install the Docker daemon, known as Docker Engine. You'll need to install that yourself.
See https://www.docker.com/get-docker
and https://docs.docker.com/engine/
