### ISSUE TITLE
gcc: Bootstrap comparison failure!

### ISSUE THREAD

**Issue by wuziniu** [Linuxbrew/brew#725]
I'm trying on install gcc using linuxbrew without sudo. I followed the instruction as in https://github.com/Linuxbrew/brew/wiki/CentOS6#install-linuxbrew-on-centos-6-without-sudo
The error encountered when running command:
HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc --without-glibc
is described in https://gist.github.com/wuziniu/5fc96415400f1e0ce57636a5d0ff63b7

**Comment by iMichka** [comment]
Hi. Thanks for reporting. Are you using gcc 4.9.4 to compile gcc? If yes, then this is the bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71399

In that case this has nothing to do with linuxbrew and we can’t help you further

**Comment by wuziniu** [comment]
@iMichka Thanks for your reply. No my gcc version is 4.4.7
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
It this version too old?

**Comment by sjackman** [comment]
```
make[3]: Leaving directory `/tmp/gcc-20180611-27611-17eskx0/gcc-5.5.0/build'
Comparing stages 2 and 3
warning: gcc/cc1obj-checksum.o differs
warning: gcc/cc1-checksum.o differs
warning: gcc/cc1plus-checksum.o differs
warning: gcc/cc1objplus-checksum.o differs
Bootstrap comparison failure!
gcc/insn-emit.o differs
gcc/insn-recog.o differs
make[2]: *** [compare] Error 1
```
https://gist.github.com/wuziniu/5fc96415400f1e0ce57636a5d0ff63b7#file-make-L71

**Comment by sjackman** [comment]
I'm afraid I haven't run into this issue myself. Perhaps try…
```sh
HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_BUILD_FROM_SOURCE=1 brew install gcc@4.9 --without-glibc
HOMEBREW_NO_AUTO_UPDATE=1 brew install glibc
HOMEBREW_NO_AUTO_UPDATE=1 brew install gcc
```

**Comment by wuziniu** [comment]
Thanks, but I got the same error as before. The make takes more than half hour. Is that a normal situation?

**Comment by sjackman** [comment]
Installing GCC from source can be quite slow. I'd say half an hour is normal. Did you get the same error after the `brew install gcc@4.9` step?
