### ISSUE TITLE
Issue chooser has vestigial Homebrew information

### ISSUE THREAD

**Issue by jacktose** [Linuxbrew/brew#728]
Let's get meta!
I went to open an issue here: https://github.com/Linuxbrew/brew/issues/new
It said:
> Please fill out one of the templates on: https://github.com/Homebrew/brew/issues/new/choose
> 
> If you want to ask a question please do so on our Discourse: https://discourse.brew.sh
> 
> We will close issues asking questions without comment.

The first URL takes you to the Homebrew repo, and the second takes to to the Homebrew discourse. Both of those are inappropriate for Linuxbrew. I assume it's left over from forking/copying the Homebrew repo, but in any case it should be updated for the appropriate actions here.
(Then I won't be embarrassingly corrected for [talking about Linuxbrew in the wrong place](https://discourse.brew.sh/t/linuxbrew-confusing-install-instructions/2377/2?u=jacktose).)

**Comment by sjackman** [comment]
Thanks for the bug report, Jack. I've opened PR #729 to address this issue.
