### ISSUE TITLE
cannot run redis

### ISSUE THREAD

**Issue by donfrigo** [Linuxbrew/brew#730]
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

Hello,

I am trying to run redis, but the service doesn't start. Other formulae like hello doesn't run either. I am enclosing the gist:
https://gist.github.com/donfrigo/c5fac3880a3656976f43c641fbf9b545
Thanks!

**Comment by sjackman** [comment]
```
$ brew services start redis
sh: 1: list: not found
Error: Failure while executing:  load -w /home/donfrigo/Library/LaunchAgents/homebrew.mxcl.redis.plist
```
`brew services start` is not supported on Linux. Sorry that the error message is not more informative.
