### ISSUE TITLE
brew pull --bottle sometimes removes mac bottles

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/brew#732]
Took me some time to find out what is going on here. Sometimes, the mac bottles get removed when I do a `brew pull --bottle`.

This one is fine:
https://github.com/Linuxbrew/homebrew-core/pull/8086
This one is not:
https://github.com/Linuxbrew/homebrew-core/pull/8076

The difference is that I ran `http://bot.linuxbrew.sh/ci-upload/github.com/Linuxbrew/homebrew-core/pull/8076?keepold=1` on the second one, because the initial bottle upload failed.

Comparing bottles commits:
https://github.com/LinuxbrewTestBot/homebrew-core/compare/Linuxbrew:master...pr-8086.patch
https://github.com/LinuxbrewTestBot/homebrew-core/compare/Linuxbrew:master...pr-8076.patch

shows the following diff for the second bottle (which is wrong):
```
diff --git a/Formula/rclone.rb b/Formula/rclone.rb
index 829f110d70..1d9fb223f1 100644
--- a/Formula/rclone.rb
+++ b/Formula/rclone.rb
@@ -8,9 +8,7 @@ class Rclone < Formula
 
   bottle do
     cellar :any_skip_relocation
-    sha256 "c5a24cebbff63e768439a63db1e824e2d68b3d1f1cb4b8721bfeece777756aac" => :high_sierra
-    sha256 "f5bd438d038265787effce38849c9b9d2b390516a9aac38b3130e2f7dd5feafb" => :sierra
-    sha256 "098a51e85a1bcaeac18295e55678f1d5345fbbbb44875b6320659f540650eb97" => :el_capitan
+    sha256 "8b91fea325d5d57a384c9ed3943dfb1868add70ef7efd4c534b5440f1d0db336" => :x86_64_linux
   end
```

This means something goes wrong when the bottle is being re-uploaded.

@sjackman Maybe you have an idea? I already had a hard time finding this out, maybe you can give me a hint at what I should look next.

**Comment by sjackman** [comment]
This diff of `rclone.rb` looks like it was run without `?keepold=1`, which would remove the macOS bottles. Is that the case?

**Comment by iMichka** [comment]
Ok my bad, I was using `keepold` instead of `keep-old` ... not sure why I have this typo and never noticed. Closing, not a bug.
