### ISSUE TITLE
Error: glibc cannot be built with any available compilers.

### ISSUE THREAD

**Issue by exavi** [Linuxbrew/brew#738]
Please fill out one of the templates at https://github.com/Linuxbrew/brew/issues/new/choose

I can't seem to be able to install anything with brew, running into a weird dependency loop where glibc is needed for everything but it can't be compiled somehow.

I am running CentOS 6.9, and have tried with both the default gcc v4.4.7, and the devtoolset-3 one, gcc v4.9.2.

>>> brew install gcc
==> Installing dependencies for gcc: glibc, m4, gmp, mpfr, libmpc, isl@0.18
==> Installing gcc dependency: glibc
Error: glibc cannot be built with any available compilers.
Install Clang or brew install gcc

**Comment by iMichka** [comment]
Hi. Did you follow these instructions: https://github.com/Linuxbrew/brew/wiki/CentOS6 ?

**Comment by exavi** [comment]
Ah no, apologies, I did not see that. 
I have a question for an error I am getting when building some formulas, but I'll close this and ask separately.

**Comment by mbinge** [comment]
if you get "curl: (35) SSL connect error"
you could try https://gitlab.com/davidjpeacock/kurly.git to replace curl by default

**Comment by sjackman** [comment]
Another new option is to use `HOMEBREW_CURL_PATH` and `HOMEBREW_GIT_PATH` to specify newer versions of `curl` and `git`.
```sh
export HOMEBREW_CURL_PATH=~/.linuxbrew/bin/curl
export HOMEBREW_GIT_PATH=~/.linuxbrew/bin/git
```

**Comment by iMichka** [comment]
Just one side note (unrelated to this topic) for @mbinge : please do not multi-post "advertisements" for this alternative `kurly` project on this issue tracker. I have nothing against `kurly` or you specifically, just that I think this way of proceeding is wrong and not really constructive.

If you want to promote alternative tools, fine, please open a new issue, and explain why your project is a good alternative to curl. Even better, propose a pull request and show us that it works well as a good alternative. But you can not just come here and promote that project out of nowhere. This is not going to work.

I think the problem has been solved. If there is anything else, a new issue can be opened.
