### ISSUE TITLE
Do you plan to implement brew-cask for linuxbrew

### ISSUE THREAD

**Issue by sebma** [Linuxbrew/brew#742]
Hi,

Do you plan to implement brew-cask for linuxbrew ?

It would facilitate greatly the installation of more up to date applications than the one in the Linux repositories.

In the meantime, I found this alternative : [Linuxbrew Binary Formulaes](https://github.com/athrunsun/homebrew-linuxbinary).

**Comment by shikhir-arora** [comment]
Brew cask images are mostly incompatible with Linux. The apps there are bundled for macOS and many of them don't have Linux alternatives - so this doesn't seem very viable.

**Comment by sebma** [comment]
@shikhir-arora Hi, why not first create a new brew cask image format specific to Linux ?

**Comment by sjackman** [comment]
No, we have no plans to implement `brew cask` in Linuxbrew. Here's a couple of other projects that tackle this use case.
https://snapcraft.io/store
https://flathub.org/home
