### ISSUE TITLE
Ubuntu 18.04 - brew install php (cannot install)

### ISSUE THREAD

**Issue by ghost** [Linuxbrew/brew#743]
**Please fill out the issue checklist below and provide all the requested information.**

- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
  Fresh install of Ubuntu 18.04 & Brew, ran `brew install php` and it failed at 3 different points. ZLib check, BZip2 Check & Berkeley DB check. When installing those packages through apt it passes and moves on to the next one however im still stuck at the QDBM & GDBM packages. It seems that although the proper paths were added to ~/.bashrc it seems it does not use those paths for the checks when running install php. For example, i also installed composer and it did not install the php automatically, when running 'composer' it also says php no such file or directory referring to /usr/bin/env.

- What happened (include command output)
  when running 'brew install php'

```==> Downloading https://php.net/get/php-7.2.7.tar.xz/from/this/mirror
Already downloaded: /home/incog/.cache/Homebrew/php-7.2.7.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/php/7.2.7 --localstat
Last 15 lines from /home/incog/.cache/Homebrew/Logs/php/01.configure:
checking for libcurl.pc... using /home/linuxbrew/.linuxbrew/opt/curl/lib/pkgconfig/libcurl.pc
checking for cURL 7.10.5 or greater... 7.60.0
checking for SSL support in libcurl... yes
checking how to run the C preprocessor... gcc-5 -E
checking for openssl support in libcurl... yes
checking openssl/crypto.h usability... yes
checking openssl/crypto.h presence... yes
checking for openssl/crypto.h... yes
checking for gnutls support in libcurl... no
checking for curl_easy_perform in -lcurl... yes
checking for curl_easy_strerror in -lcurl... yes
checking for curl_multi_strerror in -lcurl... yes
checking for QDBM support... no
checking for GDBM support... no
configure: error: DBA: Could not find necessary header file(s).```

brew config

HOMEBREW_VERSION: 1.6.9
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 3ba4c2ed9b0587040949a4a9a95b576f520bae84
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: de1386470742d1a55e3aa637ee9f6f8a9bb4fa4e
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/incog/.cache/Homebrew
CPU: quad-core 64-bit 0x1630
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.15.0-23-generic x86_64 GNU/Linux
OS: Ubuntu 18.04 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A```

- What you expected to happen
  Install php

- Step-by-step reproduction instructions (by running `brew` commands)
  ```sudo apt install linuxbrew-wrapper
  brew```
  added the following 3 paths to end of ~/.bashrc;
  
 ```export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  export MANPATH="/home/linuxbrew/.linuxbrew/share/man:$MANPATH"
  export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH"```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by ghost** [comment]
@sjackman Thanks, tried it just doesn't seem to wrap correctly anyways.

**Comment by sjackman** [comment]
Please report issues with individual formula to [Linuxbrew/core](https://github.com/Linuxbrew/homebrew-core).

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-core#8373
