### ISSUE TITLE
Build binutils, patchelf and zlib with centos 6

### ISSUE THREAD

**Issue by iMichka** [Linuxbrew/brew#756]
There is an update of the binutils formula. Following the instructions here (https://github.com/Linuxbrew/brew/wiki/Build-a-portable-bottle), it needs to be built on centos 5.

Installing linuxbrew on centos 5 is not working anymore, as GitHub and Bintray have moved to tls 1.2 (centos 5 has only tls 1.1).
These instructions are not working anymore: https://github.com/Linuxbrew/brew/wiki/CentOS5

The patches in the docker file could be moved from gist.gitbub to pastebin (this works).
The portable ruby bottle could be hosted on a server that does not require tls 1.2. But users may hit other issues down the road on centos 5. To me it looks that system is really unusable now.

The instructions say:
> Linuxbrew supports host systems with glibc 2.5 and newer.
This would change to:
> Linuxbrew supports host systems with glibc 2.12 and newer.

All other bottles requite glibc 2.19 or better. (we could update the main readme to reflect both requirements), as the 2.5/2.12 glibc information can only be found in the wiki.

I would then build the next binutils bottles on centos 6.
This could be coupled with the brew 1.7.0 release which is ready to be merged.

I am trying to find out if there is any minimum kernel version needed. The install file from glibc 2.12 talks about kernel 2.2, so this is lower than the expected kernel 2.6.16 from our readme, so we should be fine here.

Any thoughts?

**Comment by sjackman** [comment]
Mike built the recently updated portable-ruby bottle on CentOS 6. I was planning to rebuild that bottle for CentOS 5 when I got back. Now may be a good time however to drop support for CentOS 5. I’m okay with that. Let’s post a comment on Linuxbrew Updates saying so and update the README with the release of 1.7.0.

**Comment by iMichka** [comment]
Release 1.7.0 has been merged. I'll tag it after the documentation update and some bottle builds.
Wiki pages have already been updated.

Trying to build binutils right now. It works on my ubuntu 18 setup, but not on centos 6 ...
I updated the documentation and these are the steps I am following: https://github.com/Linuxbrew/brew/wiki/Build-a-portable-bottle

```
==> ./configure  --with-sysroot=/ --enable-deterministic-archives --prefix=/home/linuxbrew/.linuxbrew/Cellar/binutils/2.31 --infodir=/home/linuxbrew/.linuxbrew/Cellar/binutils/2.31/
==> make
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/binutils/02.make:
configure: error: C compiler cannot create executables
See `config.log' for more details
checking for x86_64-pc-linux-gnu-ar... ar
checking for x86_64-pc-linux-gnu-ranlib... ranlib
checking whether to install libiberty headers and static library... no
configure: target_header_dir = 
checking for x86_64-pc-linux-gnu-gcc... gcc-4.4
make[1]: *** [configure-intl] Error 1
make[1]: *** Waiting for unfinished jobs....
checking for suffix of object files... configure: error: in `/tmp/binutils-20180720-235-lt1ca9/binutils-2.31/libiberty':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details
make[1]: *** [configure-libiberty] Error 1
make[1]: Leaving directory `/tmp/binutils-20180720-235-lt1ca9/binutils-2.31'
make: *** [all] Error 2
```

**Comment by iMichka** [comment]
The log file is quite unhelpful ... but on centos 6 I get the following when building zlib from source. `gcc-4.4: Command not found`. And there is no gcc-4.4 installed on the system, only gcc and g++.

The symlinks are created correctly though:
```
[linuxbrew@d1aa7876f454 ~]$ ls -l /home/linuxbrew/.linuxbrew/bin/
total 0
lrwxrwxrwx 1 linuxbrew linuxbrew 44 Jul 20 21:44 brew -> /home/linuxbrew/.linuxbrew/Homebrew/bin/brew
lrwxrwxrwx 1 linuxbrew linuxbrew 12 Jul 20 21:45 g++-4.4 -> /usr/bin/g++
lrwxrwxrwx 1 linuxbrew linuxbrew 12 Jul 20 21:45 gcc-4.4 -> /usr/bin/gcc
lrwxrwxrwx 1 linuxbrew linuxbrew 37 Jul 20 21:47 patchelf -> ../Cellar/patchelf/0.9_1/bin/patchelf
```

**Comment by iMichka** [comment]
`brew install hello` gives:

```
make[2]: Leaving directory `/tmp/hello-20180720-5450-1v6oot/hello-2.10/po'
make[2]: Entering directory `/tmp/hello-20180720-5450-1v6oot/hello-2.10'
rm -f lib/charset.alias-t lib/charset.alias && \
	/bin/sh ./lib/config.charset 'x86_64-unknown-linux-gnu' > lib/charset.alias-t && \
	mv lib/charset.alias-t lib/charset.alias
rm -f lib/ref-add.sed-t lib/ref-add.sed && \
	sed -e '/^#/d' -e 's/@''PACKAGE''@/hello/g' lib/ref-add.sin > lib/ref-add.sed-t && \
	mv lib/ref-add.sed-t lib/ref-add.sed
rm -f lib/ref-del.sed-t lib/ref-del.sed && \
	sed -e '/^#/d' -e 's/@''PACKAGE''@/hello/g' lib/ref-del.sin > lib/ref-del.sed-t && \
	mv lib/ref-del.sed-t lib/ref-del.sed
gcc-4.4 -DLOCALEDIR=\"/home/linuxbrew/.linuxbrew/Cellar/hello/2.10/share/locale\" -DHAVE_CONFIG_H -I.  -Ilib -I./lib -Isrc -I./src   -g -O2 -c -o lib/c-ctype.o lib/c-ctype.c
make[2]: gcc-4.4: Command not found
```

**Comment by iMichka** [comment]
```
configure:4014: checking whether the C compiler works
configure:4036: gcc-4.4    conftest.c  >&5
r)
per/gcc-4.4:428:in `<main>'
configure:4040: $? = 1
configure:4078: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU Hello"
| #define PACKAGE_TARNAME "hello"
| #define PACKAGE_VERSION "2.10"
| #define PACKAGE_STRING "GNU Hello 2.10"
| #define PACKAGE_BUGREPORT "bug-hello@gnu.org"
| #define PACKAGE_URL "http://www.gnu.org/software/hello/"
| #define PACKAGE "hello"
| #define VERSION "2.10"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:4083: error: in `/tmp/hello-20180720-4982-1iun87h/hello-2.10':
configure:4085: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by iMichka** [comment]
When this failed we had:
```
==> ENV
HOMEBREW_CC: gcc-4.4
HOMEBREW_CXX: g++-4.4
```

**Comment by iMichka** [comment]
I found a hack:
```
# Create symlinks for GCC 4.4
sudo ln -s /usr/bin/gcc /usr/bin/gcc-4.4
sudo ln -s /usr/bin/g++ /usr/bin/g++-4.4
```

**Comment by iMichka** [comment]
Current status of this issue: 1.7.0 was tagged, the wiki page was updated, and the README was updated. Support for centos 5 was dropped and glibc 2.12 is required. The `binutils` bottle was built and uploaded.

The only remaining problem is the weird hack I needed to use to get Linuxbrew going on centos 6:
> sudo ln -s /usr/bin/gcc /usr/bin/gcc-4.4
sudo ln -s /usr/bin/g++ /usr/bin/g++-4.4

**Comment by iMichka** [comment]
@sjackman any idea why I need to run:
```
sudo ln -s /usr/bin/gcc /usr/bin/gcc-4.4
sudo ln -s /usr/bin/g++ /usr/bin/g++-4.4
```

to make this work? I think this is the last outstanding problem in this ticket.

**Comment by sjackman** [comment]
Those symlinks are meant to be created by `Install.symlink_host_gcc`. Evidently that code is not working in this case. Do you have time to troubleshoot?

https://github.com/Linuxbrew/brew/blob/58c5c32ba35f7e22f1cf20a8e62891d3009b8418/Library/Homebrew/install.rb#L76-L88

**Comment by sjackman** [comment]
I'm closing this issue since no one is actively working on it. The original issue was that @iMichka was unable to build `binutils` on CentOS 6. See https://github.com/Linuxbrew/brew/issues/756#issuecomment-406712116

**Comment by iMichka** [comment]
Yeah, sorry. I do not have much time to troubleshoot this. Closing for the moment.
