### ISSUE TITLE
moreutils: The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by chubin** [Linuxbrew/brew#76]
```
==> Installing moreutils
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/m/moreutils/moreutils_0.58.orig.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/m/moreutils/moreutils_0.58.orig.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "moreutils"
Download failed: https://mirrorservice.org/sites/ftp.debian.org/debian/pool/main/m/moreutils/moreutils_0.58.orig.tar.gz
```

This version is indeed unavailable on the server, but there is another one: 59.1

**Comment by sjackman** [comment]
I'm at a conference and will merge Homebrew/core into Linuxbrew once I get back in about a week, which will fix this bug. Sorry for the delay.

In the mean time you have three options:
`brew install homebrew/dupes/less` or
`brew install --HEAD moreutils` or
`brew edit moreutils` and update the URL and remove the `sha256`.
