### ISSUE TITLE
CentOS 7 install error. 

### ISSUE THREAD

**Issue by w-hc** [Linuxbrew/brew#760]
https://gist.github.com/w-hc/ba39f7b2f99651ff2d7d6d8d142dd77d

Above is the gist of brew -config, brew doctor and brew install.
It seems that brew cannot find my system gcc, and the alias it creates for gcc-4.8 somehow fails. I have tried to manually set --cc but got the error invalid value. See gist. 

Thank you so much.

**Comment by w-hc** [comment]
The login node on which I am installing this has the following CPU:
```
Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
```
This CPU is rather old and I am not sure how this plays out with the gcc version

**Comment by w-hc** [comment]
okay for now the issue seems resolved. 
My cluster has a login node with old CPUs and compute nodes with new CPUs. 
1. I used the solution mentioned in #340 with the following line:
```
brew install --env=std glibc && brew install gcc
```
2. More importantly, I ran the above command on the login node with old CPU. If I do not do this, gcc compiled on compute node would trigger Illegal Instruction error on the login node. Any programs compiled using this gcc on compute node would also throw Illegal Instruction error as well. 

3. As long as I compiled gcc on the login node, any subsequent packages can be compiled with this new gcc on the compute node. This is good since compiling on login node is bad practice. 

Out system admin ppl in general advise us to compile things on compute nodes to reduce the pressure on login node. But in this case, I must go for the weakest link. 

__Still__, I don't quite understand why step 1 is needed.

**Comment by w-hc** [comment]
strangely when I go into linuxbrew/lib, and do ls, there is a segfault. This may be related to using different compilers. Otherwise installing packages work for now.

**Comment by iMichka** [comment]
Hi.

> It seems that brew cannot find my system gcc, and the alias it creates for gcc-4.8 somehow fails.

I think something is broken in the symlink setup (see https://github.com/Linuxbrew/brew/issues/756#issuecomment-411473576), I need to have a closer look.

> strangely when I go into linuxbrew/lib, and do ls, there is a segfault

This is probably not related to brew.

**Comment by sjackman** [comment]
`export HOMEBREW_ARCH=core2` may be useful to you, if you you're compiling on a newer machine and running on an older machine. See https://github.com/Linuxbrew/brew/issues/208

**Comment by w-hc** [comment]
Thank you for the help!

**Comment by sjackman** [comment]
Closing this issue. Feel free to follow up if you have further questions.

**Comment by w-hc** [comment]
sure
