### ISSUE TITLE
Can't install linuxbrew with non-root user even though that user has passwordless sudo

### ISSUE THREAD

**Issue by rex** [Linuxbrew/brew#764]
**Please fill out the issue checklist below and provide all the requested information.**

- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Attempting to install Linuxbrew onto an ubuntu machine
- What happened (include command output)
Installation failed because it's asking for a password that simply does not exist. The user in question is an automated user and was explicitly created without a password.

```deploy@pierce:~$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
==> Select the Linuxbrew installation directory
- Enter your password to install to /home/linuxbrew/.linuxbrew (recommended)
- Press Control-D to install to /home/deploy/.linuxbrew
- Press Control-C to cancel installation
[sudo] password for deploy:
```

- What you expected to happen
I expected to be able to install the software
- Step-by-step reproduction instructions (by running `brew` commands)
Same as above. 

I went through issue #574 and can confirm that the "new" way to detect sudo works for this user:

```
deploy@pierce:~$ sudo -v; echo $?
[sudo] password for deploy:
1
deploy@pierce:~$ sudo -ln mkdir; echo $?
/bin/mkdir
0
```

It would be really fantastic if we could begin using Linuxbrew on our CI systems because of the simplicity it provides us, but we can't use it unless it can be installed by this or some other non-root user.

**Comment by iMichka** [comment]
Hi. I see that #574 did not end in any decision or implementation. Would you like to pick this up and propose a pull request?

**Comment by sjackman** [comment]
> Installation failed because it's asking for a password that simply does not exist. The user in question is an automated user and was explicitly created without a password.

Can you configure `sudo` to have passwordless access? See for example
https://github.com/Linuxbrew/brew/blob/4ff4e7f32fcb854b334c529351a8bb8133dca674/Dockerfile#L10

**Comment by sjackman** [comment]
If your CI system is using Docker, you could consider using the `linuxbrew/linuxbrew` Docker image as your base image.

**Comment by rex** [comment]
@iMichka Just created a PR for the installer :)
