### ISSUE TITLE
Why not port homebrew to all UNIX-like system ?

### ISSUE THREAD

**Issue by iamybj** [Linuxbrew/brew#768]
I use homebrew in my macbook, and I just find linuxbrew.
So, why not make homebrew be a all unix-like system package manager?
We can use subcommand install system separated software.

brew install xxx
brew install mac/xxx
brew install linux/xxx
brew install bsd/xxx

**Comment by sjackman** [comment]
Linuxbrew/brew is a fork of Homebrew/brew, and quite recently, Linuxbrew/brew has been (mostly) merged into Homebrew/brew, so that Homebrew/brew is now able to run on either macOS or Linux.
