### ISSUE TITLE
fish failed to build

### ISSUE THREAD

**Issue by au5ton** [Linuxbrew/brew#770]
**Please fill out the issue checklist below and provide all the requested information.**

- [X] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I was trying to install [fish](https://fishshell.com/)
- What happened (include command output)
Fish failed to install. See: https://gist.github.com/au5ton/93aee61d84da16a107042ff668b69686
- What you expected to happen
I expected fish to install successfully.
- Step-by-step reproduction instructions (by running `brew` commands)
`brew install fish`

**Comment by iMichka** [comment]
Hi. Please report this to the right repository: https://github.com/Linuxbrew/homebrew-core
