### ISSUE TITLE
bump-formula-pr throwing "could not read Username for 'https://github.com': No such device or address"

### ISSUE THREAD

**Issue by Daniel15** [Linuxbrew/brew#772]
I filed this in the Homebrew repo (https://github.com/Homebrew/brew/issues/4602) but they said that they don't support Linuxbrew so I'm cross-posting here.

___

- [x] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

For Yarn, we have a script that automatically pushes new versions to Homebrew. It's started failing with this error:
```
fatal: could not read Username for 'https://github.com': No such device or address
```

Example command:
```
BROWSER=/bin/true brew bump-formula-pr --strict yarn --url=https://yarnpkg.com/downloads/1.9.4/yarn-v1.9.4.tar.gz --sha256=7667eb715077b4bad8e2a832e7084e0e6f1ba54d7280dc573c8f7031a7fb093e '--message=This PR was automatically created via a script. Contact @Daniel15 with any questions.'
```
Full output: https://build.dan.cx/job/yarn-homebrew/51/console

I tried running the command manually, and it looks like it's prompting for the username and password?
```
Switched to a new branch 'yarn-1.9.4'
[yarn-1.9.4 5df7f2f502] yarn 1.9.4
 1 file changed, 2 insertions(+), 2 deletions(-)
Username for 'https://github.com': DanBuild
Password for 'https://DanBuild@github.com':
Counting objects: 18472, done.
Compressing objects: 100% (6324/6324), done.
```

Note: I am actually using Linuxbrew as the build system is on Linux, however AFAIK this still uses Homebrew's implementation of `bump-formula-pr`.

`brew config`:
```
jenkins@build03:~$ brew config
HOMEBREW_VERSION: 1.7.1-1-gc46aef1
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: c46aef12fef6a29746df86640628ea2e61f6afe1
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/homebrew/homebrew-core
Core tap HEAD: 4c8f7c1f11b463c93b504503f4e80f2a82a3805a
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /var/lib/jenkins/.linuxbrew
HOMEBREW_REPOSITORY: /var/lib/jenkins/.linuxbrew
HOMEBREW_CELLAR: /var/lib/jenkins/.linuxbrew/Cellar
HOMEBREW_CACHE: /var/lib/jenkins/.cache/Homebrew
HOMEBREW_BOTTLE_DEFAULT_DOMAIN_LINUX: https://linuxbrew.bintray.com
HOMEBREW_BOTTLE_DEFAULT_DOMAIN_MACOS: https://homebrew.bintray.com
HOMEBREW_DEV_CMD_RUN: 1
CPU: single-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /var/lib/jenkins/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.11.0 => /bin/git
Curl: 7.52.1 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.16.0-1-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 9.4 (stretch) (stretch)
Host glibc: 2.24
/usr/bin/gcc: 6.3.0
glibc: N/A
gcc: N/A
xorg: N/A
```

**Comment by iMichka** [comment]
Mac formulae get merged daily to linuxbrew-core. So if a version bump happens, this needs to be done upstream in the homebrew-core repository, using brew bump-formula-pr, on a mac.

There is one exception, there are some formulae here that are linux only. In that case brew bump-formula-pr could be used. But we often do this by hand.
So `brew bump-formula-pr` is probably not what you need for your specific update, as you need to do that in the mac repo first.

Of course we would accept a PR to fix `brew bump-formula-pr` on Linux, which may be needed in the long run if we decide one day to merge linuxbrew-core into homebrew-core.

**Comment by Daniel15** [comment]
> if a version bump happens, this needs to be done upstream in the homebrew-core repository, using brew bump-formula-pr, on a mac.

Since I don't have a Mac build machine handy, I'm actually using Linuxbrew to run `bump-formula-pr` against the `homebrew-core` repo, which is a bit weird but it works. Here's the script: https://github.com/yarnpkg/yarn/blob/master/scripts/update-homebrew.sh

Anyways, I figured out the issue at https://github.com/yarnpkg/yarn/issues/6224: `bump-formula-pr` uses HTTPS authentication, but I only had SSH auth configured on the build server.
