### ISSUE TITLE
fails to download Bottles

### ISSUE THREAD

**Issue by Lesmiscore** [Linuxbrew/brew#780]
**Please fill out the issue checklist below and provide all the requested information.**

- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

`brew config`

```
HOMEBREW_VERSION: 1.7.1
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 468d869022ebe725d7b7745adfa872db3e6c16c9
Last commit: 13 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: aa25e19bd132847fb1fecdd9db5de4444d750019
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /home/nao20010128/.brew
HOMEBREW_REPOSITORY: /home/nao20010128/.brew
HOMEBREW_CELLAR: /home/nao20010128/.brew/Cellar
HOMEBREW_CACHE: /home/nao20010128/.cache/Homebrew
HOMEBREW_BOTTLE_DEFAULT_DOMAIN_LINUX: https://linuxbrew.bintray.com
HOMEBREW_BOTTLE_DEFAULT_DOMAIN_MACOS: https://homebrew.bintray.com
CPU: single-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /home/nao20010128/.brew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 6.0 build 600
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Java: N/A
Kernel: Linux 4.15.0-20-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.1 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.3.0
glibc: N/A
gcc: N/A
xorg: N/A
```

`brew doctor`
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!
```

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade Formulaes with Bottles
- What happened (include command output)

`brew upgrade`

```
==> Upgrading icu4c
==> Downloading /bottles/icu4c-62.1.x86_64_linux.bottle.tar.gz
curl: (3) <url> malformed
Error: Failed to download resource "icu4c"
Download failed: /bottles/icu4c-62.1.x86_64_linux.bottle.tar.gz
```
- What you expected to happen
Bottles are downloaded and used.
- Step-by-step reproduction instructions (by running `brew` commands)
`brew upgrade`
Conditions: You need old Formulae installed which has Bottle.

**Comment by sjackman** [comment]
That's pretty weird. I haven't seen that error before, and I'm not able to reproduce it. Here's the expected output:
```
$ brew fetch icu4c
==> Downloading https://linuxbrew.bintray.com/bottles/icu4c-62.1.x86_64_linux.bo
######################################################################## 100.0%
Downloaded to: /gsc/btl/linuxbrew/var/cache/homebrew/icu4c--62.1.x86_64_linux.bottle.tar.gz
SHA256: d13472ec966b71ee9c4acbb961d37f64eeb729657f6c51233ecc3670624a1c53
```

Please report `env | grep HOMEBREW`

**Comment by sjackman** [comment]
Please also report the output of `brew irb <<<HOMEBREW_BOTTLE_DEFAULT_DOMAIN`

**Comment by Lesmiscore** [comment]
`brew fetch icu4c` worked as expected. 

`env | grep HOMEBREW`
Empty.

`brew irb <<<HOMEBREW_BOTTLE_DEFAULT_DOMAIN`
```
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
Switch to inspect mode.
HOMEBREW_BOTTLE_DEFAULT_DOMAIN
"https://linuxbrew.bintray.com"
```

**Comment by sjackman** [comment]
What happens now when you run `brew upgrade`?

**Comment by Lesmiscore** [comment]
Downloading worked well.

**Comment by sjackman** [comment]
Glad to hear it. I can't say what wrong previously.
