### ISSUE TITLE
Relocate RPATH

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/brew#8]
When installing a bottle, Linuxbrew uses `patchelf` to wipe out the existing `RPATH` and replace it with `$HOMEBREW_PREFIX/lib`, which is overly simplistic. The fix is pretty straight forward. The `RPATH` in the bottle needs to fixed up to relocate `@@HOMEBREW_PREFIX@@` to `$HOMEBREW_PREFIX` and then add `$HOMEBREW_PREFIX/lib` if it's missing, probably to the end of the list.

**Comment by DoomHammer** [comment]
I'd say you need to replace `/home/linuxbrew/.linuxbrew` with `$HOMEBREW_PREFIX` as well in existing `RPATH`

**Comment by DoomHammer** [comment]
```
patchelf --print-rpath perl/5.22.1/bin/perl
/home/linuxbrew/.linuxbrew/Cellar/perl/5.22.1/lib/5.22.1/x86_64-linux-thread-multi/CORE
```

vs

```
patchelf --print-rpath hello/2.10/bin/hello                                                                                                             
@@HOMEBREW_PREFIX@@/lib
```

**Comment by DoomHammer** [comment]
Something like #35?

**Comment by sjackman** [comment]
> I'd say you need to replace /home/linuxbrew/.linuxbrew with $HOMEBREW_PREFIX as well in existing RPATH

Yes, that prefix should not exist in bottles, but a few bottles were being built without `patchelf` installed if they didn't themselves depend on any bottles, and those bottles have the `RPATH` set to `/home/linuxbrew/.linuxbrew/lib` rather than `@@HOMEBREW_PREFIX@@/lib`.

**Comment by sjackman** [comment]
My plan was to remove any `RPATH` variables that did not start with `@@HOMEBREW_PREFIX@@` and then append `$HOMEBREW_PREFIX/lib` to the `RPATH` if it did not already contain it.

**Comment by sjackman** [comment]
```
patchelf --print-rpath perl/5.22.1/bin/perl
/home/linuxbrew/.linuxbrew/Cellar/perl/5.22.1/lib/5.22.1/x86_64-linux-thread-multi/CORE
```

``` sh
brew install patchelf
brew install --build-bottle perl
brew bottle perl
tar xf perl*bottle*.tar.gz
```

You should see that all the `/home/linuxbrew/.linuxbrew` in `RPATH` and text files have been replaced by `@@HOMEBREW_PREFIX@@`. It's a bug if not.

**Comment by DoomHammer** [comment]
Hmm, I'll check if I had `patchelf` in place when bottling `perl`.

**Comment by DoomHammer** [comment]
The missing `patchelf` was the problem. Shall we allow bottling without `patchelf`?

**Comment by DoomHammer** [comment]
Same question about using system `gcc`?

**Comment by sjackman** [comment]
> Shall we allow bottling without `patchelf`?

Probably not. It should give an error and exit.

**Comment by sjackman** [comment]
> Same question about using system `gcc`?

I do want to support using the system `gcc`. The bottles are built on Ubuntu 14 using `glibc 2.19` and `gcc 4.8` by design so that those bottles can be run on Ubuntu 14 and newer distros without requiring that they install either Linuxbrew `glibc` or `gcc`.

**Comment by DoomHammer** [comment]
Original issue is no more thanks to #35. Talks about whether `patchelf` is needed for bottling can be split to separate issue.
