### ISSUE TITLE
Can't install pkg-config

### ISSUE THREAD

**Issue by smprather** [Linuxbrew/brew#80]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
### Bug reports:

```
$ brew install gcc
Warning: gcc-5.3.0 already installed

$ brew install pkg-config
Error: pkg-config cannot be built with any available compilers.
To install this formula, you may need to either:
  brew install apple-gcc42
or:
  brew install gcc

$ which gcc
/remote/us01home20/myles/.linuxbrew/bin/gcc

$ ldd --version
ldd (GNU libc) 2.19
```

**Comment by sjackman** [comment]
Odd. I haven't been able to reproduce this issue myself. Please report the output of:

``` sh
brew config
brew doctor
```

**Comment by bw-yuhogg** [comment]
@sjackman similar errors occured in the issue #78 

I've never seen it happen outside of the tests though.

**Comment by sjackman** [comment]
Try
`brew install --cc=gcc-5 pkg-config`
