### ISSUE TITLE
What happened with the standalone installation?

### ISSUE THREAD

**Issue by OmeGak** [Linuxbrew/brew#81]
I've been not following up with recent developments in Linuxbrew, but something that brought a great deal of problems for me last time I installed it was setting up my standalone installation. Now I can't find any trace of it anywhere and I saw this in README.md:

> Bottles are Linuxbrew's precompiled binary packages. Linuxbrew bottles work on any Linux system. They do however require glibc 2.19 or better. On systems with an older version of glibc, Linuxbrew will install glibc the first time that you install a bottled formula

Does it mean that I don't have to worry about it anymore? :D

**Comment by sjackman** [comment]
That's right! Right after a clean installation of Linuxbrew, I recommend running `brew install gcc`. On a system with `glibc` older than 2.19, it will start by installing `glibc`. That's all you need to do!
