### ISSUE TITLE
Linuxbrew no longer uses a bottle when installing binutils

### ISSUE THREAD

**Issue by andrewyatz** [Linuxbrew/brew#811]
Not sure if this has been raised before (please slap me down otherwise). Recently I have noticed that binutils attempts to recompile itself on my Linuxbrew installations. I do not install to the `~linuxbrew/.brew` location and am using a non-standard root. However I am sure that binutils could be installed using a relocatable bottle. 

Has anything changed recently in brew to stop this feature?

**Comment by jonchang** [comment]
You can try `brew install --force-bottle binutils`

**Comment by andrewyatz** [comment]
Hi. That does work and brew doesn't complain. However it's really odd that
brew now chooses not to use the binutils bottle.

**Comment by jonchang** [comment]
Yes, it's a known issue, Homebrew could be better at detecting whether bottles could be relocated.

**Comment by jonchang** [comment]
Actually, binutils is a special case, check out https://github.com/Linuxbrew/brew/wiki/Build-a-portable-bottle

**Comment by jonchang** [comment]
Fixed in https://github.com/Linuxbrew/homebrew-core/commit/5041f9e7a6b2ab41c75827fc8fd05b29a09939f7

**Comment by andrewyatz** [comment]
Fantastic thank you :)
