### ISSUE TITLE
Error installing Conan which depends on python@2

### ISSUE THREAD

**Issue by acgetchell** [Linuxbrew/brew#828]
**Please fill out the issue checklist below and provide all the requested information.**

- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

Using LInuxbrew to install Conan, which requires python.

==> Installing conan dependency: python@2
==> Downloading https://www.python.org/ftp/python/2.7.15/Python-2.7.15.tar.xz
Error: undefined method `sdk_path_if_needed' for OS::Mac:Module

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/420677681#L991

My Travis-CI setup to get Linuxbrew to run is here:

https://github.com/acgetchell/CDT-plusplus/blob/feature/conan/.travis.yml

Note that on the osx images, Conan installs fine.

**Comment by sjackman** [comment]
Thanks for the bug report, Adam.
Duplicate of https://github.com/Linuxbrew/brew/issues/828
Fixed by PR https://github.com/Linuxbrew/homebrew-core/pull/9073

**Comment by tekpriest** [comment]
I just experienced this issue while trying to install php7.2
`brew install php@7.2`
The results
`
./buildconf --force
Error: An exception occurred within a child process:
  NoMethodError: undefined method `sdk_path_if_needed' for OS::Mac:Module
`

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
The formula `php@7.2` is not found in Linuxbrew/core. You'll need to contact the tap maintainer and ask them whether they'll consider supporting Linux.
