### ISSUE TITLE
Is gcc required if you plan to only install bottles (pre-built bins)?

### ISSUE THREAD

**Issue by andrevtg** [Linuxbrew/brew#83]
If dependencies are minimized Linuxbrew would be an _awesome_ to produce safer (non-root) Docker images.

I may be doing something wrong, but even if try to install just pre-built bottles it still requires  gcc (and some more stuff). Can requirements be reduced for "bottle-only" use?

**Comment by sjackman** [comment]
Programs compiled with C++ depend on `libstdc++.so.6` which is included in `gcc`, which is why precompiled binary bottles depend on `gcc`. This is true only of Linux distributions with `glibc` older than 2.19. On Ubuntu trusty 14 or newer we use the host's `glibc` and `gcc`. What distribution of Linux are you using?

**Comment by andrevtg** [comment]
I am trying to use Linuxbrew to create small CentOS-based Docker images with more recent versions of stuff that is quite old in their repo (like zsh, for example).

By small I mean no dev tools. :)

So my distro is the "centos:7" Docker image (glibc 2.17), but I am trying with other base images too. I'll try trusty now.

Tnx!

**Comment by staticfloat** [comment]
For what it's worth, I've written formulae to steal runtime libraries from `gcc` (in my case, `libgfortran`), bottle them up in a different formula ([`libgfortran.rb`](https://github.com/staticfloat/homebrew-juliadeps/blob/c5f2c96fe298588821150e1c1fcc1d7ecb33fe84/libgfortran.rb)) and then add `post_install` steps to all the bottles that rely on `libgfortran`.  Here's an example of what it looks like in the formula for [`ipopt.rb`](https://github.com/staticfloat/homebrew-juliadeps/blob/c5f2c96fe298588821150e1c1fcc1d7ecb33fe84/ipopt.rb#L18-L21).

It's possible it create a special `libstdc++` formula which does something similar to what `libgfortran` is doing above: steal the libraries from a full `gcc` installation, rewrite their install names, and bottle them up.  You would then install the `libstdc++` formula whenever it is needed and `gcc` is not already installed, and you'd need to perform some steps for any formulae that are looking for `libstdc++.so` to point them from looking in the `gcc` keg and instead look inside the `libstdc++` keg.

Possibly more trouble than its worth except on very resource-constrained systems.

**Comment by sjackman** [comment]
> Possibly more trouble than its worth except on very resource-constrained systems.

I thought of doing something like this, and yeah, more trouble than it's worth is sort of the conclusion that I came to, though I do like the idea. How do you avoid `gcc` and `libstdc++` from conflicting with each other?

**Comment by staticfloat** [comment]
I would set `libstdc++` to be `keg_only`, then in the `post_install` step rewrite the shared library paths to point to the opt path of the `libstdc++` keg.  You would run the risk of `gcc` being updated and having newer versions of the libraries, so you'd have to keep `libstdc++` updated as fast as `gcc` is.

**Comment by sjackman** [comment]
That's a simple solution. I like it. `gcc` is almost a gigabyte when extracted. Packaging `libstdc++` isn't a high priority for me, but it's something I'd consider.

**Comment by staticfloat** [comment]
I can work up a PR if you like.  I've already thought through a lot of this kind of stuff with my `libgfortran` formula.  The main thing I don't like about this is that we would have to add a `post_install` step to every formula that uses a C compiler, which is essentially all of them.

**Comment by sjackman** [comment]
Each formula doesn't require a `post_install` block. We would need to add the `lib` directory of `libstdc++` to the default library search path and `RPATH`.

I can't guarantee that we will merge the PR, as it adds complexity to save disk space, and installing `gcc` is also my first recommendation when a user compiling a package from source fails, but it's worth discussing. I don't want to waste your time though.

**Comment by staticfloat** [comment]
Ah, that's right, linux doesn't hardcode absolute paths.  I forgot.  :)
