### ISSUE TITLE
Install gettext - Missing dependency libxml

### ISSUE THREAD

**Issue by vork** [Linuxbrew/brew#832]
- [x] have a problem with `brew install gettext`
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs gettext` and included the output link? https://gist.github.com/dc6d82c78389d5699fbea44614864539

Running `brew install gettext` is failing due to a dependency to libxml in libcroco

**Comment by sjackman** [comment]
Please fill out the issue template. In particular:

- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
