### ISSUE TITLE
brew audit --strict  is different on TRAVIS/CIRCLE

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/brew#841]
Locally, with `brew audit --strict --online` I am allowed to do

* `head "*http:// .... .git"`
* `depends_on` can non-alphabetical

But when i submit a formula these both fail audit.

**Comment by sjackman** [comment]
Try…
```sh
brew audit --strict --online --new-formula
```

**Comment by tseemann** [comment]
Ok thanks - i didn't know that. No wonder i've been randomly confused for so long. I will update my `brew-audit` alias!

**Comment by sjackman** [comment]
I'm regularly surprised by things I didn't know about Homebrew.

**Comment by tseemann** [comment]
I'm NOT surprised...  `brew -h` is still a shambles.
