### ISSUE TITLE
pkg-config and super env on Linux

### ISSUE THREAD

**Issue by maxim-belkin** [Linuxbrew/brew#848]
Currently, `xorg` formulae are picked up even if they're not dependencies of the formula being built. This is not a problem for users but is for "developers": one has to uninstall _all_ currently installed formulae to make sure that nothing is picked up and all required dependencies are brought in by declarations within the formula.

I suspect the problem is coming from `homebrew_extra_pkg_config_paths` in `Library/Homebrew/extend/os/linux/extend/ENV/super.rb`. Thoughts?

**Comment by sjackman** [comment]
Probably this here:
https://github.com/Linuxbrew/brew/blob/1699a7ec1347679daf102f9a8b4cc43e902aa002/Library/Homebrew/extend/os/linux/extend/ENV/super.rb#L86-L96

I agree it'd be great to back out these patches if we're no longer using `depends_on :x11`.

**Comment by sjackman** [comment]
@maxim-belkin Would you like to test and open a PR to remove all the magic `xorg` hackery from `extend/ENV/super.rb`?

**Comment by maxim-belkin** [comment]
I've done it locally already - just didn't have a chance to submit a PR

**Comment by maxim-belkin** [comment]
quick question: I was replacing contents of functions with `[]` so they return no "extra" paths. I guess we can also simply delete them right?

**Comment by sjackman** [comment]
Yes, those empty functions can be deleted.

**Comment by sjackman** [comment]
I believe this issue was resolved by https://github.com/Linuxbrew/brew/commit/9769fb22fe2cef2dc00420111fd4ecf5b19e5c0d

**Comment by maxim-belkin** [comment]
I think you're right (no time to test it at the moment though)
