### ISSUE TITLE
using system python and pip

### ISSUE THREAD

**Issue by ahundt** [Linuxbrew/brew#85]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

I'm dealing with something similar to #55 , I added a python package requirement `requires 'pybindgen' => :python` to one of my custom packages and I'm trying to use the system python. However, I think the dependency is being checked on the linuxbrew python so it fails.

I'm trying to automate some stuff so I know I can manually workaround by installing the same thing on the other python but that probably won't be what I want to tell other users of my code. Are there other options?

```
± brew install tasks
==> Installing tasks from ahundt/robotics
spacevecalg: Unsatisfied dependency: pybindgen
Homebrew does not provide special Python dependencies; install with:
  `pip install pybindgen`
Error: An unsatisfied requirement failed this build.
-> [1]
```

https://gist.github.com/9b6cecf699d68e16e3f714ee79393264

**Comment by sjackman** [comment]
Whichever Python is first in the `PATH` should be used by Linuxbrew. If Linuxbrew `python` is installed, that should be used in preference to the system `python`. `brew unlink python` or `brew remove python` should cause it to use the system `python`. Mixing and matching `python` interpreters isn't really supported. I'd suggest either removing the brewed `python` and using the system one, or using the brewed one exclusively. Using the brewed `python` would be my recommendation.
