### ISSUE TITLE
Error start httpd

### ISSUE THREAD

**Issue by tamacroft** [Linuxbrew/brew#857]
I'm use WSL Debian. I have to install apache2, but when I'm start httpd by typing "brew services start httpd" ,then show error:
sh: 1: list: not found
sh: 1: list: not foundError: Failure while executing; `'' load -w /home/tamacroft/Library/LaunchAgents/homebrew.mxcl.httpd.plist` exited with 1

**Comment by iMichka** [comment]
> brew services start httpd

`brew services` is not supported on Linux. You will have to find the right command in the httpd documentation to start the service manually.

Pull requests are of course welcome to disable the `brew services` command on Linux, with a better error message.

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).
