### ISSUE TITLE
root install fails with "No libpythonX.Y.{a,dylib} file found!" error

### ISSUE THREAD

**Issue by sidebo** [Linuxbrew/brew#866]
I have what appears to be the same issue as listed here https://github.com/Homebrew/homebrew-services/issues/157, but there was no real solution given. I'm on an slc6 machine and trying to install root (with python3 bindings), via `brew install root`. I get the error
```
Error: No libpythonX.Y.{a,dylib} file found!
Error: An exception occured within a child process:
  SystemExit: exit
```
However, I do have such lib files,  see below, but seems they are not picked up for some reason. Any ideas on how I can solve this? 

```
[psidebo@gluino ~]$ find /home/linuxbrew/.linuxbrew/ -name "libpython*.a"
/home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.15_1/lib/python2.7/config/libpython2.7.a
/home/linuxbrew/.linuxbrew/Cellar/python/3.7.0/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a
/home/linuxbrew/.linuxbrew/lib/python2.7/config/libpython2.7.a
/home/linuxbrew/.linuxbrew/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7m.a
[psidebo@gluino ~]$ find /home/linuxbrew/.linuxbrew/ -name "libpython*.dylib"
/home/linuxbrew/.linuxbrew/lib/libpython2.7.dylib
/home/linuxbrew/.linuxbrew/lib/libpython3.dylib
/home/linuxbrew/.linuxbrew/lib/libpython3.7m.dylib
```

**Comment by sjackman** [comment]
This formula `root` has not yet been fixed for Linux. We'd appreciate a pull request to fix it if you're able to get it working. You can start with `brew edit root`. See https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/root.rb
