### ISSUE TITLE
CANNOT LINK EXECUTABLE "/bin/bash": library "libandroid-support.so" not found

### ISSUE THREAD

**Issue by Merith-TK** [Linuxbrew/brew#867]
**Please fill out the issue checklist below and provide all the requested information.**

- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew` commands)

Literally installing via the alternative method into Termux for Android, and it sorta works, but when i run "brew" anything, it returns this error even though i have `libandroid-support` and `libandroid-support-dev` istalled

**Comment by sjackman** [comment]
I'm afraid that Android is not currently a supported target of Linuxbrew. I'd suggest asking the Termux developers. I know they were looking into it at one point.

**Comment by Merith-TK** [comment]
Okay, fair enough.
