### ISSUE TITLE
Installed bash using brew not sourcing system wide `/etc/bash.bashrc`

### ISSUE THREAD

**Issue by cevhyruz** [Linuxbrew/brew#869]
**Please fill out the issue checklist below and provide all the requested information.**

- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I installed another bash shell by `brew install bash`
- What happened (include command output)
It was running fine actually, the problem is it didn't source the `/etc/bash.bashrc`
- Step-by-step reproduction instructions (by running `brew` commands)
Install bash using `brew install bash`
change default shell `chsh /home/linuxbrew/.linuxbrew/bin/bash`
restart terminal.

**Comment by sjackman** [comment]
Add `source /etc/bash.bashrc` to your local `~/.bashrc`.
