### ISSUE TITLE
brew rust install fail

### ISSUE THREAD

**Issue by ipstone** [Linuxbrew/brew#877]
Hello, 

I am installing fd on ubuntu linux, but generating the following error to report (error from rust package):

==> Installing fd dependency: rust
==> Downloading https://linuxbrew.bintray.com/bottles/rust-1.30.0.x86_64_linux.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring rust-1.30.0.x86_64_linux.bottle.1.tar.gz
Error: wrong number of arguments (given 1, expected 2)
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:548:in `block in initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:557:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/exceptions.rb:557:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:10:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:10:in `safe_popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:134:in `needed_libraries_using_readelf'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:111:in `needed_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:87:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:150:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:150:in `metadata'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/os/linux/elf.rb:158:in `dynamically_linked_libraries'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:98:in `block in check_dylibs'
/usr/lib/ruby/2.5.0/pathname.rb:565:in `block in find'
/usr/lib/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
/usr/lib/ruby/2.5.0/find.rb:48:in `catch'
/usr/lib/ruby/2.5.0/find.rb:48:in `block in find'
/usr/lib/ruby/2.5.0/find.rb:43:in `each'
/usr/lib/ruby/2.5.0/find.rb:43:in `find'
/usr/lib/ruby/2.5.0/pathname.rb:565:in `find'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:91:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/linkage_checker.rb:23:in `check_dylibs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/linkage_checker.rb:25:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:653:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:653:in `block in finish'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cache_store.rb:15:in `use'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:650:in `finish'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:603:in `install_dependency'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:564:in `block in install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:564:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:564:in `install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:256:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:325:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:256:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:254:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:254:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

**Comment by ipstone** [comment]
Somehow, this only seems tansient, I just run the brew install fd again, and it shows rust is installed and fd is also working properly. Not sure what is the issue.

My env: 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.1 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 20FRS0A800 ThinkPad X1 Yoga 1st 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.15.0-34-generic

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Thanks for the bug report, Isaac. Glad to hear that the issue seems to have gone away on its own. Feel free to comment here if the issue recurs.
