### ISSUE TITLE
Where is profile?

### ISSUE THREAD

**Issue by bozeyman9000** [Linuxbrew/brew#887]
Please fill out one of the templates at https://github.com/Linuxbrew/brew/issues/new/choose

I am trying to install this linuxbrew on my lg q7 however i do not know where profile is.

**Comment by bozeyman9000** [comment]
Im also unable to drop a screenshot from my device.

**Comment by iMichka** [comment]
> https://github.com/Linuxbrew/brew/issues/new/choose

Please do that. It is a little bit unclear what your problem is.

We will re-open the issue once you provided the needed information. Thanks!
