### ISSUE TITLE
Cannot link executable

### ISSUE THREAD

**Issue by bozeyman9000** [Linuxbrew/brew#890]
When i run brew install gcc into termux i get this error and it advises me to install clang or gcc. Clang is up to date using both pkg install clang and apt install clang. Any advice would be awesome.

I am simply trying to get brew running and see that all ia good. Obviously its not all good.

**Comment by sjackman** [comment]
Please complete the issue template. Please try installing `gcc`. `clang` should work, but it's less tested. Please report the exact output of `brew config` and `brew install hello`.
