### ISSUE TITLE
Did you mean?  prepend_path_in_profile

### ISSUE THREAD

**Issue by RogerWeihrauch** [Linuxbrew/brew#892]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)
Due to the fact, 'brew' command, after re-login, was not recognized in my ENV after successful installation of LinuxBrew, I tried/hacked to get it working that way using an additional .bash_profile file to export related paths. (See file in archive)

# What happened (include command output)
After executing twice 'brew update' and after that, 'brew doctor', the following output on terminal was shown:

<details>
  <summary>Command output</summary>
  <pre>
  
 vagrant@StretcH:~$ brew update
Already up-to-date.
vagrant@StretcH:~$ brew update
Already up-to-date.
vagrant@StretcH:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have HOMEBREW_BUILD_FROM_SOURCE set. This environment variable is
intended for use by Homebrew developers. If you are encountering errors,
please try unsetting this. Please do not file issues if you encounter
errors when using this environment variable.
Error: undefined method `prepend_variable_in_profile' for Utils::Shell:Module
Did you mean?  prepend_path_in_profile
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/os/linux/diagnostic.rb:48:in `check_xdg_data_dirs'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:69:in `block in doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:61:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:61:in `doctor'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
vagrant@StretcH:~$ 
  
  </pre>
</details>

# What you expected to happen

Well, no error message after executing 'brew doctor'.

# Step-by-step reproduction instructions (by running `brew` commands)
'brew update'; executed twice as requested, after that:
'brew doctor' to check my LinuxBrew environment.

Following my bash files: (echo's are for my orientation on execution chronology)
[brew_bug.tar.gz](https://github.com/Linuxbrew/brew/files/2612295/brew_bug.tar.gz)

**Comment by jonchang** [comment]
Can you please include output of `brew config`, thanks.

**Comment by sjackman** [comment]
Thanks for the bug report, Roger. This bug appears to be present in both Homebrew/brew and Linuxbrew/brew. This function `Utils::Shell.prepend_variable_in_profile` appears to have been removed from Homebrew/brew. There are functions `set_variable_in_profile` and `prepend_path_in_profile`, but no `prepend_variable_in_profile`.

https://github.com/Linuxbrew/brew/blob/ed2316c9638bd9086eafa9e9bfbef6527aa88a65/Library/Homebrew/extend/os/linux/diagnostic.rb#L48

https://github.com/Linuxbrew/brew/blob/ed2316c9638bd9086eafa9e9bfbef6527aa88a65/Library/Homebrew/utils/shell.rb#L43

https://github.com/Linuxbrew/brew/blob/ed2316c9638bd9086eafa9e9bfbef6527aa88a65/Library/Homebrew/utils/shell.rb#L54

**Comment by sjackman** [comment]
Something like the following untested fix may work.
```diff
-#{Utils::Shell.prepend_variable_in_profile("XDG_DATA_DIRS", HOMEBREW_PREFIX/"share")}
+#{Utils::Shell.set_variable_in_profile("XDG_DATA_DIRS", HOMEBREW_PREFIX/"share:$PATH")}
```

**Comment by RogerWeihrauch** [comment]
@jonchang:
Hello Jonathan
Well, wasn't it in the archive? So, sure, here you are:
[brew_config.txt](https://github.com/Linuxbrew/brew/files/2616592/brew_config.txt)
Thank you for your support.

@sjackman:
Hello Shaun
Thank you for your support by reporting a possible workaround. Well, since I am not really a SW-Dev and very unexperienced on SW-Dev steps/tools; where do I have to add your mentioned workaround?
Thanks for your reply.

Regards to you both,
Roger

**Comment by sjackman** [comment]
This bug should hopefully be resolved by PR https://github.com/Linuxbrew/brew/pull/895 once it's merged.

**Comment by sjackman** [comment]
This issue should be resolved. Run `brew update`
