### ISSUE TITLE
Error : Running the installation script

### ISSUE THREAD

**Issue by jimenezfer** [Linuxbrew/brew#898]
Please fill out one of the templates at https://github.com/Linuxbrew/brew/issues/new/choose
Am on ubuntu 18.04 , when I run the curl link:

sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

I get this error:

==> This script will install:
/home/linuxbrew/.linuxbrew/bin/brew
/home/linuxbrew/.linuxbrew/share/doc/homebrew
/home/linuxbrew/.linuxbrew/share/man/man1/brew.1
/home/linuxbrew/.linuxbrew/share/zsh/site-functions/_brew
/home/linuxbrew/.linuxbrew/etc/bash_completion.d/brew
/home/foxelvoret/.cache/Homebrew/
/home/linuxbrew/.linuxbrew/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Linuxbrew...
error: unable to create file Library/Homebrew/.rubocop.yml: Permission denied
error: unable to create file Library/Homebrew/.simplecov: Permission denied
error: unable to create file Library/Homebrew/PATH.rb: Permission denied
error: unable to create file Library/Homebrew/README.md: Permission denied
error: unable to create file Library/Homebrew/brew.rb: Permission denied
error: unable to create file Library/Homebrew/brew.sh: Permission denied
error: unable to create file Library/Homebrew/build.rb: Permission denied
error: unable to create file Library/Homebrew/build_environment.rb: Permission denied
error: unable to create file Library/Homebrew/build_options.rb: Permission denied
error: unable to create file Library/Homebrew/cache_store.rb: Permission denied
fatal: cannot create directory at 'Library/Homebrew/cask': Permission denied
Failed during: git reset --hard origin/master

I flailed at the error by changing permissions , chown the dir to my user, but nothing helped.

**Only the alternative installation was able to resolve this.**

I thought it would be a good idea to leave this for the next traveler.

Closing

Cheers!

**Comment by sjackman** [comment]
Sorry that you ran int trouble, and glad to hear that you got it working with the alternative installation instructions.
