### ISSUE TITLE
How properly change compiler?

### ISSUE THREAD

**Issue by svetlov** [Linuxbrew/brew#9]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

logs - http://pastebin.com/iMT9sDT3 , 
gcc/cc outputs - http://pastebin.com/8TQs04Db

i'm trying to install new glibc on ubuntu 12.04, but threre's bug with glibc and gcc-4.7. I tried to change compiler with -cc option, but have no luck. Unfortunately, i haven't sudo on this server. Any idea, how can i fix it?

**Comment by sjackman** [comment]
You need two hyphens. `brew install --cc=gcc-4.6`
Please report `brew gist-logs glibc` to https://github.com/Linuxbrew/homebrew-core/issues
