### ISSUE TITLE
tutorial of offline install

### ISSUE THREAD

**Issue by livc** [Linuxbrew/brew#900]
How to install Linuxbrew in an offline (no internet connection) machine?

**Comment by sjackman** [comment]
You can download a release tarball from here: https://github.com/Homebrew/brew/releases
Follow the`Source code (tar.gz)` link.
Then follow these instructions: https://linuxbrew.sh/#alternative-installation
On a machine that has Internet access, you can `brew fetch` the bottles for the formulae that you want to install, then copy `~/.cache/Homebrew` to the machine that does not have Internet access.

**Comment by sjackman** [comment]
Note that Homebrew/brew now supports Linux.
