### ISSUE TITLE
Brew installs fail with "error: C compiler cannot create executables"

### ISSUE THREAD

**Issue by skeledrew** [Linuxbrew/brew#901]
- [ y] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [y ] ran `brew update` and can still reproduce the problem?
- [* ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [y ] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

Install applications via Linuxbrew to remove dependency on JuNest <https://github.com/fsquillace/junest> which I use as an essentials bootstrapper (git, gcc, make). I'm working on a setup which doesn't need sudo at all to completely configure a system. Linuxbrew was installed via `sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"` and was successful only after a `cd ~`; before the install did not complete.

# What happened (include command output)

No brew install (beyond gcc) works. Have tried installing git, make and tmux. They all give the same error shown.

<details>
  <summary>Command output</summary>
  <pre>
  
...
Updating Homebrew...
proot info: pid 23093: terminated with signal 11
Warn: Proot is not working, disabling SECCOMP instead. Expect the application to run slowly in particular when it uses syscalls intensively.
==> Installing dependencies for tmux: pkg-config, openssl, libevent, gpatch and ncurses
==> Installing tmux dependency: pkg-config
proot info: pid 23311: terminated with signal 11
Warn: Proot is not working, disabling SECCOMP instead. Expect the application to run slowly in particular when it uses syscalls intensively.
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Already downloaded: /home/skeledrew/.cache/Homebrew/downloads/5bdbf3b3fdadaf72744884b98b74a2ff887bd63a20b246f811a222a146ad7b64--pkg-config-0.29.2.tar.gz
==> ./configure --prefix=/home/skeledrew/.linuxbrew/Cellar/pkg-config/0.29.2_1 --disable
Last 15 lines from /home/skeledrew/.cache/Homebrew/Logs/pkg-config/01.configure:
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for style of include used by make... none
checking for gcc... gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/pkg-config-20181206-23316-dag8cr/pkg-config-0.29.2':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."
  
  </pre>
</details>

# What you expected to happen

Apps should install and be available to run

# Step-by-step reproduction instructions (by running `brew` commands)

brew install tmux

# Further notes

`brew doctor` also fails:

```Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Missing Homebrew/brew git origin remote.

Without a correctly configured origin, Homebrew won't update
properly. You can solve this by adding the Homebrew remote:
  git -C "/home/skeledrew/.linuxbrew/Homebrew" remote add origin https://github.com/Linuxbrew/brew.git

Warning: python is symlinked to python3
This will confuse build scripts and in general lead to subtle breakage.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /home/skeledrew/.conda/bin/python3.7m-config
  /home/skeledrew/.conda/bin/python3.7-config
  /home/skeledrew/.conda/bin/ncursesw6-config
  /home/skeledrew/.conda/bin/python3-config
proot info: pid 24762: terminated with signal 11
Warn: Proot is not working, disabling SECCOMP instead. Expect the application to run slowly in particular when it uses syscalls intensively.
Error: Version value must be a string; got a NilClass ()
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/version.rb:210:in `create'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/diagnostic.rb:494:in `check_git_version'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:69:in `block in doctor'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:61:in `each'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/doctor.rb:61:in `doctor'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'```

Attempting to run `git -C "/home/skeledrew/.linuxbrew/Homebrew" remote add origin https://github.com/Linuxbrew/brew.git` gives:
```fatal: remote origin already exists.```

`brew config` yields:

```HOMEBREW_VERSION: 1.8.4
ORIGIN: (none)
HEAD: (none)
Last commit: never
Core tap ORIGIN: (none)
Core tap HEAD: (none)
Core tap last commit: never
HOMEBREW_PREFIX: /home/skeledrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/skeledrew/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/skeledrew/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/skeledrew/.cache/Homebrew
HOMEBREW_NO_ENV_FILTERING: 1
CPU: single-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git:  => /home/skeledrew/.jigde/bin/git
Curl: 7.52.1 => /usr/bin/curl
Kernel: Linux 4.9.0-8-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 9.5 (stretch) (stretch)
Host glibc: 2.24
/usr/bin/gcc: N/A
glibc: N/A
gcc: 5.5.0_4
xorg: N/A```

Git (/home/skeledrew/.jigde/bin/git) is a script that runs `junest -- git $@` (runs git installed in junest).

Homebrew-related env vars:

```declare -x HOMEBREW_CELLAR="/home/skeledrew/.linuxbrew/Cellar"
declare -x HOMEBREW_GIT="/home/skeledrew/.appimages/links/git"
declare -x HOMEBREW_NO_ENV_FILTERING="1"
declare -x HOMEBREW_PREFIX="/home/skeledrew/.linuxbrew"
declare -x HOMEBREW_REPOSITORY="/home/skeledrew/.linuxbrew/Homebrew"```

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `util-linux`.
Another possible workaround for you is `brew install --force-bottle util-linux`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
Please report the output of…
```sh
brew install hello
brew gist-logs hello
```

**Comment by skeledrew** [comment]
This is a personal project where I'm designing a setup which doesn't require root at any point, and it would defeat the purpose to install in `/home/linuxbrew`. Actually I was using Linuxbrew in a previous install just fine (my only issue is that it force updates instead of giving me the choice to update or not) for the past couple years, so I'm surprised it doesn't work well now. I've never had a problem with it compiling everything from scratch as I preferred that flexibility.

`brew install --force-bottle util-linux` also fails with the same error.

`$ brew install hello`
```==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Downloading https://linuxbrew.bintray.com/bottles/hello-2.10.x86_64_linux.bottle.tar
######################################################################## 100.0%
==> Pouring hello-2.10.x86_64_linux.bottle.tar.gz
🍺  /home/skeledrew/.linuxbrew/Cellar/hello/2.10: 52 files, 595.6KB```

`$ brew gist-logs hello`
```Error: No logs.```

I think I will try to see if I can get my previous install working again. I maintain the same core structure across all my installs so the prefix is the same and should allow for drop-in functionality.

**Comment by sjackman** [comment]
> my only issue is that it force updates instead of giving me the choice to update or not

You can set `export HOMEBREW_NO_AUTO_UPDATE=1`

**Comment by sjackman** [comment]
Sorry. That should have been…
```sh
brew remove hello
brew install -s hello
brew gist-logs hello
```

**Comment by skeledrew** [comment]
`$ brew remove hello` gives:
```Error: Failure while executing; `/home/skeledrew/.linuxbrew/bin/patchelf --print-needed /home/skeledrew/.linuxbrew/Cellar/patchelf/0.9_1/bin/patchelf` exited with 1. Here's the output:```

There's no actual output.

Wiped and attempted to reinstall and getting an error that I got several times earlier:

```...
==> Tapping homebrew/core
Cloning into '/home/skeledrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 4924, done.
remote: Counting objects: 100% (4924/4924), done.
remote: Compressing objects: 100% (4727/4727), done.
Receiving objects: 100% (4924/4924), 4.22 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (48/48), done.
remote: Total 4924 (delta 48), reused 301 (delta 4), pack-reused 0
Checking out files: 100% (4940/4940), done.
Tapped 3 commands and 4704 formulae (4,965 files, 13.2MB).
Error: no implicit conversion of false into String
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `initialize'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `popen'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `popen'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:3:in `popen_read'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:760:in `block in []'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:265:in `block in cd'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:265:in `chdir'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:265:in `cd'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:759:in `[]'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:635:in `read_or_set_private_config'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:218:in `private?'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:327:in `install'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/tap.rb:88:in `tap'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Failure while executing; `/home/skeledrew/.linuxbrew/bin/brew tap homebrew/core` exited with 1.
Failed during: /home/skeledrew/.linuxbrew/bin/brew update --force```

**Comment by skeledrew** [comment]
`$ brew update` reports already updated.

`$ brew install gcc` works fine.

`$ brew install -s hello` yields:
```==> Downloading https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/home/skeledrew/.linuxbrew/Cellar/hello/
Last 15 lines from /home/skeledrew/.cache/Homebrew/Logs/hello/01.configure:
--prefix=/home/skeledrew/.linuxbrew/Cellar/hello/2.10

configure: WARNING: unrecognized options: --disable-debug
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for gcc... gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/hello-20181206-31001-sfzh9z/hello-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."```

`$ brew gist-logs hello`
```https://gist.github.com/2785168a6e510cd7aeb66277ffbe8208```

**Comment by sjackman** [comment]
```
configure:4036: gcc-5    conftest.c  >&5
gcc-5: error trying to exec 'as': execvp: No such file or directory
```
https://gist.github.com/skeledrew/2785168a6e510cd7aeb66277ffbe8208#file-config-log-L84
Try installing `binutils` either with your host package manager or with brew.
```sh
brew install binutils
```

**Comment by skeledrew** [comment]
Installing binutils did not make any noticeable change to the issue. I have been attempting a variety of other possibilities however none are solving the core problem of getting Linuxbrew to install anything beyond binutils and gcc. Seeing that this issue has been closed I would like to know if I should open a new one even though my original problem hasn't been solved, since I'm getting a different error message but leading to the same issue. 

I am currently attempting to do all brew-related tasks within JuNest itself (which is just an Arch distro running within the regular) and so git, etc are in their expected locations. However I am using the alternative setup method (git clone https://github.com/Linuxbrew/brew ~/.linuxbrew/Homebrew) as it generates the proper prefixes so I can then copy the .linuxbrew folder to the regular distro.

After doing a fresh setup I do 2 `brew install -s hello` and then `brew gist-logs hello` and got these:

```==> Downloading https://linuxbrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz
Already downloaded: /home/skeledrew/.cache/Homebrew/portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz
==> Pouring portable-ruby-2.3.7.x86_64_linux.bottle.tar.gz
==> Tapping homebrew/core
Cloning into '/home/skeledrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 4924, done.
remote: Counting objects: 100% (4924/4924), done.
remote: Compressing objects: 100% (4727/4727), done.
Receiving objects: 100% (4924/4924), 4.22 MiB | 3.40 MiB/s, done.
remote: Total 4924 (delta 48), reused 302 (delta 4), pack-reused 0
Resolving deltas: 100% (48/48), done.
Checking out files: 100% (4940/4940), done.
Tapped 3 commands and 4704 formulae (4,965 files, 13.2MB).
Error: no implicit conversion of false into String
Please report this bug:
  https://github.com/Linuxbrew/brew/wiki/troubleshooting
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `initialize'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `popen'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:25:in `popen'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:3:in `popen_read'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:760:in `block in []'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:265:in `block in cd'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:265:in `chdir'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/extend/pathname.rb:265:in `cd'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:759:in `[]'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:635:in `read_or_set_private_config'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:218:in `private?'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:327:in `install'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/tap.rb:88:in `tap'
/home/skeledrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Error: Failure while executing; `/home/skeledrew/.linuxbrew/bin/brew tap homebrew/core` exited with 1.```

```==> Downloading https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
Already downloaded: /home/skeledrew/.cache/Homebrew/downloads/0d3dc7a1e45d7ac6eb8d853c8ecccad6a4ab6abbbf38038f552e4735ad15d3cc--hello-2.10.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/skeledrew/.linuxbrew/Cellar/hello/
Last 15 lines from /home/skeledrew/.cache/Homebrew/Logs/hello/01.configure:
checking whether strnlen is declared... (cached) yes
checking for pid_t... yes
checking for mode_t... yes
checking whether <wchar.h> uses 'inline' correctly... mv: cannot move 'conftest.o' to 'conftest1.o': No such file or directory
mv: cannot move 'conftest.o' to 'conftest2.o': No such file or directory
no
configure: error: <wchar.h> cannot be used with this compiler (gcc-8 -g -O2 ).
This is a known interoperability problem of glibc <= 2.5 with gcc >= 4.3 in
C99 mode. You have four options:
  - Add the flag -fgnu89-inline to CC and reconfigure, or
  - Fix your include files, using parts of
    <http://sourceware.org/git/?p=glibc.git;a=commitdiff;h=b037a293a48718af30d706c2e18c929d0e69a621>, or
  - Use a gcc version older than 4.3, or
  - Don't use the flags -std=c99 or -std=gnu99.
Configuration aborted.

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."```

```https://gist.github.com/a97fe52530f4c0eeff7e383464866c2d```

Even if I were to get a hint as to why these errors are occurring it'd help to find a way to fix or bypass it.

**Comment by sjackman** [comment]
> as it generates the proper prefixes so I can then copy the ~/.linuxbrew folder to the regular distro.

Keep in mind this only works if your home directory is the same on both machines.

**Comment by sjackman** [comment]
> Seeing that this issue has been closed I would like to know if I should open a new one even though my original problem hasn't been solved, since I'm getting a different error message but leading to the same issue.

Feel free to continue commenting. JuNest and Arch aren't really first-class supported distributions of Linuxbrew, but I'm happy to answer questions.

**Comment by sjackman** [comment]
```
checking whether <wchar.h> uses 'inline' correctly... mv: cannot move 'conftest.o' to 'conftest1.o': No such file or directory
mv: cannot move 'conftest.o' to 'conftest2.o': No such file or directory
no
configure: error: <wchar.h> cannot be used with this compiler (gcc-8 -g -O2 ).
This is a known interoperability problem of glibc <= 2.5 with gcc >= 4.3 in
C99 mode. You have four options:
  - Add the flag -fgnu89-inline to CC and reconfigure, or
  - Fix your include files, using parts of
    <http://sourceware.org/git/?p=glibc.git;a=commitdiff;h=b037a293a48718af30d706c2e18c929d0e69a621>, or
  - Use a gcc version older than 4.3, or
  - Don't use the flags -std=c99 or -std=gnu99.
```

It looks like `gcc` is not able to find your installation of `glibc`, or there is some other problem with your `wchar.h` file.
https://gist.github.com/skeledrew/a97fe52530f4c0eeff7e383464866c2d#file-01-configure-L126

Linuxbrew found your `glibc` version 2.28 though:
https://gist.github.com/skeledrew/a97fe52530f4c0eeff7e383464866c2d#file-01-configure-L154

Try…
```sh
brew unpack hello
cd hello-2.10
./configure
make
```

If you're able to reproduce this issue with these commands outside of Linuxbrew, then your issue is with JuNest not with Linuxbrew, and so please report the issue to JuNest.

**Comment by skeledrew** [comment]
Thanks a lot for that tip. I was able to reproduce the issue when attempting a manual compile and so did it in the regular distro (Debian).

One thing I find strange is that I have to `brew install gcc` twice for it to complete successfully. The first time it errors on patchelf but doesn't give any output. I'm wondering if there's a minor issue in the patchelf formula; maybe it exits with the wrong return code and brew quits because of it?

```==> Installing dependencies for gcc: patchelf, zlib, gmp, mpfr, libmpc and isl@0.18
==> Installing gcc dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle
Already downloaded: /home/skeledrew/.cache/Homebrew/downloads/db57574a8c5d4c51b86703f6616af7807a37eaa47e9fb7be610f04617dc29e2a--patchelf-0.9_1.x86_64_linux.bottle.tar.gz
==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
Error: Failure while executing; `/home/skeledrew/.linuxbrew/bin/patchelf --print-needed /home/skeledrew/.linuxbrew/Cellar/patchelf/0.9_1/bin/patchelf` exited with 1. Here's the output:```

I'm now trying to install git, however it and apparently many other packages rely on pkg-config to compile. I thought I would be able to follow the `brew unpack hello` example in order to fix it, and was able to make some progress. On Debian I fixed missing crt[1|i|n].o files by copying from JuNest, but am currently stumped on a `ld: cannot find -lc` as I can't find a fix anywhere. This error occurs with brew install and ./configure. Any idea of what I should be looking for?

Within Junest I'm having a different error, and again both methods:
```https://gist.github.com/7ea7de3033deebabb4fd4693060d07b7```

Any thoughts on why it wouldn't find the Makefile (which I verified is actually in the folder)? Also in general is there a rule of thumb that I can use to manually replicate the dependency resolution and compilation process that Linuxbrew does? Thanks.

**Comment by sjackman** [comment]
`brew install patchelf` succeeds for me, but I can confirm that `patchelf --print-needed patchelf` fails.
```console
$ /home/linuxbrew/.linuxbrew/bin/patchelf --print-needed /home/linuxbrew/.linuxbrew/Cellar/patchelf/0.9_1/bin/patchelf
cannot find section .dynamic
$ echo $?
1
```
I believe it's because your host system does not have the `readelf` executable, which is provided by `binutils`.

`ld: cannot find -lc`
You need the file `libc.so`, which is provided by `glibc`.
See http://linuxbrew.sh/#dependencies
