### ISSUE TITLE
Default password for user "linuxbrew" in docker

### ISSUE THREAD

**Issue by paulhybryant** [Linuxbrew/brew#903]
Please fill out one of the templates at https://github.com/Linuxbrew/brew/issues/new/choose

I want to change the login shell, and I cannot find out what the password is

**Comment by paulhybryant** [comment]
Stupid me. I can sudo passwd to change it. Closing.

**Comment by sjackman** [comment]
Glad you got it sorted.

**Comment by sjackman** [comment]
If you're using the `linuxbrew/linuxbrew` Docker image currently, try the `linuxbrew/brew` Docker image which is based on https://github.com/Homebrew/brew rather than Linuxbrew/brew. Homebrew now supports Linux.
