### ISSUE TITLE
Support Cask for Fonts

### ISSUE THREAD

**Issue by iandol** [Linuxbrew/brew#906]
# A detailed description of the proposed feature

Brew cask is dedicated to macOS binary images so it makes sense to not allow it to work from the main cask formulae. **But** cask can also install a huge variety of regularly updated fonts:

https://github.com/Homebrew/homebrew-cask-fonts

```
$ brew tap homebrew/cask-fonts                  # you only have to do this once!
$ brew cask install font-inconsolata
```
Now I suspect, just as has been the case for macOS `brew` working to integrate linux brew directly, `cask` will need to know if it is linux, where to move the fonts etc.

# The motivation for the feature

An easy way to standardise font installs across Linux machines.

# How the feature would be relevant to at least 90% of Homebrew users

I suspect many Linux brew users have preferences for different types of monospace coding and other fonts, and it is a pain to get and install them. 

# What alternatives to the feature have been considered

Well I currently just manually install fonts from Github etc. Perhaps there is an amazing tool, but at least apt is limited in font selection and not regularly updated normally.

**Comment by sjackman** [comment]
Hi, Ian. Linuxbrew/brew is being merged into Homebrew/brew, so we're not accepting new features into Linuxbrew. It's an interesting idea though. If you're able to get it working, you're welcome to submit a PR to Homebrew/brew.

**Comment by iMichka** [comment]
There is also this alternative to consider: https://dev.to/xtaniguchimasaya/linuxbrew-as-a-font-manager-5af2

**Comment by iandol** [comment]
Thank you to both, I am unlikely to be able to develop this myself in the short term. I'll close this and have a look at how difficult it would be for getting Homebrew/brew to do this.

**Comment by sjackman** [comment]
I didn't known about xtaniguchimasaya/fonts, which has 1,158 fonts! That seems a better approach than bringing casks to Linuxbrew just for fonts. `brew tap xtaniguchimasaya/fonts` and off you go!
See https://github.com/xtaniguchimasaya/homebrew-fonts#readme https://github.com/xtaniguchimasaya/homebrew-fonts/tree/master/Formula

**Comment by iMichka** [comment]
Maybe we should propose them to join the linuxbrew org and make it an official tap. Looks like a great project.

**Comment by sjackman** [comment]
Sounds good to me if it's still actively maintained.
