### ISSUE TITLE
Repeated `xorgproto`-related warnings output from several core commands (e.g. `doctor`, `leaves`)

### ISSUE THREAD

**Issue by jaredsampson** [Linuxbrew/brew#909]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

Fixed all issues I can--I'm on a shared system where I'm not an admin, so there are still extra `.la/.pc/.a` files in /usr/local/lib that I can't remove.  I also have a `conda` installation that has several `*-config` scripts.  Full `brew doctor` uploaded (see below). 

- [x] ran `brew config` and `brew doctor` and included their output with your issue?

Both uploaded to: https://gist.github.com/jaredsampson/1339f500413970a047f0cf4736961bfa

# What you were trying to do (and why)

Run `brew doctor` or `missing`, or `leaves` to check the status of my Linuxbrew installation, or `brew uninstall XXX` to uninstall a given formula.

# What happened (include command output)

The commands run successfully, but also output every time a long list of warnings related to `xorgproto` and older, deprecated `proto` programs.

<details>
  <summary>Command output</summary>
  <pre> 
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated xproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated kbproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated renderproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated xextproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated bigreqsproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated compositeproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated damageproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated dmxproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated dri2proto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated dri3proto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated fixesproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated fontsproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated glproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated inputproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated kbproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated presentproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated randrproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated recordproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated renderproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated resourceproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated scrnsaverproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated videoproto
Warning: Use linuxbrew/xorg/xorgproto instead of deprecated xcmiscproto
...and this goes on for 250 lines 
  </pre>
</details>

A complete version of the warnings is included in the same [gist](https://gist.github.com/jaredsampson/1339f500413970a047f0cf4736961bfa#file-proto_warnings-txt).

I find this unusual, particularly because I have xorgproto installed, but none of the deprecated programs:

```
$ brew list | grep proto
protobuf
xcb-proto
xorgproto
```

# What you expected to happen

I would expect these warnings to tell me which formula specifies the deprecated programs, or to have some other way of finding out how to resolve the apparent dependency issue.  It would be nice not to have 250 lines of warnings every time I run one of these basic commands, but I'm not sure how to go about fixing it.

# Step-by-step reproduction instructions (by running `brew` commands)

For me, this happens every time I run one of the aforementioned commands (`brew doctor`, `brew leaves`, `brew missing`, `brew uninstall X`), with no other steps necessary.  I suspect this will not be the case for other users or it would have been reported previously.

**Comment by sjackman** [comment]
@maxim-belkin Any thoughts on the cause of this issue?

**Comment by maxim-belkin** [comment]
@jaredsampson Could you please post (as a gist) the output of `brew list`?

**Comment by maxim-belkin** [comment]
Actually, could you please post (as a gist) the output you get upon executing these commands:
```
export HOMEBREW_DEBUG=1
brew doctor
```

**Comment by JuPlutonic** [comment]
Have these warnings "Warning: Use linuxbrew/xorg/xorgproto instead of deprecated".
((((I think something wrong with /home/l-b/.l-b/Library/Taps/linuxbrew/homebrew-xorg. I'm thinking about re-pour all bottles what actually comes from linuxbew/xorg.)))
I can reproduce warnings with Taps related formulas:
https://gist.github.com/JuPlutonic/f6a7ab40165b92e26f02a1c6a40182d7

PS: Sorry for my English.

**Comment by JuPlutonic** [comment]
See: homebrew-xorg/Formula/font-util.rb [output3.log](https://github.com/Linuxbrew/brew/files/2728508/output3.log)
```
export HOMEBREW_DEBUG=1
brew doctor

```

**Comment by jaredsampson** [comment]
I've added the [`brew list` output](https://gist.github.com/jaredsampson/1339f500413970a047f0cf4736961bfa#file-brew_list-txt) to the previous gist I used before.

I'm in the middle of a `brew upgrade` which I had hoped might take care of this issue, so I'll wait until that's done to post the new `brew doctor` output with debug info, hopefully later today (I had quite a few things outdated, including some built from source).

**Comment by maxim-belkin** [comment]
@JuPlutonic, thanks for for log file. So, it is `check_missing_deps` that causes these warnings. I'll have a look into it.

Another question: why do you have 
```
/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/
```
and not 
```
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
```
?

Have you tried
```
brew update
brew update
brew upgrade
brew cleanup --prune=0
brew prune
```
?

**Comment by maxim-belkin** [comment]
Thanks, @jaredsampson. Your problem might come from any of the outdated `linuxbrew/xorg` packages. The first thing I'd try is `brew remove linuxbrew/xorg/xorg` :)

**Comment by JuPlutonic** [comment]
Yep, did today many times (brew cleanup / brew update && brew update / brew cleanup --prune=0 && brew prune, ```brew upgrade``` I didn't use because I don't want pg to be upgraded)

**Comment by JuPlutonic** [comment]
> Another question: why do you have
> 
> ```
> /home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/
> ```
> and not
> 
> ```
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
> ```

Yes

**Comment by maxim-belkin** [comment]
> Yes

Thank you

**Comment by maxim-belkin** [comment]
> Yep, did today many times (brew cleanup / brew update && brew update / brew cleanup --prune=0 && brew prune, brew upgrade I didn't use because I don't want pg to be upgraded)

Try this:

```
brew upgrade $(brew list | grep -v pg)
```

**Comment by sjackman** [comment]
> Another question: why do you have `/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/` and not `/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula`

Older installations of Linuxbrew used $REPOSITORY == $PREFIX, and those older installations are not automatically migrated automatically to the current directory structure of $REPOSITORY == $PREFIX/Homebrew.

**Comment by iMichka** [comment]
I found a similar problem on an older install where I ran an update right now.
I was able to debug this a little bit. `brew doctor` was for example triggering these warnings.

I put a `raise` just here: https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/formulary.rb#L248

It got stuck on `libxcb` and `libx11`. Uninstalling both and then rebuilding them from source fixed the problem for me. I guess that both bottles need to be rebuilt.

**Comment by sjackman** [comment]
Perhaps a patch to Homebrew/brew is warranted?

**Comment by jaredsampson** [comment]
@maxim-belkin My `brew upgrade` finished overnight last night, so I've posted the `brew doctor` output with debug info [here](https://gist.github.com/jaredsampson/1339f500413970a047f0cf4736961bfa#file-debug_brew_doctor-txt).

Thanks for the debugging work, @iMichka.  I'll try uninstalling those and reinstall from source as you suggest.

**Comment by jaredsampson** [comment]
@sjackman Looking at the code where @iMichka added the raise statement, it would help in narrowing down the source of these warnings by simply adding the name of the formula that has that particular dependency, perhaps something like:

```ruby
opoo "#{name}: Use #{new_name} instead of deprecated #{old_name}"
```

although I just tried that, and it produces the errors:

```
Warning: xorgproto: Use linuxbrew/xorg/xorgproto instead of deprecated dri3proto
```

so being unfamiliar with the source, it seems must have the wrong variable.

**Comment by sjackman** [comment]
@jaredsampson That looks right to me. Try…
```ruby
opoo "#{path}: Use #{new_name} instead of deprecated #{old_name}"
```

**Comment by maxim-belkin** [comment]
Looks like these lines are triggered:
https://github.com/Linuxbrew/brew/blob/aed454897a835834a62ced40609b66d876a99904/Library/Homebrew/formulary.rb#L230-L235
so, taking https://github.com/Linuxbrew/brew/issues/909#issuecomment-451746038 as an example, `name = dri3proto`...
We have to figure out where that `dri3proto` comes from given that it is not installed (according to brew list).

**Comment by JuPlutonic** [comment]
Any changes in L248 didn't give me any clue(yhe raised error/ more complex message shows that xorgproto found problem in itself… maybe linuxbrew/xorg/xorgproto != xorgproto).
I think what on L227/L230 we need some more checks.

**Comment by maxim-belkin** [comment]
What does it say when you change line 248 to
```
opoo "#{path}: Use #{new_name} instead of deprecated #{old_name}"
```
?

**Comment by JuPlutonic** [comment]
@maxim-belkin 
[output2.txt](https://github.com/Linuxbrew/brew/files/2731078/output2.txt)
…
Warning: /opt/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorgproto.rb: Use linuxbrew/xorg/xorgproto instead of deprecated xorg-protocols
…
I did
export HOMEBREW_DEBUG=1; brew remove --debug font-inconsolata-nerd-font
from tap ta2gch/fonts

**Comment by jaredsampson** [comment]
@sjackman using `path` instead of `name` in L248 I get:

```
Warning: /home/ME/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorgproto.rb: Use linuxbrew/xorg/xorgproto instead of deprecated dri3proto
```

And yes, as @maxim-belkin noted, `dri3proto` is not installed.  I actually tried installing it and got this:

```
$ brew install dri3proto
Updating Homebrew...
Warning: linuxbrew/xorg/xorgproto 2018.4 is already installed and up-to-date
To reinstall 2018.4, run `brew reinstall xorgproto`
```

So apparently `dri3proto` (and presumably others) somehow alias to `xorgproto`?

I see a couple pull requests, but no formula for it.  

```
$ brew search dri3proto
No formula or cask found for "dri3proto".
Closed pull requests:
new formulae: dri3proto (https://github.com/Homebrew/homebrew-core/pull/11843)
openni2 2.2.0-debian (https://github.com/Homebrew/homebrew-science/pull/5192)
```

**Comment by sjackman** [comment]
Just to be sure, `dri3proto` is not reference in that file?
```
grep dri3proto /home/ME/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorgproto.rb
echo $?
```

**Comment by jaredsampson** [comment]
Nope, not referenced there.  

```
$ grep dri3proto ~/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorgproto.rb

$ echo $?
1
```

**Comment by sjackman** [comment]
Try…
```
ls -d ~/.linuxbrew/Cellar/*proto
```

**Comment by JuPlutonic** [comment]
xcb-proto and xorgproto

> Try…
> 
> ```
> ls -d ~/.linuxbrew/Cellar/*proto
> ```
And 
grep dri3proto /opt/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xcb-proto.rb
echo $?
Is `1`
[brew-list.txt](https://github.com/Linuxbrew/brew/files/2732436/brew-list.txt)

**Comment by ghost** [comment]
⚠️ The [GitHub App](https://github.com/apps/move) must be installed for the target repository.

**Comment by ghost** [comment]
This issue was moved by [sjackman](https://github.com/sjackman) to [Linuxbrew/homebrew-xorg#452](https://github.com/Linuxbrew/homebrew-xorg/issues/452).
