### ISSUE TITLE
sha1 is deprecated

### ISSUE THREAD

**Issue by mertcangokgoz** [Linuxbrew/brew#91]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._
### Bug reports:

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/home/mertcan/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/man-db.rb:6:in `class:ManDb'
Please report this to the homebrew/core tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/home/mertcan/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/man-db.rb:6:in `class:ManDb'
Please report this to the homebrew/core tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/home/mertcan/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/man-db.rb:6:in `class:ManDb'
Please report this to the homebrew/core tap!
### Propose a feature:

Instead of creating an issue here, please create a pull request with your change proposal in the [Homebrew Evolution](https://github.com/Homebrew/brew-evolution) repository using the [proposal template](https://github.com/Homebrew/brew-evolution/blob/master/proposal_template.md).

**Comment by bw-yuhogg** [comment]
Hi @MertcanGokgoz, can you try running `brew update` again? Sometimes it needs to be run twice in order to work.

Shaun already changed `man-db` to use SHA-256 instead of SHA-1, so I suspect that's all that's necessary.

Thanks!

**Comment by mertcangokgoz** [comment]
yes now working normally but sometimes i can see deprecated warning and i suspect sha1

```
mertcan@mertcan:~$ brew update
Already up-to-date.
mertcan@mertcan:~$ 
```

**Comment by sjackman** [comment]
If you're seeing more warnings please quote the command that you run and warning that you see.
