### ISSUE TITLE
brew audit/style error when your Ruby2.6RubyGems3.0.2

### ISSUE THREAD

**Issue by JuPlutonic** [Linuxbrew/brew#913]
**Please note that we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Homebrew/homebrew-core: https://github.com/Homebrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
<details>
  <summary>brew doctor output</summary>
    <pre>
HOMEBREW_VERSION: 1.8.6-2-g3996032
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: 399603206a6197208eedce9023a5e3e7d964e8c8
Last commit: 17 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 4680c487eb268b75f5ad59750acb9753d53c1642
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /opt/.linuxbrew
HOMEBREW_REPOSITORY: /opt/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /opt/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/salessionato/.cache/Homebrew
HOMEBREW_DEBUG: 1
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_LIVECHECK_WATCHLIST: /home/salessionato/etc-bbq/.linuxbrew-changed-formulas/brew_livecheck_watchlist
HOMEBREW_NO_ANALYTICS: 1
HOMEBREW_NO_EMOJI: 0
HOMEBREW_VISUAL: /usr/bin/subl
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.0 => /usr/bin/ruby2.6
Clang: 7.0 build 701
Git: 2.20.1 => /opt/.linuxbrew/bin/git
/usr/bin/curl --version
Curl: 7.61.0 => /usr/bin/curl
java -version
Kernel: Linux 4.18.0-11-generic x86_64 GNU/Linux
OS: Ubuntu 18.10 (cosmic)
Host glibc: 2.28
/usr/bin/gcc: 8.2.0
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb
glibc: N/A
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
gcc: N/A
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Formula/xorg.rb
xorg: 20170115_1
    </pre>
</details>

- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

make brew audit or brew style on locally changed formulas

# What happened (include command output)
<details>
  <summary>brew style --fix mkvtoolnix.rb output</summary>
    <pre>
 1000HA   …/Formula   master   
     vim mkvtoolnix.rb                                        18:17:51   

  1000HA   …/Formula   master   
      export HOMEBREW_DEBUG=1; brew style --fix --strict mkvtoolnix.rb
Error: invalid option: --strict
/opt/.linuxbrew/Homebrew/Library/Homebrew/cli_parser.rb:126:in `parse'
/opt/.linuxbrew/Homebrew/Library/Homebrew/cmd/style.rb:56:in `style'
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'

  1000HA   …/Formula   master   
   ✘   export HOMEBREW_DEBUG=1; brew style --fix mkvtoolnix.rb 
==> Installing or updating 'rubocop' gem
Error: invalid option: --no-ri
/usr/local/lib/site_ruby/2.6.0/rubygems/command.rb:396:in `handle_options'
/opt/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:231:in `install_gem!'
/opt/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:242:in `install_gem_setup_path!'
/opt/.linuxbrew/Homebrew/Library/Homebrew/style.rb:20:in `check_style_impl'
/opt/.linuxbrew/Homebrew/Library/Homebrew/style.rb:8:in `check_style_and_print'
/opt/.linuxbrew/Homebrew/Library/Homebrew/cmd/style.rb:82:in `style'
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
  </pre>
</details>

<details>
  <summary>brew audit output</summary>
  <pre>
  1000HA   ~ 
   ✘  ll /home/salessionato/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle-standalone/ruby/2.6.0
lrwxrwxrwx 1 salessionato salessionato 5  6 gen 19.04 /home/salessionato/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle-standalone/ruby/2.6.0 -> 2.3.0 
------ symlink doesn't help

  1000HA   ~ 
     gem2.6 -v; gem -v                                                  17:58:47   
3.0.2
3.0.2

  1000HA   ~ 
     ruby -v                                        8.59 ⏱  17:59:17   
ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]
------ changing ruby by rbenv doesn't help, same error --no-ri

  1000HA   …/bin 
   ✘  rbenv global system                                     18:59:18   
------ changing ruby by rbenv doesn't help, same error --no-ri

  1000HA   …/bin 
     ruby -v                                                 18:59:33   
Alias tip: rb -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]
------ changing ruby by rbenv doesn't help, same error --no-ri

 1000HA   ~ 
   ✘  _ gem2.6 install rubocop                                18:01:12   
[sudo] password  
Fetching rainbow-3.0.0.gem
Fetching jaro_winkler-1.5.2.gem
Fetching parser-2.5.3.0.gem
Fetching unicode-display_width-1.4.1.gem
Fetching parallel-1.12.1.gem
Fetching ruby-progressbar-1.10.0.gem
Fetching powerpack-0.1.2.gem
Fetching ast-2.4.0.gem
Fetching rubocop-0.62.0.gem
Building native extensions. This could take a while...
Successfully installed jaro_winkler-1.5.2
Successfully installed parallel-1.12.1
Successfully installed ast-2.4.0
Successfully installed parser-2.5.3.0
Successfully installed powerpack-0.1.2
Successfully installed rainbow-3.0.0
Successfully installed ruby-progressbar-1.10.0
Successfully installed unicode-display_width-1.4.1
Successfully installed rubocop-0.62.0
9 gems installed
  </pre>
</details>

# What you expected to happen
Working style checking
- [x] When I'm using brewed  by **brew-gem** nothing happens (no --no-ri errors)
- [x] rubocop on system ruby (2.6) works pretty well:
```
rubocop --format json                                   18:50:01   
{"metadata":{"rubocop_version":"0.62.0","ruby_engine":"ruby","ruby_version":"2.6.0","ruby_patchlevel":"0","ruby_platform":"x86_64-linux-gnu"},"files":[{"path":"brew-gem","offenses":[{"severity":"convention","message":"Style/ExpandPathArguments: Use `expand_path('..', __dir__)` instead of `expand_path('../..', __FILE__)`.","cop_name":"Style/ExpandPathArguments","corrected":false,"location":{"start_line":3,"start_column":22,"last_line":3,"last_column":32,"length":11,"line":3,"column":22}}]}],"summary":{"offense_count":1,"target_file_count":1,"inspected_file_count":1}}%
```
# Step-by-step reproduction instructions (by running `brew` commands)
`sudo gem update --system`

**Comment by JuPlutonic** [comment]
```
brew audit mkvtoolnix --online                          19:00:03   
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/binutils.rb
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/make.rb
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /opt/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/mkvtoolnix.rb
==> Installing or updating 'rubocop' gem
Error: invalid option: --no-ri
/usr/local/lib/site_ruby/2.6.0/rubygems/command.rb:396:in `handle_options'
/opt/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:231:in `install_gem!'
/opt/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:242:in `install_gem_setup_path!'
/opt/.linuxbrew/Homebrew/Library/Homebrew/style.rb:20:in `check_style_impl'
/opt/.linuxbrew/Homebrew/Library/Homebrew/style.rb:14:in `check_style_json'
/opt/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/audit.rb:149:in `audit'
/opt/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Thanks for the bug report, @JuPlutonic. There's a PR open upstream to address this issue. https://github.com/Homebrew/brew/pull/5503
