### ISSUE TITLE
brew bundle dump fails

### ISSUE THREAD

**Issue by kleinjm** [Linuxbrew/brew#926]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Trying to run a `brew bundle dump -f` in order to get a new list of packages.

- What happened (include command output)
```
➜  linux master ✓ brew bundle dump -f
sh: 1: list: not found
sh: 1: list: not found
sh: 1: list: not found
sh: 1: list: not found
sh: 1: list: not found
➜  linux master ✓ brew bundle dump
Error: /home/james/GitHubRepos/dotfiles/linux/Brewfile already exists
➜  linux master ✓ rm Brewfile
removed 'Brewfile'
➜  linux master ✗ brew bundle dump
sh: 1: list: not found
sh: 1: list: not found
sh: 1: list: not found
sh: 1: list: not found
sh: 1: list: not found
```
I tried removing the brewfile and doing it without `-f` but no difference.

- What you expected to happen
Produce an updated `Brewfile`

- Step-by-step reproduction instructions (by running `brew install` commands)
See above. Happy to include more if needed

[Here are my entire dotfiles](https://github.com/kleinjm/dotfiles/tree/master/linux) in the `linux` directory where I ran the command from. Feel free to poke around.

**Comment by sjackman** [comment]
Hi, James. I'm unfortunately not able to reproduce this error locally. I don't doubt that you're seeing it, but it's difficult for me to troubleshoot it, when I can't reproduce it. If you're familiar with Docker, are you able to reproduce this error in a clean Docker container? If you're able to give me a small reproducible test case, I'll be able to tackle this bug. Please report the output of `brew config`

**Comment by kleinjm** [comment]
Hey I'm actually off linux for the time being but if I switch back and am able to reproduce it in a container I'll post here. I'm fine closing this issue for now. Thanks!
