### ISSUE TITLE
`brew install yarn` does not support `--without-node`

### ISSUE THREAD

**Issue by eGust** [Linuxbrew/brew#928]
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

Missing option `--without-node` for `yarn` which is available on mac.

# What you were trying to do (and why)

Install `yarn` without `node`. Because I am using `nvm` to manage `node`.

# What happened (include command output)

I could install yarn without node by `--ignore-dependencies`. But `brew doctor` will come with a warning message:

```
Warning: Some installed formulae are missing dependencies.
You should `brew install` the missing dependencies:
  brew install node

Run `brew missing` for more details.
```

# What you expected to happen

Be able to `brew install yarn --without-node`

# Step-by-step reproduction instructions (by running `brew` commands)

```
brew install yarn --without-node
brew install yarn --ignore-dependencies
brew doctor
```

**Comment by iMichka** [comment]
See https://discourse.brew.sh/t/brew-install-yarn-without-node-busted/4087/5.

And especially:
> yarn depends on node : it does not function without it. #31510 5 provides context. Instead of trying to install without Homebrew’ node instead adjust your PATH so nvm 's node s are before Homebrew’s node .
