### ISSUE TITLE
Cannot execute one-line installation as root

### ISSUE THREAD

**Issue by FeynmanZhou** [Linuxbrew/brew#930]
I got return `Don't run this as root!` when execute one-line installation as root, do I need to execute as other users instead of root?
```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
Don't run this as root!
```

**Comment by sjackman** [comment]
Yes, that's correct. Run it as a different user than run, preferably a user with `sudo` access. One option is to create a `linuxbrew` user.
