### ISSUE TITLE
Stuck in rebase

### ISSUE THREAD

**Issue by black-snow** [Linuxbrew/brew#933]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?

# What you were trying to do (and why)

`brew update` when linux brew and homebrew "merged".

# What happened (include command output)
 ```
rebase in progress; onto ff898bcb4
You are currently rebasing branch 'master' on 'ff898bcb4'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)

        deleted by us:   Homebrew/os/linux/hardware.rb
```

I did not change anything manually. `brew doctor`:

```
Warning: You have uncommitted modifications to Homebrew
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /home/linuxbrew/.linuxbrew/Homebrew/Library && git stash && git clean -d -f
```

Stashing does not work due to merge conflicts, though.

I tried to reset and checkout all files but I cannot `rebase --continue`.

How do I fix this? Is a reinstall the only option?

**Comment by iMichka** [comment]
Can you try `brew update-reset`. That should set you back to a clean state.

**Comment by black-snow** [comment]
Yup, that worked out, thanks!
