### ISSUE TITLE
Unable to resolve dependency: user requested 'did_you_mean'

### ISSUE THREAD

**Issue by slhck** [Linuxbrew/brew#935]
- [x] ran a `brew` command and reproduced the problem with multiple formulae? If it's a problem with a single, official formula (not cask) please file this issue at Linuxbrew/homebrew-core: https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew config` and `brew doctor` and included their output with your issue?

# What you were trying to do (and why)

    brew audit

# What happened (include command output)

```
➜ brew audit
==> Installing or updating 'bundler' gem
Error: Unable to resolve dependency: user requested 'did_you_mean (= 1.2.1)'
```

# What you expected to happen

Brew should install the required dependencies and run audit.

# Step-by-step reproduction instructions (by running `brew` commands)

- Install Linuxbrew
- Run `brew audit`

This does not happen under macOS, therefore creating an issue here.

# Environment

```
➜ brew config
HOMEBREW_VERSION: 2.0.1-44-g058bd4b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 058bd4bf7c093eb753b238fb2e19ac27ff4242c8
Last commit: 24 hours ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 4c02e399ae7ba30befb90508b96fdc13b09add26
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/werner/.cache/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_DISPLAY: :1
HOMEBREW_LOGS: /home/werner/.cache/Homebrew/Logs
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
Clang: N/A
Git: 2.19.1 => /usr/bin/git
Curl: 7.61.0 => /usr/bin/curl
Kernel: Linux 4.18.0-13-generic x86_64 GNU/Linux
OS: Ubuntu 18.10 (cosmic)
Host glibc: 2.28
/usr/bin/gcc: 8.2.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
```

**Comment by sjackman** [comment]
Thanks for the bug report, Werner. Could you please open this issue at https://github.com/Homebrew/brew? If you have access to macOS, it'd be helpful if you could try to reproduce the issue on macOS. Thanks!

**Comment by slhck** [comment]
Shaun, please re-read my report:

> This does not happen under macOS, therefore creating an issue here.

It works under Homebrew/homebrew-core.

**Comment by slhck** [comment]
... that said, if this should *still* be reported under Homebrew, please let me know. Since this works fine under macOS, I think the error is here, specifically.

**Comment by sjackman** [comment]
Ah, sorry, I missed that.
Try…
```sh
rm -rf $(brew --repo)/Library/Homebrew/vendor/bundle
rm -rf $(brew --repo)/Library/Homebrew/vendor/portable-ruby
brew vendor-install ruby
brew style
```

**Comment by slhck** [comment]
That worked, thank you. Any idea what the underlying cause could be?

**Comment by sjackman** [comment]
The Ruby gems get confused, but no, I don't know why.

**Comment by sjackman** [comment]
```
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
```
`brew vendor-install ruby` install Ruby 2.3.7. My best guess would be a difference between these two versions of Ruby.

**Comment by slhck** [comment]
I looked at some similar messages from Homebrew-core, and the problem seemed to be caused by Gems being yanked (removed) from RubyGems. Since this is a no-repro and there's a workaround, I'm closing this issue. Thanks for your help!
