### ISSUE TITLE
pipenv does not install

### ISSUE THREAD

**Issue by psionman** [Linuxbrew/brew#937]
pipenv does not install

ubuntumate 16.04

```
jeff@snowdon:~/bfg/event_builder$ brew install pipenv
Error: uninitialized constant Language::Python::Virtualenv
Please report this bug:

/home/jeff/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/pipenv.rb:2:in `<class:Pipenv>'
/home/jeff/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/pipenv.rb:1:in `load_formula'
/home/jeff/.linuxbrew/Library/Homebrew/formulary.rb:21:in `module_eval'
/home/jeff/.linuxbrew/Library/Homebrew/formulary.rb:21:in `load_formula'
/home/jeff/.linuxbrew/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/home/jeff/.linuxbrew/Library/Homebrew/formulary.rb:83:in `load_file'
/home/jeff/.linuxbrew/Library/Homebrew/formulary.rb:74:in `klass'
/home/jeff/.linuxbrew/Library/Homebrew/formulary.rb:70:in `get_formula'
/home/jeff/.linuxbrew/Library/Homebrew/formulary.rb:207:in `factory'
/home/jeff/.linuxbrew/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/home/jeff/.linuxbrew/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/home/jeff/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/home/jeff/.linuxbrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/home/jeff/.linuxbrew/Library/Homebrew/cmd/install.rb:44:in `install'
/home/jeff/.linuxbrew/Library/brew.rb:84:in `<main>'
```

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
I'm not able to reproduce this issue. Please run `brew update` and report the output of `brew config` and `brew doctor` and the complete output of `brew install pipenv`.

**Comment by iMichka** [comment]
It fails to build due to the pip/setuptools bug though: https://github.com/Linuxbrew/homebrew-core/pull/11586

I am waiting for upstream to cut a new release.

**Comment by sjackman** [comment]
`brew install pipenv` and `brew test pipenv` worked in `linuxbrew/brew` Docker container.

**Comment by psionman** [comment]
Thanks guys. My pc cannot currently e accessed. I'll try again  when
available

**Comment by iMichka** [comment]
The build passed in core, I will add the bottled back soon.

**Comment by psionman** [comment]
```Please run `brew update`,  `brew config` and `brew doctor` ```

Works after this. Thanks

**Comment by sjackman** [comment]
Glad to hear that you got it working, @psionman.

**Comment by sjackman** [comment]
and thanks for bottling, @iMichka.
