### ISSUE TITLE
Errno::EINVAL: Invalid argument - recvmsg(2) [Windows]

### ISSUE THREAD

**Issue by pnomolos** [Linuxbrew/brew#98]
# Please follow the general troubleshooting steps first:
- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports:

`brew install -dv asciidoc` fails with the following output in Bash on Windows:

```
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/asciidoc.rb        
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/docbook.rb         
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-dupes/unzip.rb                      
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/bzip2.rb           
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/gpatch.rb          
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/xz.rb              
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/libxml2.rb         
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/zlib.rb            
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/docbook-xsl.rb     
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/patchelf.rb        
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/pnomolos/.linuxbrew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb           
/home/pnomolos/.linuxbrew/Library/Homebrew/build.rb:181:in `dump': instance of IO needed (TypeError)                                                                            
        from /home/pnomolos/.linuxbrew/Library/Homebrew/build.rb:181:in `rescue in <main>'                                                                                      
        from /home/pnomolos/.linuxbrew/Library/Homebrew/build.rb:170:in `<main>'                                                                                                
Error: Suspicious failure                                                                                                                                                       
/home/pnomolos/.linuxbrew/Library/Homebrew/utils/fork.rb:41:in `block (3 levels) in safe_fork'                                                                                  
/home/pnomolos/.linuxbrew/Library/Homebrew/utils.rb:496:in `ignore_interrupts'                                                                                                  
/home/pnomolos/.linuxbrew/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'                                                                                  
/home/pnomolos/.linuxbrew/Library/Homebrew/utils/fork.rb:7:in `open'                                                                                                            
/home/pnomolos/.linuxbrew/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'                                                                                              
/home/pnomolos/.rbenv/versions/2.2.5/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'                                                                                                  
/home/pnomolos/.linuxbrew/Library/Homebrew/utils/fork.rb:6:in `safe_fork'                                                                                                       
/home/pnomolos/.linuxbrew/Library/Homebrew/formula_installer.rb:634:in `build'                                                                                                  
/home/pnomolos/.linuxbrew/Library/Homebrew/formula_installer.rb:247:in `install'                                                                                                
/home/pnomolos/.linuxbrew/Library/Homebrew/cmd/install.rb:291:in `install_formula'                                                                                              
/home/pnomolos/.linuxbrew/Library/Homebrew/cmd/install.rb:150:in `block in install'                                                                                             
/home/pnomolos/.linuxbrew/Library/Homebrew/cmd/install.rb:150:in `each'                                                                                                         
/home/pnomolos/.linuxbrew/Library/Homebrew/cmd/install.rb:150:in `install'                                                                                                      
/home/pnomolos/.linuxbrew/Library/Homebrew/brew.rb:87:in `<main>'                                                                                                               
```

**Comment by pnomolos** [comment]
I did some more following up on this, a bit rusty at debugging non-Ruby internals so let me know if you want any other logs/traces from me.

`build.rb` is throwing the following error: `#<Errno::EINVAL: Invalid argument - recvmsg(2)>`.  If I comment out the lines at the end of `build.rb` related to `error_pipe`, then everything works properly.

**Comment by sjackman** [comment]
Hi, Phil. Can you please post a diff or submit a pull request with your change?

**Comment by pnomolos** [comment]
@sjackman I can, although I think it's more hiding the problem than actually fixing it.  I'll go through and review what I did.

**Comment by haroldSanchezb** [comment]
Is more related to the UNIXSocket.open(ENV["HOMEBREW_ERROR_PIPE"], &:recv_io), maybe don't get the ENV value, or the method UNIXSocket doesn't work properly on windows. I tried to get the value but, nothing happen

**Comment by pnomolos** [comment]
@haroldSanchezb Agreed.  I believe I tested to see if `ENV["HOMEBREW_ERROR_PIPE"]` was set, and it seemed to be - but I didn't debug further than that.

**Comment by sjackman** [comment]
https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/#comment-245

> We support both Internet and UNIX sockets. Please raise issues to see here https://github.com/Microsoft/BashOnWindows/issues

**Comment by JMoVS** [comment]
This is in all likelyhood only an issue if you use ruby < 2.x. If you use a 2.x ruby AND link it, this issue goes away.
See here: https://gist.github.com/JMoVS/75f3c6b344648deef59bc761e5e5a0e6#lets-first-upgrade-our-ruby-to-v2x-and-actually-link-it

Which brings me to the question: The homebrew-ruby is listed as "portable ruby" in homebrew config. Maybe this doesn't work *yet* as well until the Windows Spring update is out so that patchelf-ed binaries work on windows as well? Or does it just work with ruby 2.4? (I haven't tested other versions but for me, the default setting in my linked gist did the trick to get linuxbrew to work).

**Comment by JMoVS** [comment]
Which brings me to the question: The homebrew-ruby is listed as "portable ruby" in homebrew config. Maybe this doesn't work *yet* as well until the Windows Spring update is out so that patchelf-ed binaries work on windows as well.

**Comment by sjackman** [comment]
Thanks for your update. It's good to know that Ruby ≥ 2.0 should work. Homebrew has two distributions of Ruby. The first is the one that's installed by default if your host has Ruby < 2.0 and has no dependencies, called Portable Ruby. The second is the one that you get when you `brew install ruby`. The former doesn't I believe require `patchelf` and the latter does require `patchelf`.

**Comment by JMoVS** [comment]
if I don't install ruby via homebrew but have a system ruby higher than 2, is that gonna get used?

**Comment by JMoVS** [comment]
ok, so I was wrong. I had a fresh windows 10 install and found out that ruby 2.x from the brightbox ppa don't work. So one can successfully install linuxbrew with brightbox ruby 2.4. 

But one has to also install ruby 1.9 (`sudo apt-get install ruby1.9`), then run `sudo update-alternatives --config ruby` and select the 1.9 version, then run `brew config` (thereby switching homebrew to ruby portable), then run `sudo update-alternatives --config ruby` and switch back to 2.4 so system ruby is up to date again. homebrew continues to use the portable version and everything works after that.

**Comment by sjackman** [comment]
Do you know why Ruby 2.4 doesn't work with Linuxbrew; do you have an error message?

**Comment by JMoVS** [comment]
the error is
```
/home/rwbash/.linuxbrew/Library/Homebrew/build.rb:191:in `dump': instance of IO needed (TypeError)
       from /home/rwbash/.linuxbrew/Library/Homebrew/build.rb:191:in `rescue in <main>'
       from /home/rwbash/.linuxbrew/Library/Homebrew/build.rb:180:in `<main>'
Error: Suspicious failure
```

I guess it's related to the fact that Windows subsystem for linux uses ruby 1.9 as it's ubuntu 14.04 LTS. There is no *official* ruby 2.x for ubuntu trusty, but there is the brightbox ruby. But installing ruby 1.9 installs way more dependencies that 2.x, so I guess it's due to the fact that ruby 2.x is not officially supported.

This error only comes up when users are manually installing ruby 2.x in my experience. The system installed ruby 1.9 works fine with linuxbrew. (it just so happens that I needed ruby 2.x)
